{%include file="hotel/common/header.phtml"%}
<style type="text/css">
    a:link{color:#a77809;}
    a:visited{color:#a77809;}
    *{color:#000000;font-size:x-small;font-size:5;}
    .icon{vertical-align: middle;}
    a img {border: none;}

    body {
        background: #ffffff;
    }

    .hrYellow {
        color:#fbf8c9;
        border: 0;
        background-color:#fbf8c9;
        height:1px;
        margin:0.3em 0;
    }

    .hrWhite {
        color:#ffffff;
        border: 0;
        background-color:#ffffff;
        height:1px;
        margin:0.3em 0;
    }

    .hrSp {
        background-color:#fdd89e;
        color:#fdd89e;
        height:1px;
        border:0px solid #fdd89e;
        margin:0.3em 0;
    }

    #mixiHeader {
        background:#fbb03b;
    }

    .headlineFun {
        background:#cf1226;
        color:#ffffff;
    }

    .headlineBack {
        background:#f6ddbc;
    }

    .headlineTip {
        background:#fdd89e;
        color:#000000;
    }

    .toTop {
        background-color:#ffffff;
    }

    #copyright {
        background:#fbb03b;
    }

    .sectionOne {
        background:#fbf8c9;
    }

    #itemConfirm {
        background:#fbf8c9;
    }

    </style>
    <div id="itemConfirm">
        <hr class="hrWhite" size="1" />
        <div style="background:red;">{%$message%}</div>
        <div class="headlineTip">ｱｲﾃﾑを使う</div>
        <hr class="hrYellow" size="1" />
        <div class="description">
            {%$item.name%}を使用しますか？
        </div><!--/.description-->
        <div class="sectionOne">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="60" valign="top" align="center" style="width:60p;tet-align:center;vertical-align:top;"><img src="{%$staticUrl%}/{%$item.image_url%}" width="60" height="60" style="margin:2px 0;" /></td>
                    <td>{%$item.name%} {%if $number%}x{%$number%}{%/if%}</td>
                </tr>
            </table>
            <hr class="hrYellow" size="1" />
            <table width="228" cellpadding="2" cellspacing="1" border="0" style="background:#eeaa55;text-align:center;">
                <tr>
                    <td style="background:#fffdde;color:#000000;text-align:left;">【{%$item.name%}効果】<br />{%$item.introduce%}</td>
                </tr>
            </table>
            <hr class="hrYellow" size="1" />
            <div class="submit" style="text-align:left;">
                {%if $number%}
                    <span style="color:#ff9933;">⇒</span> <a href='{% "$baseUrl/mobile/hotel/itemconfirm?CF_sid=`$item.sid`&CF_model=1"|mixiurl %}'>使用する</a>
                {%else%}
                    <span style="color:#ff9933;">⇒</span>使用する
                {%/if%}
            </div><!--/.submit-->
        </div><!--/.section-->
        <hr class="hrYellow" size="1" />
        <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
    </div><!--/#itemConfirm-->
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}