{%include file="hotel/common/header.phtml"%}
<style type="text/css">
	a:link{color:#a77809;}
	a:visited{color:#a77809;}
	*{color:#000000;font-size:x-small;font-size:5;}
	.icon{vertical-align: middle;}
	a img {border: none;}

	body {
		background: #ffffff;
	}

	.hrYellow {
		color:#fbf8c9;
		border: 0;
		background-color:#fbf8c9;
		height:1px;
		margin:0.3em 0;
	}

	.hrWhite {
		color:#ffffff;
		border: 0;
		background-color:#ffffff;
		height:1px;
		margin:0.3em 0;
	}

	.hrSp {
		background-color:#fdd89e;
		color:#fdd89e;
		height:1px;
		border:0px solid #fdd89e;
		margin:0.3em 0;
	}

	#mixiHeader {
		background:#fbb03b;
	}

	.headlineFun {
		background:#cf1226;
		color:#ffffff;
	}

	.headlineBack {
		background:#f6ddbc;
	}

	.headlineTip {
		background:#fdd89e;
		color:#000000;
	}

	.toTop {
		background-color:#ffffff;
	}

	#copyright {
		background:#fbb03b;
	}

	.sectionOne {
		background:#fbf8c9;
	}

	#itemList {
		background:#fbf8c9;
	}

	.tdBg {
		background-color:#d2d0bc;
	}
	#minifeed {
		background:#fbf8c9;
	}

</style>

{% if $itemlist %}
    <div id="itemList">
        <hr class="hrWhite" size="1" />

        <div class="headlineTip" style="color:#000000;">所有ｱｲﾃﾑ({%$count%})</div>
        <hr class="hrWhite" size="1" />
	        {% foreach from=$itemlist item=data key=key %}
		        <div class="section">
		            <table {% if $key%2==0 %}class="tdBg"{% /if %} width="100%" cellpadding="0" cellspacing="0" border="0">
		                <tr>
		                    <td width="60" valign="top" align="center" style="width:60px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/{%$data.image_url%}" width="60" height="60" /></td>
		                    <td style="color:#000000;">{%$data.name%} x{%$data.number%}<br />
                            </td>
		                </tr>
		                <tr>
		                  <td>
                              <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/itemconfirm?CF_sid=`$data.sid`"|mixiurl %}'>使用する</a><br/>
                              <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/`$hotelUrl`"|mixiurl %}'>戻る</a>
		                  </td>
		                </tr>
		            </table>
		        </div><!--/.section-->
	        {% /foreach %}
        <hr class="hrYellow" size="1" />

            {%include file="hotel/common/pager.phtml"%}
        <hr class="hrYellow" size="1" />

         <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
    </div><!--/#mymixilist-->
{%else%}
    <div id="minifeed">
        <hr class="hrWhite" size="1" />

		<div class="headlineTip" style="color:#000000;">所有ｱｲﾃﾑ</div>

		<hr class="hrWhite" size="1" />

		<div class="description">
			残念ながら、まだ何もありません｡
		</div><!--/.description-->

        <div class="nullImage" style="text-align:center;">
            <img src="{%$staticUrl%}/apps/hotel/mobile/img/null.gif" width="118" height="106" style="margin:2px 0;" />
        </div><!--/.nullImage-->
        <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
        <hr class="hrYellow" size="1" />

    </div><!--/#minifeed-->
{%/if%}
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}