{%include file="hotel/common/header.phtml"%}
    <style type="text/css">
    a:link{color:#a77809;}
    a:visited{color:#a77809;}
    *{color:#000000;font-size:x-small;font-size:5;}
    .icon{vertical-align: middle;}
    a img {border: none;}

    body {
        background: #ffffff;
    }

    .hrYellow {
        color:#fbf8c9;
        border: 0;
        background-color:#fbf8c9;
        height:1px;
        margin:0.3em 0;
    }

    .hrWhite {
        color:#ffffff;
        border: 0;
        background-color:#ffffff;
        height:1px;
        margin:0.3em 0;
    }

    .hrSp {
        background-color:#fdd89e;
        color:#fdd89e;
        height:1px;
        border:0px solid #fdd89e;
        margin:0.3em 0;
    }

    #mixiHeader {
        background:#fbb03b;
    }

    .headlineFun {
        background:#cf1226;
        color:#ffffff;
    }

    .headlineBack {
        background:#f6ddbc;
    }

    .headlineTip {
        background:#fdd89e;
        color:#000000;
    }

    .toTop {
        background-color:#ffffff;
    }

    #copyright {
        background:#fbb03b;
    }

    .sectionImg {
        background:#dedcc6;
    }

    .sectionList {
        background:#fbf8c9;
    }
    .owner {
        background:#fbf8c9;
    }
    </style>
    <div id="profile">
        <hr class="hrWhite" size="1" />
        <div class="owner">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td valign="top" width="44" align="center" style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/womenSmall.gif" style="margin:2px 0;" /></td>
                    <td valign="top" style="padding-top:5px;">客室担当（<a href='{% "$baseUrl/mobile/hotel/techlist"|mixiurl %}'>Lv{%$roomInfo.manager%}</a>)<br />
                        <span style="font-size:small;color:#ffcc00;">"店長様、客室の昇格して売上が増えるよ～！"</span>
                    </td>
                </tr>
            </table>
        </div><!--/.owner-->
        <div style="height:10px;" class="setInterval"></div>
        <div class="sectionImg">
        <div><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomCare2.gif" /></div>
        </div><!--/.section-->
         <div class="sectionList">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室1<span style="color:#666666;">〓</span>(lv{%$roomInfo.room1%})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomOne.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    {% if $techName == 'room1' %}
                            updating... remain {%$time%} to complete.
                        {% else %}
                            <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomOne"|mixiurl %}'>詳細を見る</a>&nbsp;
                        {%/if%}
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="sectionList">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室2<span style="color:#666666;">〓</span>(lv{%$roomInfo.room2%})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomTwo.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    {% if $techName == 'room2' %}
                            updating... remain {%$time%} to complete.
                        {% else %}
                            <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomTwo"|mixiurl %}'>詳細を見る</a>&nbsp;
                        {%/if%}
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="sectionList">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室3<span style="color:#666666;">〓</span>(lv{%$roomInfo.room3%})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomThree.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    {% if $techName == 'room3' %}
                            updating... remain {%$time%} to complete.
                        {% else %}
                            <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomThree"|mixiurl %}'>詳細を見る</a>&nbsp;
                        {%/if%}
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
    </div><!--/#profile-->
    <hr class="hrWhite" size="1" />
        <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}