{%include file="hotel/common/header.phtml"%}
<style type="text/css">
    a:link{color:#a77809;}
    a:visited{color:#a77809;}
    *{color:#000000;font-size:x-small;font-size:5;}
    .icon{vertical-align: middle;}
    a img {border: none;}

    body {
        background: #ffffff;
    }

    .hrYellow {
        color:#fbf8c9;
        border: 0;
        background-color:#fbf8c9;
        height:1px;
        margin:0.3em 0;
    }

    .hrWhite {
        color:#ffffff;
        border: 0;
        background-color:#ffffff;
        height:1px;
        margin:0.3em 0;
    }

    .hrSp {
        background-color:#fdd89e;
        color:#fdd89e;
        height:1px;
        border:0px solid #fdd89e;
        margin:0.3em 0;
    }

    #mixiHeader {
        background:#fbb03b;
    }

    .headlineFun {
        background:#cf1226;
        color:#ffffff;
    }

    .headlineBack {
        background:#f6ddbc;
    }

    .headlineTip {
        background:#fdd89e;
        color:#000000;
    }

    .toTop {
        background-color:#ffffff;
    }

    #copyright {
        background:#fbb03b;
    }

    #minifeed {
        background-color:#fbf8c9;
    }
    </style>
<div id="minifeed">
	<hr class="hrWhite" size="1" />
	   <div class="headlineTip">履歴<br />
	       収入履歴&nbsp;<a href='{% "$baseUrl/mobile/hotel/minifeed"|mixiurl %}'>Feed履歴</a>&nbsp;<a href='{% "$baseUrl/mobile/hotel/minifeed"|mixiurl %}'>システム更新履歴</a></div>
	<hr class="hrYellow" size="1" />
	<div class="description">
	   ○○さんに関連する情報の最新10件を表示しています｡
	</div><!--/.description-->
	<hr class="hrYellow" size="1" />
		<div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <span style="color:#666666;">〓</span>収入は増加します<span style="color:#666666;">〓</span><br />
            <div class="inner" style="color:#777777;">○○さん収入は増加します○○さん収入は増加します</div>
            <div style="text-align:right;">09/05/05 10:25</div>
        </div><!--/.section-->
    </div><!--/#minifeed-->
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}