{%include file="hotel/common/header.phtml"%}

<style type="text/css">
	a:link{color:#a77809;}
	a:visited{color:#a77809;}
	*{color:#000000;font-size:x-small;font-size:5;}
	.icon{vertical-align: middle;}
	a img {border: none;}

	body {
		background: #ffffff;
	}

	.hrYellow {
		color:#fbf8c9;
		border: 0;
		background-color:#fbf8c9;
		height:1px;
		margin:0.3em 0;
	}

	.hrWhite {
		color:#ffffff;
		border: 0;
		background-color:#ffffff;
		height:1px;
		margin:0.3em 0;
	}

	.hrSp {
		background-color:#fdd89e;
		color:#fdd89e;
		height:1px;
		border:0px solid #fdd89e;
		margin:0.3em 0;
	}

	#mixiHeader {
		background:#fbb03b;
	}

	.headlineFun {
		background:#cf1226;
		color:#ffffff;
	}

	.headlineBack {
		background:#f6ddbc;
	}

	.headlineTip {
		background:#fdd89e;
		color:#000000;
	}

	.toTop {
		background-color:#ffffff;
	}

	#copyright {
		background:#fbb03b;
	}

	#constructionlist {
		background-color:#fbf8c9;
	}

	.tdBg {
		background-color:#d2d0bc;
	}
</style>

<div id="constructionlist">
        <hr class="hrWhite" size="1" />
		<div class="headlineTip">建築物一覧</div>
		<hr class="hrWhite" size="1" />

        <!--<div class="description">
			CF建築物一覧
            <hr class="hrYellow" size="1" />
            <div class="money" style="text-align:right;">現在の所持金:${%$userInfo.money%}</div>
        </div>/.description-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>受付室<span style="color:#666666;">〓</span></div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/frontM.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
               <a href='{% "$baseUrl/mobile/hotel/frontprofile"|mixiurl %}'>詳細を見る</a>&nbsp;
            </div><!--/.description-->
        </div><!--/.section-->

        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>店長室<span style="color:#666666;">〓</span></div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/bossM.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <a href='{% "$baseUrl/mobile/hotel/bossprofile"|mixiurl %}'>詳細を見る</a>&nbsp;
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>レストラン<span style="color:#666666;">〓</span>(lv{%$roomlist.restaurant %})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/restM.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                       <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=restM"|mixiurl %}'>詳細を見る</a>&nbsp;
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室1<span style="color:#666666;">〓</span>(lv{%$roomlist.room1 %})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomOne.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomOne"|mixiurl %}'>詳細を見る</a>&nbsp;
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室2<span style="color:#666666;">〓</span>(lv{%$roomlist.room2 %})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomTwo.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomTwo"|mixiurl %}'>詳細を見る</a>&nbsp;
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>客室3<span style="color:#666666;">〓</span>(lv{%$roomlist.room3 %})</div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/roomThree.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    <a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=roomThree"|mixiurl %}'>詳細を見る</a>&nbsp;
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <div class="section">
            <hr class="hrSp" size="1" />
            <div class="headline"><span style="color:#666666;">〓</span>技能研究室<span style="color:#666666;">〓</span></div>
            <table class="tdBg" width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" align="center" style="width:100px;text-align:center;"><img src="{%$staticUrl%}/apps/hotel/mobile/img/system.gif" width="100" height="59" style="margin:2px 0;" /></td>
                    <td style="color:#333333;">&nbsp;</td>
                </tr>
            </table>
            <div class="description">
                <div class="submit" style="text-align:left;">
                    <span style="color:#ff9933;">⇒</span>
                    <a href='{% "$baseUrl/mobile/hotel/techlist"|mixiurl %}'>詳細を見る</a>&nbsp;
                </div>
            </div><!--/.description-->
        </div><!--/.section-->
        <hr class="hrSp" size="1" />
        <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
    </div><!--/#constructionlist-->
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}