{%include file="hotel/common/header.phtml"%}
<style type="text/css">
    a:link{color:#a77809;}
    a:visited{color:#a77809;}
    *{color:#000000;font-size:x-small;font-size:5;}
    .icon{vertical-align: middle;}
    a img {border: none;}

    body {
        background: #ffffff;
    }

    .hrYellow {
        color:#fbf8c9;
        border: 0;
        background-color:#fbf8c9;
        height:1px;
        margin:0.3em 0;
    }

    .hrWhite {
        color:#ffffff;
        border: 0;
        background-color:#ffffff;
        height:1px;
        margin:0.3em 0;
    }

    .hrSp {
        background-color:#fdd89e;
        color:#fdd89e;
        height:1px;
        border:0px solid #fdd89e;
        margin:0.3em 0;
    }

    #mixiHeader {
        background:#fbb03b;
    }

    .headlineFun {
        background:#cf1226;
        color:#ffffff;
    }

    .headlineBack {
        background:#f6ddbc;
    }

    .headlineTip {
        background:#fdd89e;
        color:#000000;
    }

    .toTop {
        background-color:#ffffff;
    }

    #copyright {
        background:#fbb03b;
    }

    #itemConfirm {
        background:#fbf8c9;
    }

    .sectionOne {
        background:#fbf8c9;
    }
    </style>
<div id="itemConfirm">
        <hr class="hrWhite" size="1" />
        <div style="background:red;">{% if $message %}{%$message%}<a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=`$type`"|mixiurl %}'>更新</a>{%/if%}</div>
        <div class="headlineTip">{%$typeName%}</div>
        <hr class="hrWhite" size="1" />
        <div class="sectionOne">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="100" valign="top" align="center" style="width:100px;text-align:center;vertical-align:top;">
                        <img src="{%$staticUrl%}{%$roominfo.image_url%}" width="100" height="59" style="margin:2px 0;" />
                    </td>
                    <td style="color:blue;">
                        Lv：{%$lv%}級<br/>
                        {%if $type == 'restM' %}
	                                                使用率：{%$fullInfo.restaurant_dining_rate%}%<br/>
	                                                食事代：{%$fullInfo.restaurant_dining_fee%}円<br/>
                        {%else%}
                                                         部屋数：
                            {%if $type == 'roomOne' %}
                                {%$fullInfo.room1_living_in%}
                            {%elseif $type == 'roomTwo' %}
                                {%$fullInfo.room2_living_in%}
                            {%else%}
                                {%$fullInfo.room3_living_in%}
                            {%/if%}軒<br/>
                                                         宿泊料：
                            {%if $type == 'roomOne' %}
                                {%$fullInfo.room1_fee%}
                            {%elseif $type == 'roomTwo' %}
                                {%$fullInfo.room2_fee%}
                            {%else%}
                                {%$fullInfo.room3_fee%}
                            {%/if%}円<br/>
                        {%/if%}
                    </td>
                </tr>
            </table>
            <hr class="hrYellow" size="1" />
            <table width="228" cellpadding="2" cellspacing="1" border="0" style="background:#eeaa55;text-align:center;">
                <tr>
                    <td style="background:#fffdde;color:#000000;text-align:left;">
                                                    昇格料金:{%$roominfo.update_money%} 円<br/>
                                                    所持金：{%$info.money%} 円<br/>
                          {%if $type == 'restM' %}
                            lv{%$next_lv%}の食事代：{%$fullInfo.restaurant_next_dining_fee%} 円
                          {%else%}
                            lv{%$next_lv%}の宿泊料：
                            {%if $type == 'roomOne' %}
                                {%$fullInfo.room_next_fee%}
                            {%elseif $type == 'roomTwo' %}
                                {%$fullInfo.room2_next_fee%}
                            {%else%}
                                {%$fullInfo.room3_next_fee%}
                            {%/if%}
                                                         円<br/>
                          {%/if%}
                    </td>
                </tr>
            </table>
            <hr class="hrYellow" size="1" />
            <div class="submit" style="text-align:left;">
                {% if $roominfo.update_money >= $info.money || not $model%}
                    <span style="color:#ff9933;">⇒</span><span>昇格する&nbsp;</span>
                {%else%}
                    <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/roomupconfirm?CF_room=`$type`&CF_model=1"|mixiurl %}'>昇格する</a>&nbsp;
                {%/if%}
                <br/><span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/roomlist"|mixiurl %}'>戻る</a>&nbsp;
            </div><!--/.submit-->
        </div><!--/.section-->
        <hr class="hrYellow" size="1" />
        <!--<div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>トップへ戻る</a>&nbsp;
        </div>/.toTop-->
    </div><!--/#itemConfirm-->
{%include file="hotel/common/menu.phtml"%}
{%include file="hotel/common/footer.phtml"%}