{%include file="header.phtml"%}
<body id="admin">
	<h1>OPENSOCIAL APPS ADMIN</h1>
    {%include file="nav.phtml"%}
	<div id="container">
		<h2>駐車戦争 - アプリケーション管理</h2>
		<div id="appsAdmin">
            <ul class="nav">
                <li><a href="{%$baseUrl%}/aparking/top">トップページ</a></li>
                <li><a href="{%$baseUrl%}/aparking/addcar">自動車 追加・編集</a></li>
                <li><span>不動産 追加・編集</span></li>
            </ul><!--/.nav-->
			<table width="100%" cellpadding="0" cellspacing="0" border="0" id="twoPain">
				<tr>
					<td>{%include file="aparking/common/listbackground.phtml"%}</td>
					<th>
						<h3><strong>不動産 追加・編集</strong></h3>
                       <div id="step1">
						<form id="frmEditBackground" method="post" enctype="multipart/form-data">
							<div class="description">
								<p>不動産の登録内容を変更できます。</p>
							</div><!--/.description-->
                            <div id="errMsg" class="error" style="display: none;">
                                <p>エラーメッセージ</p>
                            </div>
                            <!--/.error-->
							<ul>
                                <li><label for="#">名称：</label><br />
                                    <input type="text" id="txtName" name="txtName" class="required" maxlength="50" value="{% $backgroundInfo.name %}" size="50" />
                                    <div id="advice-required-txtName" class="validation-advice" title="名称を入力してください" style="display: none;"></div>
                                </li>
                                <li><label for="#">ユニークKEY：</label><br />
                                    {%$staticUrl%}/apps/parking/img/background/<input type="text" id="txtCavName" name="txtCavName" class="required validate-alphanum-hyphen" maxlength="20" value="{% $backgroundInfo.cav_name %}" size="20" />
                                    <div id="advice-required-txtCavName" class="validation-advice" title="ユニークKEYを入力してください" style="display: none;"></div>
                                </li>
                                <li><label for="#">イメージ：</label><br />
                                    <img width="420" heigth="60" src="{%$staticUrl%}/apps/parking/img/background/{%$backgroundInfo.cav_name%}.gif" />{%$backgroundInfo.cav_name%}.gif
                                </li>
                                
                                <li><label for="#">不動産ランク：</label><br />{%$backgroundInfo.rank%}
                                    <select id="selRank" name="selRank" disabled>
                                        {% foreach from=$ranks item=rank %}
                                        {% if $rank == $backgroundInfo.type %}
                                        <option value="{%$rank%}" selected>{%$rank%}</option>
                                        {% else %}
                                        <option value="{%$rank%}">{%$rank%}</option>
                                        {% /if %}
                                        {% /foreach %}
                                    </select>
                                </li>
                                
                                <li><label for="#">紹介：</label><br />
                                    <textarea name="txtIntroduce" id="txtIntroduce" class="required" maxlength="200" rows="4" cols="70">{%$backgroundInfo.introduce%}</textarea>
                                    <div id="advice-required-txtIntroduce" class="validation-advice" title="紹介を入力してください" style="display: none;"></div>
                                </li>
                                <li><label for="#">駐車料金：</label><br />
                                    <input type="text" id="txtFee" name="txtFee" class="required validate-int-range-1000-100000" maxlength="10" value="{%$backgroundInfo.fee%}" size="10" />
                                    <div id="advice-required-txtFee" class="validation-advice" title="駐車料金を入力してください" style="display: none;"></div>
                                </li>
                                <li><label for="#">値段：</label><br />
                                    <input type="text" id="txtPrice" name="txtPrice" class="required validate-int-range-1000-2147483647" maxlength="10" value="{%$backgroundInfo.price%}" size="10" />
                                    <div id="advice-required-txtPrice" class="validation-advice" title="値段を入力してください" style="display: none;"></div>
                                </li>
                                
                                <li><label for="#">不動産ランクリスト：</label><br />
                                    <table width="25%">
                                        <tr><td><strong>ランク</strong></td><td><strong>駐車可能台数</strong></td></tr>
                                        {% foreach from=$aryRank item=rank %}
                                        <tr><td>{% $rank.rank %}</td><td>{% $rank.parking %}</td></tr>
                                        {% /foreach %}
                                    </table>
                                </li>
								<li><input type="button" id="btnConfirm" name="btnConfirm" value="　上記の内容に変更する　" /></li>
							</ul>
							<input type="hidden" id="id" name="id" value="{%$id%}">
						</form>
						</div><!--/.step1 End -->
                        <div id="step2" style="display: none">
                            <div class="description">
                                <p>以下の内容でよろしければ、変更をクリックしてください。</p>
                            </div><!--/.description-->
                            <ul>
                                <li><label for="#">名称：</label><br />
                                    <p id="pName"></p>
                                </li>
                                <li><label for="#">ユニークKEY：</label><br />
                                    <p id="pCavName"></p>
                                </li>
                                <li><label for="#">イメージ：</label><br />
                                    <img width="420" heigth="60" src="{%$staticUrl%}/apps/parking/img/background/{%$backgroundInfo.cav_name%}.gif" />
                                </li>
                                <li><label for="#">不動産ランク：</label><br />
                                    <p id="pRank"></p>
                                </li>
                                <li><label for="#">紹介：</label><br />
                                    <p id="pIntroduce"></p>
                                </li>
                                <li><label for="#">駐車料金：</label><br />
                                    <p id="pFee"></p>
                                </li>
                                <li><label for="#">値段：</label><br />
                                    <p id="pPrice"></p>
                                </li>
                                
                                <li><label for="#">不動産ランクリスト：</label><br />
                                    <table width="25%">
                                        <tr><td><strong>ランク</strong></td><td><strong>駐車可能台数</strong></td></tr>
                                        {% foreach from=$aryRank item=rank %}
                                        <tr><td>{% $rank.rank %}</td><td>{% $rank.parking %}</td></tr>
                                        {% /foreach %}
                                    </table>
                                </li>
                                <li>
                                    <input type="button" id="btnRevision" name="btnRevision" value="　戻る　" />
                                    <input type="button" id="btnSubmit" name="btnSubmit" value="　変更　" />
                                </li>
                            </ul>
                        </div><!--/.step2 End -->
                        <div id="loading" style="display: none"></div>
                        <div id="step3" style="display: none">
                            <div class="description">
                                <p>不動産変更が完了しました。</p>
                            </div><!--/.description-->
                        </div><!--/.step3 End -->
					</th>
				</tr>
			</table><!--/#towPain-->
		</div><!--/#appsAdmin-->
	</div><!--/#container-->
	<script src="{%$staticUrl%}/admin/js/aparking/editbackground.js?{%$version.js%}"></script>
{%include file="footer.phtml"%}