{%include file="header.phtml"%}
<body id="admin">
	<h1>OPENSOCIAL APPS ADMIN</h1>
    {%include file="nav.phtml"%}
	<div id="container">
		<h2>駐車戦争 - アプリケーション管理</h2>
		<div id="appsAdmin">
            <ul class="nav">
                <li><a href="{%$baseUrl%}/aparking/top">トップページ</a></li>
                <li><span>自動車 追加・編集</span></li>
                <li><a href="{%$baseUrl%}/aparking/addbackground">不動産 追加・編集</a></li>
            </ul><!--/.nav-->
			<table width="100%" cellpadding="0" cellspacing="0" border="0" id="twoPain">
				<tr>
					<td>{%include file="aparking/common/listcar.phtml"%}</td>
					<th>
						<h3><strong>自動車 追加・編集</strong></h3>
                       <div id="step1">
						<form id="frmEditCar" method="post" enctype="multipart/form-data">
							<div class="description">
								<p>自動車の登録内容を変更できます。</p>
							</div><!--/.description-->
                            <div id="errMsg" class="error" style="display: none;">
                                <p>エラーメッセージ</p>
                            </div>
                            <!--/.error-->
							<ul>
								<li><label for="#">名称：</label><br />
									<input type="text" id="txtName" name="txtName" class="required" maxlength="50" value="{%$carInfo.name%}" size="50" />
									<div id="advice-required-txtName" class="validation-advice" title="名称を入力してください" style="display: none;"></div>
							    </li>
								<li><label for="#">値段：</label><br />
									<input type="text" id="txtPrice" name="txtPrice" class="required validate-int-range-1000-2147483647" maxlength="10" value="{%$carInfo.price%}" size="10" />
                                    <div id="advice-required-txtPrice" class="validation-advice" title="値段を入力してください" style="display: none;"></div>
								</li>
								<li><label for="#">ユニークKEY：</label><br />
									{%$staticUrl%}/apps/parking/img/car/<input type="text" id="txtCavName" name="txtCavName" class="required validate-alphanum-hyphen" maxlength="20" value="{%$carInfo.cav_name%}" size="20" />
                                    <div id="advice-required-txtCavName" class="validation-advice" title="ユニークKEYを入力してください" style="display: none;"></div>
								</li>
                                <li><label for="#">イメージ：</label><br />                                    
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/black.png" />small-black.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/blue.png" />small-blue.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/red.png" />small-red.png<br/>
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/silver.png" />small-silver.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/white.png" />small-white.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/yellow.png" />small-yellow.png<br/><br/>
                                    
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/black.png" />big-black.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/blue.png" />big-blue.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/red.png" />big-red.png<br/>
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/silver.png" />big-silver.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/white.png" />big-white.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/yellow.png" />big-yellow.png
                                </li>
								<li><label for="#">駐車料金の掛け率：</label><br />
									<input type="text" id="txtTimes" name="txtTimes" class="required validate-float-range-0-1000" value="{%$carInfo.times%}" size="20" />
                                    <div id="advice-required-txtTimes" class="validation-advice" title="駐車料金の掛け率を入力してください" style="display: none;"></div>
								</li>
								<li><input type="button" id="btnConfirm" name="btnConfirm" value="　上記の内容に変更する　" /></li>
							</ul>
							<input type="hidden" id="cid" name="cid" value="{%$cid%}">
						</form>
						</div><!--/.step1 End -->
                        <div id="step2" style="display: none">
                            <div class="description">
                                <p>以下の内容でよろしければ、変更をクリックしてください。</p>
                            </div><!--/.description-->
                            <ul>
                                <li><label for="#">名称：</label><br />
                                    <p id="pName"></p>
                                </li>
                                <li><label for="#">値段：</label><br />
                                    <p id="pPrice"></p>
                                </li>
                                <li><label for="#">ユニークKEY：</label><br />
                                    <p id="pCavName"></p>
                                </li>
                                <li><label for="#">イメージ：</label><br />
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/black.png" />small-black.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/blue.png" />small-blue.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/red.png" />small-red.png<br/>
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/silver.png" />small-silver.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/white.png" />small-white.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/small/yellow.png" />small-yellow.png<br/><br/>
                                    
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/black.png" />big-black.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/blue.png" />big-blue.png
				    				<img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/red.png" />big-red.png<br/>
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/silver.png" />big-silver.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/white.png" />big-white.png
                                    <img src="{%$staticUrl%}/apps/parking/img/car/{%$carInfo.cav_name%}/big/yellow.png" />big-yellow.png
                                </li>
                                <li><label for="#">駐車料金の掛け率：</label><br />
                                    <p id="pTimes"></p>
                                </li>
                                <li>
                                    <input type="button" id="btnRevision" name="btnRevision" value="　戻る　" />
                                    <input type="button" id="btnSubmit" name="btnSubmit" value="　変更　" />
                                </li>
                            </ul>
                        </div><!--/.step2 End -->
                        <div id="loading" style="display: none"></div>
                        <div id="step3" style="display: none">
                            <div class="description">
                                <p>自動車変更が完了しました。</p>
                            </div><!--/.description-->
                        </div><!--/.step3 End -->
					</th>
				</tr>
			</table><!--/#towPain-->
		</div><!--/#appsAdmin-->
	</div><!--/#container-->
	<script src="{%$staticUrl%}/admin/js/aparking/editcar.js?{%$version.js%}"></script>
{%include file="footer.phtml"%}