{%include file="disney/common/header.phtml"%}
    <div id="bgcolor1" style="color:#630;font-size:x-small;background-color:#edd9ae;">
    	<div align="center" style="background-color:#f8f1df;">
    	<div style="background-color:#50b83a; text-align:center; color:#f8f1df;" >
		{% disneyimg name="sub_ti_buy" %}<br />
        </div><!--#sitein_link-->
		</div><!--/#center-->
		
		<img src="http://mm.mixi.net/img/dot0.gif" height="10"/><br />
		<div style="text-align:center;">購入完了したよ!</div>
		<img src="http://mm.mixi.net/img/dot0.gif" height="10"/><br />
		{% disneyimg name="dotline_fff5f5_s" %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		
		<div style="text-align:left;">
			移動をしたらｱﾌﾟﾘﾄｯﾌﾟから｢ﾁｪｯｸ｣ﾎﾞﾀﾝを押して早速ｱｲﾃﾑを使おう!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="10"/><br />
			<div style="text-align:center;"><a href='{% "$baseUrl/mobile/disney/index"|mixiurl %}'>ｱﾌﾟﾘﾄｯﾌﾟへ</a></div>
		</div>
{%include file="disney/common/footer.phtml"%}