{%include file="disney/common/header.phtml"%}

    <div style="background-color:#fbe1ff;font-size:x-small;">
	<div style="background-color:#50b83a;text-align:center;">
		{% disneyimg name="sub_ti_enjoy" %}
	    	{%include file="disney/common/topmenu.phtml"%}
	<br />
		<div style="color:#701b94;">
		    <span style="color:#ff0000;">Q 現地へ行ってGET!</span><br /
		    <span style="color:#0000ff;">A</span>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝは､47都道府県に各1つずつｵﾘｼﾞﾅﾙのご当地ｷｬﾗｸﾀｰがいるんだよ!旅行などで他県へ出かけたとき{% emoji code="F8FA"%}には､『ご当地GET!』ﾎﾞﾀﾝを押してね｡{% emoji code="F8F6"%}<br />
		<div style="text-align:center;">   
			<div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>
		</div>   
			<span style="color:#ff0000;">Q ﾀｰｹﾞｯﾄﾂｱｰでGET!</span><br />
		    <span style="color:#0000ff;">A</span> 『￮￮県のご当地ｷｬﾗｸﾀｰが欲しい!』そんな時は､ﾀｰｹﾞｯﾄﾂｱｰで手に入れることができるよ!日々の移動でﾀｰｹﾞｯﾄとなる地域までの距離を稼せごう!ﾀｰｹﾞｯﾄまでの距離が達成されると手に入れることができるよ!<br />
		    <div style="text-align:center;">   
{% disneyimg name="line2" %}
</div>		    
		    <span style="color:#ff0000;">Q ﾏｲﾐｸとﾄﾚｰﾄﾞしてGET!</span><br />
		    <span style="color:#0000ff;">A</span> 友達のご当地ﾏｯﾌﾟを見て欲しいご当地ｷｬﾗｸﾀｰがあったら､自分のご当地ｷｬﾗｸﾀｰとﾄﾚｰﾄﾞをﾘｸｴｽﾄしてみよう!友達がokしてくれたら､ﾄﾚｰﾄﾞができるよ{% emoji code="F8F5"%}<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q 旅行のお土産やﾌﾟﾚｾﾞﾝﾄとして</span><br />
		    <span style="color:#0000ff;">A</span> 旅行{% emoji code="F99C"%}に行って記念のお土産として､ご当地ｷｬﾗｸﾀｰをﾏｲﾐｸに贈る♪こともできるよ｡ﾏｲﾐｸが後1つで地方すべてのご当地が揃うなんて時には､ﾌﾟﾚｾﾞﾝﾄとして贈ってあげても喜ばれるね{% emoji code="F991"%}<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q 携帯ﾒｰﾙをもっと可愛くする</span><br />
		    <span style="color:#0000ff;">A</span> ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝをまだ知らない友達{% emoji code="F995"%}にご当地ｷｬﾗｸﾀｰをﾃﾞｺﾒ化したﾒｰﾙ{% emoji code="F973"%}で自慢してみたり､旅行に行ったことをﾃﾞｺﾒ{% emoji code="F973"%}を使って報告してﾒｰﾙを可愛くしてみよう!<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q ﾁｬﾚﾝｼﾞｹﾞｰﾑに挑戦してみよう</span><br />
		    <span style="color:#0000ff;">A</span> 日々の移動距離がなかなか稼げない､今すぐ､ﾀｰｹﾞｯﾄの地域のご当地ｷｬﾗｸﾀｰが欲しい時には､ﾁｬﾚﾝｼﾞｹﾞｰﾑに挑戦してみよう｡"のりものﾙｰﾚｯﾄ"は､止った場所の"のりもの"によって､移動距離を一気に稼げるよ{% emoji code="F8F5"%}<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q 秘密のｱﾜｰﾄﾞ</span><br />
		    <span style="color:#0000ff;">A</span> ｱﾜｰﾄﾞは､ﾃﾞｨｽﾞﾆｰから贈る秘密{% emoji code="F97D"%}のｱｲﾃﾑだよ｡地方制覇したり､友達を招待して･･･｡どんなｱﾜｰﾄﾞがあるかは､お楽しみに!<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q ﾐｯｷｰの誕生日!?</span><br />
		    <span style="color:#0000ff;">A</span> ﾐｯｷｰの誕生日である11/18にｱﾌﾟﾘにｱｸｾｽ{% emoji code="F95E"%}すると何かが起こる!?<br />
		    <div style="text-align:center;">   
				{% disneyimg name="line2" %}
			</div>		    
		    <span style="color:#ff0000;">Q 友達を招待すると､特典があるよ</span><br />
		    <span style="color:#0000ff;">A</span> 友達を招待して､登録してくれると､招待した人と招待された人にｹﾞｰﾑﾁｹｯﾄ{% emoji code="F8DF"%}をﾌﾟﾚｾﾞﾝﾄするよ｡どんどん招待してみよう!<br />
			<div style="text-align:center;">
				{% disneyimg name="line2" %}
			</div>
		    <span style="color:#ff0000;">Q 友達を5人招待するとｱﾜｰﾄﾞが!?</span><br />
		    <span style="color:#0000ff;">A</span> まだ、ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ知らないﾏｲﾐｸを5人招待すると、ｱﾜｰﾄﾞがもらえるよ♪ 5人目の次は…。お楽しみに!<br />
			<div style="text-align:center;">
				{% disneyimg name="line2" %}
			</div>
			<span style="color:#ff0000;">Q 現在地でGET日記を書こう！</span><br />
			<span style="color:#0000ff;">A</span> 旅先でGETしたご当地ｷｬﾗｸﾀｰはｱﾌﾟﾘからすぐに日記を書けるよ。ﾌﾟﾚｾﾞﾝﾄ希望者を募ってﾌﾟﾚｾﾞﾝﾄすれば、良いお土産になるね♪<br />
	
		</div>
			<!--<span style="color:#ff0000;">Q ﾒｰﾙﾌｧｸﾄﾘｰ会員特典!</span><br />
		    <span style="color:#0000ff;">A</span> ﾃﾞｨｽﾞﾆｰ公式携帯ｻｲﾄ『ﾒｰﾙﾌｧｸﾄﾘｰ』の会員特典として､会員にしかもらえないｱﾜｰﾄﾞがあるんだよ｡会員の人は､今すぐ､こちらにｱｸｾｽしてみてね｡<br />
			<div style="text-align:center;">   
				{% disneyimg name="line2" %}-->
	

{%include file="disney/common/firstfooter.phtml"%}