{%include file="disney/common/header.phtml"%}

{% if $action == 'start' %}

<div style="font-size:x-small;background-color:#edd9ae;text-align:center;">
    {% disneyimg name="sub_ti_roulet" %}<br />
    <br />
        {% disneyimg style='align="top"' name="roulet" %}<br /><br />
	{% if $disneyUser.remain_distance - $disney.flash_distance > 0 && $disneyUser.game_ticket > 0 %}
		<div style="color:#5e250f;text-align:center;">
			ｹﾞｰﾑﾁｹｯﾄ枚数:{%$disneyUser.game_ticket%}枚
		</div>
        	{% disneyimg name="dot0" style='height="4"' %}<br />
		{% disneyimg name="map_line" %}<br />
        	{% disneyimg name="dot0" style='height="4"' %}<br />
		<div style="color:#5e250f;text-align:left;">
			乗り物が出ればﾀｰｹﾞｯﾄﾂｱｰの距離を稼げるｶﾞﾁｬｶﾞﾁｬ風ﾙｰﾚｯﾄだよ<br />
			{% disneyimg name="dot0" style='height="4"' %}<br />
			
			{% if $ua == 4 %}
			<span style="color:#FF0000;">※willcom端末は､ﾌﾗｯｼｭﾑｰﾋﾞｰを表示する事が出来ないためのりものﾙｰﾚｯﾄを正しく遊ぶことができません｡
			但し､移動距離のみ稼ぐ事は出来ます｡</span><br />
			<a href='{% "$baseUrl/mobile/disney/phone"|mixiurl %}' >対応端末一覧はこちら</a><br />
			{% /if %}
			
		</div>
        	{% disneyimg name="dot0" style='height="4"' %}<br />
		{% disneyimg name="map_line" %}<br />
        	{% disneyimg name="dot0" style='height="4"' %}<br />
		<a href="{%$baseUrl%}/mobile/disneyflash/start/uid/{%$disneyUser.uid%}/r/{%$time%}">{% disneyimg name="start_btn" %}<br />※ｹﾞｰﾑﾁｹｯﾄを1枚消費します</a><br />
		<span style="color:#ff0000;">※｢今すぐ始める｣ﾎﾞﾀﾝを押下した時点でｹﾞｰﾑが開始されます。</span><br />
    {% else %}
		{% disneyimg name="dot0" style='height="4"' %}<br/>
			<div style="color:#5e250f;text-align:center;">
			ｹﾞｰﾑﾁｹｯﾄがありません。<br />
			</div>
		{% disneyimg name="dot0" style='height="4"' %}<br />
		{% disneyimg name="map_line" %}<br />
		{% disneyimg name="dot0" style='height="4"' %}<br />
			<div style="color:#5e250f;text-align:left;">
			乗り物が出ればﾀｰｹﾞｯﾄﾂｱｰの距離を稼げるｶﾞﾁﾔｶﾞﾁｬ風ﾙｰﾚｰﾄだよ<br />
			ﾁｹｯﾄを購入して今すぐ、ｹﾞｰﾑｽﾀｰﾄ!!<br />
			{% disneyimg name="dot0" style='height="4"' %}<br />
			
			{% if $ua == 4 %}
			<span style="color:#FF0000;">※willcom端末は､ﾌﾗｯｼｭﾑｰﾋﾞｰを表示する事が出来ないためのりものﾙｰﾚｯﾄを正しく遊ぶことができません｡
			但し､移動距離のみ稼ぐ事は出来ます｡</span><br />
			<a href='{% "$baseUrl/mobile/disney/phone"|mixiurl %}' >対応端末一覧はこちら</a><br />	
			{% /if %}
			
			</div>
		{% disneyimg name="dot0" style='height="4"' %}<br />
		{% disneyimg name="map_line" %}<br />
	{% /if %}
        {% disneyimg name="dot0" style='height="4"' %}<br />
        <a href='{% "$baseUrl/mobile/disney/getticket"|mixiurl %}'>{% disneyimg name="buyticket" %}</a><br />        
	<!--
        <div style="background-color:#ff0000; padding-left:2px; padding-right:2px; padding-top:2px; padding-bottom:2px; margin:5px;">
		<div style="background-color:#ffffff; padding:5px;">
			{% emoji code="F9DC"%}<span style="color:#94291b;">ﾜｰﾌﾟｹﾞｰﾑｽﾀｰﾄをするには、ﾐｸｼｨﾎﾟｲﾝﾄが0ﾎﾟｲﾝﾄ必要です。</span>
		</div>
	</div>
	-->
    <br />
    
{% elseif $action == 'settarget' %}

<div style="font-size:x-small;background-color:#edd9ae;text-align:center;">
    {% disneyimg name="sub_ti_roulet" %}<br />
    <br />
        {% disneyimg style='align="top"' name="roulet" %}<br /><br />
        {% disneyimg name="dot0" style='height="4"' %}<br/>
		<div style="color:#5e250f;text-align:center;">
		<span style="color:#5B2806;">ﾀｰｹﾞｯﾄが未設定です。ﾀｰｹﾞｯﾄ設定をしてください。</span><br/>
		{% disneyimg name="dot0" style='height="4"' %}<br/>
		<a href='{% "$baseUrl/mobile/disney/settarget"|mixiurl %}'>ﾀｰｹﾞｯﾄ設定は、こちら</a><br />
		</div>
		{% disneyimg name="dot0" style='height="4"' %}<br />
        
{% else %}

	<div id="target" style="background-color:#ffd990;font-size:x-small;text-align:center;">
		{% disneyimg name="sub_ti_targetset2" %}
		<br/><br/>
		
		{%if $ua == 4%}
		<span style="color:#ff0000;">のりものﾙｰﾚｯﾄで{% foreach from=$flashDistance item=data %}
			{% disneyimg name="km_$data" %}
		{% /foreach %}km稼いだよ!</span><br />
		{%/if%}
		{% disneyimg name="dot0" style='height="4"' %}<br />
		
		<span style="color:#5B2806;">{%$disneyUser.target_name%}まであと</span><br/>
		{% foreach from=$arrayDistance item=data %}
			{% disneyimg name="km_$data" %}
		{% /foreach %}
		{% disneyimg name="km" %}<br />
		{% emoji code="F99F"%}<span style="color:#5B2806;">10点獲得!</span>{% emoji code="F99F"%}<br/>
		<br/>
		<div style="text-align:center;">
					{% if $disneyUser.remain_distance - $disneyUser.flash_distance > 0 %}
                    {% if $disneyUser.game_ticket>0%}
                        <a href='{% "$baseUrl/mobile/disney/game"|mixiurl %}'>
                    {%else%}
                        <a href='{% "$baseUrl/mobile/disney/getticket"|mixiurl %}'>
                    {%/if%}
                    <span>ｹﾞｰﾑで一気に{% emoji code="F9B8"%}距離を稼ごう!!{% emoji code="F9D8"%}</span></a>
                {% else %}
                    <span>ｹﾞｰﾑで一気に{% emoji code="F9B8"%}距離を稼ごう!!{% emoji code="F9D8"%}</span>
                {% /if %}<br /><br />
		</div>
    
{% /if %}
{%include file="disney/common/footer.phtml"%}