{%include file="disney/common/header.phtml"%}
		
		<div style="font-size:x-small; background-color:#ffffcc; color:#4e211c; text-align:left;">
		
			<br />
			Disneyご当地ｺﾚｸｼｮﾝをご利用いただき､ありがとうございます｡<br />
			<br />
			<br />
			
			≫4/27<br />
			<br />
			本日、ｱｲﾃﾑｼｮｯﾌﾟに新しい靴が登場いたしました。<br />
			<br />
			・ｶﾞﾗｽの靴<br />
			ｶﾞﾗｽの靴は、今までの靴よりも移動距離を一気に稼ぐﾁｬﾝｽがあります。今すぐ、ｱｲﾃﾑｼｮｯﾌﾟへ!!<br />
			<br />
			⇒<a href='{% "$baseUrl/mobile/disney/shop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟはこちら</a><br />
						

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫4/6<br />
			<br />
			本日、下記のｻｰﾋﾞｽをﾘﾘｰｽいたしました。<br />
			<br />
			・ｱｲﾃﾑｼｮｯﾌﾟ<br />
			<br />
			ｱｲﾃﾑｼｮｯﾌﾟでは、稼いだ距離を数倍にしてくれる魔法の靴を販売しています。<br />
			事前に購入しても、後から購入しても移動していれば、魔法が発動されます。<br />
			<br />
			⇒<a href='{% "$baseUrl/mobile/disney/shop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟはこちら</a><br />
						

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫4/5<br />
			<br />
			下記日程において、一時的にｻｰﾋﾞｽを停止します。<br />
			ご迷惑をおかけしますが、何卒ご理解とご協力をお願いします。<br />
			<br />
			日時:4/6 15:00～17:00<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫4/1<br />
			ｻｰﾋﾞｽﾒﾝﾃﾅﾝｽに伴う、ｻｰﾋﾞｽ停止のお知らせ<br />
			<br />
			下記日程において、一時的にｻｰﾋﾞｽを停止します。<br />
			ご迷惑をおかけしますが、何卒ご理解とご協力をお願いします。<br />
			<br />
			日時:4/2 15:00～17:00<br />
     
	 		{% disneyimg style='height="5"' name="dot0" %}<br />
	 		{% disneyimg name="fna_line2" %}<br />
	 		{% disneyimg style='height="5"' name="dot0" %}<br />

			≫3/31<br />
			不具合のお知らせとお詫び<br />
			ﾀｰｹﾞｯﾄ設定において､ｱﾌﾟﾘｹｰｼｮﾝｻｰﾊﾞｰ不具合により一時的に設定が出来ないという状態が発生しておりました｡<br />
			お客様には､ご迷惑をおかけしましたことをお詫び申し上げます｡<br />
			なお､現在は修正完了しており､問題なくﾀｰｹﾞｯﾄ設 定をすることができます｡<br />
			引き続き､Disneyご当地ｺﾚｸｼｮﾝをよろしくお願いいたします｡<br />
			<br />
			■不具合発生時間<br />
			3/31 17:00-<br />
			<br />
			■修正完了時間<br />
			3/31 18:30<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫3/29<br />
			ｻｰﾋﾞｽﾒﾝﾃﾅﾝｽに伴う、ｻｰﾋﾞｽ停止のお知らせ<br />
			<br />
			下記日程において、一時的にｻｰﾋﾞｽを停止します。<br />
			ご迷惑をおかけしますが、何卒ご理解とご協力をお願いします。<br />
			<br />
			日時:3/31 15:00〜17:00<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫3/24<br />
			日記に書くｷｬﾝﾍﾟｰﾝのﾁｹｯﾄ付与のお知らせ<br />
			<br />
			3/24 15時に対象者の皆さまにﾁｹｯﾄを5枚付与いたしました。<br />
			<br />
			《対象者》<br />
			・投稿した日記が、『全体に公開』の方<br />
			・日記内に"Disneyご当地ｺﾚｸｼｮﾝ"の記載がある方<br />
			※両条件を満たした方が対象となります。<br />


			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			

			≫3/11<br />
			本日、下記2つのｷｬﾝﾍﾟｰﾝを開始いたしました。<br />
			ｷｬﾝﾍﾟｰﾝ期間:3/11 15:00 - 3/23 15:00		
			<br />
						                        
			･"日記に書く"ｷｬﾝﾍﾟｰﾝ!<br />
			ｱﾌﾟﾘ内の『日記に書く』機能使って、ｱﾌﾟﾘ紹介日記を投稿するとｹﾞｰﾑﾁｹｯﾄ5枚をﾌﾟﾚｾﾞﾝﾄいたします!!<br />
			<br />
			･"友達招待"ｷｬﾝﾍﾟｰﾝ!<br />
			ﾏｲﾐｸをｱﾌﾟﾘに招待して、登録するとあなたとﾏｲﾐｸにｹﾞｰﾑﾁｹｯﾄ2枚をﾌﾟﾚｾﾞﾝﾄいたします!!<br />
			※両ｷｬﾝﾍﾟｰﾝともに応募には、条件があるため、必ずｷｬﾝﾍﾟｰﾝ詳細をお読みください。<br />


			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />


		
			≫1/27<br />
			本日、下記のｻｰﾋﾞｽをﾘﾘｰｽいたしました。<br />
			<br />			                        
			･集めたご当地ｷｬﾗｸﾀｰの待受け画像ﾀﾞｳﾝﾛｰﾄﾞ<br />
			･取得ｷｬﾗｸﾀｰ全国一覧<br />
			<br />
			全国一覧は、現在取得しているｷｬﾗｸﾀｰの確認とﾃﾞｺﾒ、待受けのﾀﾞｳﾝﾛｰﾄﾞ状況がわかります。<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />


			{% if !$apo %}
			≫1/26 ﾏｲｽｺｱ障害発生のお詫び<br />
			<br />
			一部のお客様のﾏｲｽｺｱが表示されない不具合に関しまして、復旧が完了しましたのでご報告いたします。<br />
			<br />
			ご迷惑をおかけしてしまい、申し訳ありません。
			再発防止に努めて参りますので、今後ともよろしくお願いします。<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% else %}
			>>1/26 ﾏｲｽｺｱ障害発生のお詫び<br />
			<br />
			お客様のﾏｲｽｺｱが表示されない不具合に関しまして、お客様が1/22〜1/25の期間に、ﾀｰｹﾞｯﾄﾂｱｰでｷｬﾗｸﾀｰをGETした後に、そのｷｬﾗｸﾀｰをﾄﾚｰﾄﾞしていた場合、ｽｺｱが完全復旧できない状態であることがわかりました。<br />
			<br />
			そのため、上記の可能性のあるお客様には、現状出来うる限りの補償として、ｹﾞｰﾑﾁｹｯﾄを10枚付与させていただきました。皆さまの大切なｽｺｱの返還とは異なる補償内容となってしまい申し訳ございませんが、ご理解いただけますと幸いです。<br />
			<br />
			なお、該当されない方に関しましては、復旧が完了しております。<br />
			<br />
			ご迷惑をおかけしてしまい、申し訳ありません。
			再発防止に努めて参りますので、今後ともよろしくお願いします。<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% /if %}
			≫1/25 障害のお知らせ<br />
			
			一部のお客様のﾏｲｽｺｱが表示されない不具合が発生しておりました｡<br />
			<br />
			 
			
			￭対象のお客様<br />
			
			1/22(金)午後16:00ごろから1/25(月)午後12:00ごろまでの間に､
			『ﾒｰﾙﾌｧｸﾄﾘｰ･ﾌﾟﾚﾐｱﾑ』ｱﾜｰﾄﾞを受賞したお客様<br />
			<br />
			 
			
			￭内容<br />
			ﾗﾝｷﾝｸﾞﾍﾟｰｼﾞにおいて､ﾏｲｽｺｱが表示されない｡<br />
			<br />
			 
			
			￭対応<br />
			
			順次ﾎﾟｲﾝﾄの復旧を行っております｡<br />
			
			なお､障害は修正完了しており､現在は問題なくｱﾜｰﾄﾞを受賞できます｡<br />
			
			<br />
			ご迷惑をおかけしてしまい､申し訳ございませんが､
			
			ご理解とご協力のほど､何卒よろしくお願いいたします｡<br />


			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			≫1/22<br />
			Disney公式携帯ｻｲﾄの会員特典ｱﾜｰﾄﾞの提供を開始しました｡<br />
			第一弾は公式ﾃﾞｺﾒｻｲﾄ｢ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ｣会員様向けに､期間限定の特別ｱﾜｰﾄﾞを配信します｡<br />			                        
			⇒<a href='{% "$baseUrl/mobile/disney/mailfactory"|mixiurl %}' >詳細はｺﾁﾗ</a><br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<!--
			≫1/20<br />
			重要なお知らせ
			Disney公式携帯ｻｲﾄ会員様への特別企画がｽﾀｰﾄしました!
			第一弾は「ﾃﾞｨｽﾞﾆｰ・ﾒｰﾙﾌｧｸﾄﾘｰ」月額会員様限定へのﾌﾟﾚﾐｱﾑｱﾜｰﾄﾞﾌﾟﾚｾﾞﾝﾄです。
			TOPﾍﾟｰｼﾞ中頃のﾘﾝｸよりご利用ください。
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			-->

			≫1/08<br />
			本日、｢お知らせ｣に表示する内容について､<br />
			下記を削除いたしました｡<br />			                        
			■｢お知らせ｣表示削除内容<br />
			･自分からの招待でﾏｲﾐｸが登録し､ｹﾞｰﾑﾁｹｯﾄをGETした時<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫12/28<br />
			本日、下記のｻｰﾋﾞｽをﾘﾘｰｽいたしました。<br />
			<br />
			「TOPﾍﾟｰｼﾞ」＞「ご当地GET！」でその土地のご当地ｷｬﾗﾀｸﾀｰをGETした際に、ｱﾌﾟﾘから簡単に日記を書ける機能を追加しました。<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫12/25<br />
			本日、下記のｻｰﾋﾞｽをﾘﾘｰｽいたしました。<br />
			<br />
			･のりものﾙｰﾚｯﾄ<br />
			･集めたご当地ｷｬﾗｸﾀｰのﾃﾞｺﾒ素材ﾀﾞｳﾝﾛｰﾄﾞ<br />
			･ﾄﾚｰﾄﾞの上限数を1日3ﾘｸｴｽﾄまでに変更<br />
			<br />
			また、一部のｱﾜｰﾄﾞに正常に付与されない不具合が発生しておりましたので、該当者様には明日のｱｸｾｽ時に自動付与されるよう対応いたしました。ご迷惑をおかけしてしまい、申し訳ございません。<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			≫12/22<br />
			年末年始の弊社ｶｽﾀﾏｰｾﾝﾀｰ営業時間は下記のとおりです｡<br />
			<br />
			平日10:00-19:00<br />
			※年末年始(12/29~1/4)を除く<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫12/16<br />
			ｱﾜｰﾄﾞの付与の取得ﾀｲﾐﾝｸﾞに関しましてお知らせいたします｡<br />
			ｱﾜｰﾄﾞは､条件を満たした日の翌日にｱﾌﾟﾘへｱｸｾｽ頂くと付与されます｡<br />
			<br />
			どんなｱﾜｰﾄﾞが付与されるかは､翌日までお待ちください｡<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			≫12/11<br />
			mixiﾄｯﾌﾟﾍﾟｰｼﾞの｢ｱﾌﾟﾘ更新情報｣に表示する内容について､
			mixi側の仕様によりｱﾌﾟﾘとの時差が発生し､ｱﾌﾟﾘの内容と同期しない案内が
			表示されることがございましたので､次のように機能改善致しました｡<br />
			<br />
			■｢ｱﾌﾟﾘ更新情報｣表示内容<br />
			･ﾏｲﾐｸが当ｱﾌﾟﾘを登録した時<br />
			･ﾏｲﾐｸがご当地ｷｬﾗｸﾀｰを取得した時<br />
			･ﾏｲﾐｸがｱﾜｰﾄﾞを受賞した時<br />
			･ﾄﾚｰﾄﾞﾘｸｴｽﾄを拒否された時<br />
			･当ｱﾌﾟﾘに招待された時<br />
			<br />
			自分に関するお知らせは当ｱﾌﾟﾘTOPの｢お知らせ｣にてご確認ください｡<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			≫12/10<br />
			大変お待たせいたしました｡<br />
			次の機能を本日11:00より再開いたしました｡<br />
			<br />
			･ﾏｲﾐｸ招待<br />
			･ﾏｲﾐｸ招待ｱﾜｰﾄﾞの付与<br />
			<br />
			招待は｢TOPﾍﾟｰｼﾞ≫ﾏｲﾐｸ招待｣よりご利用いただけます｡<br />
			<br />
			ﾏｲﾐｸ招待でもらえる高得点のｱﾜｰﾄﾞ像も準備しておりますので､
			ぜひこの機会にご活用ください｡<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			≫12/8<br />
			｢お知らせ｣に表示する内容について､
			次のように機能改善いたしました｡<br />
			<br />
			■｢お知らせ｣表示内容<br />
			･自分がｱﾜｰﾄﾞを受賞した時<br />
			･自分にﾄﾚｰﾄﾞ依頼が届いている時<br />
			･自分がﾏｲﾐｸに依頼したﾄﾚｰﾄﾞが承認された時<br />
			･自分からの招待でﾏｲﾐｸが登録し､ｹﾞｰﾑﾁｹｯﾄをGETした時<br />
			<br />
			なお､ﾏｲﾐｸからのﾄﾚｰﾄﾞ依頼は｢お知らせ｣に届いたﾒｯｾｰｼﾞを
			ｸﾘｯｸすることで承認･拒否を選択できます｡<br />

			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<div style="text-align:center;">
				<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}' >よくある質問</a><br />
			</div>
			
		</div>
	</body>
</html>      
	  
