{%include file="disney/common/header.phtml"%}

    <div style="font-size:x-small; background-color:#e5fcd0;">
    
    {% disneyimg name="sub_ti_mymic" %}
    <br /><br />
    
      {% foreach from=$friendList item=data %}
	  
		{% if $ua!=3 %}
	  
        <div style="text-align:left;">
        {% if $data.type == 1 %}
            <img copyright="yes" src="{%$staticUrl%}/apps/disney/img/chara_activity/{%$data.icon%}.gif" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" align="left"/>
        {% else %}
            {% disneyimg style='height="40px" width="40px" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" align="left"' name=$data.icon %}
        {% /if %}
        <br />
        <a href='{% "$baseUrl/mobile/disney/profile?CF_uid=`$data.uid`"|mixiurl %}'><span>{%$data.displayName%}</span></a><br/>
        {% if $data.name%}{% emoji code="F99F"%}<span style=" color:#009933;">{%$data.name%}{%if $data.type==1%}ｽﾃｨｯﾁ{%else%}ｱﾜｰﾄﾞ{%/if%}GET!!</span>{% emoji code="F99F"%}<br/>{%/if%}
        </div>
        <div style="clear:both;"></div>
		
		{% else %}
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td style="width:48px;text-align:center;">
				{% if $data.type == 1 %}
            		<img copyright="yes" src="{%$staticUrl%}/apps/disney/img/chara_activity/{%$data.icon%}.gif" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" align="left"/>
        		{% else %}
            		{% disneyimg style='height="40px" width="40px" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" align="left"' name=$data.icon %}
        		{% /if %}</td>
				<td><div style="font-size:x-small; text-align:left;"><span><a href='{% "$baseUrl/mobile/disney/profile?CF_uid=`$data.uid`"|mixiurl %}'><span>{%$data.displayName%}</span></a><br/>
        {% if $data.name%}{% emoji code="F99F"%}<span style=" color:#009933;">{%$data.name%}{%if $data.type==1%}ｽﾃｨｯﾁ{%else%}ｱﾜｰﾄﾞ{%/if%}GET!!</span>{% emoji code="F99F"%}<br/>{%/if%}</span></div></td>
			</tr>
		</table>		
			
		{% /if %}
				
        {% disneyimg name="line1" %}
      {% foreachelse %}
        {% emoji code="F9CE"%}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/disney/mymixilist" %}'>ﾏｲﾐｸ招待</a><br />
      {% /foreach %}  
      
    {%include file="disney/common/pager.phtml"%}
    
{%include file="disney/common/footer.phtml"%}
