{%include file="disney/common/header.phtml"%}
<style type="text/css">
</style>
{% disneyimg name="sub_ti_phone" %}<br />
<div style="background-color:#f8f1df; font-size:x-small;" >
	<div style="color:#5b2806;">
		
		{% emoji code="F8E9"%}<span style="color:#ff3385;">Disney Mobile</span><br />
		全端末<br />
		<br />
		
		{% emoji code="F8E9"%}<span style="color:#ff0000;">DoCoMo</span><br />
		FOMA対応機種(903ｼﾘｰｽﾞ以降)<br />
		<br />
		
		{% emoji code="F8E9"%}<span style="color:#32a123;">au</span><br />
		Flash lite1.1対応のWIN端末<br />
		<br />
		
		{% emoji code="F8E9"%}<span style="color:#611477;">SoftBank</span><br />
		Flash lite1.1対応の3G端末<br />
		<br />
		
		※WILLCOM端末は非対応です<br />
		<br />

		※上記該当端末でも､位置情報通知機能のない端末は､位置情報を利用したｺﾝﾃﾝﾂを正しく遊ぶことができません｡<br />
		<br />
		
		※上記の端末でも一部機種では正常に動作しない挙動が確認されております｡
		ﾌﾟﾚｲ中に不具合が生じた場合は｢提供者に問い合わせる｣より機種情報をお送りいただけますようお願いいたします｡<br />
		
		
	</div>

{%include file="disney/common/footer.phtml"%}