{%include file="disney/common/header.phtml"%}

    <div id="bgcolor1" style="font-size:x-small;background-color:#edd9ae;">
    	<div align="center" style="background-color:#f8f1df;">
    	<div style="background-color:#50b83a; text-align:center; color:#f8f1df;" >
		{% disneyimg name="sub_ti_itemshop" %}<br />
        </div><!--#sitein_link-->
		</div><!--/#center-->
		<a name="top"></a>
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		<span style="color:#630;">ﾁｪｯｸ!で稼いだ移動距離を自動的に数倍伸ばすVIPｱｲﾃﾑ</span><br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		{% disneyimg name="dotline_fff5f5_s" %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
	
		<div class="glass_" style="color:#630;">
		    <img src="{%$staticUrl%}/apps/disney/img/shoes/itemshop3_60.gif" width="60" height="60" align="left" style="float:left; margin-top:0;margin-right:1; margin-left:3; margin-bottom:0" />
			<span>{% emoji code="F99F"%}<span style="color:#36F;">ｶﾞﾗｽの靴</span>{% emoji code="F99F"%}<br />
			■300pt　<a href='{% "$baseUrl/mobile/disney/buyitem/CF_sid/7/CF_from/$from"|mixiurl %}'>購入する</a><br />
			距離が<span style="color:#F00;">10倍以上</span>に伸びる靴<br /></span>
		</div>
		<div style="clear:both"></div>
		
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		{% disneyimg name="dotline_fff5f5_s" %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />

		<div class="gold_" style="color:#630;">
		<span class="glass_" style="color:#630;">
		    <img src="{%$staticUrl%}/apps/disney/img/shoes/itemshop2_60.gif" width="60" height="60" align="left" style="float:left; margin-top:0;margin-right:1; margin-left:3; margin-bottom:0" />
		    </span><span>{% emoji code="F99F"%}<span style="color:#36F;">ｺﾞｰﾙﾄﾞ･ｼｭｰｽﾞ</span>{% emoji code="F99F"%}<br />
			■200pt　<a href='{% "$baseUrl/mobile/disney/buyitem/CF_sid/8/CF_from/$from"|mixiurl %}'>購入する</a><br />
			距離が<span style="color:#F00;">5倍以上</span>に伸びる靴<br /></span>
		</div><!--/.gold_-->
		<div style="clear:both"></div>
		
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		{% disneyimg name="dotline_fff5f5_s" %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		
		
		<div class="glass_" style="color:#630;"><span class="glass_" style="color:#630;">
		    <img src="{%$staticUrl%}/apps/disney/img/shoes/itemshop1_60.gif" width="60" height="60" align="left" style="float:left; margin-top:0;margin-right:1; margin-left:3; margin-bottom:0" />
		    </span><span>{% emoji code="F99F"%}<span style="color:#36F;">快適ｽﾆｰｶｰ</span>{% emoji code="F99F"%}<br />
			■50pt　<a href='{% "$baseUrl/mobile/disney/buyitem/CF_sid/9/CF_from/$from"|mixiurl %}'>購入する</a><br />
			距離が<span style="color:#F00;">2倍以上</span>に伸びる靴<br /></span>
		</div>
		<div style="clear:both"></div>
		
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		{% disneyimg name="dotline_fff5f5_s" %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
	    
{%include file="disney/common/footer.phtml"%}