<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
	<meta http-equiv="pragma" content="no-cache" />
	<meta http-equiv="cache-control" content="no-cache" />
	<meta http-equiv="expires" content="0" />
    <title>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ</title>

</head>
    <body>
		
		<div style="font-size:x-small; background-color:#ffffcc; color:#4e211c; text-align:left;">
		
			お使いの端末は､このｺﾝﾃﾝﾂに対応しておりません｡<br />
			下記ﾍﾟｰｼﾞから対応端末をご確認ください｡<br />
			<br />
			<div style="text-align:center;">
				<a href='{% "$baseUrl/mobile/disney/phone"|mixiurl %}' >対応端末一覧へ</a><br />
				{% disneyimg style='height="3"' name="dot0" %}<br />
				<div style="text-align:center;">-------------</div>
				{% disneyimg style='height="3"' name="dot0" %}<br />
				<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}' >よくある質問</a><br />
			</div>
			
		</div>
	</body>
</html>      
	  