<address id="copyright">&copy; 2009 Community Factory Inc. All Rights Reserved.</address>
    <div id="overlay" style="display:none;"></div><!--/#overlay-->
    <div id="overlay1" style="display:none;"></div>
</div></div></div><!--/#continer-->

<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var pageTracker = _gat._getTracker("UA-1572579-42");
        pageTracker._trackPageview();
    } 
    catch(err) {}
</script>

</body>
</html>
