{%include file="chat/common/header.phtml"%}

<body id="static" class="invite">
<div id="container">
	{%include file="chat/common/nav.phtml"%}

	<div id="mainColumn">
		<div id="inviteBox" class="innerBox">

			<h1><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/tit_edit.png" width="121" height="21" alt="チャット編集" /></h1>
			<div class="inner">

				<form id="frmEdit" name="frmEdit" action="{%$baseUrl%}/chat/edit" method="post" onsubmit="return false;">
					<h2><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/tit_invite_form.png" width="128" height="20" alt="招待フォーム" /></h2>
					<table class="rowTable">
						<tr>
							<th scope="row">チャット名</th>
							<td><input type="text" id="txtName" name="txtName" value="{%$chatName%}" class="inputText" maxlength="20"/></td>
						</tr>
						<tr>
							<th scope="row">開催日時</th>
							<td>
								日程：<input type="text" id="datepicker" name="txtDate" class="inputDate" value="{%$chatDate%}" maxlength="10" />　時刻：
								<select id="selHour" name="selHour">
									<option value="1" {% if "01"==$chatHour %}selected{% /if %}>01</option>
									<option value="2" {% if "02"==$chatHour %}selected{% /if %}>02</option>
									<option value="3" {% if "03"==$chatHour %}selected{% /if %}>03</option>
									<option value="4" {% if "04"==$chatHour %}selected{% /if %}>04</option>
									<option value="5" {% if "05"==$chatHour %}selected{% /if %}>05</option>
									<option value="6" {% if "06"==$chatHour %}selected{% /if %}>06</option>
									<option value="7" {% if "07"==$chatHour %}selected{% /if %}>07</option>
									<option value="8" {% if "08"==$chatHour %}selected{% /if %}>08</option>
									<option value="9" {% if "09"==$chatHour %}selected{% /if %}>09</option>
									<option value="10" {% if "10"==$chatHour %}selected{% /if %}>10</option>
									<option value="11" {% if "11"==$chatHour %}selected{% /if %}>11</option>
									<option value="12" {% if "12"==$chatHour %}selected{% /if %}>12</option>
									<option value="13" {% if "13"==$chatHour %}selected{% /if %}>13</option>
									<option value="14" {% if "14"==$chatHour %}selected{% /if %}>14</option>
									<option value="15" {% if "15"==$chatHour %}selected{% /if %}>15</option>
									<option value="16" {% if "16"==$chatHour %}selected{% /if %}>16</option>
									<option value="17" {% if "17"==$chatHour %}selected{% /if %}>17</option>
									<option value="18" {% if "18"==$chatHour %}selected{% /if %}>18</option>
									<option value="19" {% if "19"==$chatHour %}selected{% /if %}>19</option>
									<option value="20" {% if "20"==$chatHour %}selected{% /if %}>20</option>
									<option value="21" {% if "21"==$chatHour %}selected{% /if %}>21</option>
									<option value="22" {% if "22"==$chatHour %}selected{% /if %}>22</option>
									<option value="23" {% if "23"==$chatHour %}selected{% /if %}>23</option>
									<option value="24" {% if "24"==$chatHour %}selected{% /if %}>24</option>
								</select> 時
								<select id="selMinute" name="selMinute">
									<option value="0" {% if "00"==$chatMinute %}selected{% /if %}>00</option>
									<option value="15" {% if "15"==$chatMinute %}selected{% /if %}>15</option>
									<option value="30" {% if "30"==$chatMinute %}selected{% /if %}>30</option>
									<option value="45" {% if "45"==$chatMinute %}selected{% /if %}>45</option>
								</select> 分
								<p class="note">※終了時間は、開催日時より1時間後となります（延長可能）</p>


								<div style="display: none;" class="demo-description">

								<p>The datepicker is tied to a standard form input field.  Focus on the input (click, or use the tab key) to open an interactive calendar in a small overlay.  Choose a date, click elsewhere on the page (blur the input), or hit the Esc key to close. If a date is chosen, feedback is shown as the input's value.</p>

								</div><!-- End demo-description -->
							</td>
						</tr>
						<tr>
							<th scope="row">メッセージ</th>
							<td><textarea rows="5" id="txtMessage" name="txtMessage">{%$chatMessage|escape%}</textarea></td>
						</tr>
					</table>

					<div id="memberWrap">
					<h2><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/tit_invite_member_select.png" alt="招待メンバー選択" /></h2>
					<div id="memberSearch" class="clearfix">
						<div class="searchInner"><input type="text" id="memberSearchForm" /></div>
						<div class="description">ここに「ニックネーム」を入力してください。</div>
						<div id="divError" style="color: red; padding-left: 10px; display: none;">検索結果なし</div>
					</div>

    				<ul id="frameNav"><!--
    					--><li id="frameNavLeft"><a id="btnLeft" href="javascript:void(0);"><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/frameNav_left.png" width="18" height="143" alt="左" /></a></li><!--
    					--><li id="frameNavRight"><a id="btnRight" href="javascript:void(0);"><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/frameNav_right.png" width="18" height="143" alt="右" /></a></li><!--
    				--></ul>
    				<div id="memberFrame">
    					<div id="innaerFrame" style="width:990000px">
    					</div>
    				</div>
    				<input type="hidden" id="hidFriendCnt" value="{%$friendCount%}" />
    				<input type="hidden" id="cid" name="cid" value="{%$cid%}" />
    				<input type="hidden" id="curDate" value="{%$curDate%}" />
    				<input type="hidden" id="hidSearch" value=" " />
					<div id="divMask" class="filterOff"></div>
					</div><!--/#memberWrap-->

					<h2><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/tit_invite_member_resalt.png" alt="招待メンバー一覧" /></h2>
					<div id="memberList">
						<ul id="ulSelected"><!--
							{% foreach name=selectedList from=$lstMemCon item=pdata key=index %}
							{% if $pdata.uid=="0" %}
							--><li id="liSel{%$index%}" class="null">選択されていません</li><!--
							{% else %}
							  {% if $pdata.ismember=="1" %}
							  --><li id="liSel{%$index%}" class="selected"><p><span>{%$pdata.displayName%}</span><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/spacer.gif" width="76" height="76" alt="{%$pdata.displayName%}" style="background-image:url({%$pdata.thumbnailUrl%})" /></p><input name="chkMem[]" type="hidden" value="{%$pdata.uid%}" /></li><!--
							  {% else %}
							  --><li id="liSel{%$index%}" class="selected"><p><span>{%$pdata.displayName%}</span><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/spacer.gif" width="76" height="76" alt="{%$pdata.displayName%}" style="background-image:url({%$pdata.thumbnailUrl%})" /><a href="javascript:void(0);" onclick="doCancelSel('liSel{%$index%}');" title="選択解除">選択解除</a></p><input name="chkMem[]" type="hidden" value="{%$pdata.uid%}" /></li><!--
							  {% /if %}
							{% /if %}
							{% /foreach %}
						--></ul>
					</div>

    				<ul class="btnList"><!--
    					--><li><a href="javascript:void(0);" id="btnEdit"><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/btn_edit.png" width="228" height="34" alt="修正する" /></a></li><!--
    				--></ul>
				</form>

			</div><!--/.inner-->
		</div><!--/.innerBox-->

		<div id="xxxxBox" class="innerBox">
			<h1><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/tit_chat_cancel.png" width="179" height="21" alt="チャットを取り消し" /></h1>
			<div class="inner">
				<ul class="btnList"><!--
					--><li><a href="{%$baseUrl%}/chat/del?cid={%$cid%}"><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/btn_chat_cancel.png" width="228" height="34" alt="チャットを取り消しする" /></a></li><!--
				--></ul>
			</div><!--/.inner-->
		</div><!--/.innerBox-->

	</div><!--/#mainColumn-->

	<div id="subColumn">
		{%include file="chat/common/subcolumn.phtml"%}
	</div><!--/#subColumn-->

	<div id="dialog" title="メッセージ"><p style="text-align:center;padding-top:20px" id="pMessage"></p></div>

	<script type="text/javascript" src="{%$staticUrl%}/apps/chat/cmn/js/edit.js?{%$version.js%}"></script>
{%include file="chat/common/footer.phtml"%}
