{%include file="chat/common/header.phtml"%}

<body id="static" class="invite">
<div id="container">
	{%include file="chat/common/nav.phtml"%}

	<div id="mainColumn">

		<div id="diaryBox" class="innerBox">
			Welcome!!<br />
			Flash !! Flash【ガイダンス】※Flashコンテンツ
			<br />TODO TODO!!<br />
			<a href="/chat/index">chat Index page</a>
		</div><!--/.innerBox-->

	</div><!--/#mainColumn-->

	<div id="subColumn">
		{%include file="chat/common/subcolumn.phtml"%}
	</div><!--/#subColumn-->

	<script type="text/javascript">
    	adjustHeight();
	</script>
{%include file="chat/common/footer.phtml"%}
