<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>パーキングウォー</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />

	<link rel="stylesheet" href="{%$staticUrl%}/apps/parking/css/import.css" type="text/css" media="print,screen" />
</head>
<body id="error">

<div id="continer">
	<div id="mainArea">
		<img src="cmn/img/error.png" alt="" width="945" height="210" usemap="#Map" />
		<map name="Map" id="Map"><area shape="rect" coords="2,159,618,208" target="_top" href="http://platform001.mixi.jp/run_appli.pl?id=507" alt="パーキングのページに戻る" />
		</map>
	</div><!--/#mainArea-->
	
	<address id="copyright">&copy; 2009 LinNo Inc. All Rights Reserved. - <a href="">広告のお問い合わせ</a> - <a href="">提供アプリ一覧</a> - Powered by <a href="">カーセンサーnetWebサービス</a></address>
	
</div><!--/#continer-->
</body>
</html>
