
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ｱｼﾞﾄについて<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            このｹﾞｰﾑにﾁｬﾚﾝｼﾞする勇敢なﾕｰｻﾞｰには、1つのｱｼﾞﾄと4人のﾋｯﾄﾏﾝを与えよう。<br />
            <br />
            ﾋｯﾄﾏﾝの体力は、時間とともに回復していくが、体力が0になってしまうと殉職してしまい、戦線を離脱してしまうぞ。<br />
            <br />
            ｱｼﾞﾄを守っている4人のﾋｯﾄﾏﾝが全員殉職してしまうと、GAMEOVERになってしまい、所持金が半分に減ってしまうから、気をつけろ!!<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->