
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾋｯﾄﾏﾝを雇う<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            ﾋｯﾄﾏﾝは、個性豊かなｷｬﾗｸﾀｰが全部で10種類用意されている。<br />
            <br />
            所持金の総額に応じて、より強いﾋｯﾄﾏﾝが力を貸してくれるようになるぞ！<br />
            <br />
            最強のﾋｯﾄﾏﾝを集めて、ﾏｲﾐｸからｱｼﾞﾄを守り切れっ!<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->