
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾋｯﾄﾏﾝの回復と蘇生<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
			ﾀﾞﾒｰｼﾞを負ったﾋｯﾄﾏﾝの体力は、時間とともに回復していくが、時にはｱｲﾃﾑ（元気ﾄﾞﾘﾝｸetc）を使って、日ごろの労をねぎらい、体力を回復させてあげるのも、BOSSのつとめというものだ。<br />
            <br />
			殉職してしまったﾋｯﾄﾏﾝも、72時間の眠りの後に回復するのだが、ｱｲﾃﾑ（復活の儀式etc）を使って、再び戦線へと復活させれば、BOSSの為に命を捧げたﾋｯﾄﾏﾝ達の魂も報われることだろう。<br />
            <br />
			ｱｲﾃﾑの中には、自分のｱｼﾞﾄの全てのﾋｯﾄﾏﾝの体力を完全に回復し、殉職したﾋｯﾄﾏﾝをも復活させてしまう奇跡のｱｲﾃﾑが存在するらしい。<br />
            <br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->