
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾋｯﾄﾏﾝの強さ<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            どのﾋｯﾄﾏﾝを雇うかで勝負の分かれ目になる。ここではﾋｯﾄﾏﾝを雇うにあたって、その強さの判断基準を説明しよう!<br />
            <br />
            ｽﾋﾟｰﾄﾞの値が高いﾋｯﾄﾏﾝは、ﾀﾞｲﾅﾏｲﾄを設置後の攻撃力増加時間が短くなるぞ!<br />
            <br />
            体力の値が高いﾋｯﾄﾏﾝは、多少のﾀﾞﾒｰｼﾞにも耐えられるﾀﾌなﾎﾞﾃﾞｨをもっている!<br />
            <br />
            回復力の値が高いﾋｯﾄﾏﾝは、ﾀﾞﾒｰｼﾞを受けた後、時間の経過とともに回復するｽﾋﾟｰﾄﾞが高速だ!<br />
            <br />
            攻撃を重視しているときは、ｽﾋﾟｰﾄﾞの高いﾋｯﾄﾏﾝを。ｹﾞｰﾑから離れるときは、体力の値が高いﾋｯﾄﾏﾝを雇うと、このﾊﾞﾄﾙに勝ち抜けるかもしれない…。<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->