    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            このｹﾞｰﾑの遊び方<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="intro" style="text-align:center;">
            <object data="{%$staticUrl%}/apps/dynamite/mobile/swf/splash.swf" type="application/x-shockwave-flash" width="210" height="160">
                <param name="bgcolor" value="FFFFFF" />
                <param name="loop" value="off" />
                <param name="quality" value="high" />
                <embed src="{%$staticUrl%}/apps/dynamite/mobile/swf/splash.swf" width="210" height="160" loop="off" quality="high" bgcolor="#FFFFFF"></embed>
            </object>
        </div><!--/.intro-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            時間とともに破壊力が増大する特殊なダイナマイト爆弾を使ったマイミク同士の、仁義なきバトルロワイヤル!!<br />
            <br />
            個性豊かなヒットマンを雇って、自分のアジトを守り抜けっ!<br />
            <br />
            バレないようにダイナマイトを仕掛け、マイミクのアジトを爆破せよ!!<br />
            <br />
            アイテムを駆使して自分のアジトを守りつつ、マイミクのヒットマンにかけられた懸賞金を奪い取れ!<br />
            <br />
            目には目を、裏切り者には報復を!!<br />
            <br />
            この終わりなき闘争に終止符を打つのは誰だ!?<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->