
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            お問い合わせ対応について<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
			ﾕｰｻﾞｰの皆様から頂戴したお問い合わせに関し､担当者が1件1件目を通し“必ず”返信をさせていただいております｡<br />
			<br />
			ただし､お客様が以下ﾄﾞﾒｲﾝでのﾒｰﾙ受信を許可していない場合､せっかくお問い合わせいただいたにも関わらず､弊社担当者が返信できないことがございます｡<br />
			<br />
			<form method="get" action="#"><input type="text" value="communityfactory.com" style="color:#000;background:#fff;" /></form><br />
			<br />
			もしも､｢問い合わせをしたのに返信がない!｣と､お心当たりがある場合は､上記のﾄﾞﾒｲﾝのﾒｰﾙを受信できるように設定し､再度お問い合わせの送信をお願いいたします｡<br />
			<br />
			なお､ｻﾎﾟｰﾄｺﾐｭﾆﾃｨに関しては､原則､返信を行っておりませんので､回答をお求めの場合は､ﾒｰﾙにてお問い合わせいただけたら幸いです｡<br />
			<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">※「←」or「戻るﾎﾞﾀﾝ」で､前の画面に戻ってください</div><!--/.description-->

    </div><!--/#help-->