
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ｱｲﾃﾑ説明<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="section" style="background:#000000;">
            <table width="100%" cellpadding="0" cellspacing="0" border="0">
                <tr>
                    <td width="60" valign="top" align="center" style="width:56px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/item/10.gif" width="56" height="56" style="margin:2px 0;" /></td>
                    <td style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">神々の怒り</td>
                </tr>
            </table>

            <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

            <table width="228" cellpadding="2" cellspacing="1" border="0" style="background:#eeaa55;text-align:center;">
                <tr>
                    <td style="background:#fffdde;color:#000000;text-align:left;"><span style="color:#000000;">【アイテム効果】<br />最強のヒットマンが怒りの制裁を与える！</span></td>
                </tr>
            </table>

        </div><!--/.section-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">※「←」or「戻るﾎﾞﾀﾝ」で､前の画面に戻ってください</div><!--/.description-->

    </div><!--/#help-->