
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ｱｲﾃﾑを手に入れるには?<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            ｱｲﾃﾑ以下の方法で手に入れることができるぞ!!<br />
            <br />
            (1)敵対ﾋｯﾄﾏﾝ撃破でもらえる爆破ﾎﾞｰﾅｽ<br />
            (2)1日1回の訪問でもらえるﾋﾞｼﾞﾀｰｷﾞﾌﾄ<br />
            <br />
            爆破ボーナスは、貴重なアイテムを何回も手に入れる貴重なチャンスだ！<br />
            <br />
            確実に一発で仕留められるよう、狙いすまして敵ヒットマンを爆破せよ!!<br />
            <br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}
        
    </div><!--/#help-->
