
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            その他 Q&A<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">知らない人(ﾕｰｻﾞｰ)から攻撃されて困っています</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">｢ﾏｲﾐｸｼｪﾙﾀｰ｣というｱｲﾃﾑを使うと、ﾏｲﾐｸ限定でのﾊﾞﾄﾙが楽しめます｡ｱﾅﾀを知らないﾏｲﾐｸから攻撃されることはありません｡ただし､使用後はｱﾅﾀもﾏｲﾐｸ以外攻撃できなくなりますのでご注意ください。｢ﾏｲﾐｸｼｪﾙﾀｰ｣を使用するには､このｹﾞｰﾑに参加しているｱﾅﾀのﾏｲﾐｸが5人必要です。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">1度｢ﾏｲﾐｸ限定｣に変更したら､｢ﾐｸｼｨ全体｣でのﾊﾞﾄﾙﾛﾜｲｱﾙには参加できませんか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">いいえ。｢宣戦布告｣というｱｲﾃﾑを使うと､ﾐｸｼｨ全体でのﾊﾞﾄﾙが楽しめます｡ただし、ｱﾅﾀの知らないﾕｰｻﾞｰから攻撃されることがありますので、使用の際は十分に注意してください。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">弱い者ｲｼﾞﾒをしていいんですか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ｱﾅﾀを知らない人にﾀﾞｲﾅﾏｲﾄを仕掛けることは可能ですが、すべて自己責任でﾌﾟﾚｲしてください｡弱い者ｲｼﾞﾒしすぎると､あとで後悔することになるかもしれません。できれば､ｱﾅﾀと同じくらいの強さのﾕｰｻﾞｰと競い合うのがいいかもしれませんよ…｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾏｲﾐｸを招待したのですがｱｲﾃﾑがもらえません</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾏｲﾐｸ招待でもらえるｱｲﾃﾑは、ﾏｲﾐｸを招待した時点でもらえるのではなく、招待したﾏｲﾐｸが当ｱﾌﾟﾘを追加し、訪問したときに支給されます。ただし、1度でも登録したことがあるﾕｰｻﾞｰを招待しても、ｱｲﾃﾑはもらえませんので、ご注意ください。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾏｲﾐｸｼｪﾙﾀｰと宣戦布告は使用後にまた補充されますか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">いいえ｡ﾏｲﾐｸｼｪﾙﾀｰと宣戦布告は､頻繁に利用するとｹﾞｰﾑ内での成績に影響を与えるため､すべてのﾕｰｻﾞｰ様に2つずつ配布しています｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾏｲﾐｸｼｪﾙﾀｰを使用し､ﾏｲﾐｸﾓｰﾄﾞに切り替えた場合､設置中のﾀﾞｲﾅﾏｲﾄはどうなりますか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">無くなります。これは、ﾏｲﾐｸｼｪﾙﾀｰ内では､ﾏｲﾐｸ以外のﾕｰｻﾞｰ様に攻撃ができないためです。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾀﾞｲﾅﾏｲﾄはいつ補充されますか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾀﾞｲﾅﾏｲﾄは､未使用ﾀﾞｲﾅﾏｲﾄのすべてを設置し､それら全部を爆破した時点で新しく補充されます｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾋｯﾄﾏﾝを変更すると、設置中のﾀﾞｲﾅﾏｲﾄはどうなりますか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">設置中のﾀﾞｲﾅﾏｲﾄはそのままですが、その時点で蓄積された破壊力が「0」に戻ってしまいますのでご注意ください｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">復活のｼｬﾜｰ､復活の儀式を持っていたのに､ｱｼﾞﾄが壊滅してしまいました</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">復活のｼｬﾜｰ､復活の儀式は所有しているだけでは効力はありません｡それぞれ使用した時点で､その効果は適用されますのでご注意ください｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾀﾞｲﾅﾏｲﾄほいほいはｱｼﾞﾄのﾋｯﾄﾏﾝ全員に適用されますか?また､没収したﾀﾞｲﾅﾏｲﾄはどうなりますか?</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ﾀﾞｲﾅﾏｲﾄほいほいは自分のｱｼﾞﾄの4人のﾋｯﾄﾏﾝ全員に適用されます。なお没収したﾀﾞｲﾅﾏｲﾄについては自分の未使用ﾀﾞｲﾅﾏｲﾄに追加されていきます。ただし、設置済みﾀﾞｲﾅﾏｲﾄと未使用ﾀﾞｲﾅﾏｲﾄの合計数が26個を超えると、没収したﾀﾞｲﾅﾏｲﾄは自分のﾀﾞｲﾅﾏｲﾄに追加されることなく消滅していきます｡</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ｱｼﾞﾄのﾀﾞｲﾅﾏｲﾄが撤去出来ない</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ｱｼﾞﾄに設置されたﾀﾞｲﾅﾏｲﾄは爆破までの待機時間（ﾋｯﾄﾏﾝのｽﾋﾟｰﾄﾞによって異なる）が経過するまで、撤去する事が出来ません。ただし、撤去時の破壊力（数字）が既に表示されている状態のﾀﾞｲﾅﾏｲﾄについては、設置された瞬間に撤去する事が出来ます。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">TOPﾍﾟｰｼﾞで表示される所持金とﾗﾝｷﾝｸﾞで表示される自分の所持金額が違う</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">現在、ﾗﾝｷﾝｸﾞのﾃﾞｰﾀは負荷対策の為、10分に1回の更新となっております。申し訳ございませんが、ご了承ください。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <div class="section">
            <table width="100%" cellpadding="2" cellspacing="0" border="0">
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">久々にﾌﾟﾚｲしたら全滅していて、所持金が半分以下になっていた。</td>
                </tr>
                <tr>
                    <td width="20" valign="top" align="center" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
                    <td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;">ｱｼﾞﾄ壊滅後72時間が経過すると、壊滅させられたﾕｰｻﾞｰ様がｱﾌﾟﾘにﾛｸﾞｲﾝしなくても勝手にｱｼﾞﾄが再結成される仕様となっております。申し訳ございませんが、何卒ご理解下さい。</td>
                </tr>
            </table>
            <hr style="color:#666666;background-color:#666666;height:1px;border:0px solid #666666;margin:0.3em 0;" size="1" />
        </div><!--/.section-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->