
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾀﾞｲﾅﾏｲﾄの撤去<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            自分のｱｼﾞﾄに設置されてしまったﾀﾞｲﾅﾏｲﾄは、爆破される前に見つけることができれば撤去可能だ!<br />
            <br />
            撤去したﾀﾞｲﾅﾏｲﾄは、撤去した時点での破壊力（数字）のまま、他のﾕｰｻﾞｰのｱｼﾞﾄに仕掛けることもできるので、ﾍﾞｽﾄなﾀｲﾐﾝｸﾞを考えて撤去せよっ。ﾏｲﾐｸを出し抜くには撤去した爆弾の再設置が一番だ！<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->
