
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾀﾞｲﾅﾏｲﾄの設置と爆破<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
            最初にﾀﾞｲﾅﾏｲﾄを4つ与えるから、上手に使うんだ。もし全部のﾀﾞｲﾅﾏｲﾄを使い切ってしまったら、また4つのﾀﾞｲﾅﾏｲﾄを支給するから、安心してﾊﾞﾄﾙに挑んでくれ!!<br />
            <br />
            ﾀﾞｲﾅﾏｲﾄは、最大で26個まで持つことができるぞ!<br />
            <br />
            他のｱｼﾞﾄにﾀﾞｲﾅﾏｲﾄを設置すると、時間とともに破壊力（数字）が上昇して行くぞ!<br />
			※最大「5」まで上昇します<br />
            <br />
            爆破ボタンを押すと、その時点で設置されているﾀﾞｲﾅﾏｲﾄの破壊力（数字）を全て合算したﾀﾞﾒｰｼﾞを与えることができるぞ！だから、じっくり威力を高めつつ、ﾀｲﾐﾝｸﾞを見計らって爆破するんだ!!（のんびりしてると、敵のﾋｯﾄﾏﾝに撤去されてしまうから気をつけろ！）<br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->