
    <div id="help">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">
            ヘルプ<br />
            <hr style="color:#ffffff;background-color:#ffffff;height:1px;border:0px solid #ffffff;margin:0.3em 0;" size="1" />
            ﾏｲﾐｸﾓｰﾄﾞの切り替え<br />
        </div><!--/.headline-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
			ｱｲﾃﾑ「ﾏｲﾐｸｼｪﾙﾀｰ」を使用すると、ﾏｲﾐｸ対戦ﾓｰﾄﾞに切り替えることが出来るぞ!<br />
			ｱｲﾃﾑ「宣戦布告」を使用することで、元の全体対戦ﾓｰﾄﾞに戻すことも出来る。<br />
			<br />
			これらのｱｲﾃﾑは使用できる回数が決まっているので、戦略的に使ってみよう!<br />
			<br />
			※ﾏｲﾐｸ対戦ﾓｰﾄﾞとは<br />
			ﾀﾞｲﾅﾏｲﾄの設置・撤去・爆破が「ﾏｲﾐｸのみ」で可能になります。<br />
			つまり、ﾏｲﾐｸ以外のﾕｰｻﾞｰから攻撃を受けることがなくなります。<br />
			ただし、ﾏｲﾐｸが5人以上いなければ、ﾏｲﾐｸ対戦ﾓｰﾄﾞには出来ません。 <br />
            <br />
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {%include file="dynamite/common/totop.phtml"%}

    </div><!--/#help-->