{%include file="board/common/header.phtml"%}
{% if $step=="start" %}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url({% $designSetting.bgImage %});">
    <a id="pagetop" name="pagetop"></a>
    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
    {%include file="board/common/ad_header.phtml"%}
    <div id="contribution">
        <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#{% $designSetting.reverseText %};">ｺﾒﾝﾄを書き込む</div>
                <div class="description">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                            ｺﾒﾝﾄを入力し､[確認]をおしてください｡<br />
                      {% if $board.errcomment == 1 %}
                                                ・ｺﾒﾝﾄが未入力です<br />
                      {% /if %}
                      {% if $board.errcomment == 2 %}
                                                ・ｺﾒﾝﾄは全角100文字以内で入力してください<br />
                      {% /if %}
                    <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
                </div><!--/.description-->
            <form method="post" action='?guid=ON&url={%$url%}'>
                <div class="target">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○宛先</span><br />
                    <table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
                        <tr>
                            <td style="width:44px;text-align:center;"><img src="{%$ownerInfo.miniThumbnailUrl%}" /></td>
                            <td style="text-align:left;"><span style="color:#{%$designSetting.normalText%};font-size:x-small;">{% $title %}{% if $commentedCount %} ({%$commentedCount%}) {% /if %}</span></td>
                        </tr>
                    </table>
                </div><!--/.target-->
                <div class="comment">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○ｺﾒﾝﾄ内容</span><br />
                    <textarea id="postComment" name="postComment" rows="3">{%$board.content%}</textarea>
                    <div class="warn" style="text-align:right;">※全角100文字以内</div>
                </div><!--/.comment-->
                <div class="btn" style="text-align:center;">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <input type="submit" value="確 認" /><br />
                    <input type="hidden" name="CF_uid" value="{%$ownerId%}" />
                    <input type="hidden" name="CF_step" value="confirm" />
                </div><!--/.btn-->
            </form><!--/#contribute-->
            <div style="text-align:center;">
                <form method="post" action='?guid=ON&url={%$cancelUrl%}'>
                    <input type="hidden" name="CF_uid" value="{%$ownerId%}" />
                    <input type="submit" value="ｷｬﾝｾﾙ" />
                </form>
            </div>
        </div><!--/#contribution-->
        {%include file="board/common/ad_footer.phtml"%}
        {%include file="board/common/footer.phtml"%}
{% /if %}
{% if $step=="confirm" %}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">

    <a id="pagetop" name="pagetop"></a>

    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">

        <div id="contributionConfirm">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#{% $designSetting.reverseText %};">入力内容の確認</div>
            <div class="description">
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                    次の内容を確認し､よろしければ[送信]をおしてください｡
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
            <form id="contributeConfirm" name="contributeConfirm" method="post" action='?guid=ON&url={%$url%}'>
                <div class="target">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○宛先</span><br />
                    <table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
                        <tr>
                            <td style="width:44px;text-align:center;"><img src="{%$ownerInfo.miniThumbnailUrl%}" /></td>
                            <td style="text-align:left;"><span style="{% if $ua==1 %}font-size:x-small;{% /if %}">ニックネームは{%$ownerInfo.displayName%}のあしあと帳</span></td>
                        </tr>
                    </table>
                </div><!--/.target-->
                <div class="comment">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○ｺﾒﾝﾄ内容</span><br />
                        {%$confirmContent|escape|nl2br|unescape_emoji%}
                </div><!--/.target-->
                <div class="btn" style="text-align:center;">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <input type="hidden" id="postComment" name="postComment" value="{%$confirmContent%}" />
                    <input type="submit" value="送 信" />
                </div><!--/.btn-->
            </form><!--/#contributeConfirm-->
            <div style="text-align:center;">
                <form method="post" action='?guid=ON&url={%$cancelUrl%}'>

                    <input type="submit" value="戻 る" />
                </form>
            </div>
        </div><!--/.contributionConfirm-->

        {%include file="board/common/footer.phtml"%}
{% /if %}
{% if $step=="complete" %}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url({% $designSetting.bgImage %});">
    <a id="pagetop" name="pagetop"></a>
    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
        <div id="contributionComplete">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#{% $designSetting.reverseText %};">ｺﾒﾝﾄ送信完了</div>
            <div class="description">
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                    ｺﾒﾝﾄの送信が完了しました｡<br />
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
        </div><!--/#contributionComplete-->

        {%include file="board/common/ad_complete.phtml"%}

        <div id="footLink" style="color:#{% $designSetting.linkText %};">
            {% emoji code="F8F9"%}<a href='{% "$baseUrl/mobile/board/list?CF_uid=`$ownerInfo.uid`"|mixiurl %}'>{%$ownerInfo.displayName%}さんのあしあと帳</a><br />
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="3" /><br />
        </div><!--/#footLink-->
        {%include file="board/common/menu.phtml"%}
        {%include file="board/common/recommend.phtml"%}
        {%include file="board/common/footer.phtml"%}
{% /if %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>無題ドキュメント</title>
</head>

<body>
</body>
</html>
