{%include file="board/common/header.phtml"%}
<body style="background-color:#{% $designSetting.bg_color %};background-image:url({% $designSetting.bgImage %});">
	<a id="pagetop" name="pagetop"></a>
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="designPreview">
			<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
			<div class="headline" style="background:#{% $designSetting.tplColor_i %};color:#{% $designSetting.reverseText %};">ﾃﾞｻﾞｲﾝﾌﾟﾚﾋﾞｭｰ</div>
			<div class="description">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				変更後のﾃﾞｻﾞｲﾝは次のようになります｡<br />
			</div><!--/.description-->

			<div id="templateBody" style="background-color:#{% $newSkinInfo.bg_color %};background-image:url({% $newSkinInfo.bgImage %});">

				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />

				<div id="templateHead" style="text-align:center;">
					<img src="{%$staticUrl%}/apps/board/mobile/{% $newSkinInfo.tpl_head_path%}" width="{% $newSkinInfo.tpl_head_width%}" height="{% $newSkinInfo.tpl_head_height%}" style="margin:2px;" />
				</div><!--/#templateHead-->

				<div id="header">
					<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
					<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/board/mobile/img/avator.gif" /></td>
							<td style="text-align:left;"><span style="{% if $ua==1 %}font-size:x-small;{% /if %}">ﾃﾞｻﾞｲﾝﾌﾟﾚﾋﾞｭｰ</span></td>
						</tr>
					</table>
				</div><!--/#header-->

				<div id="description">
					<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
					<table width="228" cellpadding="2" cellspacing="0" border="0" align="center" style="text-align:center;">
						<tr>
							<td style="background:#ffffff;text-align:left;">ここに紹介文が表示されます｡</td>
						</tr>
					</table>
				</div><!--/#description-->

				<div id="tabMenu">
					<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
					<div class="inner" style="background:#{% $newSkinInfo.tpl_color_i %};">
					<table width="100%" cellpadding="2" cellspacing="0" border="0">
						<tr>
							<td style="width:50%;background:#{% $newSkinInfo.tpl_color_i %};text-align:center;"><span style="color:#{% $newSkinInfo.reverse_text %};{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F987"%}掲示板</span></td>
							<td style="width:50%;background:#{% $newSkinInfo.tpl_color_ii %};text-align:center;"><span style="color:#{% $newSkinInfo.tpl_color_i %};{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F989"%}投稿履歴</span></td>
						</tr>
					</table>
					<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /><br />
					</div><!--/.inner-->
				</div><!--/#tabMenu-->

				<div id="contentCount">
					50件中 1-10件<br />
					<div class="line" style="background:#{% $newSkinInfo.tpl_color_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
				</div><!--/#contentCount-->

				<div id="comment">

					<div class="section" style="background:#{% $newSkinInfo.list_colorA %};">
						<span style="color:#{% $newSkinInfo.link_text %};">▼</span><span style="color:#{% $newSkinInfo.link_text %};">[1]</span><span style="color:#{% $newSkinInfo.normal_text %};">2011/12/25 12:34</span><br />
						<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/board/mobile/img/avator.gif" /></td>
								<td style="text-align:left;"><span style="color:#{% $newSkinInfo.link_text %};{% if $ua==1 %}font-size:x-small;{% /if %}">○○さん</span></td>
							</tr>
						</table>
						<div class="comment" style="color:#{% $newSkinInfo.normal_text %};">
							ここにコメントが表示されます。<br />
						</div><!--/.comment-->
						<div class="line" style="background:#{% $newSkinInfo.tpl_color_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
					</div><!--/.section-->

					<div class="section" style="background:#{% $newSkinInfo.list_colorB %};">
						<span style="color:#{% $newSkinInfo.link_text %};">▼</span><span style="color:#{% $newSkinInfo.link_text %};">[1]</span><span style="color:#{% $newSkinInfo.normal_text %};">2011/12/25 12:34</span><br />
						<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/board/mobile/img/avator.gif" /></td>
								<td style="text-align:left;"><span style="color:#{% $newSkinInfo.link_text %};{% if $ua==1 %}font-size:x-small;{% /if %}">○○さん</span></td>
							</tr>
						</table>
						<div class="comment" style="color:#{% $newSkinInfo.normal_text %};">
							ここにコメントが表示されます。<br />
						</div><!--/.comment-->
						<div class="line" style="background:#{% $newSkinInfo.tpl_color_ii %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
					</div><!--/.section-->

				</div><!--/#comment-->
				<div id="templateFoot" style="text-align:center;">
					<img src="{%$staticUrl%}/apps/board/mobile/{% $newSkinInfo.tpl_foot_path %}" width="{% $newSkinInfo.tpl_foot_width %}" height="{% $newSkinInfo.tpl_foot_height %}" style="margin:2px 0;" />
				</div><!--/#templateFoot-->
			</div><!--/#templateBody-->
		</div><!--/#designPreview-->

		<div id="previewSetting">
			<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
			<div class="description">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				このﾃﾞｻﾞｲﾝに変更しますか?<br />
			</div><!--/.description-->
			<div class="submit" style="color:#e73598;">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				⇒<a href='{% "$baseUrl/mobile/board/designcomplete?CF_skin=$selectSkin"|mixiurl %}'>変更する</a><br />
				⇒<a href='{% "$baseUrl/mobile/board/design"|mixiurl %}'>ﾃﾞｻﾞｲﾝ一覧</a><br />
			</div><!--/.submit-->
			<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
		</div><!--/#designSetting-->

		{%include file="board/common/footer.phtml"%}