{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">
	<a id="pagetop" name="pagetop"></a>
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="customDesignComplete">
		<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
		<div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#{% $designSetting.reverseText %};">ﾃﾞｻﾞｲﾝ変更完了</div>
		<div class="description">
			<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />ﾃﾞｻﾞｲﾝの変更が完了しました｡<br/>
			<div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
		</div><!--/.description-->
	</div>

	{%include file="board/common/ad_complete.phtml"%}

	<div id="footLink" style="color:#{% $designSetting.linkText %};">
		{% emoji code="F8F9"%}<a href='{% "$baseUrl/mobile/board?CF_uid=`$ownerInfo.uid`"|mixiurl %}'>{% $ownerInfo.displayName %}さんのあしあと帳</a><br />
		<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="3" /><br />
	</div><!--/#footLink-->


	{%include file="board/common/menu.phtml"%}
	{%include file="board/common/recommend.phtml"%}
	{%include file="board/common/ad_footer.phtml"%}
	{%include file="board/common/footer.phtml"%}

