{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url({% $designSetting.bgImage %});">
    <a id="pagetop" name="pagetop"></a>

    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">

        {%include file="board/common/ad_header.phtml"%}

        <div id="designList">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="3" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#{% $designSetting.reverseText %};">ﾃﾞｻﾞｲﾝ変更</div>
            <div class="description">
				あしあと帳のﾃﾞｻﾞｲﾝが変更できます｡お好みのﾃﾞｻﾞｲﾝを選択してください｡</br>
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
            <div id="contentCount">
                6件中 1-6件<br />
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/#contentCount-->

            {%foreach from=$skinInfo item=rowdata key=index%}
            <div class="section" {%if ($index%2)==0%}style="background:#{% $designSetting.listColorA %};"{%else%}style="background:#{% $designSetting.listColorB %};"{%/if%}>
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                <table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
                    <tr>
                        <td style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/board/mobile/img/template/{%$rowdata.pic%}/thumb.gif" width="40" height="40" /></td>
                        <td style="text-align:left;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{%$rowdata.name%}</div>
                            {%if $skinId == $rowdata.pic%}
	                            <div style="text-align:right;">使用中</div>
                            {%else%}
	                            <div style="text-align:right;"><a style="color:#{% $designSetting.linkText %};" href='{% "$baseUrl/mobile/board/designconfirm?CF_skin=`$rowdata.pic`"|mixiurl %}'>ﾌﾟﾚﾋﾞｭｰで確認</a></div>
                            {%/if%}
                        </td>
                    </tr>
                </table>
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
            </div><!--/.section-->
            {%/foreach%}
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
        </div><!--/#designList-->

{%include file="board/common/menu.phtml"%}
{%include file="board/common/ad_footer.phtml"%}
{%include file="board/common/recommend.phtml"%}
{%include file="board/common/footer.phtml"%}