{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">
	<a id="pagetop" name="pagetop"></a>

    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">

        {%include file="board/common/ad_header.phtml"%}

        <div id="friendList">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="3" /><br />
            <div class="headline" style="background:#{% $designSetting.tplColor_i %};color:#ffffff;">ﾏｲﾐｸ一覧({% $count %})</div>
            <div class="description">
            {% if $friendList %}
                                ﾏｲﾐｸのあしあと帳にｺﾒﾝﾄを残そう!<br />
            {% else %}
                                まだﾏｲﾐｸがいません<br />
            {% /if %}
                <div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->

            {% if $friendList %}
            <div id="contentCount">
                {% $count %}件中 {% $listCount.startCount %}-{% $listCount.endCount %}件<br />
                <div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/#contentCount-->
            {% foreach from=$friendList item=friend key=index%}
            <div class="section" {%if ($index%2)==0%}style="background:#{% $designSetting.listColorA %};"{%else%}style="background:#{% $designSetting.listColorB %};"{%/if%}>
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                <table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
                    <tr>
                        <td style="width:44px;text-align:center;">
                            {%if !$friend.miniThumbnailUrl%}
                                <img src="http://img.mixi.jp/img/basic/common/noimage_member40.gif" />
                            {%else%}
                                <img src="{%$friend.miniThumbnailUrl%}" />
                            {%/if%}
                        </td>
                        <td style="text-align:left;">
                            <div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><a style="color:#{% $designSetting.linkText %}" href='{% "$baseUrl/mobile/board/list?CF_uid=`$friend.uid`"|mixiurl %}'>{%if !$friend.displayName%}NONAME{%else%}{%$friend.displayName%}{%/if%}</a></div>
                            {% if $friend.isLoginApp %}
                            <div style="text-align:right;">ｺﾒﾝﾄ({%$friend.commentCount%})</div>
                            {% else %}
                            <div style="text-align:right;"><a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/board/list" %}'>ｱﾌﾟﾘ未追加[招待]</a></div>
                            {% /if %}
                        </td>

                    </tr>
                </table>
                <div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
            </div><!--/.section-->
            {% /foreach %}

            {%include file="board/common/pager.phtml"%}
            {% /if %}

            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />

        </div><!--/#friendList-->

        {%include file="board/common/menu.phtml"%}

        {%include file="board/common/recommend.phtml"%}
        {%include file="board/common/ad_footer.phtml"%}
		{%include file="board/common/footer.phtml"%}
