{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">
	<a id="pagetop" name="pagetop"></a>
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		{%include file="board/common/ad_header.phtml"%}
		<div id="help">
			<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
			<div class="headline" style="background:#{% $designSetting.tplColor_i %};color:#ffffff;">よくある質問</div>
			<div class="description">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				皆さまから寄せられる質問にお答えします。<br />
				<div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
			</div><!--/.description-->

			<div class="section" style="background:#{% $designSetting.listColorA %};">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[質問]</span><br />
				画像のｺﾒﾝﾄはどのように投稿しますか?<br />
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="5" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[回答]</span><br />
				画像のｺﾒﾝﾄはPC版のみの機能となります｡ﾓﾊﾞｲﾙ版で閲覧のみご利用いただけます｡<br />
				<div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
			</div><!--/.section-->

			<div class="section" style="background:#{% $designSetting.listColorB %};">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[質問]</span><br />
				あしあと帳は株式会社ﾐｸｼｨが運営するｻｰﾋﾞｽですか?<br />
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="5" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[回答]</span><br />
				いいえ、あしあと帳は株式会社ﾐｸｼｨが提供するﾐｸｼｨｱﾌﾟﾘﾌﾟﾗｯﾄﾌｫｰﾑを利用し､株式会社ｺﾐｭﾆﾃｨﾌｧｸﾄﾘｰが開発し､運営しています｡<br />
				<div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
			</div><!--/.section-->

			<div class="section" style="background:#{% $designSetting.listColorA %};">
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[質問]</span><br />
				あしあと帳を削除したい<br />
				<img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="5" /><br />
				<span style="color:#{% $designSetting.tplColor_i %};">[回答]</span><br />
				画面再下部の「ﾏｲｱﾌﾟﾘから削除する」からｱﾌﾟﾘを削除してください。<br />
				<div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /></div>
			</div><!--/.section-->

		</div><!--/.help-->
		{%include file="board/common/menu.phtml"%}
		{%include file="board/common/recommend.phtml"%}
		{%include file="board/common/ad_footer.phtml"%}
		{%include file="board/common/footer.phtml"%}