{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url({% $designSetting.bgImage %});">
    <a id="pagetop" name="pagetop"></a>

    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
        {%include file="board/common/ad_header.phtml"%}
        <div id="introBoard">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{% $designSetting.tplColor_i %};color:#{% $designSetting.reverseText %};">あしあと帳をﾌﾟﾛﾌで紹介</div>
            <div class="description">
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                以下のURLをﾌﾟﾛﾌに貼って､あしあと帳の訪問者を増やそう♪<br />
                <div class="line" style="background:#{% $designSetting.tplColor_i %};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
            <form id="intro" name="intro" method="get" action="#">
                <div class="copyUrl">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#ff9933;">○あしあと帳のURL</span><br />
                    <input type="text" value="{% $url %}" />
                    <div class="alert">
                        <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="3" /><br />
                                                ※こちらのURLはPC版のmixiでのみ移動が可能です(ﾓﾊﾞｲﾙ版では現段階の仕様上､実現できません)｡ご不便をおかけし誠に申し訳ありませんが、何卒ご理解のほどお願いいたします｡
                        </div>
                </div><!--/.copyUrl-->
            </form><!--/#intro-->
        </div><!--/.introBoard-->

        {%include file="board/common/menu.phtml"%}

        {%include file="board/common/recommend.phtml"%}
{%include file="board/common/ad_footer.phtml"%}
{%include file="board/common/footer.phtml"%}