{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">

    <a id="pagetop" name="pagetop"></a>

    <div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
        {%include file="board/common/ad_header.phtml"%}
        <div id="setting">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#ffffff;">設定変更</div>
            <div class="description">
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                         ﾀｲﾄﾙと説明を入力し､[確認]をおしてください｡<br />
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
            <form id="set" name="set" method="post" action='?guid=ON&url={%$url%}'>
                <div class="target">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○ﾀｲﾄﾙ</span><br />
                    <input type="text" id="postTitle" name="postTitle" value="{% $title|escape|nl2br|unescape_emoji%}"/>
                    <div class="warn" style="text-align:right;">※全角20文字(必須)</div>
                </div><!--/.target-->
                <div class="comment">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○説明</span><br />
                    <textarea id="postDescription" name="postDescription" rows="3">{%$introduce|escape|unescape_emoji%}</textarea><br />
                    <div class="warn" style="text-align:right;">※全角100文字</div>
                </div><!--/.target-->
                <div class="btn" style="text-align:center;">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <input type="submit" value="確 認" /><br />
                </div><!--/.btn-->
            </form>
			<div style="text-align:center;">
				<form method="post" action='?guid=ON&url={%$cancelUrl%}'>
					<input type="hidden" name="CF_uid" value="{%$ownerId%}" />
					<input type="submit" value="ｷｬﾝｾﾙ" />
				</form>
			</div>
        </div><!--/.setting-->
        {%include file="board/common/menu.phtml"%}
		{%include file="board/common/ad_footer.phtml"%}
		{%include file="board/common/footer.phtml"%}