{%include file="board/common/header.phtml"%}
<body style="background-color:#{%$designSetting.bgColor%};background-image:url();">
	<a id="pagetop" name="pagetop"></a>
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
        <div id="setting">
            <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
            <div class="headline" style="background:#{%$designSetting.tplColor_i%};color:#ffffff;">入力内容の確認</div>
            <div class="description">
                <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                                    次の内容を確認し､よろしければ[送信]をおしてください｡<br />
                <div class="line" style="background:#{%$designSetting.tplColor_i%};"><img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="1" /></div>
            </div><!--/.description-->
            <form id="setConfirm" name="setConfirm" method="post" action='?guid=ON&url={%$url%}'>
                <div class="target">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○ﾀｲﾄﾙ</span><br />
                     {%$postTitle%}<br />
                </div><!--/.target-->
                <div class="comment">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <span style="color:#{% $designSetting.tplColor_i %};">○説明</span><br />
                     {%$postDescription|escape|nl2br|unescape_emoji%}<br />
                </div><!--/.target-->
                <div class="btn" style="text-align:center;">
                    <img src="{%$staticUrl%}/apps/board/mobile/img/spacer.gif" width="1" height="2" /><br />
                    <input type="hidden" id="CF_postTitle" name="CF_postTitle" value="{%$postTitle%}" />
                    <input type="hidden" id="CF_postDescription" name="CF_postDescription" value="{%$postDescription%}" />
                    <input type="submit" value="送 信" /><br />
                </div><!--/.btn-->
            </form><!--/#setConfirm-->
            <div style="text-align:center;">
                <form method="post" action='?guid=ON&url={%$cancelUrl%}'>
                    <input type="hidden" name="CF_uid" value="{%$cancelUid%}" />
                    <input type="submit" value="戻 る" />
                </form>
            </div>
        </div><!--/.setting-->
{%include file="board/common/footer.phtml"%}