{%include file="parking/common/header.phtml"%}

<div id="estate">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">&nbsp;{%$title%}</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%$message%}<br />
	</div><!--/.description-->

	<div class="commodity" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/background/{%$newHouseInfo.cav_name%}_m.gif" width="210" height="105" style="margin:2px 0;" /><br />
	</div><!--/.commodity-->

	<div class="link">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_rand=$rand" | mobile_flashurl %}'>さっそく駐車場を確認</a>{% emoji code="F8F2"%}<br />
	</div><!--/.link-->
</div><!--/#estate-->

{%include file="parking/common/footer.phtml"%}