{%include file="parking/common/header.phtml"%}

<div id="itemShop">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">{%$title%}</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%$message%}{% emoji code="F99F"%}<br />
	</div><!--/.description-->

	<div class="commodity" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/items/{%$cardId%}_m.gif" width="156" height="100" style="margin:2px 0;" /><br />
	</div><!--/.commodity-->

	<div class="link">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%if $cardId==2 || $cardId==4%}
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/itemshop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟにもどる</a><br />
		{%elseif $canUse==1%}
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/useitemconform?parking_id=$cardId"|mixiurl %}'>さっそく使ってみる</a><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/itemshop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟにもどる</a><br />
		{%else%}
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/itemshop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟにもどる</a><br />
		{%/if%}
	</div><!--/.link-->

</div><!--/#itemShop-->

{%include file="parking/common/footer.phtml"%}