{%include file="parking/common/header.phtml"%}
<div id="check">

	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ｼｽﾃﾑｴﾗｰ</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		ｼｽﾃﾑｴﾗｰが発生しました<br />
		恐れ入りますが、再度､駐車場にお戻りください｡<br />
	</div><!--/.description-->

	<div class="error" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/error.gif" width="156" height="100" /><br />
	</div><!--/.error-->

	<div class="link">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_rand=$rand" | mobile_flashurl %}'>駐車場にもどる</a><br />
	</div><!--/.link-->

</div><!--/#check-->

{%include file="parking/common/footer.phtml"%}