{%include file="parking/common/header.phtml"%}

<div id="estate">

	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">不動産屋</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		不動産のｸﾞﾚｰﾄﾞをUPすると、駐車料金や駐車区画が増えます{% emoji code="F99F"%}<br />
		<div style="text-align:right;">所持金:¥{%$userAsset|outputdollars%}&nbsp;</div>
	</div><!--/.description-->

	<div style="background:#fcc;text-align:center;"><img src="{%$staticUrl%}/apps/parking/mimg/dot.gif" width="228" height="1" /></div>

	{%foreach from=$houseList item=rowdata key=index%}
		<div class="section" {%if ($index%2)==0 %}style="background:#fee;"{%else%}style="background:#ffe;"{%/if%}>
			<span style="color:#cd424a;">{% emoji code="F8C5"%}{%$rowdata.name%}</span><br />
			<div style="text-align:right;">¥{%$rowdata.price|outputdollars%}&nbsp;</div>
			<table width="220" cellpadding="2" cellspacing="1" border="0" align="center" style="text-align:center;">
				<tr>
					<td style="text-align:left;"><div style="font-size:x-small;">
						駐車料金 ¥{%$rowdata.fee|outputdollars%}/15分<br />
						駐車区画 {%$rowdata.type%}台<br />
						</div></td>
				</tr>
			</table>
			<div style="color:#999;text-align:right;">
				{%if ($rowdata.price-$oldHousePrice*0.9)>$userAsset%}
					購入する&nbsp;<br />
				{%elseif ($rowdata.id == $oldHouseId)||($oldHouseType>=$rowdata.type)||($oldHousePrice>$rowdata.price)%}
				{%else%}
					<a href='{% "$baseUrl/mobile/parking/buyhouse?parking_hid=`$rowdata.id`"|mixiurl %}'>購入する</a>&nbsp;<br />
				{%/if%}
			</div>
			<div style="background:#fcc;text-align:center;"><img src="{%$staticUrl%}/apps/parking/mimg/dot.gif" width="228" height="1" /></div>
		</div><!--/.section-->
	{%/foreach%}

	<div class="pager" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%include file="parking/common/pager.phtml"%}
	</div><!--/.pager-->

</div><!--/#estate-->

{%include file="parking/common/footer.phtml"%}