{%include file="parking/common/header.phtml"%}

<div id="check">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">取り締まり完了</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%$car_user%}の{%$car_name%}を取り締まりました{% emoji code="F9F8"%}<br />
	</div><!--/.description-->

	<div class="car" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/car/{%$cav_name%}/m/normal/{%$car_color%}.gif" width="200" height="100" /><br />
		<span style="color:#c00;">\{%$money%} 獲得{% emoji code="F9A7"%}</span>
	</div><!--/.car-->

	<div class="ranking">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		総資産 \{%$asset%}<br />
		ﾏｲﾐｸ内ﾗﾝｷﾝｸﾞ {%$friendRanking%}位{% emoji code=$friendRankEmoji %}<br />
		ﾐｸｼｨ内ﾗﾝｷﾝｸﾞ {%$mixiRanking%}位{% emoji code=$mixiRankEmoji %}<br />
	</div><!--/.ranking-->

	<div class="link">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_rand=$rand" | mobile_flashurl %}'>駐車場にもどる</a><br />
	</div><!--/.link-->

</div><!--/#check-->

{%include file="parking/common/footer.phtml"%}