{%include file="parking/common/header.phtml"%}

<div id="itemList">

	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">{%$title%}</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%$message%}<br />
	</div><!--/.description-->

	<div class="item" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/parking/mimg/items/{%$itemId%}_m.gif" width="156" height="100" alt="" style="margin-top:2px;" />
	</div><!--/.item-->

	<div class="link">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{%if $itemId == 11%}
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_pid=`$fid`&parking_rand=$rand"|mobile_flashurl %}'>さっそく駐車場を確認</a>{% emoji code="F8F2"%}<br />
		{%else%}
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_rand=$rand" | mobile_flashurl %}'>さっそく駐車場を確認</a>{% emoji code="F8F2"%}<br />
		{%/if%}
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/item"|mixiurl %}'>ｱｲﾃﾑ一覧にもどる</a><br />
	</div><!--/.link-->

</div><!--/#itemList-->

{%include file="parking/common/footer.phtml"%}