		<div id="copyright" style="color:#777777;text-align:center;">
			<div class="line" style="background:#ca8251;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			<br />
			(C)Community Factory<br />
			<br />
			<div class="line" style="background:#ca8251;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		</div><!--/#copyright-->
	    <div class="section" style="text-align:center;">
			<a href="http://m.mixi.jp/view_appli.pl?id=19008&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/expose_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />オモシロ質問に答えよ～♪</a><br />
	    </div><!--/.section-->
	    <div class="section" style="text-align:center;">
			<a href="http://m.mixi.jp/view_appli.pl?id=19735&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/shindan_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />おﾊﾞｶな検定が盛りだくさん!</a><br />
	    </div><!--/.section-->
		<img src="http://app-stats.communityfactory.net/addpv?app_id=1&nocache=1&time={%$smarty.now|date_format:"%Y-%m-%d %H:%M:%S"%}
		" height="1" width="1" border="0"/>
		{%if $footerAd%}{%include file="ship/common/ad_footer.phtml"%}{%/if%}
    </div><!--/#container-->
    
    {% html_mobile_tracker aqid="785Q668UNMPJ6FYFNRXA" %}
    
</body>
</html>
