<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
{% if $ua!=1 %}
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% else %}
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% /if %}
	<title>よこどりパイレーツ</title>
	<style type="text/css">
		a:link{color:#258fb8;}
		a:visited{color:#258fb8;}
		*{
			{% if $ua==3 %}
				font-size:5;
			{% else %}
				font-size:x-small;
			{% /if %}
			color:#333;
		}
	</style>
</head>
<body style="background:#ffffff;">
	<div id="container"{% if $ua==1 %} style="font-size:x-small;"{% /if %}>
	<input type="hidden" value='{%emoji code="F8B3"%}'>
	{%if $headerAd%}{%include file="ship/common/ad_header.phtml"%}{%/if%}
