{% if $pager.maxPager > 1 %}
<div class="pager" style="color:#258fb8;text-align:center;">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	{% if $pager.pageIndex == 1 %}<span style="color:#aaa;">←[*]前へ</span>{% else %}←[*]<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex-1`"|mixiurl %}' accesskey="*">前へ</a>{% /if %} {% if $pager.maxPager == $pager.pageIndex%}<span style="color:#aaa;">次へ[#]→</span>{% else %}<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex+1`"|mixiurl %}' accesskey="#">次へ</a>[#]→{% /if %}<br />
</div><!--/.pager-->
{% /if %}
