		<div id="ftr">
			<address>&copy; 2009 <span><a href="http://communityfactory.com/" target="_blank">Community Factory</a></span> Inc. All Rights Reserved. - <a href="http://communityfactory.com/" target="_blank">広告のお問い合わせ</a> - <a href="http://platform001.mixi.jp/view_community.pl?id=4172244" target="_top">サポートコミュニティ</a>{% if $admin eq 1 %} - <a href="/millionminds/approvelist">admin</a>{% /if %}</address>
		</div><!--/#ftr-->

	</div><!--/#container-->
	
	<script type="text/javascript">	
        jQuery(function($) {
            adjustHeight();
        });
	</script>
</body>
</html>