<div id="hdr">
	<h1><a href="{%$baseUrl%}/millionminds" title="MillionMindsトップへ">MillionMinds</a></h1>
	<div class="ads">
		<ul>
			<li><a href="#"><img src="{%$staticUrl%}/apps/millionminds/img/hdr_ad01.png" width="224" height="50" alt="" /></a></li>
			<li><a href="#"><img src="{%$staticUrl%}/apps/millionminds/img/hdr_ad02.png" width="224" height="50" alt="" /></a></li>
		</ul>
	</div><!--/.ads-->
	<address><a href="http://communityfactory.com/" target="_blank" title="株式会社コミュニティファクトリー">株式会社コミュニティファクトリー</a></address>
</div><!--/#hdr-->