{% if $showNature %}


<div id="q">
	<h3 class="default">相性診断クエスチョン</h3>
	<table width="100%" cellpadding="0" cellspacing="0" border="0" class="q">
		<tr>
			<td class="author"><span><a href="{%$baseUrl%}/millionminds/profile/uid/{%$nature.uid%}" style="background-image: url({% $nature.thumbnailUrl %});" title="{% $nature.displayName %}">{% $nature.displayName %}</a></span></td>
			<td class="content">
			    <h2>{% $nature.question|escape %}</h2>			
				<dl>
					<dt>作成者：</dt>
					<dd><a href="{%$baseUrl%}/millionminds/profile/uid/{%$nature.uid%}">{% $nature.displayName %}</a>さん</dd>
					<dt>カテゴリー：</dt>
					<dd><a>{% $nature.category %}</a></dd>
					<dt>回答数：</dt>
					<dd>{% $nature.answer %}</dd>
				</dl>
			</td>
		</tr>
	</table><!--/.q-->
	<p class="timer"><img src="{% $staticUrl %}/apps/millionminds/img/timer.gif" width="580" height="25" alt="" id="timerImg"/></p>
	<ul class="select">
		<li><a href="{%$baseUrl%}/millionminds/nature?qid={%$nature.qid%}&aid=1"><strong>はい</strong></a></li>
		<li><a href="{%$baseUrl%}/millionminds/nature?qid={%$nature.qid%}&aid=2"><strong>いいえ</strong></a></li>
		<li><a href="{%$baseUrl%}/millionminds/nature?qid={%$nature.qid%}&aid=3"><strong>どちらでもない</strong></a></li>
	</ul><!--/.select-->
	{% if $natureAnswer %}
	<h3 class="answers">このクエスチョンに回答した人</h3>
	<ul class="answers">
	    {% foreach from=$natureAnswer item=data %}
		<li><span><a href="{%$baseUrl%}/millionminds/profile/uid/{%$data.uid%}" style="background-image: url({% $data.thumbnailUrl %});" title="{% $data.displayName %}">{% $nature.displayName %}</a></span></li>
		{% /foreach %}
	</ul>
	{% /if %}
</div><!--/#q-->

<script type="text/javascript" language="javascript">
$().ready(function() 
{   
    $('#timerImg').attr('src', UrlConfig.StaticUrl + '/apps/millionminds/img/timer.gif'); 
});
</script>
{% /if %}