<div id="ftr" class="clearfix">
	<div class="inner">
		<div id="pageTop"><a href="#"><img src="http://static.linno.jp/_cmn/img/ftr/btn_pageTop.png" width="130" height="26" alt="ページトップへ" /></a></div>
		<ul id="ftrPageLink"><!--
			--><li><a href="/home">ホーム</a></li><!--
			--><li><a href="/home/news">プロフィール</a></li><!--
			--><li><a href="/home/friend">友達</a></li><!--
			--><li><a href="/diary/popular">日記</a></li><!--
			--><li><a href="/circle/popular">サークル</a></li><!--
			--><li><a href="/class/popular">授業</a></li><!--
			--><li><a href="/note/popular">ノート</a></li><!--
			--><li><a href="/message">メッセージ</a></li><!--
			--><li><a href="/home/edit/profile">環境設定</a></li><!--
			--><li><a href="/help">ヘルプ</a></li><!--
			--><li><a href="/home/invite">友達を招待</a></li><!--
			--><li><a href="/logout">ログアウト</a></li><!--
		--></ul>
		<ul id="ftrCorpLink"><!--
			--><li id="logoLinno"><a href="http://linno.co.jp" target="_blank"><img src="http://static.linno.jp/_cmn/img/ftr/logo_linno.png" width="90" height="37" alt="株式会社リンノ" /></a></li><!--
			--><li id="logoCF"><a href="http://communityfactory.com" target="_blank"><img src="http://static.linno.jp/_cmn/img/ftr/logo_cf.png" width="162" height="26" alt="株式会社コミュニティファクトリー" /></a></li><!--
		--></ul>
		<address id="copyright">&copy; 2007-2008 LinNo inc.</address>
		<ul id="ftrPolicyLink"><!--
			--><li><a href="http://linno.co.jp/" target="_blank">運営会社</a></li><!--
			--><li><a href="http://s.linno.jp/corporate/privacy.html" target="_blank">プライバシーポリシー</a></li><!--
			--><li><a href="http://s.linno.jp/corporate/rule.html" target="_blank">利用規約</a></li><!--
			--><li><a href="http://s.linno.jp/corporate/notice.html" target="_blank">ご利用上の注意</a></li><!--
			--><li><a href="/auth/contact">お問い合わせ</a></li><!--
		--></ul>
	</div><!--/.inner-->
</div><!--/#ftr-->

</div><!--/#wrap-->
</body>
</html>