<div id="wrap">

<div id="hdr" class="clearfix">
	<div id="logo"><a href="#"><img src="{%$staticUrl%}/apps/linno/img/logo.png" width="179" height="78" alt="LinNo（リンノ）" /></a></div>
	<div id="gNav">
		<ul id="homeNav"><!--
			--><li id="navHome" class="stay"><a href="#"><span>トップ</span></a></li><!--
			--><li id="navProfile"><a href="#"><span>プロフィール</span></a></li><!--
			--><li id="navSurvey"><a href="#"><span>アンケート</span></a></li><!--
			--><li id="navReport"><a href="#"><span>キャラクター通信簿</span></a></li><!--
			--><li id="navMessage"><a href="#"><span>足あと</span></a></li><!--
		--></ul><!--/#homeNav-->
		<ul id="subNav"><!--
			--><li id="navHelp"><a href="#">ヘルプ</a></li><!--
			--><li id="navInvite"><a href="#">友達を招待</a></li><!--
		--></ul><!--/#subNav-->
	</div><!--/#gNav-->
</div><!--/#hdr-->
