{%include file="brain/common/header.phtml" headerAd=1 %}

<div id="about">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#cc3366;color:#ffffff;text-align:center;">ﾏｲﾐｸ頭脳くらべについて</div><!--/.headline-->
	<div class="inner">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		先生から出される問題に対して制限時間内にできるだけ多く答えていくゲームです！<br />
		選択式ではなく携帯では珍しい文字入力式！運だけでは答えられないので注意！<br />
		問題はどれも小中学校で習った問題ばかりだけど忘れてることも多いかも！？<br />
		マイミクと頭脳で勝負しよう！<br />
	</div><!--/.inner-->
</div><!--/#about-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}