{%include file="brain/common/header.phtml" headerAd=1 %}

<div id="guide">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#009999;color:#ffffff;text-align:center;">
		{%$gameInfo.gname%}<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		ゲーム説明<br />
	</div><!--/.headline-->
	<div class="inner">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{%$gameInfo.description%}<br />
	</div><!--/.inner-->
	<div class="play" style="color:#009999;text-align:center;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="text-decoration:blink;">≫</span><a href="{%$baseUrl%}/mobile/brain/start?gid={%$gameInfo.gid%}&opensocial_app_id={%$APP_ID%}&opensocial_owner_id={%$uid%}&rand={%$rand%}">ゲーム起動</a><span style="text-decoration:blink;">≪</span>
	</div><!--/.play-->
</div><!--/#guide-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}