{%include file="brain/common/header.phtml" headerAd=1 %}

<div id="title" style="text-align:center;">
	<img src="{%$staticUrl%}{%$gameInfo.pic_big%}" width="100" height="100" style="margin:3px 0;" /><br />
	………………………………………<br />
	{%$gameInfo.gname%}<br />
	………………………………………<br />
</div><!--/#title-->

<div id="description">
	{%$gameInfo.summary%}<br />
	<br />
	{% if $ua!=2 %}{% emoji code="F8EC"%}{% else %}{% emoji code="F8E9"%}{% /if %}<a href="{%$baseUrl%}/mobile/brain/start?gid={%$gameInfo.gid%}&opensocial_app_id={%$APP_ID%}&opensocial_owner_id={%$uid%}&rand={%$rand%}">ｹﾞｰﾑ起動</a><br />
	{% emoji code="F8E4"%}<a href='{% "$baseUrl/mobile/brain/description?gid=`$gameInfo.gid`"|mixiurl %}'>ｹﾞｰﾑ説明</a><br />
	{% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/brain/rankingthree?pos=1&page=1&gid=`$gameInfo.gid`"|mixiurl %}'>ﾗﾝｷﾝｸﾞ</a><br />
	<br />
	{% emoji code="F973"%}<a href='invite:friends?callback={% "$baseUrl/mobile/brain/start?gid=`$gameInfo.gid`"|mixiurl %}'>ﾏｲﾐｸを招待する</a><br />
	<br />
	{% emoji code="F8E9"%}対応機種<br />
	docomo:FOMA70x,90x,0xAシリーズ<br />
	au:WIN flash 対応機<br />
	SoftBank:3G flash対応機<br />
	※一部、音がでない機種がございます。<br />
	<br />
	※ランキング送信などで通信を頻繁に実施しますので、必ずﾊﾟｹｯﾄ定額ｻｰﾋﾞｽへご加入の上、ご利用ください。<br />
</div><!--/#description-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}