{%include file="brain/common/header.phtml" headerAd=1 %}

<div id="help">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
    <div class="headline" style="background:#cc3366;color:#ffffff;text-align:center;">ﾍﾙﾌﾟ･よくある質問</div><!--/.headline-->
    <div class="inner">
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            マイミク頭脳くらべってどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            先生から出される問題に対して制限時間内にできるだけ多く答えていくゲームです！<br />
            問題はどれも小中学校で習った問題ばかりだけど忘れてることも多いかも！？<br />
            マイミクと頭脳で勝負しよう！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            数学科 計算編はどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            計算式が画面上に表示されるので、計算の答えを入力していこう！<br />
            制限時間内にできるだけ多くの計算を解いて自己ベストの得点を目指せ！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            英語科 英単語編はどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            日本語が画面上に表示されるので、同じ意味の英単語を入力していこう！<br />
            制限時間内にできるだけ多くの英単語を入力して自己ベストの得点を目指せ！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            日本語の意味に合うはずの英単語が正解にならない</span><br />
            <span style="color:#009999;">［回答］</span><br />
            携帯電話の仕様上の問題から当クイズでは日本の英語教育で一般的な訳語を元に問題を制作しています。日本語の意味から複数の英単語が連想される問題もございますがゲーム内での正解は一つとしてご了承ください。<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            国語科 漢字編はどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            例文が画面上に表示されるので、漢字の読みを入力していこう！<br />
            制限時間内にできるだけ多く答えて自己ベストの得点を目指せ！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            社会科 日本史編はどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            日本史に関する問題が表示されるので答えを入力していこう！<br />
			制限時間内にできるだけ多くの問題を解いて自己ベストを目指せ！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            和同開珎を「わどうかいほう」と答えても正解にならない。</span><br />
            <span style="color:#009999;">［回答］</span><br />
            携帯電話の仕様上の問題から当クイズでは複数の読み方がある用語についても答えを一つにしております。<br />
			ご了承下さい。<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
{%*
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            社会科 戦国武将編はどんなゲーム？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            戦国武将に関する説明が画面上に表示されるので、武将の名前を入力していこう！<br />
            制限時間内にできるだけ多くの計算を解いて自己ベストの得点を目指せ！<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            社会科 戦国武将編の得点が総合得点に入らない？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            社会科 戦国武将編については特別授業に入りますので、獲得した得点は
            総合得点に含まれません。あらかじめご了承下さい。<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
*%}
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            対応機種は？</span><br />
            <span style="color:#009999;">［回答］</span><br />
            Flash Lite 1.1以上が動く携帯電話でご利用頂けます。<br />
            docomo:FOMA70x,90x,0xAシリーズ<br />
            au:WIN flash対応機種<br />
            Softbank:3G flash対応機種<br />
            ※一部、音がでない機種があります。<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            途中でメールや電話が来たらゲームがリセットされた。</span><br />
            <span style="color:#009999;">［回答］</span><br />
            Flashゲームの場合、携帯機種の制限によりゲーム中に電話やメールを受けるとゲームが
            リセットされてしまいます。<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            決定ｷｰを2回押してもｽｷｯﾌﾟ出来ません。</span><br />
            <span style="color:#009999;">［回答］</span><br />
            誤動作を避けるために2回押すﾀｲﾐﾝｸﾞを早めに取ってあります｡早めのﾀｲﾐﾝｸﾞで2回押してください｡<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        <div class="section">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <span style="color:#cc3366;">［質問］<br />
            自己ﾍﾞｽﾄを更新したのにﾗﾝｷﾝｸﾞが更新されない!</span><br />
            <span style="color:#009999;">［回答］</span><br />
            ﾗﾝｷﾝｸﾞの更新は1日1回となっております｡何卒ご了承ください｡<br />
            <div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
        </div><!--/.section-->
        
    </div><!--/.inner-->
</div><!--/#help-->

<div id="menu">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#009999;color:#ffffff;text-align:center;">ｱﾌﾟﾘﾒﾆｭｰ</div>
    <div class="inner">
        {% emoji code="F987"%}<a href='{% "$baseUrl/mobile/brain/top"|mixiurl %}' accesskey="1">ﾏｲﾐｸ頭脳くらべTOP</a><br />
        {% emoji code="F973"%}<a href='invite:friends?callback={%$baseUrl%}/mobile/brain/top'>ﾏｲﾐｸを招待する</a><br />
    </div><!--/.inner-->
</div><!--/#menu-->

{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}