{%include file="brain/common/header.phtml" headerAd=0 %}

<div id="inviteComplete">
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ﾏｲﾐｸの招待が完了しました｡<br />
	</div><!--/.description-->

	<div class="ad" style="text-align:center;">
		<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="center" id="ec963db98d470730e72e03e89e852fbe431dc922" />
	</div><!--/.ad-->

	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		新しい授業はﾏｲﾐｸがこのｱﾌﾟﾘを登録して､いずれかの授業でｽｺｱ登録を行なった段階で成立します｡<br />
		<br />
		ﾏｲﾐｸ招待が成立するまでしばらくお待ち下さい｡<br />
		<br />
	</div><!--/.description-->
</div><!--/#inviteComplete-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=0 %}