{%include file="brain/common/header.phtml" headerAd=1 %}

<div id="ranking">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#cc3366;color:#ffffff;text-align:center;">
		{% emoji code="F9BF"%}科目別ﾗﾝｷﾝｸﾞ{% emoji code="F9BF"%}<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		{%$gname%}<br />
	</div><!--/.headline-->
	<div class="inner">
		<div class="switch" style="text-align:center;">
			{% if $pos == '1' %}
				ﾏｲﾐｸ内 <span style="color:#cccccc;">|</span> <a href='{% "$baseUrl/mobile/brain/rankingthree?pos=2&gid=`$gid`"|mixiurl %}'>ﾐｸｼｨ全体</a><br />
			{%else%}
				<a href='{% "$baseUrl/mobile/brain/rankingthree?pos=1&gid=`$gid`"|mixiurl %}'>ﾏｲﾐｸ内</a> <span style="color:#cccccc;">|</span> ﾐｸｼｨ全体<br />
			{%/if%}
			<div class="line" style="background:#cc3366;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
		</div><!--/.switch-->
		{% if $classInfo %}
			<div class="contentCount">
				{%if $listCount.startCount == $listCount.endCount%}
					{%$count%}件中{%$listCount.startCount%}件<br />
				{%else%}
					{%$count%}件中{%$listCount.startCount%}-{%$listCount.endCount%}件<br />
				{%/if%}
            </div><!--/.contentCount-->
			{% foreach from=$classInfo item=data key=key %}
				<div class="section">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$data.miniThumbnailUrl%}" /></td>
							{% if $data.uid == $uid%}
								<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#cc0000;">〓{%$data.rank%}位〓</span><br />
							{% else %}
								<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#666666;">〓</span>{%$data.rank%}位<span style="color:#666666;">〓</span><br />
							{% /if %}
									{%$data.displayName%}<br />
									<div class="score" style="text-align:right;">{% $data.score %}点&nbsp;</div>
									</div></td>
						</tr>
					</table>
					<div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
				</div><!--/.section-->
			{% /foreach %}

			<div class="pager" style="color:#3399cc;text-align:center;">
				{%include file="brain/common/pager.phtml"%}
				<div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
			</div><!--/.pager-->

			<div class="footLink" style="color:#cc0000;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%*⇒<a href='{% "$baseUrl/mobile/brain/rankingthree?pos=$pos&left=1&right=5&gid=`$gid`"|mixiurl %}'>1位～5位をﾁｪｯｸ!</a><br />*%}
				⇒<a href='{% "$baseUrl/mobile/brain/game?gid=`$gid`"|mixiurl %}'>この科目に挑戦する!</a><br />
				⇒<a href='{% "$baseUrl/mobile/brain/ranking?pos=1"|mixiurl %}'>ﾗﾝｷﾝｸﾞ一覧へ</a><br />
			</div><!--/.footLink-->
		{%else%}
			<div class="description" style="text-align:center;">
				まだ何もありません<br />
				<div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
			</div><!--/.description-->
			<div class="footLink" style="color:#cc0000;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				⇒<a href='{% "$baseUrl/mobile/brain/game?gid=`$gid`"|mixiurl %}'>この科目に挑戦する!</a><br />
				⇒<a href='{% "$baseUrl/mobile/brain/ranking?pos=1"|mixiurl %}'>ﾗﾝｷﾝｸﾞ一覧へ</a><br />
			</div><!--/.footLink-->
		{%/if%}
	</div><!--/.inner-->
</div><!--/#ranking-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}