{%include file="brain/common/header.phtml" headerAd=1 %}

<div class="ranking">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
    <div class="headline" style="background:#cc3366;color:#ffffff;text-align:center;">{% emoji code="F9BF"%}ﾏｲﾐｸ内ﾗﾝｷﾝｸﾞ一覧{% emoji code="F9BF"%}</div>

	<div class="group">
		{% if $totalInfo %}
				<div class="head">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="headline" style="background:#009999;color:#ffffff;">{% emoji code="F99F"%}総合成績<br /></div>
				</div><!--/.head-->
				{% foreach from=$totalInfo item=data key=key%}
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$data.miniThumbnailUrl%}" /></td>
								{% if $data.uid == $uid%}
								<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#cc3366;">〓{%$data.ranknm%}位〓</span><br />
								{% else %}
								<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#666666;">〓</span>{%$data.ranknm%}位<span style="color:#666666;">〓</span><br />
								{% /if %}
									{%$data.displayName%}<br />
									<div class="score" style="text-align:right;">{% $data.totalScore %}点&nbsp;</div>
									</div></td>
							</tr>
						</table>
						<div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
					</div><!--/.section-->
				{% /foreach %}
				<div class="footLink" style="color:#cc3366;text-align:right;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% if $totalInfo|@count >= 3 %}
						⇒<a href='{% "$baseUrl/mobile/brain/rankingtwo?pos=1"|mixiurl %}'>もっと見る</a>&nbsp;<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% /if %}
				</div><!--/.footLink-->
		{% else %}
			<div class="switch" style="text-align:center;">
				{% if $pos == '1' %}
					ﾏｲﾐｸ内<span style="color:#cccccc;">|</span> <a href='{% "$baseUrl/mobile/brain/ranking?pos=2"|mixiurl %}'>ﾐｸｼｨ全体</a>
				{%else%}
					<a href='{% "$baseUrl/mobile/brain/ranking?pos=1"|mixiurl %}'>ﾏｲﾐｸ内 </a><span style="color:#cccccc;">|</span>ﾐｸｼｨ全体
				{%/if%}
				<hr style="color:#cccccc;background-color:#cccccc;height:1px;border:0px solid #cccccc;margin:0.3em 0;" size="1" />
			</div><!--/.switch-->
	   {% /if %}
    </div><!--/.group-->
    <!--/.totalInfo-->

{% if $classInfo %}
	{% foreach from=$classInfo item=data key=key %}
		{% if $data.info %}
			<div class="head">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#009999;color:#ffffff;">{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/brain/game?gid=`$data.gid`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">{%$data.gname%}</span></a><br /></div>
			</div><!--/.head-->
			{% foreach from=$data.info item=aryInfo key=key %}
				<div class="section">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;vertical-align:top;"><img src="{%$aryInfo.miniThumbnailUrl%}" /></td>
								{% if $aryInfo.uid == $uid%}
									<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#cc3366;">〓{%$aryInfo.ranknm%}位〓</span><br />
								{% else %}
									<td style="vertical-align:top;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><span style="color:#666666;">〓</span>{%$aryInfo.ranknm%}位<span style="color:#666666;">〓</span><br />
								{% /if %}
									{%$aryInfo.displayName%}<br />
									<div class="score" style="text-align:right;">{% $aryInfo.score %}点&nbsp;</div>
									</div></td>
						</tr>
					</table>
					<div class="line" style="background:#ebebae;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /></div>
				</div><!--/.section-->
			{% /foreach %}
			<div class="footLink" style="color:#cc3366;text-align:right;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $data.info|@count >= 3 %}
					⇒<a href='{% "$baseUrl/mobile/brain/rankingthree?pos=1&gid=`$data.gid`"|mixiurl %}'>もっと見る</a>&nbsp;<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%/if%}
			</div><!--/.footLink-->
		{%/if%}
	{% /foreach %}
{%/if%}

</div><!--/.ranking-->

{%include file="brain/common/menu.phtml"%}
{%include file="brain/common/recommend.phtml"%}
{%include file="brain/common/footer.phtml" footerAd=1 %}