{%include file="shopping/common/header.phtml"%}

<body id="help">
<div id="continer">
	{%include file="shopping/common/hdr.phtml"%}

	<div id="mainColumn">

		<div id="helpBox" class="box">

			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_help.png" alt="ヘルプ" /></h2>
			</div><!--/.hdr-->

			<div class="section">
				<h3><img src="{%$staticUrl%}/apps/shopping/img/content/heading_help_0.png" alt="" /></h3>
				<p>このゲームは制限時間内にお買物の合計金額が目標金額に近づくように商品を選んでいくゲームです。商品の金額は表示されていませんので、想像力を働かせて、目標金額に近くなるように商品を選んでください。</p>
			</div>
			<div class="section">

				<h3><img src="{%$staticUrl%}/apps/shopping/img/content/heading_help_0.png" alt="" /></h3>
				<p>このゲームは制限時間内にお買物の合計金額が目標金額に近づくように商品を選んでいくゲームです。商品の金額は表示されていませんので、想像力を働かせて、目標金額に近くなるように商品を選んでください。</p>
			</div>

			<div class="section">
				<h3><img src="{%$staticUrl%}/apps/shopping/img/content/heading_help_0.png" alt="" /></h3>
				<p>このゲームは制限時間内にお買物の合計金額が目標金額に近づくように商品を選んでいくゲームです。商品の金額は表示されていませんので、想像力を働かせて、目標金額に近くなるように商品を選んでください。</p>
			</div>
			<div class="section">

				<h3><img src="{%$staticUrl%}/apps/shopping/img/content/heading_help_0.png" alt="" /></h3>
				<p>このゲームは制限時間内にお買物の合計金額が目標金額に近づくように商品を選んでいくゲームです。商品の金額は表示されていませんので、想像力を働かせて、目標金額に近くなるように商品を選んでください。</p>
			</div>

		</div><!--/#helpBox.box-->

	</div><!--/#mainColumn-->

<hr />

	<div id="subColumn">
		{%include file="shopping/common/adbox.phtml"%}
		{%include file="shopping/common/profbox.phtml"%}
		{%include file="shopping/common/wishbox.phtml"%}
	</div><!--/#subColumn-->

{%include file="shopping/common/footer.phtml"%}