{%include file="shopping/common/header.phtml"%}

<body id="wish">

<input type="hidden" id="hidIid" name="hidIid" value=""/>
<input type="hidden" id="hidOldPrice" name="hidOldPrice" value=""/>

<div id="overlay" style="display: none;">
    <div id="overBox">
    <a id="sBlankTop" href="#"></a>
        <!-- removeCart info -->
            <div id="removeCart" style="display: none;">
                <div class="inner">
                    <h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_myCart_remove_b.png" alt="" /></h2>
                    <div class="section">

                        <div class="lead" id="removeMessage1">以下の商品をショッピングカートからはずしますか？</div>
                        <div class="lead" id="removeMessage2" style="display: none;">以下の商品をショッピングカートから削除しました。<br />引き続き商品を選択するか、精算を行ってください。</div>
                        <div class="lead" id="removeMessage3" style="display: none;">失敗しました。</div>

                        <dl class="itemBlock clearfix"><!--
                            --><dt class="pic"><a id="itemPic" href="javascript:void(0);" style="cursor:default;background-image:url({%$staticUrl%}/apps/shopping/img/dummy/pic_item.png)"><img src="{%$staticUrl%}/apps/shopping/img/spacer.gif" width="76"  height="76" alt="" /></a></dt><!--
                            --><dd class="name" id="itemName">私のFXバイブル</dd><!--
                            --><dd class="price">予想価格：￥<label id="lblPrice1"></label></dd><!--
                            --><dd class="buy"><a href="#" id="goRakuten">楽天市場でこの商品を購入</a></dd><!--
                        --></dl>
                    </div>
                    <ul class="btnSection clearfix" id="btnList"><!--
                        --><li><a href="javascript:void(0);" id="removeBack"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_cancel_s.png" alt="" /></a></li><!--
                        --><li><a href="javascript:void(0);" id="removeFinish"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_remove_s.png" alt="" /></a></li><!--
                    --></ul>
                </div>
            </div>
        <!-- /removeCart info -->

        <!-- changePrice div info -->
            <div id="changePrice" style="display: none;"><!-- changePrice div info -->
		        <div class="inner">
		            <h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_change.png" alt="" /></h2>
		            <div class="section">

		                <div class="lead" id="changePriceMessage1">以下の商品をショッピングカートに追加しますか？<br />予想価格は未入力でも大丈夫です。</div>
		                <div class="lead" id="changePriceMessage2" style="display: none;">以下の商品の予想価格を変更しました。<br />引き続き商品を選択するか、精算を行ってください。</div>
		                <div class="lead" id="changePriceMessage3" style="display: none;">失敗しました。</div>

		                <dl class="itemBlock clearfix"><!--
		                    --><dt class="pic"><a id="itemPic2" href="javascript:void(0);" style="cursor:default;background-image:url({%$staticUrl%}/apps/shopping/img/dummy/pic_item.png)"><img src="{%$staticUrl%}/apps/shopping/img/spacer.gif" width="76"  height="76" alt="" /></a></dt><!--
		                    --><dd class="name" id="itemName2">私のFXバイブル</dd><!--
		                    --><dd class="priceForm" id="itemPrice2">予想価格：<input type="text" id="price" value="2000" /></dd><!--
		                    --><dd class="buy"><a href="#" id="goRakuten2">楽天市場でこの商品を購入</a></dd><!--
		                --></dl>
		            </div>
		            <ul class="btnSection clearfix" id="btnList2"><!--
		                --><li><a href="javascript:void(0);" id="changeBack"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_cancel_s.png" alt="" /></a></li><!--
		                --><li><a href="javascript:void(0);" id="changeFinish"><img id="addImg" src="{%$staticUrl%}/apps/shopping/img/content/btn_change_s.png" alt="" /></a></li><!--
		            --></ul>
		        </div>
		    </div><!-- /changePrice div info -->

		    <!-- /game end info -->
            <div id="gameEndConfim" style="display: none">
                <div class="inner">
                <h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_adjust_b.png" alt="" /></h2>
                <div class="section">
                    <div class="lead">精算画面に移動するとゲーム終了になります。よろしいですか？</div>
                </div>
                <ul class="btnSection clearfix"><!--
                    --><li><a href="javascript:void(0);" id="gameBack"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_cancel_s.png" alt="" /></a></li><!--
                    --><li><a href="{%$baseUrl%}/shopping/gameend"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_adjust_s.png" alt="" /></a></li><!--
                --></ul>
                </div>
            </div>
        <!-- /game end info -->

	</div>
</div>

<div id="continer">
    {%include file="shopping/common/hdr.phtml"%}
    <script type="text/javascript">
        $j('#gNavMyCart').addClass('active');
        $j('#gNavHome > a').removeAttr('href');
		$j('#gNavWish > a').removeAttr('href');
    </script>

    <div id="mainColumn">
        {%include file="shopping/common/adjustbox.phtml"%}
        <div id="myCartBox" class="box">

            <div class="hdr">
                <h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_myCart.png" alt="商品一覧" /></h2>
            </div><!--/.hdr-->
            <div id="message1" class="message" style="display: {% if $challengeCount > 0 %}none{% else %}block{% /if %};">まだ、欲しいものリストが登録されていません。</div>
            {% if $lstCartItem %}
                <div class="resultSummary" style="display: {% if $challengeCount == 0 %}none{% else %}block{% /if %};" id="message2"><em id="maxCount">{% $challengeCount %}</em>件中&nbsp;<em><label id="lblNumS">1</label>-<label id="lblNumB">{% if $challengeCount > "10" %}10{% else %}{% $lstCartItem|@count %}{% /if %}</label>件</em>を表示</div>
                <div class="itemList" id="lstItem"><!--
                    {% foreach name=lstCartItem from=$lstCartItem item=data key=key %}
                        --><div class="section">
                            <dl class="itemBlock clearfix"><!--
                                --><dt class="pic" id="pic{% $key %}"><a style="cursor:default;background-image:url({%$data.pic_small%})"><img src="{%$staticUrl%}/apps/shopping/img/spacer.gif" width="76"  height="76" alt="" /></a></dt><!--
                                --><dd class="name" id="name{% $key %}">{% $data.name %}</dd><!--
                                --><dd class="price">価格：￥ {% $data.format_guess_price %}</dd><!--
                            --></dl>
                            <ul class="btnBlock clearfix"><!--
                                --><li class="remove"><a href="javascript:void(0);" onclick="removeNext({% $key %});"><span>カートからはずす</span></a></li><!--
                                --><li class="change"><a href="javascript:void(0);" onclick="changeNext({% $key %});"><span>予想価格を変更する</span></a></li><!--
                                --><li class="rakuten"><a href="{%$baseUrl%}/shopping/torakuten?iid={%$data.iid%}"><span>楽天市場で購入する</span></a></li><!--
                            --></ul>
                            <input type="hidden" id="hidIid{% $key %}" value="{% $data.iid %}" />
                            <input type="hidden" id="hidGuessPrice{% $key %}" value="{% $data.guess_price %}" />
                        </div><!--
                    {% /foreach %}
                --></div>
                {% /if %}

            {% if $challengeCount > 10 %}
                   <div id="navPopItem"><ul class="resultNav"><!--
                       {% foreach name=page from=$page item=data %}
                            {% if $data == "1" %}
                            --><li class="stay">{%$data%}</li><!--
                            {% else %}
                            --><li><a href="javascript:changePageAction({%$data%});">{%$data%}</a></li><!--
                            {% /if %}
                       {% /foreach %}
                       --><li class="next"><a href="javascript:changePageAction(2);">Next&gt;</a></li><!--
                    --></ul></div>
                {% /if %}

            <input type="hidden" id="pageIndex" value="1" />
            <input type="hidden" id="hidCid" value="{% $cid %}" />
        </div><!--/#wishBox.box-->

    </div><!--/#mainColumn-->
<hr />
    <div id="subColumn">
        {%include file="shopping/common/adbox.phtml"%}
        {%include file="shopping/common/trialcalbox.phtml"%}
    </div><!--/#subColumn-->

<script type="text/javascript" src="{%$staticUrl%}/apps/shopping/js/mycart.js?{%$version.js%}"></script>
{%include file="shopping/common/footer.phtml"%}