{%include file="shopping/common/header.phtml"%}

<body id="rakuten">
<div id="continer">
	{%include file="shopping/common/hdr.phtml"%}
	<script type="text/javascript">
		{% if $isInGame %}
		$j('#gNavHome > a').removeAttr('href');
		$j('#gNavWish > a').removeAttr('href');
		{% else %}
		$j('#gNavStore > a').removeAttr('href');
		$j('#gNavMyCart > a').removeAttr('href');
		{% /if %}
		if (null != cm_getCookie('app_top_url')) {
    		top.location.href = cm_getCookie('app_top_url') +  '#pagetop';
    	}
	</script>
	<div id="mainColumn">

		<div id="wishBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/shopping/img/content/tit_rakuten.png" alt="楽天市場で購入" /></h2>
			</div><!--/.hdr-->

			<div class="message">ここから先は楽天市場の商品ページとなります。現実のショッピングとなりますので、ご理解のうえ、移動なさってください。</div>
			{% if $isInGame %}
			<p class="des2">※ゲームプレイ中に以下の「楽天市場に移動する」をクリックすると、ゲーム内容が無効になりますのでご注意ください。</p>
			{% /if %}
			<div class="itemList">
				<div class="section itemView">
					<dl class="itemBlock clearfix"><!--
						--><dt class="pic"><a style="background-image:url({%$itemInfo.pic_small%})"><img src="{%$staticUrl%}/apps/shopping/img/spacer.gif" width="76"  height="76" alt="" /></a></dt><!--
						--><dd class="name">{%$itemInfo.name|escape%}</dd><!--
						--><dd class="price">価格：￥{% if $isInGame %}??????{% else %}{%$itemInfo.format_price%}{% /if %}</dd><!--
					--></dl>
				</div>
			</div>

			<ul class="btnSection clearfix"><!--
				--><li><a href="javascript:cm_goBack();"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_cancel.png" alt="" /></a></li><!--
				--><li><a id="btnGoOut" href="javascript:void(0);" onclick="goOut('{%$itemInfo.url%}');return false;"><img src="{%$staticUrl%}/apps/shopping/img/content/btn_toRakuten.png" alt="" /></a></li><!--
			--></ul>
			<input type="hidden" id="hidInGame" value="{%$isInGame%}" />
		</div><!--/#wishBox.box-->

	</div><!--/#mainColumn-->

<hr />

	<div id="subColumn">
		{%include file="shopping/common/adbox.phtml"%}
		{%include file="shopping/common/profbox.phtml"%}
	</div><!--/#subColumn-->

<script type="text/javascript">
	function goOut(url) {
		if ('1' == $j('#hidInGame').val()) {
    		$j.ajax({
    		    type: "POST",
    		    url: UrlConfig.HostUrl + '/ajax/shopping/stopgame',
    		    dataType: "text",
    		    complete : function(response) {
    	            //if ('true' == response) {
    				//	alert('Game Over!');
    				//}
    				setTimeout(function() {to_outer_site(url);} , 500);
    			}
    		});
		}
		else {
			to_outer_site(url);
		}
	}
</script>

{%include file="shopping/common/footer.phtml"%}