{%include file="scripteditor/common/header.phtml"%}

<body id="help">
{%include file="topad.phtml"%}
<div id="continer">

	{%include file="scripteditor/common/topbox.phtml"%}
	
	<div id="mainColumn">
	
		{%include file="scripteditor/common/searchbox.phtml"%}
		
		<div id="wrap">
            
            <h1><img src="{%$staticUrl%}/apps/scripteditor/img/tit_help.png" alt="ヘルプ" /></h1>
            
            <div class="inner">
                
                <div class="box">
                    <h3>ScriptEditorについて</h3>
                    <p>ScriptEditorは、サーバーサイドスクリプトを書いて・動かして・共有する、ウェブプログラマーのためのスクリプト共有アプリです。</p>
                    <p>ウェブプログラミングに関するちょっとした実験やQ&Aなど、ウェブブラウザで入力した内容がすぐに確認できるので便利です。新しい言語の学習などにも、ぜひご利用ください。</p>
                    <p>※現在、PHPのみ対応しています。Perl, Python, Rubyに関しては、順次対応予定です。</p>
                
                    <h3>ScriptEditorでの禁止行為について</h3>
                    <p>以下の投稿は、不正投稿として禁止しております。<strong>不正投稿を行うとサービスの利用自体ができなくなります</strong>のでご注意ください。</p>
                    <ul>
                        <li>サービスの中断を目的とした内容を含む投稿</li>
                        <li>利用者のサービス利用妨害を目的とした内容を含む投稿</li>
                        <li>利用者の個人情報を取得する投稿、あるいは、取得しようとする投稿</li>
                        <li>猥褻あるいはグロテスクな、他者が見て不快に思う画像・テキストなどを含む投稿</li>
                    </ul>
                
                    <h3>各言語のバージョンについて</h3>
                    <p>各言語のバージョンは以下となります。</p>
                    <table>
                        <tbody>
                            <tr>
                                <th scope="row">Perl</th>
                                <td>未対応</td>
                            </tr>
                            <tr>
                                <th scope="row">PHP</th>
                                <td>5.2.6</td>
                            </tr>
                            <tr>
                                <th scope="row">Python</th>
                                <td>未対応</td>
                            </tr>
                            <tr>
                                <th scope="row">Ruby</th>
                                <td>未対応</td>
                            </tr>
                        </tbody>
                    </table>
                
                    <h3>記述を禁止している関数</h3>
                    <p>サービスを継続して運営するため、以下記述は原則利用できません。</p>
                    <table>
                        <tbody>
                            <tr>
                                <th scope="row">Perl</th>
                                <td>未対応</td>
                            </tr>
                            <tr>
                                <th scope="row">PHP</th>
                                <td>dbmopen(), dbase_open(), filepro(), filepro_rowcount(), filepro_retrieve(), ifx_*(), ingres_*(), mysql_*(), pg_lo_import(), posix_mkfifo(), putenv(), move_uploaded_file(), chdir(), dl(), backtick operator, shell_exec(), exec(), system(), passthru(), popen(), fopen(), mkdir(), rmdir(), rename(), unlink(), copy(), chgrp(), chown(), chmod(), touch(), symlink(), link(), apache_request_headers(), header(), PHP_AUTH variables, highlight_file(), parse_ini_file(), set_time_limit(), max_execution_time, mail(), session_start()</td>
                            </tr>
                            <tr>
                                <th scope="row">Python</th>
                                <td>未対応</td>
                            </tr>
                            <tr>
                                <th scope="row">Ruby</th>
                                <td>未対応</td>
                            </tr>
                        </tbody>
                    </table>
                </div><!--/.box-->
                
            </div><!--/.inner-->
            
        </div><!--/#wrap-->
		
	</div><!--/#mainColumn-->
	
    {%include file="scripteditor/common/subbox.phtml"%}
    <script type="text/javascript">
       jQuery(function($){
           adjustHeight();
       });
    </script>
{%include file="scripteditor/common/footer.phtml"%}

