{%include file="disney/common/header.phtml"%}
<style type="text/css">
    #ranking{
        background-color:#bb8c70;
        color: #ffffff;
    }
    #sitein_link{
        background-color:#f8f1df;
        color:#f8f1df;
    }
    #bgcolor1{
        background-color:#edd9ae;
    }
    #ranking1{
        background-color:#f8b463;
        color:#5e250f;
    }
    #ranking2{
        background-color:#f8f1df;
        color:#5e250f;
    }
    #bgcolor2{
        background-color:#d4f1f9;
    }
    #menu2{
        background-color:#faefc5;
        text-align:left;
    }
    #bgcolor3{
        background-color:#fcdbf5;
    }
    #bgcolor4{
        background-color:#e5fcd0;
    }
    #bgcolor5{
        background-color:#fbe1ff;
    }
</style>

    <div style="font-size:x-small;">
        <div id="sitein_link" style="text-align:center;" >
            <img src="{%$staticUrl%}/apps/disney/img/top.gif" copyright="yes" />
            <!--/#top_img-->
            <!--ｻｲﾄ内ﾘﾝｸ-->
            <br />
            {% emoji code="F8DE"%}<a href='{% "$baseUrl/mobile/disney/map"|mixiurl %}'>ご当地ﾏｯﾌﾟ</a> 
            {% emoji code="F8EC"%}<a href='{% "$baseUrl/mobile/disney/game"|mixiurl %}'>ﾁｬﾚﾝｼﾞｹﾞｰﾑ</a><br />
            {% emoji code="F8BF"%}<a href='#target'>ﾀｰｹﾞｯﾄﾂｱｰ</a> 
            {% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/disney/cuplist"|mixiurl %}'>ｱﾜｰﾄﾞ</a> 
            {% emoji code="F9DC"%}<a href='{% "$baseUrl/mobile/disney/news"|mixiurl %}'>お知らせ</a><br />
        </div>
        <!--/#sitein_link-->
                
        <div id="bgcolor1">
	        <div align="center">
	        <br />
	        {% if $noticeCount > 1 %}
	            {% emoji code="F982"%}<a href='{% "$baseUrl/mobile/disney/news"|mixiurl %}'>お知らせがあります({%$noticeCount%})</a>{% emoji code="F982"%}<br />
	        {% elseif $noticeCount == 1 %}
	            {% emoji code="F982"%}
	            {% if $noticeList.0.type == 1 %}
	                <a href='{% "$baseUrl/mobile/disney/index?CF_nid=`$noticeList.0.id`"|mixiurl %}'>
	            {% elseif $noticeList.0.type == 2 %}
	                <a href='{% "$baseUrl/mobile/disney/award?CF_pid=`$noticeList.0.pid`&CF_fid=`$noticeList.0.actor_uid`&CF_from=trade&CF_nid=`$noticeList.0.id`"|mixiurl %}'>
	            {% elseif $noticeList.0.type == 3 %}
	                <a href='{% "$baseUrl/mobile/disney/cuplist"|mixiurl %}'>
	            {% elseif $noticeList.0.type == 4 %}
	                <a href='{% "$baseUrl/mobile/disney/tradeaward?CF_nid=`$noticeList.0.id`&CF_step=accept"|mixiurl %}'>
	            {% elseif $noticeList.0.type == 5 %}
	                <a href='{% "$baseUrl/mobile/disney/award?CF_pid=`$noticeList.0.pid`&CF_nid=`$noticeList.0.id`"|mixiurl %}'>
	            {% elseif $noticeList.0.type == 7 %}
	                <a href='{% "$baseUrl/mobile/disney/award?CF_pid=`$noticeList.0.pid`&CF_fid=`$noticeList.0.actor_uid`&CF_from=acceptsend&CF_nid=`$noticeList.0.id`"|mixiurl %}'>
	            {% else %}
	                <a href='{% "$baseUrl/mobile/disney/index?CF_nid=`$noticeList.0.id`"|mixiurl %}'>
	            {% /if %}
	            {%$noticeList.0.title%}</a>{% emoji code="F982"%}<br />
	        {% /if %}
	        
	        <a href='{% "location:cell?url=$baseUrl/mobile/disney/getcurrent" %}'><img src="{%$staticUrl%}/apps/disney/img/bn01.gif" copyright="yes" /><br />
	        現在地で今すぐGET♪</a><br />    
	        <a href="#target">▼ﾀｰｹﾞｯﾄﾂｱｰはこちら</a>
	        </div>
	        <!--ご当地ﾏｯﾌﾟ-->
	        <a name="map"></a>
	        <img src="{%$baseUrl%}/mobile/disney/showmap?CF_aid={%$lastTargetAid%}" align="top" copyright="yes" /><br /><br />
	        <!--ﾗﾝｷﾝｸﾞ-->
	        <div id="ranking1">
	        &nbsp;&nbsp;{% emoji code="F995"%}{%$userAwardCount%}ｱｲﾃﾑGET!!<br />
	        </div>      
	        <div id="ranking2">
	        &nbsp;&nbsp;{% emoji code="F9BF"%}ﾏｲﾐｸ内ﾗﾝｷﾝｸﾞ&nbsp;&nbsp;<a href='{% "$baseUrl/mobile/disney/ranking"|mixiurl %}'>{%$friendRank.rank%}位</a><br />
	        </div>
	        <div id="ranking1">
	        &nbsp;&nbsp;{% emoji code="F9BF"%}全体ﾗﾝｷﾝｸﾞ&nbsp;&nbsp;&nbsp;&nbsp;<a href='{% "$baseUrl/mobile/disney/ranking?CF_type=0"|mixiurl %}'>{%$allRank.rank%}位</a><br/>
	        </div>
	        <div align="right">
	        	<a href='{% "$baseUrl/mobile/disney/map"|mixiurl %}'>もっと見る</a>
	        </div>
	        <br />
	        <div align="center">
	        {% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/disney/ranking"|mixiurl %}'>ﾗﾝｷﾝｸﾞ</a> {% emoji code="F8C4"%}<a href='{% "$baseUrl/mobile/disney/sethome"|mixiurl %}'>ﾏｲﾀｳﾝ設定</a> {% emoji code="F9CE"%}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/disney/index" %}'>ﾏｲﾐｸ招待</a><br />
	        <br />
	        {% emoji code="F8E6"%}<a href="#">ﾒｰﾙﾌｧｸﾄﾘｰ会員特典</a>{% emoji code="F8E6"%}
	        </div>
        </div><!--bgcolor1-->
        <!--ﾀｰｹﾞｯﾄﾂｱｰ-->
        <a name="target"></a>
        <div id="bgcolor2" align="center">
        <img src="{%$staticUrl%}/apps/disney/img/m_02.gif" align="top" copyright="yes" />
        
        <font color="#ff0000">毎日の移動でGET!</font><br />
        <br />
        {% if $disneyUser.remain_distance - $disneyUser.flash_distance > 0 %}
            <br />{%$disneyUser.target_name%}まであと<br />
            {% foreach from=$arrayDistance item=data %}
                <img src="{%$staticUrl%}/apps/disney/img/img_docomo/km_{%$data%}_d.gif" copyright="yes" />
            {% /foreach %}
            <img src="{%$staticUrl%}/apps/disney/img/km.gif" copyright="yes" /><br />
            <a href='{% "location:cell?url=$baseUrl/mobile/disney/checkdistance" %}'>
            <img src="{%$staticUrl%}/apps/disney/img/target_bn.gif" copyright="yes" /></a><br />
        {% else %}
            <br />{%$disneyUser.target_name%}まで到達しました!<br />
            次のﾀｰｹﾞｯﾄを設定して下さい<br /><br />
        {% /if %}
        
        {% emoji code="F9BD"%}<a href='{% "$baseUrl/mobile/disney/settarget"|mixiurl %}'>ﾀｰｹﾞｯﾄ設定</a><br />
        </div><!--bgcolor2-->
	        <!--ﾁｬﾚﾝｼﾞｹﾞｰﾑ-->
	        <a name="game"></a>
	   	<div id="bgcolor3">     
	        <img src="{%$staticUrl%}/apps/disney/img/m_03.gif" align="top" copyright="yes" /><br />
	        <div style="text-align:center">
		        <font color="#ff0000">ｹﾞｰﾑで一気に距離を稼ごう!</font><br />
		        (残りﾁｹｯﾄ枚数:{%$disneyUser.game_ticket%}枚)<br />
	        <img src="{%$staticUrl%}/apps/disney/img/roulet.gif" align="left" style="float:left; margin-top:0; margin-right:6; margin-left:0; margin-bottom:0" copyright="yes"/><br />
	        {% emoji code="F9A4"%}<a href='{% "$baseUrl/mobile/disney/game"|mixiurl %}'><span>のりものﾙｰﾚｯﾄ</span></a>{% emoji code="F9A4"%}<br />
	        (mixiﾎﾟｲﾝﾄが必要です)<br />
	        <a href='{% "$baseUrl/mobile/disney/getticket"|mixiurl %}'>ﾁｹｯﾄ購入はこちら</a><br />
	        </div><div style="clear:both"></div>
        </div><!--bgcolor3-->
        <!--ﾏｲﾐｸ情報-->
        <a name="mymic"></a>
        <div id="bgcolor4">
	        <img src="{%$staticUrl%}/apps/disney/img/m_04.gif" align="top" copyright="yes" />
	        <br />
	        {% foreach from=$friendFeedList item=data %}
	            <div style="text-align:left">
		            {%if $data.type == 1 %}
		            <img src="{%$staticUrl%}/apps/disney/img/chara_activity/{%$data.icon%}.gif" align="left" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" copyright="yes"/><br />
		            {% else %}
		            <img src="{%$staticUrl%}/apps/disney/img/img_docomo/{%$data.icon%}_d.gif" width="40px" height="40px" align="left" style="float:left; margin-top:2;margin-right:10; margin-left:5; margin-bottom:2" copyright="yes"/><br />
                    {% /if %}

		            <a href='{% "$baseUrl/mobile/disney/profile?CF_uid=`$data.uid`"|mixiurl %}'><span>{%$data.displayName%}</span></a><br/>
		            {% emoji code="F99F"%}{%$data.name%}{%if $data.icon%}ｽﾃｨｯﾁ{%else%}ｱﾜｰﾄﾞ{%/if%}GET!!{% emoji code="F99F"%}<br/>
	            </div>
	            <div style="clear:both"></div>
	            <img src="{%$staticUrl%}/apps/disney/img/line1.gif" copyright="yes" />
	        {% /foreach %}
	        <div align="right">
	        <a href='{% "$baseUrl/mobile/disney/mymixilist"|mixiurl %}'>もっと見る</a>
	        </div>
	  	</div><!--bgcolor4-->
        <!--もっとﾂｱｰを楽しもう-->
    <div id="bgcolor5">
    	<img src="{%$staticUrl%}/apps/disney/img/m_05.gif" align="top" copyright="yes" />  
        <br />  
        <div align="left">
		    <font color="#ff0000">Q</font> <font color="#ff0000">秘密のｱﾜｰﾄﾞ</font><br />
		    <font color="#0000ff">A</font> ｱﾜｰﾄﾞは､ﾃﾞｨｽﾞﾆｰから贈る秘密のｱｲﾃﾑだよ｡地方制覇したり､友達を招待して･･･｡どんなｱﾜｰﾄﾞがあるかは､お楽しみに!<br />
        <img src="{%$staticUrl%}/apps/disney/img/line2.gif" copyright="yes" />
		    <font color="#ff0000">Q</font> <font color="#ff0000">友達を招待して､特典があるよ</font><br />
		    <font color="#0000ff">A</font> 友達を招待して､登録してくれると､招待した人と招待された人にｹﾞｰﾑﾁｹｯﾄをﾌﾟﾚｾﾞﾝﾄするよ｡どんどん招待してみよう!<br />
        <img src="{%$staticUrl%}/apps/disney/img/line2.gif" copyright="yes" />
		    <font color="#ff0000">Q</font> <font color="#ff0000">ﾒｰﾙﾌｧｸﾄﾘｰ会員特典!</font><br />
		    <font color="#0000ff">A</font> ﾃﾞｨｽﾞﾆｰ公式携帯ｻｲﾄ『ﾒｰﾙﾌｧｸﾄﾘｰ』の会員特典として､会員にしかもらえないｱﾜｰﾄﾞがあるんだよ｡会員の人は､今すぐ､こちらにｱｸｾｽしてみてね｡<br /><br />
        </div>      
        <img src="{%$staticUrl%}/apps/disney/img/line2.gif" copyright="yes" />
        <div align="right">
        <a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}'>もっと見る</a>
        </div>
    </div><!--bgcolor5-->
        
        <!--topfooter-->
        <div style="background-color:#f8f1df;">
                ├{% emoji code="F9A8"%}<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}'>FAQ</a>{% emoji code="F9A8"%}<br />
                ├{% emoji code="F8E9"%}<a href="#">対応端末一覧</a><br />
                ├{% emoji code="F97D"%}<a href="#">ﾌﾟﾗｲﾊﾞｼｰﾎﾞﾘｼｰ</a><br />
                └{% emoji code="F8E4"%}<a href="#">特商法</a><br />
        </div><!--#bgcolor#f8f1df;-->
        
</div>
</body>
</html>
        