{%include file="disney/common/header.phtml"%}

	<div style="background-color:#f8f1df; font-size:x-small;" >
	<a name="#top"></a>
	{% disneyimg  name="sub_ti_charge" style='width="100%"' %}<br />
	<br />
	<div style="color:#7f7670;">
		当ｱﾌﾟﾘは基本的に無料で遊べますが､一部のｺﾝﾃﾝﾂ･ｻｰﾋﾞｽは有料となります｡<br />
		
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
		
		{% disneyimg name="charge_line" style='width="100%"' %}<br />
		<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />

		<div class="title" style="color:#ff6600;font-weight: bold;text-align:center;">
			有料ｻｰﾋﾞｽ利用規約<br />
			Disney.jpﾓﾊﾞｲﾙ･ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽ<br />
		</div><!--/.title-->
		<br />

		<div class="txt1" style="text-align:left;">
			このDisney.jpﾓﾊﾞｲﾙ･ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽは､ｳｫﾙﾄ･ﾃﾞｨｽﾞﾆｰ･ｼﾞｬﾊﾟﾝ株式会社が運営する有料ｻｰﾋﾞｽです｡<br />
			有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽに登録するか､または有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽから有料ｺﾝﾃﾝﾂをﾀﾞｳﾝﾛｰﾄﾞすることにより､
			この支払条件とDisney.jpの利用規約にご同意いただくことになります｡<br />
		</div><!--/.txt1-->
		<br />

		<div class="tx_1" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">1. ｱｲﾃﾑ課金型ｺﾝﾃﾝﾂ</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			有料ｺﾝﾃﾝﾂｻｰﾋﾞｽからﾀﾞｳﾝﾛｰﾄﾞにより取得したｱｲﾃﾑ課金型ｺﾝﾃﾝﾂについては､
			単体でまたは月単位の加入ｻｰﾋﾞｽの一部としてかを問わず､お客様は､
			そのｺﾝﾃﾝﾂについて所定の情報料(税額込み)を請求され､ﾃﾞｨｽﾞﾆｰに支払うことになります｡<br />
		</div><!--/.tx_1-->
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
		<br />

		<div class="tx_2" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">2. 情報料の回収</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			mixiが､ﾃﾞｨｽﾞﾆｰに代わり､ﾃﾞｨｽﾞﾆｰから情報料に対する権利を引き継ぐ形で､
			情報料を回収します｡お客様の情報料の支払義務は､理由のいかんを問わず
			(特に､ﾈｯﾄﾜｰｸ障害､携帯電話ｻｰﾋﾞｽの停止､機種の不適合､ｱｶｳﾝﾄ停止､
			またはﾊｰﾄﾞｳｪｱ､ｿﾌﾄｳｪｱもしくはｺﾝﾃﾝﾂｻｰﾋﾞｽ向けのｺﾝﾃﾝﾂのｱｯﾌﾟﾃﾞｰﾄおよびﾒﾝﾃﾅﾝｽを含みます｡)､
			有料ｺﾝﾃﾝﾂｻｰﾋﾞｽへのｱｸｾｽ不能により影響されないものとします｡
			情報量には､ﾈｯﾄﾜｰｸ通信費またはﾃﾞｰﾀ通信費は含まれません｡
			こうした費用は､携帯電話会社(ﾃﾞｨｽﾞﾆｰ･ﾓﾊﾞｲﾙを含みます｡)との契約に従って､
			別途お客様のご負担となります｡<br />
		</div><!--/.tx_2-->
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
		<br />

		<div class="tx_3" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">3. 返金､交換または移管が行われないこと</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			情報料の返金はいかなる理由であっても行われません｡
			有料ｻｰﾋﾞｽから取得したｺﾝﾃﾝﾂは､その他のｺﾝﾃﾝﾂと交換することはできず､
			有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽへの登録は､各有料ｺﾝﾃﾝﾂｻｰﾋﾞｽにおいて別段の定めがない限り､
			他のｺﾝﾃﾝﾂ･ｻｰﾋﾞｽやその他のﾕｰｻﾞｰに移管することはできません｡<br />
		</div><!--/.tx_3-->
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
		<br />

		<div class="tx_4" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">4. 支払不履行</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			mixiが定める支払期日までにお客様が情報料を支払わなかった場合､
			mixiは､お客様の氏名および未払いの情報料の詳細についてﾃﾞｨｽﾞﾆｰに
			通知することができます｡ﾃﾞｨｽﾞﾆｰは､お客様に通知することなく､
			有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽの提供を停止することができます｡<br />
		</div><!--/.tx_4-->
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
		<br />

		<div class="tx_5" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">5. 保証の不存在</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			ﾃﾞｨｽﾞﾆｰは､有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽ､ｻｰﾋﾞｽを通じて提供されたｺﾝﾃﾝﾂもしくは情報､
			またはお客様によるこれらの利用に関して､一切の保証を行いません｡
			ﾃﾞｨｽﾞﾆｰは､理由のいかんを問わず(特に､携帯電話機の故障もしくは破壊
			または携帯電話機もしくはｺﾝﾋﾟｭｰﾀに記憶されたﾃﾞｰﾀの消失を含みます｡)､
			有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽの利用不能､お客様による利用またはお客様が利用できない
			ことを原因とする損害について､一切の責任を負わないものとします｡<br />
		</div><!--/.tx_5-->
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
		<br />

		<div class="tx_6" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">6. 責任の制限</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			ﾃﾞｨｽﾞﾆｰ側の重過失または故意の不正行為による場合を除き､有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽに
			関する損害についてのﾃﾞｨｽﾞﾆｰのお客様に対する責任総額は､特定の有料ｺﾝﾃﾝﾂｻｰﾋﾞｽに
			ついてお客様が支払った情報料の総額を超えないものとします｡<br />
		</div><!--/.tx_6--> 
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
			<br />

		<div class="tx_7" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">7. 裁判管轄</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			Disney.jpﾓﾊﾞｲﾙのｺﾝﾃﾝﾂｻｰﾋﾞｽは､日本国内の在住の方のみがご利用になれます｡
			この有料ｻｰﾋﾞｽ利用規約は､日本法に準拠し､全ての紛争は東京地方裁判所で
			解決されるものとします｡<br />
		</div><!--/.tx_7-->     	

		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る<br />
		</div>
	</div>
{%include file="disney/common/footer.phtml"%}