{%include file="disney/common/header.phtml"%}

{% if $isArrive == 1 %}
	<div style="font-size:x-small; background-color:#d4f1f9; text-align:center;">
		{% disneyimg name="sub_ti_target" style='align="top" width="100%"' %}<br />
		<img copyright="yes" src="{%$staticUrl%}/apps/disney/img/chara_get/{%$disneyUser.t_award_icon%}_{%if $ua==3%}a.png{%elseif $ua==2%}s.pnz{%else%}d.gif{%/if%}" align="top" /><br /><br />
		{%if $ua == 3%}
			{% emoji code="F9BE"%}<a href="{%$diaryUrl%}" style="color:#ffffff;">日記に書く</a><br />
		{% else %}
			<form method="post" action="http://m.mixi.jp/add_diary.pl" accept-charset="Shift_JIS,utf-8">
				<input type="hidden" name="diary_title" value="{%$diary_title%}" />
				<input type="hidden" name="diary_body" value="{%$diary_body%}" /></br>
				<input type="submit" value="日記に書く" />
			</form>
		{% /if %}

		<a href='{% "$baseUrl/mobile/disney/settarget"|mixiurl %}'>次のﾀｰｹﾞｯﾄ設定へ</a>
		<br /><br />
{% else %}
	<div style="font-size:x-small; background-color:#d4f1f9;text-align:center;">
		{% disneyimg name="sub_ti_targetset2" style='align="top" width="100%"' %}
		<br /><br />
		<span style="color:#232577;">移動距離</span>
		{% foreach from=$arrayMove item=data %}
			{% disneyimg style='higth="12px" width="12px"' name="km_$data" %}
		{% /foreach %}
		{% disneyimg style='higth="20px" width="20px"' name="km" %}<br />
		<br />
		<span style="color:#232577;">{%$disneyUser.target_name%}まであと</span><br />
		{% foreach from=$arrayRemain item=data %}
			{% disneyimg name="km_$data" %}
		{% /foreach %}
		{% disneyimg name="km" %}<br />

		<div style="text-align:right;">
			<a href='{% "$baseUrl/mobile/disney/help?CF_help=location"|mixiurl %}'>位置情報の差異について</a><br />
		</div>
		<div class="message" style="color:#ff0000;text-align:left;">
			※前回の｢ﾁｪｯｸ!｣から<br />
			今回の｢ﾁｪｯｸ!｣までのKmです。
		</div><!--/.message-->		
		<br />
{% /if %}
{%include file="disney/common/footer.phtml"%}