{%include file="disney/common/header.phtml"%}

	<div id="campain_dirly" style="font-size:x-small;background-color:#edd9ae;">
	
    	<div class="title" style="background-color:#39F; text-align:center; color:#ffffff;" >
			<img src="http://mm.mixi.net/img/dot0.gif" height="2"/><br />
			日記投稿キャンペーン<br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="2"/><br />
		</div><!--/#title-->
				
		<div class="campain_info" style="color:#630;text-align:center;">
			<div class="campain_title1" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
				{% disneyimg name="campain_bn1" style='width="100%"'%}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
			</div><!--/#campain_title1-->		
			期間限定!!<br />
			日記投稿でｹﾞｰﾑﾁｹｯﾄを<br />
			5枚GET!<br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
			
			{%if $ua == 3%}
				<a href="{%$diaryUrl%}">{% disneyimg name="campain_btn1" style='width="69%"'%}</a><br />
			{% else %}
				<form method="post" action="http://m.mixi.jp/add_diary.pl" accept-charset="Shift_JIS,utf-8">
					<input type="hidden" name="diary_title" value="{%$diary_title%}" />
					<input type="hidden" name="diary_body" value="{%$diary_body%}" /></br>
					<input type="submit" value="日記に書く" />
				</form>
			{% /if %}
				
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<div style="text-align:center;">↓詳細はこちら↓</div>
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />	
		</div><!--/#campain_info-->
		
		<div class="get_gameticket" style="color:#630;">
			<div class="title" style="background-color:#39F; text-align:center; color:#ffffff;" >
				<img src="http://mm.mixi.net/img/dot0.gif" height="2"/><br />
				キャンペーン概要<br />
				<img src="http://mm.mixi.net/img/dot0.gif" height="2"/><br />
			</div><!--/#title-->
			<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
			
			<div class="get_ticket_info">
				今なら、期間限定でこのﾍﾟｰｼﾞから日記を投稿すると、必ず<span style="color:#F00;">ｹﾞｰﾑﾁｹｯﾄが5枚</span>もらえるよ。<br />
				詳しくは、下記を読んでね。<br />
				<br />
				<span style="color:#39F;">{% emoji code="F99F"%}条件{% emoji code="F99F"%}</span><br />
				・ｱﾌﾟﾘ紹介日記を<span style="color:#F06;font-size:small;">『全体に公開』</span>で投稿した方。<br />
				・ｷｰﾜｰﾄﾞ<span style="color:#F06;font-size:small;">『Disneyご当地ｺﾚｸｼｮﾝ』</span>を記載している方。<br />
				<br />
				{% disneyimg name="dotline_fff5f5_s" style='width="100%"'%}
				【日記例】<br />
				<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
				今日、北海道ｽﾃｨｯﾁをようやく手にいれました。北海道といえば、ｼﾞﾝｷﾞｽｶﾝ。。。<br />
				最近、食べてないな~。今度、近所のｼﾞﾝｷﾞｽｶﾝ屋にいこーっと。<br />
				{% disneyimg name="dotline_fff5f5_s" style='width="100%"'%}
				などなど、あなたの地域のご当地名産や、地域の情報を盛り込んだりと、投稿内容は、自由です。<br />
				<span style="color:#F06;">※自動的に当ｱﾌﾟﾘの名前とURL、が日記に張り付けられます。</span><br />
				<br />
				<span style="color:#39F;">{% emoji code="F8E6"%}ﾌﾟﾚｾﾞﾝﾄ内容{% emoji code="F8E6"%}</span><br />
				ｹﾞｰﾑﾁｹｯﾄ5枚<br />
				<br />
				<span style="color:#39F;">{% emoji code="F9A0"%}応募回数{% emoji code="F9A0"%}</span><br />
				お１人様１回まで<br />
				<br />
				<span style="color:#39F;">{% emoji code="F9A0"%}ｷｬﾝﾍﾟｰﾝ期間{% emoji code="F9A0"%}</span><br />
				3月11日15:00～3月23日15:00<br />
				<br />
				<span style="color:#39F;">{% emoji code="F8E6"%}ﾌﾟﾚｾﾞﾝﾄ付与時期{% emoji code="F8E6"%}</span><br />
				3月24日15:00に付与します。<br />
				<span style="color:#F06;">※付与された旨は､通知されません｡のりものﾙｰﾚｯﾄのﾍﾟｰｼﾞでﾁｹｯﾄ追加をご確認ください。<br />
				※付与の有無に関する､お問い合わせには､応じられません｡</span><br />
			</div><!--/#get_ticket_info-->
			
			<div class="dirly_btn" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
				
			{%if $ua == 3%}
    				<a href="{%$diaryUrl%}">{% disneyimg name="campain_btn1" style='width="69%"'%}</a><br />
    			{% else %}
    				<form method="post" action="http://m.mixi.jp/add_diary.pl" accept-charset="Shift_JIS,utf-8">
    					<input type="hidden" name="diary_title" value="{%$diary_title%}" />
    					<input type="hidden" name="diary_body" value="{%$diary_body%}" /></br>
    					<input type="submit" value="日記に書く" />
    				</form>
    			{% /if %}
    			
			</div><!--/#dirly_btn-->
			{% disneyimg name="dotline_fff5f5_s" style='width="100%"'%}
			<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />
			<blink>同時実施中!!</blink><br />
			ﾏｲﾐｸ招待でｹﾞｰﾑﾁｹｯﾄGET!<br />
			<div style="text-align:right;">≫<a href='{% "$baseUrl/mobile/disney/invite"|mixiurl %}'>詳しくは、こちら</a></div>
			<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />

		</div><!--/#get_gameticket-->
        
{%include file="disney/common/footer.phtml"%}
