{%include file="disney/common/header.phtml"%}
		
		<div style="font-size:x-small; background-color:#ffffcc; color:#4e211c; text-align:left;">
		
			【ﾒﾝﾃﾅﾝｽのお知らせ】<br />
			
			<br />
			Disneyご当地ｺﾚｸｼｮﾝをご利用いただき､ありがとうございます｡<br />
			<br />
			
			12/25(金)午前9:00 - 12:00に､ｻｰﾋﾞｽﾘﾆｭｰｱﾙのためﾒﾝﾃﾅﾝｽ作業を行います｡この間､ご当地ｺﾚｸｼｮﾝ全ｻｰﾋﾞｽに一時的にｱｸｾｽができない状態になります｡<br />
			<br />
			- ﾒﾝﾃﾅﾝｽ予定日時:12/25(金)午前9:00 - 12:00<br />
			- 対象ｻｰﾋﾞｽ:全ｻｰﾋﾞｽ<br />
			<br />
			ご利用のﾕｰｻﾞｰの皆さまには､ご迷惑をお掛け致しまして大変申し訳ございませんが､ﾒﾝﾃﾅﾝｽへのご理解をいただけますと幸いです｡<br />
			<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<div style="text-align:center;">
				<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}' >よくある質問</a><br />
			</div>
			
		</div>
	</body>
</html>      
	  