{%include file="disney/common/header.phtml"%}
		
		<div style="font-size:x-small; background-color:#ffffcc; color:#4e211c; text-align:left;">
		
			<br />
			Disneyご当地ｺﾚｸｼｮﾝをご利用いただき､ありがとうございます｡<br />
			<br /> 
			≫12/25<br /> 
			 ｱﾜｰﾄﾞ不具合についてのお詫び<br /> 
			 12月7日から12月25日まで､次の条件の場合ｱﾜｰﾄﾞが正しく表示されない不具合が
			 発生しておりました｡<br /> 
			<br /> 
			・内容<br /> 
			 ﾄﾚｰﾄﾞにより､地域をｺﾝﾌﾟﾘｰﾄする最後のご当地ｷｬﾗｸﾀｰを入手した場合､
			 地域制覇ｱﾜｰﾄﾞが付与されない<br /> 
			<br /> 
			・対応<br /> 
			 該当のお客様には12/26以降の初ｱｸｾｽ時にｱﾜｰﾄﾞを付与いたします<br /> 
			<br /> 
			 ご迷惑をおかけしてしまい､申し訳ございませんでした｡<br /> 
			 今後ともDisneyご当地ｺﾚｸｼｮﾝをよろしくお願いいたします｡
			<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<div style="text-align:center;">
				<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}' >よくある質問</a><br />
			</div>
			
		</div>
	</body>
</html>      
	  