{%include file="disney/common/header.phtml"%}
		
		<div style="font-size:x-small; background-color:#ffffcc; color:#4e211c; text-align:left;">
		
			≫1/19<br />
			1/20(水)午後14:00 - 16:00に､ｻｰﾊﾞｰﾒﾝﾃﾅﾝｽ作業に伴い､ご当地ｺﾚｸｼｮﾝ全ｻｰﾋﾞｽに一時的にｱｸｾｽができない状態になります｡<br />
			<br />
			･ﾒﾝﾃﾅﾝｽ予定日時:1/20(水)午後14:00 - 16:00<br />
			･対象ｻｰﾋﾞｽ:全ｻｰﾋﾞｽ<br />
			<br />
			ご利用のﾕｰｻﾞｰの皆さまには､ご迷惑をお掛け致しまして大変申し訳ございませんが､ﾒﾝﾃﾅﾝｽへのご理解をいただけますと幸いです｡<br />
			
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<div style="text-align:center;">
				<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}' >よくある質問</a><br />
			</div>
			
		</div>
	</body>
</html>      
	  