{%include file="disney/common/header.phtml"%}
	<div id="award" style="background-color:#fffcc7;font-size:x-small;text-align:center;" >

	{% disneyimg name="sub_ti_sp" style='align="top" width="100%"' %}
	<br />
	{% disneyimg style='height="3"' name="dot0" %}<br />
	<div class="message" style="color:#930;text-align:left;">	
		Disney公式携帯ｻｲﾄの会員は特別なｱﾜｰﾄﾞをGETできるよ!<br />
	</div>
	<br />
	<div style="background-color:#F90; color:#FF9;">
		ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ会員特典
	</div>
	<img src="http://mm.mixi.net/img/dot0.gif" height="5"/><br />	
	{% disneyimg name="t_mail_q" style='align="top" width="100%"' %}

	<br />
	<div style="color:#930;">
		ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ･ﾌﾟﾚﾐｱﾑ<br />
		【取得ｽｺｱ: 300点】
	</div>
	<br />
	<span style="color:#F60;">対象ｻｲﾄ:ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ</span><br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	<div class="message" style="color:#930;text-align:left;">
		GETすれば一気にﾗﾝｷﾝｸﾞUP!まずは次のﾍﾟｰｼﾞで｢登録確認｣をﾁｪｯｸしよう!
	</div>
	<br />
	<!--a href="http://mt9020.mixi.jp/list_skin_deluxe_disney.pl?guid=ON">次へ</a><br /-->
	<a href="http://m.mixi.jp/pr_disney_link.pl?guid=ON">次へ</a><br />
	<br />
{%include file="disney/common/footer.phtml"%}