{%include file="disney/common/header.phtml"%}

        <div id="bgcolor1" style="background-color:#ffe2ae; text-align:center;font-size:x-small;">
        <div style="background-color:#50b83a; text-align:center;">
                {% disneyimg  name="sub_ti_playrule" style='align="top" width="100%"' %}
                {%include file="disney/common/topmenu.phtml"%}
         		<span style="color: rgb(255, 102, 0);">ご当地ｺﾚｸｼｮﾝにようこそ!</span><br/>
		 
		{% disneyimg name="tuto_line" style='align="top" width="100%"' %}<br/>
        <div style="text-align: left; color: rgb(102, 0, 0);">
         		{% disneyimg name="tu_th" style='height="107" width="80" align="left" style="float: left; margin-top: 0pt; margin-left: 0pt;"' %}<br/>
                ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝは、全国各地のご当地ｷｬﾗｸﾀｰをｺﾚｸｼｮﾝすることができるｱﾌﾟﾘだよ!
         </div><!--/left-->
        <div style="clear: both;" clear="all"/></div>
         
        <div id="yellow" style="background-color: rgb(255, 255, 176); text-align: left;">
            {% disneyimg name="ti_atumeyou" style='align="top" width="100%"' %}
        <div class="select" style="color: rgb(255, 51, 102);">
            {% disneyimg name="targettour_icon1" style='height="22" width="28" align="left" style="float: left; margin-top: 0pt; margin-bottom: 0pt;"' %}
            <span style="text-align: left;">現在地でGET!</span>
            <div style="clear: both;" clear="all"/></div>
            <div style="color: rgb(102, 51, 0); text-align: left;">
                『ご当地GET!』ﾎﾞﾀﾝを押すと現在地のご当地ｷｬﾗｸﾀｰがその場で手に入れることが出来るんだよ!旅先でGETして､友達へのお土産にもﾋﾟｯﾀﾘ｡
            </div>
  			
			{% disneyimg name="award_line2" style='align="top" width="100%"' %}
  
            {% disneyimg name="targettour_icon2" style='height="22" width="28" align="left" style="float: left; margin-top: 0pt; margin-bottom: 0pt;"' %}
            <span style="text-align: left;">日々の移動距離でGET!</span>
            <div style="clear: both;" clear="all"/></div>
            <div style="color: rgb(102, 51, 0); text-align: left;">
                日々の移動距離によってお目当ての県のご当地ｷｬﾗｸﾀｰを手に入れることがことができるよ。移動したらｺﾏﾒに『ﾁｪｯｸする』ﾎﾞﾀﾝを忘れずに押してね
            </div>
			
			{% disneyimg name="award_line2" style='align="top" width="100%"' %}
			
            {% disneyimg name="targettour_icon3" style='height="22" width="28" align="left" style="float: left; margin-top: 0pt; margin-bottom: 0pt;"' %}
            <span style="text-align: left;">ﾏｲﾐｸとﾄﾚｰﾄﾞしてGET!</span>
            <div style="clear: both;" clear="all"/></div> 
            <div style="color: rgb(102, 51, 0); text-align: left;">
                集めたご当地ｷｬﾗｸﾀｰは、ﾏｲﾐｸと交換することが出来るよ。友達のﾏｯﾌﾟを見に行って、
                欲しいご当地ｷｬﾗｸﾀｰがあったら、すかさず、｢ﾄﾚｰﾄﾞする｣ﾎﾞﾀﾝを押して、ﾘｸｴｽﾄしてみよう!
            </div>
        </div><!--/.select-->           
        
        
      <div id="pulple" style="background-color: rgb(251, 225, 255);">
          {% disneyimg name="ti_atumeyou2" style='align="top" width="100%"' %}
          <div style="text-align: left; color: rgb(204, 0, 204);">
                獲得点数の累計でﾗﾝｷﾝｸﾞが決まるよ｡さらにｺｺだけの限定ご当地ﾒｰﾙ素材や待受にも加工できるよ｡
                <br/><br/>
          </div>
          <img copyright="yes" width="100%" src="{%$staticUrl%}/apps/disney/img/7_3_ehime.gif"/><br/>
		  <img copyright="yes" width="100%" src="{%$staticUrl%}/apps/disney/img/8_8_okinawa.gif"/><br/>
		  
                <br/>
                <div style="color:#ff0f64;text-align:center;">
					他にも楽しいｲﾍﾞﾝﾄがいっぱい!<br/>
                </div>
      
      </div><!--/#yellow-->
      </div>
      {%include file="disney/common/firstfooter.phtml"%}