{%include file="disney/common/header.phtml"%}

	<div style="background-color:#f8f1df; font-size:x-small;" >
	{% disneyimg  name="sub_ti_tokus" style='width="100%"' %}<br />
	<br />
	<div style="color:#7f7670;">
		<div class="title" style="color:#ff6600;font-weight: bold;text-align:center;">
			特定商取引に関する法律に基づく表示<br />
		</div><!--/.title-->
		<br />

		<div class="txt1" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">役務提供事業者</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			ｳｫﾙﾄ･ﾃﾞｨｽﾞﾆｰ･ｼﾞｬﾊﾟﾝ株式会社<br />
		</div><!--/.txt1-->
		<br />

		<div class="tx_1" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">所在地</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			〒153-8922 東京目黒区下目黒1-8-1 ｱﾙｺﾀﾜｰ7階<br />
		</div><!--/.tx_1-->
		<br />

		<div class="tx_2" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">通信販売に関する責任者</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			ｳｫﾙﾄ･ﾃﾞｨｽﾞﾆｰ･ｼﾞｬﾊﾟﾝ株式会社<br />
			ﾃﾞｨｽﾞﾆｰ･ｲﾝﾀｰﾗｸﾃｨﾌﾞ･ﾒﾃﾞｨｱ･ｸﾞﾙｰﾌﾟ(ｼﾞｬﾊﾟﾝ) 鳥海 清<br />  
		</div><!--/.tx_2-->
		<br />

		<div class="tx_3" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">問い合わせ先</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			ﾃﾞｨｽﾞﾆｰ･ｲﾝﾀｰﾈｯﾄ･ｸﾞﾙｰﾌﾟ･ｶｽﾀﾏｰｾﾝﾀｰ<br />
			お問い合わせは､<a href="http://m.mixi.jp/inquiry_appli.pl?&id=11122">こちら</a>までお願いします｡<br />
		</div><!--/.tx_3-->
		<br />

		<div class="tx_4" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">ｻｰﾋﾞｽ料およびｻｰﾋﾞｽ期間</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			各有料ｺﾝﾃﾝﾂ･ｻｰﾋﾞｽまたは個々のｺﾝﾃﾝﾂに関する情報料は､1ヶ月単位の加入､
			ﾀﾞｳﾝﾛｰﾄﾞ毎またはこれらの組み合わせとして､税込みの所定額により請求されます｡
			毎月の支払額は､mixiが定める請求期間に基づいて計算されるものとします｡
			1ヶ月未満の請求月(お客様が有料ｺﾝﾃﾝﾂｻｰﾋﾞｽに登録するかまたは登録を解除した
			月を含みます｡)についても､1ヶ月分の情報料が請求されます｡
			お試し登録やﾌﾟﾛﾓｰｼｮﾝｷｬﾝﾍﾟｰﾝなどの一定の場合には､月額情報料は免除または
			割引されることがあります｡お客様は､登録日から登録解除日まで､
			有料ｺﾝﾃﾝﾂｻｰﾋﾞｽにｱｸｾｽし､当該有料ｺﾝﾃﾝﾂｻｰﾋﾞｽから入手したｺﾝﾃﾝﾂを
			利用することができます｡情報料にはﾈｯﾄﾜｰｸ料金またはﾃﾞｰﾀ通信費は含まれません｡
			こうした費用は､携帯電話会社との契約に従って､別途お客様のご負担となります｡<br />
		</div><!--/.tx_4-->
		<br />

		<div class="tx_5" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">返金および交換</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			提供するｺﾝﾃﾝﾂおよびｻｰﾋﾞｽの性質により､ご購入いただいたｺﾝﾃﾝﾂまたは有料ｻｰﾋﾞｽの
			登録について返金および交換は行われません｡<br />
		</div><!--/.tx_5-->
		<br />

		<div class="tx_6" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">支払の時期および方法</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			有料ｺﾝﾃﾝﾂｻｰﾋﾞｽへのｱｸｾｽまたは有料ｺﾝﾃﾝﾂのﾀﾞｳﾝﾛｰﾄﾞについては､mixiのｱｶｳﾝﾄを
			通じて請求が行われます｡mixiが定める方法により､mixiによる請求を
			支払わなければなりません｡<br />
		</div><!--/.tx_6--> 
		<br />

		<div class="tx_7" style="text-align:left;">
			<span style="color:#ff6600;font-weight: bold;">ｻｰﾋﾞｽ利用のための対応機種およびｿﾌﾄｳｪｱの要件</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			有料ｺﾝﾃﾝﾂｻｰﾋﾞｽに関連する対応機種またはｿﾌﾄｳｪｱの要件については､
			個々の有料ｺﾝﾃﾝﾂｻｰﾋﾞｽおよびお客様の携帯電話会社でご確認ください｡<br />
			<br />
		</div><!--/.tx_7-->
	</div>
{%include file="disney/common/footer.phtml"%}