{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">ご当地ｷｬﾗｸﾀｰ取得</span><br />
			<br />
			<span style="color:#5b2806; font-size:large:">ご当地ﾏｯﾌﾟ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>他の地方をみるには?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>都道府県の横の数字は､何ですか?</a><br />
			<span style="color:#cc6600;">Q3.</span><a href='#003'>ご当地ｷｬﾗｸﾀｰの詳細を見るには?</a><br />
			
			<br />
			<hr />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.他の地方をみるには?</span><br />
			<hr />         
			<span style="color:#3300FF;">A1.</span>現在表示されているご当地ﾏｯﾌﾟの都道府県名下部にある地方名を押下してください｡<br />
			
			<br />
			<hr />

			<a name="002"></a>
			<span style="color:#cc6600;">Q2.都道府県の横の数字は､何ですか?</span><br /> 
			<hr />                   
			<span style="color:#3300FF;">A2.</span>重複して手に入れているご当地ｷｬﾗｸﾀｰ数です｡<br />
			
			<br />
			<hr />
			
			<a name="003"></a>
			<span style="color:#cc6600;">Q3.ご当地ｷｬﾗｸﾀｰの詳細を見るには?</span><br />            
			<hr />           
			<span style="color:#3300FF;">A3.</span>ご当地ﾏｯﾌﾟの各都道府県名を押下してください｡<br />	

	</div><!--/#contet-->

	<br />
	<hr />
	
	<div id="comment">
		解決しなかった場合は、お手数ですが下記より再度内容をご確認のうえ、お問い合わせください。
	</div><!--/#comment-->

	<br />
			<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
