{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾀｰｹﾞｯﾄﾂｱｰ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>移動したのに､ﾀｰｹﾞｯﾄまでの距離が変わりません｡</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ﾀｰｹﾞｯﾄ達成後､｢ﾁｪｯｸする｣ﾎﾞﾀﾝがなくなりました｡</a><br />
		<span style="color:#cc6600;">Q3.</span><a href='#003'>ﾀｰｹﾞｯﾄを変更したら､移動距離があらたに設定されました｡</a><br />
		
		<hr />
		
		<a name="001"></a>
		<span style="color:#cc6600;">Q1.移動したのに､ﾀｰｹﾞｯﾄまでの距離が変わりません｡</span><br />
		<hr /><span style="color:#3300FF;">A1.</span>ﾀｰｹﾞｯﾄﾂｱｰの距離は､位置情報をもとに算出されています｡そのため､移動開始場所と移動終了場所が同じだと0kmになってしまいます｡<br />
		
		<br />
		
		<hr />
		
		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ﾀｰｹﾞｯﾄ達成後､｢ﾁｪｯｸする｣ﾎﾞﾀﾝがなくなりました｡</span><br /> 
		<hr /><span style="color:#3300FF;">A2.</span>ﾀｰｹﾞｯﾄが達成されるとﾀｰｹﾞｯﾄ設定をしなければﾂｱｰで遊ぶことは､できません｡そのため､未設定の場合は､非表示になります､一度､設定されているかを確認してください｡<br />
		
		<br />
		
		<hr />
		
		<a name="003"></a>
		<span style="color:#cc6600;">Q3.ﾀｰｹﾞｯﾄを変更したら､移動距離があらたに設定されました｡</span><br />            
		<hr /><span style="color:#3300FF;">A3.</span>ﾀｰｹﾞｯﾄを再設定すると､今までのﾀｰｹﾞｯﾄまでの距離がﾘｾｯﾄされ､再設定した地域までの距離が表示されます｡<br />
		
		<br />
			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div id="comment">
		解決しなかった場合は、お手数ですが下記より再度内容をご確認のうえ、お問い合わせください。
	</div><!--/#comment-->

	<br />
			<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
