{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾗﾝｷﾝｸﾞ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.このﾗﾝｷﾝｸﾞは､何のﾗﾝｷﾝｸﾞですか?</span><br />
			<hr />
			
			<span style="color:#3300FF;">A1.</span>
			様々なｱｸｼｮﾝにより､点数が付与され､それをもとに順位付けしています｡各ｱｸｼｮﾝと点数は､下記の通りです｡<br />
			
			･現地に行ってご当地ｷｬﾗｸﾀｰをGETする          250点<br />
			･ﾀｰｹﾞｯﾄﾂｱｰでご当地ｷｬﾗｸﾀｰをGETする      100点<br />
			･ﾁｬﾚﾝｼﾞｹﾞｰﾑに挑戦する(1回につき)                      10点<br />
			･ご当地ｷｬﾗｸﾀｰを1ｱｲﾃﾑﾄﾚｰﾄﾞで送付する          10点<br />
			･ご当地ｷｬﾗｸﾀｰを1ｱｲﾃﾑﾄﾚｰﾄﾞで受け取る          10点<br />
			･ご当地ｷｬﾗｸﾀｰをﾃﾞｺﾒ化してﾀﾞｳﾝﾛｰﾄﾞする  10点<br />
			･ご当地ｷｬﾗｸﾀｰをﾏｲﾐｸに贈る                              50点<br />
			
			<span style="color:ff0000;">※各ｱﾜｰﾄﾞでも点数を取得するこができます｡ｱﾜｰﾄﾞは､公表していないため点数を開示していません｡</span><br />
	
			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div id="comment">
		解決しなかった場合は、お手数ですが下記より再度内容をご確認のうえ、お問い合わせください。
	</div><!--/#comment-->

	<br />
			<hr />			
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
