{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾃﾞｺﾒ化</span><br />
		<br />
		<span style="color:#cc6600;">Q1.ご当地ｷｬﾗｸﾀｰをﾃﾞｺﾒ化にするには?</span><br />
		
		<hr />
		
		<span style="color:#3300FF;">A1.</span>
		自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢ﾃﾞｺﾒ化する｣を押下してください｡その後､ﾃﾞｺﾒ化完了画面が表示されたら｢ﾀﾞｳﾝﾛｰﾄﾞ｣を押下します｡あとは､お持ちのｹｰﾀｲの使用方法に従ってください｡<br />
		<span style="color:ff0000;">※ﾃﾞｺﾒ化は､有料ｻｰﾋﾞｽです。</span><br />

	</div><!--/#contet-->

	<br />
	<hr />
	
	<div id="comment">
		解決しなかった場合は、お手数ですが下記より再度内容をご確認のうえ、お問い合わせください。
	</div><!--/#comment-->

	<br />
			<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
