{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾏｲﾐｸ情報</span><br />
		<br />
		<span style="color:#cc6600;">Q1.ﾏｲﾐｸ情報とは何ですか?</span><br />
		
		<hr />
		
		<span style="color:#3300FF;">A1.</span>
		ﾏｲﾐｸ情報とは､自分のﾏｲﾐｸが取得した最新のご当地ｷｬﾗｸﾀｰ及びｱﾜｰﾄﾞが表示されます｡<br />
			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div id="comment">
		解決しなかった場合は、お手数ですが下記より再度内容をご確認のうえ、お問い合わせください。
	</div><!--/#comment-->

	<br />
			<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
