{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">ご当地キャラクター取得</span><br />
			<br />
			<span style="color:#5b2806; font-size:large:">ご当地マップ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>アイテムショップとは?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>アイテムの種類は、何種類ありますか?</a><br />
			<span style="color:#cc6600;">Q3.</span><a href='#003'>アイテムは、回数がある限り、移動距離に反映されますか?</a><br />
			<span style="color:#cc6600;">Q4.</span><a href='#004'>一度購入したアイテムを変更することは、できますか?</a><br />
			
			<br />
			<hr />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.アイテムショップとは?</span><br />
			<hr />         
			<span style="color:#3300FF;">A1.</span>稼いだ距離を自動的に数倍にするアイテムを購入する事ができるショップです。<br />
			
			<br />
			<hr />

			<a name="002"></a>
			<span style="color:#cc6600;">Q2.アイテムの種類は、何種類ありますか?</span><br /> 
			<hr />                   
			<span style="color:#3300FF;">A2.</span>現在、快適シューズとゴールド・シューズの2種類あります。<br />
			ー快適スニーカーは、2倍以上稼ぐ事が出来ます。(mixiポイントが50pt必要です)<br />
			ーゴールト・シューズは、5倍以上稼ぐ事が出来ます。(mixiポイントが100pt必要です）<br />
			<br />
			<hr />
			
			<a name="003"></a>
			<span style="color:#cc6600;">Q3.アイテムは、回数がある限り、移動距離に反映されますか?</span><br />            
			<hr />           
			<span style="color:#3300FF;">A3.</span>一度、アイテムを購入すると、次回の「チェック!」時にもアイテムの効果は、反映されます。<br />
			なお、移動距離が0kmの場合は、アイテムの効果は、反映されません(使用回数も消費されません）<br />
			<br />
			<hr />
			
			<a name="004"></a>
			<span style="color:#cc6600;">Q4.一度購入したアイテムを変更することは、できますか?</span><br />            
			<hr />           
			<span style="color:#3300FF;">A4.</span>一度購入したアイテムは、使い切るまで、他のアイテム並びに同じアイテムを続けて購入することはできません。<br />
			他のアイテムを購入したい場合、現在、持っているアイテムを全て使用した後に、購入してください。<br />

	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
