{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">mixiﾎﾟｲﾝﾄ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>mixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>mixiﾎﾟｲﾝﾄを購入するにはどうすればいいのですか?</a><br />
		
		<hr />
			
		<a name="001"></a>
		<span style="color:#cc6600;">Q1.mixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは?</span><br />
		<hr />         
		<span style="color:#3300FF;">A1.</span>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ内でmixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは下記の通りです｡<br /> 
			･ご当地ｷｬﾗｸﾀｰのﾃﾞｺﾒ化		50ﾎﾟｲﾝﾄ<br />  
			･ご当地ｷｬﾗｸﾀｰをﾏｲﾐｸに贈る	200ﾎﾟｲﾝﾄ<br /> 
			･ｹﾞｰﾑﾁｹｯﾄ購入( 1枚)         30ﾎﾟｲﾝﾄ<br />  
			･ｹﾞｰﾑﾁｹｯﾄ購入( 5枚)         140ﾎﾟｲﾝﾄ<br />  
			･ｹﾞｰﾑﾁｹｯﾄ購入(10枚)         270ﾎﾟｲﾝﾄ<br />
		
		
		<hr />
		
		<a name="002"></a>
		<span style="color:#cc6600;">Q2.mixiﾎﾟｲﾝﾄを購入するにはどうすればいいのですか?</span><br /> 
		<hr />                   
		<span style="color:#3300FF;">A2.</span>mixiﾎﾟｲﾝﾄの購入については､<a href="http://m.mixi.jp/help.pl?guid=ON&mode=item&item=315">こちら</a>をご確認ください｡<br />
		
	
			
	</div><!--/#contet-->

	<br />
	<hr />

	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
