{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ｱﾜｰﾄﾞ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>ｱﾜｰﾄﾞって何ですか?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ｱﾜｰﾄﾞは、その場でもらえますか?</a><br />	
		<hr />

		<a name="001"></a>
		<span style="color:#cc6600;">Q1.ｱﾜｰﾄﾞって何ですか?</span><br />
		
		<hr />       
		  
		<span style="color:#3300FF;">A1.</span>ｱﾜｰﾄﾞは､あなたのｱﾌﾟﾘ内での様々な｢功績｣に対して付与されるｺﾚｸｼｮﾝｱｲﾃﾑです｡GETすると､｢功績｣には､例えば｢ﾏｲﾐｸを5人招待する｣､｢あるｴﾘｱのご当地ｷｬﾗｸﾀｰを全て集める｣など､様々な種類が用意されています｡どんな功績にｱﾜｰﾄﾞが付与されるかはﾋﾐﾂですが､｢もっとﾂｱｰを楽しもう｣ｺｰﾅｰに情報が出ることもあるようです｡また､ｱﾜｰﾄﾞをGETすると､ﾗﾝｷﾝｸﾞに作用する｢点数｣も付与されます｡(高得点のものが多いようです)<br />
		<br />		
		
		
		<hr />

		
		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ｱﾜｰﾄﾞは、その場でもらえますか?</span><br />
		
		<hr />  
		       
		<span style="color:#3300FF;">A2.</span>ｱﾜｰﾄﾞは、翌日にご当地ｺﾚｸｼｮﾝへｱｸｾｽしたﾀｲﾐﾝｸﾞで付与されます。<br />
		<br />
			

		<hr />

		<br />
			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
