{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾁｬﾚﾝｼﾞｹﾞｰﾑ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>のりものﾙｰﾚｯﾄって､何ですか?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>のりものﾙｰﾚｯﾄができません｡</a><br />
		<span style="color:#cc6600;">Q3.</span><a href='#003'>ｹﾞｰﾑﾁｹｯﾄGETがお知らせに表示されません。</a><br />
		
		<hr />
		
		<a name="001"></a>
		<span style="color:#cc6600;">Q1.ｹﾞｰﾑﾁｹｯﾄを買うには､どうすればいいですか?</span><br />
		<hr />
         
		<span style="color:#3300FF;">A1.</span>ﾀｰｹﾞｯﾄﾂｱｰの距離を稼ぐﾐﾆｹﾞｰﾑです｡のりものによって､距離は異なります｡<br />
		<span style="color:ff0000;">※ｹﾞｰﾑをするには､ｹﾞｰﾑﾁｹｯﾄが必要になります｡</span><br />
		
		<hr />
		
		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ｹﾞｰﾑﾁｹｯﾄは､他にも使えますか?</span><br /> 
		<hr />
                   
		<span style="color:#3300FF;">A2.</span>のりものﾙｰﾚｯﾄをするには､ｹﾞｰﾑﾁｹｯﾄを事前に購入する必要があります｡<br />
		<span style="color:ff0000;">※購入には､mixiﾎﾟｲﾝﾄが必要です｡</span><br />
		
		<hr />
		
		<a name="003"></a>
		<span style="color:#cc6600;">Q3.ｹﾞｰﾑﾁｹｯﾄGETがお知らせに表示されません。</span><br /> 
		<hr />
                   
		<span style="color:#3300FF;">A3.</span>1月8日より表示内容を変更したため、お知らせは、届きません。<br />

			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
