{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ｹﾞｰﾑﾁｹｯﾄ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>ｹﾞｰﾑﾁｹｯﾄを買うには､どうすればいいですか?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ｹﾞｰﾑﾁｹｯﾄは､他にも使えますか?</a><br />
		
		<hr />
		
		<a name="001"></a>
		<span style="color:#cc6600;">Q1.ｹﾞｰﾑﾁｹｯﾄを買うには､どうすればいいですか?</span><br />
		<hr />         
		<span style="color:#3300FF;">A1.</span>ﾄｯﾌﾟﾍﾟｰｼﾞ内､のりものﾙｰﾚｯﾄ下部にある｢ﾁｹｯﾄ購入はこちら｣から購入画面へと進んでください｡購入には､mixiﾎﾟｲﾝﾄが必要です｡<br />
		
		
		<hr />
		
		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ｹﾞｰﾑﾁｹｯﾄは､他にも使えますか?</span><br /> 
		<hr />                   
		<span style="color:#3300FF;">A2.</span>現在は､のりものﾙｰﾚｯﾄのみに対応しています｡<br />
		
	
			
	</div><!--/#contet-->

	<br />
	<hr />

	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
