{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾃﾞｺﾒ化</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>ご当地ｷｬﾗｸﾀｰをﾃﾞｺﾒ化にするには?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ご当地ｷｬﾗｸﾀｰを待受けにするには?</a><br />
		<span style="color:#cc6600;">Q3.</span><a href='#003'>auのｹｰﾀｲでﾃﾞｺﾒと待受けが保存できません。</a><br />		
		<hr />

		<a name="001"></a>		
		<span style="color:#3300FF;">A1.</span>
		自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢ﾃﾞｺﾒ化する｣を押下してください｡その後､ﾃﾞｺﾒ化完了画面が表示されたら｢ﾀﾞｳﾝﾛｰﾄﾞ｣を押下します｡あとは､お持ちのｹｰﾀｲの使用方法に従ってください｡<br />
		<span style="color:ff0000;">※ﾃﾞｺﾒ化は､有料ｻｰﾋﾞｽです。</span><br />

		<hr />

		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ご当地ｷｬﾗｸﾀｰを待受けにするには?</span><br /> 
		
		<hr />
                   
		<span style="color:#3300FF;">A2.</span>自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢待受け｣を押下してください｡mixiﾎﾟｲﾝﾄの消費の確認をした後､購入を選択すると待受け画像が表示されます｡お使いの携帯の機能沿って､画像保存をして下さい｡一度､待受けにしたご当地ｷｬﾗｸﾀｰは､mixiﾎﾟｲﾝﾄを使用せずに画像保存することができます｡<br />
<span style="color:#ff0000;">※待受け購入は､有料ｻｰﾋﾞｽです｡</span><br />
		<br />
		
		<hr />
		<a name="003"></a>
		<span style="color:#cc6600;">Q3.auのｹｰﾀｲで、ﾃﾞｺﾒと待受けを保存することができません。</span><br /> 
		
		<hr />
                   
		<span style="color:#3300FF;">A3.</span>auのｹｰﾀｲで、保存出来ない場合、端末の画面に表示されている『次へ』ﾎﾞﾀﾝを押してください。押した後に、購入した画像が表示されますので、そこで保存を行ってください。<br />

		<br />
		
		<hr />


	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
