{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾏｲﾐｸ招待</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span>ﾏｲﾐｸを招待したのに､ｹﾞｰﾑﾁｹｯﾄがもらえません｡<br />
		
		<hr />

		<span style="color:#cc6600;">Q1.ﾏｲﾐｸを招待したのに､ｹﾞｰﾑﾁｹｯﾄがもらえません｡</span><br />
		
		<hr />
		
		<span style="color:#3300FF;">A1.</span>ﾏｲﾐｸを招待後､そのﾏｲﾐｸがﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝに登録しなければﾁｹｯﾄを手に入れることができません｡まだ､登録していないか､招待ﾒｯｾｰｼﾞに気づいていない可能性があります｡<br />

			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
