{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">お試し版について</span><br />
		<br />
		
		<span style="color:#cc6600;">Q1.お試し版では､何が出来るの?</span><br />
		
		<hr />
				 
		<span style="color:#3300FF;">A1.</span>
		お試し版では､下記のｺﾝﾃﾝﾂ及び機能で遊ぶことができます｡<br />
		･現地に行ってご当地GETする<br />
		･ﾏｲﾐｸとﾄﾚｰﾄﾞする<br />
		･ﾀｰｹﾞｯﾄﾂｱｰでご当地ｷｬﾗｸﾀｰをGETする<br />
		<br />
		<!--
		近日､ご当地ｷｬﾗｸﾀｰのﾃﾞｺﾒ化､ﾏｲﾐｸへ"贈る"､ﾁｬﾚﾝｼﾞｹﾞｰﾑをすることができます｡<br />
		<span style="color:ff0000;">※こちらのｺﾝﾃﾝﾂ及び機能は､有料です｡</span><br />
		-->

			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
