{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾏｲﾐｸ情報</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>ﾏｲﾐｸ情報とは何ですか?</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ﾏｲﾐｸ情報にﾏｲﾐｸが表示されません｡</a><br />
		
		<br />
		<hr />
		
		<a name="001"></a>
		<span style="color:#cc6600;">Q1.ﾏｲﾐｸ情報とは何ですか?</span><br />
		<hr /><span style="color:#3300FF;">A1.</span>ﾏｲﾐｸ情報とは､自分のﾏｲﾐｸが取得した最新のご当地ｷｬﾗｸﾀｰ及びｱﾜｰﾄﾞが表示されます｡<br />
		
		<br />
		
		<hr />


		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ﾏｲﾐｸ情報にﾏｲﾐｸが表示されません｡</span><br />
		<hr /><span style="color:#3300FF;">A2.</span>下記の仕様をご確認ください｡<br />
		<br />
		■｢ﾏｲﾐｸ情報｣にはｱﾌﾟﾘを登録しただけで､ご当地ｷｬﾗｸﾀｰをGETしていないﾏｲﾐｸは表示されません｡<br />		
		■ﾏｲﾐｸの表示順は新着順ではありません｡<br />
		■ﾍﾟｰｼﾞ下の『次へ』ﾘﾝｸを見落としていませんか?11人目以降は､次のﾍﾟｰｼﾞに表示されます｡<br />
		<br />		
		なお､1度ﾏｲﾐｸになった人の情報は､ﾏｲﾐｸをやめた後も｢ﾏｲﾐｸ情報｣に掲載されますが､更新はされません｡<br />
		
		<br />
		
		<hr />
			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
