{%include file="faq/common/header.phtml"%}

	<br />
			<hr />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">ﾄﾚｰﾄﾞ</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span><a href='#001'>ﾄﾚｰﾄﾞの仕方がわかりません｡</a><br />
		<span style="color:#cc6600;">Q2.</span><a href='#002'>ﾄﾚｰﾄﾞしたのに､自分のご当地ﾏｯﾌﾟに表示されていません｡</a><br />
		<span style="color:#cc6600;">Q3.</span><a href='#003'>ﾏｲﾐｸからのﾄﾚｰﾄﾞを承認するには?</a><br />
		<span style="color:#cc6600;">Q4.</span><a href='#004'>ﾄﾚｰﾄﾞﾘｸｴｽﾄの有効期限とは、何ですか？</a><br />		
		
		<hr />

		<a name="001"></a>
		<span style="color:#cc6600;">Q1.ﾄﾚｰﾄﾞの仕方がわかりません｡</span><br />
		
		<hr />
         
		<span style="color:#3300FF;">A1.</span>ﾄﾚｰﾄﾞは､まず､ﾏｲﾐｸ情報から､ﾏｲﾐｸのﾆｯｸﾈｰﾑを押下します｡その次に表示されたﾏｲﾐｸのご当地ﾏｯﾌﾟでﾄﾚｰﾄﾞしたい都道府県名を押下します｡ご当地ｷｬﾗｸﾀｰ画像の下にある"ﾄﾚｰﾄﾞする"ﾎﾞﾀﾝを押下すると次に自分のご当地ﾏｯﾌﾟが表示されます｡そこで､自分が持っているご当地ｷｬﾗｸﾀｰを選択して相手のｷｬﾗｸﾀｰと自分のｷｬﾗｸﾀｰを確認して､問題がなければ"はい"ﾎﾞﾀﾝを押下してください｡これで､ﾏｲﾐｸにﾄﾚｰﾄﾞのﾘｸｴｽﾄ情報が送信され完了となります｡<br />
		<br />
		
		<hr />

		<a name="002"></a>
		<span style="color:#cc6600;">Q2.ﾄﾚｰﾄﾞしたのに､自分のご当地ﾏｯﾌﾟに表示されていません｡</span><br /> 
		
		<hr />
                   
		<span style="color:#3300FF;">A2.</span>ﾄﾚｰﾄﾞは､相手の承認がなければ､されません｡もし､表示されいない場合は､相手がﾄﾚｰﾄﾞﾘｸｴｽﾄに気づいていない､または､拒否をした可能性があります｡※承認の場合､お知らせにﾒｯｾｰｼﾞが届きます｡<br />
		<br />
		
		<hr />

		<a name="003"></a>
		<span style="color:#cc6600;">Q3.ﾏｲﾐｸからのﾄﾚｰﾄﾞを承認するには?</span><br /> 
		
		<hr />
                   
		<span style="color:#3300FF;">A3.</span>ﾏｲﾐｸからのﾄﾚｰﾄﾞ依頼は｢お知らせ｣に受信され､承認するか､拒否するかを選択することができます｡承認した場合は相手の｢お知らせ｣にその通知が届きます｡拒否した場合は相手に通知されません｡<br />
		<br />  
		
		<hr />

		<a name="004"></a>
		<span style="color:#cc6600;">Q4.ﾄﾚｰﾄﾞﾘｸｴｽﾄの有効期限とは、何ですか?</span><br /> 
		
		<hr />
                   
		<span style="color:#3300FF;">A4.</span>ﾄﾚｰﾄﾞﾘｸｴｽﾄには、1週間の有効期限があります。有効期限内にﾏｲﾐｸがﾄﾚｰﾄﾞを承認しないと、ﾄﾚｰﾄﾞのﾘｸｴｽﾄは、自動的に解除されます。<br />
		<br />  

	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
