{%include file="faq/common/header.phtml"%}

	<br />
	<hr />
	<div id="contet">
			<div style="color:#5b2806;">	
			<span style="color:#5b2806; font-size:large:">入退会</span><br />
			<br />
			<span style="color:#cc6600;">Q1.mixiの入退会方法を教えてください。</span><br />
			<hr />         
			<span style="color:#3300FF;">A1.</span>mixiの入退会については、mixiの「mixiを退会する」をご確認ください。<br />
			</div>
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
