{%include file="faq/common/header.phtml"%}

	<br />

	<div id="contet">
		<a name="top"></a>
		<span style="color:#5b2806; font-size:large:">課金情報について</span><br />
		<br />
		<span style="color:#cc6600;">Q1.</span>課金情報について詳しく教えてください。<br />
		
		<hr />
		
		<span style="color:#cc6600;">Q1.課金情報について詳しく教えてください。</span><br />
		
		<hr />
		
		<span style="color:#3300FF;">A1.</span>
		課金情報については、mixiのﾍﾙﾌﾟﾍﾟｰｼﾞをご確認ください。<br />

			
	</div><!--/#contet-->

	<br />
	<hr />
	
	<div style="text-align:center;"><a href="/faq?query_id={%$qid%}">戻る</a></div>
	<br />
	
	<br />

</div><!--/#continer-->

</body>
</html>
