{%include file="faq/common/header.phtml"%}
	
	<hr />

	
	<hr />

	<div id="contet">

	【よくある質問集】<br />
	<br />
	
		◆<a href='/faq/faq001?query_id={%$qid%}'><span style="color:#5b2806;">各種設定</span></a><br />
		◆<a href='/faq/faq002?query_id={%$qid%}'><span style="color:#5b2806;">ご当地キャラクター取得</span></a><br />
		◆<a href='/faq/faq003?query_id={%$qid%}'><span style="color:#5b2806;">ご当地マップ</span></a><br />
		◆<a href='/faq/faq004?query_id={%$qid%}'><span style="color:#5b2806;">トレード</span></a><br />
		◆<a href='/faq/faq005?query_id={%$qid%}'><span style="color:#5b2806;">デコメ･待受け化</span></a><br />
		◆<a href='/faq/faq006?query_id={%$qid%}'><span style="color:#5b2806;">マイミクに贈る</span></a><br />
		◆<a href='/faq/faq007?query_id={%$qid%}'><span style="color:#5b2806;">マイミク情報</span></a><br />
		◆<a href='/faq/faq008?query_id={%$qid%}'><span style="color:#5b2806;">アワード</span></a><br />
		<!--◆<a href='/faq/faq009?query_id={%$qid%}'><span style="color:#5b2806;">メールファクトリー会員特典</span></a><br />-->
		◆<a href='/faq/faq010?query_id={%$qid%}'><span style="color:#5b2806;">ターゲットツアー</span></a><br />
		◆<a href='/faq/faq011?query_id={%$qid%}'><span style="color:#5b2806;">チャレンジゲーム</span></a><br />
		◆<a href='/faq/faq012?query_id={%$qid%}'><span style="color:#5b2806;">ゲームチケット</span></a><br />
		◆<a href='/faq/faq020?query_id={%$qid%}'><span style="color:#5b2806;">アイテム</span></a><br />
		◆<a href='/faq/faq013?query_id={%$qid%}'><span style="color:#5b2806;">ランキング</span></a><br />
		◆<a href='/faq/faq014?query_id={%$qid%}'><span style="color:#5b2806;">マイミク招待</span></a><br />
		◆<a href='/faq/faq017?query_id={%$qid%}'><span style="color:#5b2806;">通信中断</span></a><br />
		◆<a href='/faq/faq016?query_id={%$qid%}'><span style="color:#5b2806;">mixiポイント</span></a><br />
		◆<a href='/faq/faq018?query_id={%$qid%}'><span style="color:#5b2806;">課金情報について</span></a><br />
		◆<a href='/faq/faq019?query_id={%$qid%}'><span style="color:#5b2806;">入退会</span></a><br />
		◆<a href='/faq/phone?query_id={%$qid%}'><span style="color:#5b2806;">対応機種</span></a>
		<br /><br />
		◆<a href='/faq/index2?query_id={%$qid%}'><span style="color:#5b2806;">その他の問い合わせ</span></a>

	</div><!--/#contet-->
	
	<hr />
	
	<br />
</div><!--/#continer-->

</body>
</html>
