{%include file="quiz/common/header.phtml" headAd=0 %}
{%include file="quiz/common/answer.phtml"%}

<div id="resultAd">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#993333;color:#ffffff;text-align:center;">おつかれさまでした!</div>
	<div class="banner" style="text-align:center;">
		<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="center" id="b1fa6fc117c4650bbf7adce5bfba4a89cb2aa35f" />
	</div><!--/.banner-->
</div><!--/#resultAd-->

<div id="result" style="background:#339999;">
	<div class="headline" style="background:#fbc251;text-align:center;">
		<img src="{%$staticUrl%}/apps/quiz/mobile/img/light.gif" width="228" height="10" /><br />
		<div class="inner" style="background:#993333;">
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/headline/r1.gif" width="228" height="24" />
			<div class="line" style="background:#631616;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.inner-->
		<img src="{%$staticUrl%}/apps/quiz/mobile/img/light2.gif" width="228" height="10" /><br />
	</div><!--/.headline-->
	<table width="100%" cellspacing="0" cellpadding="0" border="0">
		<tr>
			<td width="33%" align="center" style="width:33%;color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/result_t.gif" width="60" height="50" style="margin-top:3px;" /><br />〓{%$right%}問〓</td>
			<td width="34%" align="center" style="width:34%;color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/result_f.gif" width="60" height="50" style="margin-top:3px;" /><br />〓{%$wrong%}問〓</td>
			<td width="33%" align="center" style="width:33%;color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/result_pass.gif" width="60" height="50" style="margin-top:3px;" /><br />〓{%$pass%}問〓</td>
		</tr>
	</table>
	<div class="probability" style="color:#ffffff;text-align:center;">┏━━━━━━━┓<br />正解率：{%$rightRate%}%<br />┗━━━━━━━┛</div>
	<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
		<tr>
			<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{%$tips%}</td>
			<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host2.gif" width="50" height="40" /></td>
		</tr>
	</table>
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="nextLink" style="color:#ff0000;">
		⇒<a href='{% "$baseUrl/mobile/quiz/top?CF_pos=1"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">もう一度挑戦する</span></a><br />
		⇒<a href='{% "$baseUrl/mobile/quiz/transcript"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">ｸｲｽﾞ成績表を見る</span></a><br />
	</div><!--/.nextLink-->
	<div id="toDiary" style="text-align:center;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{%if $ua == 3%}
			<a href="{%$diaryUrl%}" style="color:#ffffff;"><span style="color:#ffffff;">この結果を日記に書く</span></a><br />
		{% else %}
			<form method="post" action="http://m.mixi.jp/add_diary.pl" accept-charset="Shift_JIS,utf-8">
				<input type="hidden" name="diary_title" value="{%$diary_title%}" />
				<input type="hidden" name="diary_body" value="{%$diary_body%}" />
				<input type="submit" value=" この結果を日記に書く " />
			</form>
		{% /if %}
	</div><!--/#toDiary-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="line" style="background:#993333;"><div class="line" style="background:#ffcc66;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>
</div><!--/#result-->

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=0 %}