{%include file="quiz/common/header.phtml" headAd=1 %}
	<div id="title" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/quiz/mobile/img/title.gif" width="228" height="60" style="margin:3px 0;" />
	</div><!--/#title-->

    <div id="gameError">
	    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        このｱﾌﾟﾘを利用するには1人以上のﾏｲﾐｸが必要です｡ご了承くださいますようお願いいたします。<br />
    </div><!--/#gameError-->
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}