{%include file="quiz/common/header.phtml" headAd=1 %}
<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

<div class="description">
	<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
		<tr>
			<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">よくある質問ﾃﾞｽ</td>
			<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host4.gif" width="50" height="40" /></td>
		</tr>
	</table>
</div><!--/.description-->

<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#993333;color:#ffffff;">ﾍﾙﾌﾟ(よくある質問)</div>
	<div class="section" style="background:#a8dada;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">ﾏｲﾐｸｸｲｽﾞってなに？</td>
			</tr>
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">ﾏｲﾐｸｸｲｽﾞは、ﾏｲﾐｸのﾌﾟﾛﾌｨｰﾙに関するｸｲｽﾞに答えるｱﾌﾟﾘです！普段仲のいいﾏｲﾐｸでも意外に分かってないことが多いかも。ｸｲｽﾞに答えてﾏｲﾐｸのことをもっともっと知っていこう！</td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
	<div class="section" style="background:#a8dada;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">住所などの問題が出題されないﾏｲﾐｸがいる</td>
			</tr>
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">ﾏｲﾐｸが住所などを非公開設定にしている場合はｸｲｽﾞとして出題されません。</td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
	<div class="section" style="background:#a8dada;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">ﾏｲﾐｸが少ないのでｸｲｽﾞにならない</td>
			</tr>
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">このｱﾌﾟﾘは最低6人以上のﾏｲﾐｸがいることを推奨しております。ﾏｲﾐｸが6人以下の場合はｱﾌﾟﾘを楽しむことが出来ない場合がございますが何卒ご了承下さい。</td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
	<div class="section" style="background:#a8dada;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">ｸｲｽﾞ履歴は削除できますか?</td>
			</tr>
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">お互いのｸｲｽﾞ履歴を閲覧して楽しむｱﾌﾟﾘのため､ｸｲｽﾞ履歴の削除はできないﾙｰﾙとなります｡</td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
	<div class="section" style="background:#a8dada;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#ff0000;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">Q.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">司会者の人は某芸能人にｿｯｸﾘな気がしますが…</td>
			</tr>
			<tr>
				<td width="20" align="center" valign="top" style="width:20px;color:#0000ff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;vertical-align:top;">A.</td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}">近所でｺﾞｰﾙﾃﾞﾝﾚﾄﾘｰﾊﾞｰの散歩していたｵｼﾞｻﾝをﾓﾁｰﾌにしていますので異なります｡どうかご安心ください｡</td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
</div><!--/#help-->

<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
<div class="line" style="background:#669999;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}