{%include file="quiz/common/header.phtml" headAd=1 %}
<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

<div class="description">
	<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
		<tr>
			<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">あなたのﾏｲﾐｸｸｲｽﾞのｸｲｽﾞ回答履歴を表示しています</td>
			<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host4.gif" width="50" height="40" /></td>
		</tr>
	</table>
</div><!--/.description-->

<div id="yourResult">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#993333;color:#ffffff;">あなたのｸｲｽﾞ履歴</div>
	{%include file="quiz/common/pager.phtml"%}
	{% foreach from=$myQuizlist item=data key=key %}
	<div class="section" {% if ($key%2) == 0 %}style="background:#a8dada;"{%/if%}>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{% if $data.result == '1' %}
			<span style="color:#ff3366;">[○正解]</span>{%$data.create_time|date_format:"%y/%m/%d"%}<br />ｱﾅﾀは<a href='{% "$baseUrl/mobile/quiz/profile?CF_fid=`$data.ask_uid`"|mixiurl %}'>{%$data.displayName%}</a>さんの{%$data.quiz_name%}を覚えていました!<br />
		{%else%}
			<span style="color:#666666;">[×不正解]</span>{%$data.create_time|date_format:"%y/%m/%d"%}<br />ｱﾅﾀは<a href='{% "$baseUrl/mobile/quiz/profile?CF_fid=`$data.ask_uid`"|mixiurl %}'>{%$data.displayName%}</a>さんの{%$data.quiz_name%}を知りませんでした…｡<br />
		{%/if%}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.section-->
	{% /foreach %}
	{%include file="quiz/common/pager.phtml"%}
</div><!--/#yourResult-->

<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
<div class="line" style="background:#669999;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}