{%include file="quiz/common/header.phtml" headAd=1 %}
<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

<div class="description">
	<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
		<tr>
			<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">ﾏｲﾐｸがｱﾅﾀに関連する問題を回答した結果を表示しています｡</td>
			<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host4.gif" width="50" height="40" /></td>
		</tr>
	</table>
</div><!--/.description-->

<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

<div id="allResult" style="background:#339999;">
	<div id="friendResult">
		<div class="headline" style="background:#fbc251;text-align:center;">
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/light.gif" width="228" height="10" /><br />
			<div class="inner" style="background:#993333;">
				<img src="{%$staticUrl%}/apps/quiz/mobile/img/headline/r3.gif" width="228" height="24" />
				<div class="line" style="background:#631616;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.inner-->
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/light2.gif" width="228" height="10" /><br />
		</div><!--/.headline-->
		{% if $friendAnswer.answerList %}
		<div class="description" style="color:#ffffff;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$friendInfo->getDisplayName()%}さんはｱﾅﾀの…<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% foreach from=$friendAnswer.answerList item=data %}
				{%if $data.result==1%}
					<span style="color:#ff3366;">[◯]</span> {%$data.quiz_name%}を覚えていました!<br />
				{%else%}
					<span style="color:#666666;">[×]</span> {%$data.quiz_name%}を忘れていました…<br />
				{%/if%}
			{% /foreach %}
		</div><!--/.description-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{%$friendAnswer.quizContent%}</td>
				<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host2.gif" width="50" height="40" /></td>
			</tr>
		</table>

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

		<table width="228" cellpadding="2" cellspacing="2" border="0" align="center" style="background:#cc6666;">
		<tr>
			<td align="center" style="background:#ffcccc;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><span style="color:#ff0000;text-decoration:blink">≫</span><a href="{%$url%}" style="color:#ff0000;"><span style="color:#ff0000;">あしあと帳でﾂｯｺﾐ!</span></a><span style="color:#ff0000;text-decoration:blink">≪</span></td>
		</tr>
		</table>
		{% else %}
		<div class="description" style="color:#ffffff;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$friendInfo->getDisplayName()%}さんはまだ回答していません｡
		</div><!--/.description-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{% if $fInfo %}ていうか未回答だし!{% else %}いますぐ招待してくれるｶﾅ?{% /if %}</td>
				<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host2.gif" width="50" height="40" /></td>
			</tr>
		</table>

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

		<table width="228" cellpadding="2" cellspacing="2" border="0" align="center" style="background:#cc6666;">
			<tr>
				<td align="center" style="background:#ffcccc;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/quiz/top?CF_pos=1" %}' style="color:#ff0000;"><span style="color:#ff0000;">ﾏｲﾐｸｸｲｽﾞに招待する!</span></a></td>
			</tr>
		</table>
        {% /if %}
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/#friendResult-->

	<div id="yourResult">
		<div class="headline" style="background:#fbc251;text-align:center;">
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/light.gif" width="228" height="10" /><br />
			<div class="inner" style="background:#993333;">
				<img src="{%$staticUrl%}/apps/quiz/mobile/img/headline/r4.gif" width="228" height="24" />
				<div class="line" style="background:#631616;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.inner-->
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/light2.gif" width="228" height="10" /><br />
		</div><!--/.headline-->
		{% if $myAnswer.answerList %}
		<div class="description" style="color:#ffffff;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ｱﾅﾀは{%$friendInfo->getDisplayName()%}さんの…<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% foreach from=$myAnswer.answerList item=data %}
				{%if $data.result==1%}
					<span style="color:#ff3366;">[◯]</span> {%$data.quiz_name%}を覚えていました!<br />
				{%else%}
					<span style="color:#666666;">[×]</span> {%$data.quiz_name%}を忘れていました…<br />
				{%/if%}
			{% /foreach %}
		</div><!--/.description-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{%$myAnswer.quizContent%}</td>
				<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host2.gif" width="50" height="40" /></td>
			</tr>
		</table>

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="2" cellspacing="2" border="0" align="center" style="background:#cc6666;">
			<tr>
				<td align="center" style="background:#ffcccc;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><span style="color:#ff0000;text-decoration:blink">≫</span><a href='{% "$baseUrl/mobile/quiz/top?CF_pos=1"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;">もう1度挑戦する</span></a><span style="color:#ff0000;text-decoration:blink">≪</span></td>
			</tr>
		</table>
		{% else %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">ていうか未回答だし!</td>
				<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host2.gif" width="50" height="40" /></td>
			</tr>
		</table>

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="2" cellspacing="2" border="0" align="center" style="background:#cc6666;">
			<tr>
				<td align="center" style="background:#ffcccc;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:center;"><span style="color:#ff0000;text-decoration:blink">≫</span><a href='{% "$baseUrl/mobile/quiz/top?CF_pos=1"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;">ﾏｲﾐｸｸｲｽﾞに挑戦する!</span></a><span style="color:#ff0000;text-decoration:blink">≪</span></td>
			</tr>
		</table>
		{% /if %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

		<div class="line" style="background:#993333;">
			<div class="line" style="background:#ffcc66;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" />
		</div>
	</div><!--/#yourResult-->
</div><!--/#allResult-->

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}