{%include file="quiz/common/header.phtml" headAd=1 %}
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />

	<div class="description">
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td align="left" style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{% if $result %}{%$quiz_name%}問題に正解したﾏｲﾐｸを表示しています｡{% else %}{%$quiz_name%}問題に誤答したﾏｲﾐｸを表示しています｡{%/if%}</td>
				<td width="50" style="width:50px;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host4.gif" width="50" height="40" /></td>
			</tr>
		</table>
	</div><!--/.description-->

<div class="group">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#993333;color:#ffffff;">ｱﾅﾀの
		{% if $result %}
			{%$quiz_name%}を知っているﾏｲﾐｸ
		{% else %}
			{%$quiz_name%}を知らないﾏｲﾐｸ
		{% /if %}
	</div><!--/.headline-->
	{%include file="quiz/common/pager.phtml"%}
	{% foreach from=$quizlist item=data key=key %}
	<div class="section" {% if ($key%2) == 0 %}style="background:#a8dada;"{%/if%}>
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="44" align="center" style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" style="margin:1px 0;" /></td>
				<td style="{% if $ua==1 %}font-size:x-small;{% /if %}"><a href='{% "$baseUrl/mobile/quiz/profile?CF_fid=`$data.answer_uid`"|mixiurl %}'>{%$data.displayName%}</a><br />
				<div style="text-align:right;">正解率:{%$data.right_rate%}%&nbsp;</div></td>
			</tr>
		</table>
	</div><!--/.section-->
	{% /foreach %}
	{%include file="quiz/common/pager.phtml"%}
	<div class="moreLink" style="text-align:right;">
		<img src="img/spacer.gif" width="1" height="3" /><br />
		<span style="color:#ff0000;">⇒</span><a href='{% "$baseUrl/mobile/quiz/resulttypelist?CF_result=`$result`"|mixiurl %}'>項目別に見る</a>&nbsp;
	</div><!--/.moreLink-->
</div><!--/.group-->

<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
<div class="line" style="background:#669999;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}