{% if $result == 0 || $result == null %}
	{%include file="quiz/common/header.phtml" headAd=0 %}
	{%include file="quiz/common/answer.phtml"%}
    {% if $status %}
        <div id="alert" style="background:#ffffcc;color:#ff0000;">
            <div class="line" style="background:#669999;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            ○<a href='{% "$baseUrl/mobile/quiz/transcript?CF_status=1"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;">ﾏｲﾐｸからのｸｲｽﾞ回答がｱﾘﾏｽ!</span></a><br />
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        </div><!--/#alert-->
    {% /if %}
{% else %}
	{%include file="quiz/common/header.phtml" headAd=1 %}
	{%include file="quiz/common/answer.phtml"%}
{% /if %}
<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
<div id="quiz" style="background:#339999;">
	<div class="headline" style="background:#fbc251;text-align:center;">
		<img src="{%$staticUrl%}/apps/quiz/mobile/img/light.gif" width="228" height="10" /><br />
		<div class="inner" style="background:#993333;">
			<img src="{%$staticUrl%}/apps/quiz/mobile/img/headline/q{%$answeredQuizSize%}.gif" width="228" height="24" />
			<div class="line" style="background:#631616;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		</div><!--/.inner-->
		<img src="{%$staticUrl%}/apps/quiz/mobile/img/light2.gif" width="228" height="10" /><br />
	</div><!--/.headline-->
	<div class="question">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				{% if $miniImage %}<td style="background:#fff;width:44px;text-align:center;"><img src="{%$miniImage%}"/></td>{%/if%}
				<td style="background:#fff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					このﾏｲﾐｸの{%$quizname%}は?<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /></td>
			</tr>
			<tr>
				<td{% if $miniImage %} colspan="2"{% /if %}><img src="{%$staticUrl%}/apps/quiz/mobile/img/arrow1.gif" width="228" height="6" /></td>
			</tr>
		</table>
		<table width="228" cellpadding="0" cellspacing="0" border="0" align="center" style="text-align:center;">
			<tr>
				<td width="184" style="width:184px;color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}text-align:left;">{% if $tipsInfo %}[ﾋﾝﾄ]{%$tipsInfo%}{%/if%}</td>
				<td width="44" style="width:44px;text-align:center;"><img src="{%$staticUrl%}/apps/quiz/mobile/img/host1.gif" width="40" height="40" /></td>
			</tr>
		</table>
		<table width="228" cellpadding="2" cellspacing="2" border="0" align="center" style="background:#030924;">
			<tr>
				<td align="left" style="background:#0239b0;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
					{% foreach from=$choose item=data key=key %}
						{% if $quiz == 'miniThumbnailUrl' %}
							<a href='{% "$baseUrl/mobile/quiz/top?CF_answer=`$data.uid`&CF_rightId=`$rightAnswer`&CF_qid=`$qid`&CF_logoId=`$logoId`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;"><img src='{%$data.strChoose%}'/></span></a>
						{%else%}
							{%$data.no%}）<a href='{% "$baseUrl/mobile/quiz/top?CF_answer=`$data.uid`&CF_rightId=`$rightAnswer`&CF_qid=`$qid`&CF_logoId=`$logoId`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">{%$data.strChoose%}</span></a><br />
						{%/if%}
					{% /foreach %}
				</div></td>
			</tr>
		</table>
		<div class="passLink" style="text-align:right;">
			<span style="color:#ff0000;">⇒</span><a href='{% "$baseUrl/mobile/quiz/top?CF_model=3&CF_qid=`$qid`&CF_rightId=`$rightAnswer`&CF_logoId=`$logoId`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">次の問題(ﾊﾟｽ)</span></a><br />
		</div><!--/.passLink-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="line" style="background:#993333;">
			<div class="line" style="background:#ffcc66;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" />
		</div>
	</div><!--/.question-->
</div><!--/#quiz-->

{%include file="quiz/common/menu.phtml"%}
{%include file="quiz/common/recommend.phtml"%}
{%include file="quiz/common/footer.phtml" footAd=1 %}