<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-廃車</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}友達の設置した廃車ｶｰﾄﾞによって、自分の車が廃車になってしまうことがあります。<br />
		<br />
		{% emoji code="F8BF"%}一度廃車になってしまった車は、整備ｶｰﾄﾞを使うまで、動かす事ができません。<br />
		<br />
		<span style="color:#c00;">{% emoji code="F9A9"%}廃車中は、ｶﾞｿﾘﾝ代はかかりません。</span><br />
		<br />
		{% emoji code="F8BF"%}廃車ｶｰﾄﾞのは、自動車保険ｶｰﾄﾞ使用中に一度だけ防ぐことができます。<br />
		<br />
		{% emoji code="F8BF"%}設置された廃車ｶｰﾄﾞは、ﾄﾗｯﾌﾟ回避ｶｰﾄﾞで見破ることができます。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}

</div><!--/#help-->
