<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-ｶｰｼｮｯﾌﾟ</span><br />
	</div><!--/.headline-->
	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}ｶｰｼｮｯﾌﾟでは、様々な種類の車を購入する事ができます。<br />
		<br />
		{% emoji code="F8BF"%}車を購入すると、車のｸﾞﾚｰﾄﾞに応じて、駐車料金が上昇していきます。<br />
		<br />
		{% emoji code="F8BF"%}所有車を下取りに出して、新しい車を購入する事もできます。（原価90％の差額で下取りとなります）<br />
		<br />
		{% emoji code="F8BF"%}最大で8台の車を所有することができます。<br />
		<br />
		{% emoji code="F8BF"%}同じ車種は、それぞれ1台しか持てません。<br />
		（ｱｲﾃﾑを使用して、色違いの車を購入可能にすることもできます）<br />
		<br />
		{% emoji code="F8BF"%}所有車の数が増えると、警察から直接取り締まりを受ける可能性も増えます。注意してください。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
