<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-ﾌﾟﾚｾﾞﾝﾄ</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
		{% emoji code="F8BF"%}自分の車は友達にﾌﾟﾚｾﾞﾝﾄすることができます。ただし、1ヶ月に1台ずつしか贈れません。<br />
		<br />
		{% emoji code="F8BF"%}友達から車を貰う場合も同様に、1ヶ月に1台ずつしか受け取ることができません。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
<div id="help">