<div class="link">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />
	<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/parking/help"|mixiurl %}'>ﾍﾙﾌﾟﾄｯﾌﾟにもどる</a><br />
</div><!--/.link-->

<div class="menu">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
	<span style="color:#cd424a;">◆</span>ﾍﾙﾌﾟﾒﾆｭｰ<br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=profit"|mixiurl %}'>お金を稼ぐ方法</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=parkingrule"|mixiurl %}'>駐車のﾙｰﾙ</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=stick"|mixiurl %}'>取り締まる</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=police"|mixiurl %}'>警察</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=report"|mixiurl %}'>通報</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=carshop"|mixiurl %}'>ｶｰｼｮｯﾌﾟ</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=house"|mixiurl %}'>不動産</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=item"|mixiurl %}'>ｱｲﾃﾑ</a><br />
	<span style="color:#777;">├</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=breakcar"|mixiurl %}'>廃車</a><br />
	<span style="color:#777;">└</span><a href='{% "$baseUrl/mobile/parking/help?parking_parm=gift"|mixiurl %}'>ﾌﾟﾚｾﾞﾝﾄ</a><br />
</div><!--/.menu-->