<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-不動産</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}不動産屋では、不動産（ﾊﾟｰｷﾝｸﾞ）を購入することができます。<br />
		<br />
		{% emoji code="F8BF"%}不動産を購入すると、不動産のﾗﾝｸに応じて、駐車可能台数、駐車料金が増えていきます。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
<div id="help">
