<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-ｱｲﾃﾑ</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}ｱｲﾃﾑを使って、友達の邪魔をしたり、それを防いだりすることができます。<br />
		<br />
		{% emoji code="F8BF"%}ｱｲﾃﾑｼｮｯﾌﾟでは、ｱｲﾃﾑを購入することができます。<br />
		<br />
		{% emoji code="F8BF"%}訪問時のﾋﾞｼﾞﾀｰｷﾞﾌﾄで、ｶｰﾄﾞがﾌﾟﾚｾﾞﾝﾄされる場合もあります。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
