<div id="help">
	<img src="img/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-駐車のﾙｰﾙ</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}自分の車は、友達のﾊﾟｰｷﾝｸﾞにしか駐車する事ができません<br />
		<br />
		{% emoji code="F8BF"%}ﾊﾟｰｷﾝｸﾞのｵｰﾅｰは、あなたの車に「駐車違反ｷｯﾌﾟ」を貼って取り締まることができます。ご注意ください。<br />
		<br />
		{% emoji code="F8BF"%}無料ﾊﾟｰｷﾝｸﾞに駐車すると、お金を稼ぐ事ができません。その代わり、駐車違反として取り締まられる心配がなくなります。ただし、12時間を過ぎるとﾊﾟｰｷﾝｸﾞから追い出されてしまいます。<br />
		<br />
		{% emoji code="F8BF"%}一度、ﾊﾟｰｷﾝｸﾞに駐車すると、1時間以内はその場所から車を移動する事ができません。<br />
		<br />
		{% emoji code="F8BF"%}有料ﾊﾟｰｷﾝｸﾞの場合も、駐車時間が72時間を過ぎるとﾊﾟｰｷﾝｸﾞから追い出されてしまいます。<br />
		<br />
		{% emoji code="F8BF"%}その場合、ﾊﾟｰｷﾝｸﾞﾒｰﾀｰに貯まっていた駐車料金も手に入れる事ができません。<br />
		<br />
		{% emoji code="F8BF"%}自分の車を、同じﾊﾟｰｷﾝｸﾞ内に連続して駐車することはできません。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
