<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-警察</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}ﾊﾟｰｷﾝｸﾞのｵｰﾅｰが、あまりｹﾞｰﾑにﾛｸﾞｲﾝしていないからといって油断は禁物です。警察が、直接取り締まりを行う場合があるので気をつけてください。<br />
		<br />
		{% emoji code="F8BF"%}ただし、夜間は警察の巡回も半分になるので、取り締まられる心配も少なくなります。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
