<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-お金を稼ぐ方法</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}自分の車を有料ﾊﾟｰｷﾝｸﾞに駐車すると、1,500円/15分のﾍﾟｰｽでﾊﾟｰｷﾝｸﾞﾒｰﾀｰが上昇していきます。<br />
		<br />
		ただし、ﾊﾟｰｷﾝｸﾞﾒｰﾀｰは8時間でmaxとなるので、それ以上駐車し続けたとしても駐車料金は増えません。<br />
		<br />
		<span style="color:#c00;">{% emoji code="F9A9"%}駐車料金は、不動産のﾗﾝｸ、車のｸﾞﾚｰﾄﾞによって上昇していきます。</span><br />
		<br />
		{% emoji code="F8BF"%}駐車していた車を友達に気付かれる前に、他のﾊﾟｰｷﾝｸﾞに移動させると、ﾊﾟｰｷﾝｸﾞﾒｰﾀｰに貯まっている駐車料金を手に入れる事ができます。<br />
		<br />
		{% emoji code="F8BF"%}自分のﾊﾟｰｷﾝｸﾞに、違法駐車している友達の車には「駐車違反ｷｯﾌﾟ」を貼って取り締まることができます。<br />
		<br />
		{% emoji code="F8BF"%}そうすると、ﾊﾟｰｷﾝｸﾞﾒｰﾀｰの駐車料金の1.2倍の金額を奪い取ることできます。<br />
		<br />
		{% emoji code="F8BF"%}友達の車の違法駐車を発見したら、警察に「通報」することができます。<br />
		<br />
		{% emoji code="F8BF"%}もし警察があなたの「通報」で、その友達から罰金を徴収できた場合、その罰金の金額の50%がﾎﾞｰﾅｽとしてあなたに支払われます。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
