<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-通報</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}友達の車が違法駐車しているの所を発見したら、警察に「通報」することができます。<br />
		<br />
		{% emoji code="F8BF"%}もし警察があなたの「通報」のおかげで罰金を徴収できた場合、その罰金の金額の50%がﾎﾞｰﾅｽとしてあなたに支払われます。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
