<div id="help">
	<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />

	<div class="headline" style="background:#cd424a;">
		<span style="color:#fff;">ﾍﾙﾌﾟ-取り締まる</span><br />
	</div><!--/.headline-->

	<div class="description">
		<img height="2" width="1" src="{%$staticUrl%}/apps/parking/mimg/spacer.gif"/><br />
		{% emoji code="F8BF"%}ﾊﾟｰｷﾝｸﾞのｵｰﾅｰは、違法駐車している車に「駐車違反ｷｯﾌﾟ」を貼って取り締まることができます。取り締まった車からは、正規の駐車料金の1.2倍の罰金をもらうことができます。<br />
	</div><!--/.description-->

	{%include file="parking/help/helpmenu.phtml"%}
</div><!--/#help-->
