<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
{% if $ua==1 %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% else %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% /if %}
</head>

<body>