{%include file="header.phtml"%}

<body id="admin">
	<h1>OPENSOCIAL APPS ADMIN</h1>
	{%include file="nav.phtml"%}

	<div id="container">
		<h2>あしあと帳 - コンテンツ監視</h2>
		<div id="appsAdmin">
			<ul class="nav">
				<li><a href="{%$baseUrl%}/aboard/watchtop">トップページ</a></li>
				<li><span>禁止語の設定</span></li>
				<li><a href="{%$baseUrl%}/aboard/dealstat">処理の集計</a></li>
			</ul><!--/.nav-->

			<div id="watchHead">
				<h3>禁止語の設定</h3>
				<p>全<span id="lblCount">&nbsp;</span>件を表示しています。<br />
					最終更新日：<span id="lblDate">&nbsp;</span> <span id="lblUser">&nbsp;</span></p>
				<div class="error" id="lblError" style="display:none">
					エラーメッセージ表示エリア<br />
					閲覧のみ可能な権限者の場合は、buttonがすべてdisabledになります。pager・完了画面は不要です。
				</div><!--/.error-->
			</div><!--/.watchHead-->

			<div id="divContent">
			</div>
		</div><!--/#appsAdmin-->
		<div id="hidArea" style="display:none">
			<select id="hidSelType" name="hidSelType">
    			<option value="" selected="selected">選択してください</option>
    			{% foreach from=$lstType item=data %}
    			<option value="{%$data.tid%}">{%$data.name|escape%}</option>
    			{% /foreach %}
    		</select>
    		<input type="hidden" id="hidUserName" value="{%$adminUser->name|escape%}" />
		</div>
		<input type="hidden" id="pageIndex" name="pageIndex" value="1" />
		<script src="{%$staticUrl%}/admin/js/aboard/forbidword.js?{%$version.js%}"></script>
	</div><!--/#container-->

{%include file="footer.phtml"%}