{%include file="header.phtml"%}

<body id="admin">
	<h1>OPENSOCIAL APPS ADMIN</h1>
	{%include file="nav.phtml"%}

	<div id="container">
		<h2>あしあと帳 - コンテンツ監視</h2>
		<div id="appsAdmin">
			<ul class="nav">
				<li><span>トップページ</span></li>
				<li><a href="{%$baseUrl%}/aboard/forbidword">禁止語の設定</a></li>
				<li><a href="{%$baseUrl%}/aboard/dealstat">処理の集計</a></li>
			</ul><!--/.nav-->
			<table width="100%" cellpadding="0" cellspacing="0" border="0" id="dataGrid">
				<thead>
					<tr class="head">
						<th>監視項目</th>
						<th>カテゴリ別コンテンツ一覧</th>
					</tr>
				</thead>
				<tbody>
					<tr class="a">
						<td>掲示板のタイトル</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'title');return false;">［容疑({%$lstTitle.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'title');return false;">［全投稿 | 未処理({%$lstTitle.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'title');return false;">［全投稿 | 保留({%$lstTitle.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'title');return false;">［全投稿 | 問題なし］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'title');return false;">［全投稿 | 違反］</a></td>
					</tr>
					<tr class="b">
						<td>掲示板の説明</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'des');return false;">［容疑({%$lstDes.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'des');return false;">［全投稿 | 未処理({%$lstDes.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'des');return false;">［全投稿 | 保留({%$lstDes.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'des');return false;">［全投稿 | 問題なし］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'des');return false;">［全投稿 | 違反］</a></td>
					</tr>
					<tr class="a">
						<td>コメント</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'comment');return false;">［容疑({%$lstComment.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'comment');return false;">［全投稿 | 未処理({%$lstComment.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'comment');return false;">［全投稿 | 保留({%$lstComment.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'comment');return false;">［全投稿 | 問題なし］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'comment');return false;">［全投稿 | 違反］</a></td>
					</tr>
				</tbody>
			</table><!--/#dataGrid-->
		</div><!--/#appsAdmin-->
		<form method="post" id="frmTop" name="frmTop">
			<input type="hidden" id="srhStatus" name="srhStatus" value="0" />
		</form>
	</div><!--/#container-->
	<script type="text/javascript" language="javascript">
        /**
         * search comment/title/des action
         * @param  integer status
         * @param  string page
         * @return void
         */
        function goPage(status, page) {
        	$('frmTop').action = UrlConfig.BaseUrl + '/aboard/watch' + page;
        	$('srhStatus').value = parseInt(status);
            $('frmTop').submit();
        }
	</script>

{%include file="footer.phtml"%}