
<div class="adBox">
<a style="display:block;margin-bottom:4px;" href="http://mixi.jp/run_appli.pl?id=6230" target="_blank"><img src="{%$staticUrl%}/apps/scripteditor/img/ddp_250x89.jpg" width="250" height="89" alt="どきどきダイナマイトパニック" title="" /></a>
<a style="display:block;" href="http://mixi.jp/run_appli.pl?id=2689" target="_blank"><img src="{%$staticUrl%}/apps/scripteditor/img/ttm_250x89.jpg" width="250" height="89" alt="伝説のトーテムポール" title="" /></a>
</div>

    