<link type="text/css" rel="stylesheet" href="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/css/SyntaxHighlighter.css?{%$version.js%}" />
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shCore.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushJScript.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushCss.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushPhp.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushXml.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushCSharp.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushJava.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushPython.js?{%$version.js%}"></script>
<script type="text/javascript" src="{%$staticUrl%}/apps/scripteditor/syntax_highlighter/js/shBrushRuby.js?{%$version.js%}"></script>