<address id="copyright">&copy; 2009 Community Factory Inc. All Rights Reserved. </address>
    
</div><!--/#continer-->

<script type="text/javascript" src="http://stats.communityfactory.net/stats.js"></script>

<!-- CF Stats -->
<script type="text/javascript" language="javascript">
try {
var _CF_Tracker = CfStats.getTracker(1);
var user = {'userId' : {%$_user->getId()%} };
_CF_Tracker.setCustomData(user);
_CF_Tracker.trackPageView();
_CF_Tracker.enableLinkTracking();
} catch( err ) {}
</script>
<!-- End CF Stats Tag -->

<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var pageTracker = _gat._getTracker("UA-1572579-40");
        pageTracker._trackPageview();
    } 
    catch(err) {}
</script>

</body>
</html>
