<ul id="gNav"><!--
    --><li id="gNavTop"><a href="{%$baseUrl%}/scripteditor/toppage">トップ</a></li><!--
    --><li id="gNavMyPage"><a id="gNavMyPageA" href="{%$baseUrl%}/scripteditor/profile">マイページ</a></li><!--
    --><li id="gNavArchive"><a href="{%$baseUrl%}/scripteditor/archives?lang=1&type=1">アーカイブ</a></li><!--
    --><li id="gNavEditor"><a href="{%$baseUrl%}/scripteditor/editor">エディター</a></li><!--
    --><li id="gNavTag"><a href="{%$baseUrl%}/scripteditor/tag">タグ</a></li><!--
    --><li id="gNavConfig"><a href="{%$baseUrl%}/scripteditor/config">環境設定</a></li><!--
    --><li id="gNavHelp"><a href="{%$baseUrl%}/scripteditor/help">ヘルプ</a></li><!--
    --><li id="gNavInvite"><a href="javascript:void(0);" onclick="invite();">友達に教える</a></li><!--
--></ul>