<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
{% if $ua==1 %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% else %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% /if %}
    <title>ﾏｲﾐｸｸｲｽﾞ - mixiｱﾌﾟﾘ</title>
    <style type="text/css">
        a:link{color:#0000ff;}
        a:visited{color:#0000ff;}
        a:focus{color:#ffffff;}
        *{
		    {% if $ua==1 %}
		        font-size: x-small;
		    {% elseif $ua==2 %}
		        font-size: x-small;
		    {% elseif $ua==3 %}
		        font-size:5;
		    {% /if %}
	    }
    </style>
</head>
<body style="background:#99cccc;">
    <a id="pagetop" name="pagetop"></a>
    <div id="container" style="background:#99cccc;">
{% if $headAd==1 %}
	<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="header" id="b1fa6fc117c4650bbf7adce5bfba4a89cb2aa35f" />
	<img src="{%$staticUrl%}/apps/quiz/mobile/img/spacer.gif" width="1" height="3" /><br />
{% /if %}