 <div id="menu" style="color:#0000ff;">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	■<a href='{% "$baseUrl/mobile/quiz/top?CF_pos=1"|mixiurl %}' accesskey="1">トップ</a>　■<a href='{% "$baseUrl/mobile/quiz/help"|mixiurl %}'>ヘルプ</a><br />
	■<a href='{% "$baseUrl/mobile/quiz/transcript"|mixiurl %}'>あなたのクイズ成績表</a><br />
	■<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/quiz/top?CF_pos=1" %}'>マイミクを招待する</a>
</div><!--/#menu-->