<div class="nav" style="text-align:center;">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        {%if $listCount.startCount == $listCount.endCount%}
              {%$count%}件中{%$listCount.startCount%}件
        {%else%}
              {%$count%}件中{%$listCount.startCount%}-{%$listCount.endCount%}件
        {%/if%}<br />
            {% if $pager.maxPager > 1 %}
			    {% if $pager.pageIndex == 1 %}
					<span style="color:#0000ff;">≪[*]前へ</span>
				{% else %}
				    <span style="color:#0000ff;">≪[*]</span><a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex-1``$pager.pageParam`"|mixiurl %}' accesskey="*">前へ</a>
				{% /if %}

				    <span style="color:#c9fdfd;"> | </span>

				{% if $pager.maxPager == $pager.pageIndex%}
					<span style="color:#0000ff;">次へ[#]≫</span>
				{% else %}
				    <a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex+1``$pager.pageParam`"|mixiurl %}' accesskey="#">次へ</a><span style="color:#0000ff;">[#]≫</span>
				{% /if %}
            {% /if %}
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
</div><!--/.nav-->

