	<div id="footerInfo">
		<br />
		<br />
		<br />
		お問い合わせの前に､今一度<a href='{% "$baseUrl/mobile/brain/help"|mixiurl %}'>ﾍﾙﾌﾟ･よくある質問</a>をご確認くださいますよう､お願いいたします｡
	</div><!--/#footerInfo-->

    {% html_mobile_tracker aqid="9NCWHBK23CPTJUH95PNA" %}

	{% if $footerAd %}
		<div class="footAd" style="background:#fff;">
			<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="footer" id="ec963db98d470730e72e03e89e852fbe431dc922" />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.footAd-->
	{% /if %}
    </div><!--/#container-->
</body>
</html>