    <div id="menu">
            <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
            <div class="headline" style="background:#009999;color:#ffffff;text-align:center;">ｱﾌﾟﾘﾒﾆｭｰ</div>
            <div class="inner">
                {% emoji code="F987"%}<a href='{% "$baseUrl/mobile/brain/top"|mixiurl %}' accesskey="1">ﾏｲﾐｸ頭脳くらべTOP</a><br />
                {% emoji code="F973"%}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/brain/invitecomplete" %}'>ﾏｲﾐｸを招待する</a><br />
                {% emoji code="F9A0"%}<a href='{% "$baseUrl/mobile/brain/help"|mixiurl %}'>ﾍﾙﾌﾟ･よくある質問</a><br />
            </div><!--/.inner-->
        </div><!--/#menu-->