<div id="recommend">
	<img src="{%$staticUrl%}/apps/quiz/mobile/img/spacer.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#009999;color:#ffffff;">おすすめｱﾌﾟﾘ情報</div>
    <div class="section" style="text-align:center;">
		<a href="http://m.mixi.jp/view_appli.pl?id=19008&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/expose_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />オモシロ質問に答えよ～♪</a><br />
    </div><!--/.section-->
    <div class="section" style="text-align:center;">
		<a href="http://m.mixi.jp/view_appli.pl?id=19735&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/shindan_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />おﾊﾞｶな検定が盛りだくさん!</a><br />
    </div><!--/.section-->
</div><!--/#recommend-->
