{% if $action == 'start' %}
	{% include file="ship/common/header.phtml" headerAd=1 %}
	<div id="present">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			海賊船の船長に委任する<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			この海賊船の船長に就任させるﾏｲﾐｸを選択してください｡<br />
			<div class="ship" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/ship/img/ship/{%$shipInfo.cav_name%}.gif" width="200" height="120" style="margin:3px 0;" /><br />
				{% if $friends %}
					<form method="post" action='{% "$baseUrl/mobile/ship/appointcaptain/CF_step/complete"|mixiurl %}'>
						<input type="hidden" name="CF_userShipId" value="{%$userShipId%}" />
						<select style="color:#000;" name="CF_fid">
							{% foreach from=$friends item=data %}
							<option value="{%$data.uid%}">{%$data.displayName%}</option>
							{% /foreach %}
						</select><input type="submit" value="決定" /><br />
					</form>
				{% else %}
					参加しているﾏｲﾐｸがいません｡<br />
				{% /if %}
			</div><!--/.ship-->
		</div><!--/.inner-->
		<div class="alert">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#cc0000;text-align:center;">
				<tr>
					<td align="left" style="background:#ffcccc;text-align:left;"><div style="color:#cc0000;{% if $ua==1 %}font-size:x-small;{% /if %}">
						{% emoji code="F9DC" %}ﾏｲﾐｸを船長に就任させると､この海賊船の行動の当事者が､ｱﾅﾀではなく就任させたﾏｲﾐｸとなります<br />
						</div></td>
				</tr>
			</table>
		</div><!--/.alert-->
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/#present-->
	{% include file="ship/common/footer.phtml" footerAd=1 %}
{% elseif $action == 'complete' %}
	{% include file="ship/common/header.phtml" %}
	<div id="present">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			委任完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$friendInfo->getDisplayName()%}は{%$shipInfo.shipName|escape%}号の船長に就任しました！<br />
		</div><!--/.description-->

		{%include file="ship/common/ad_complete.phtml"%}

		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/myship"|mixiurl %}'>海賊船一覧へ</a><br />
		</div><!--/.link-->
	</div><!--/#present-->
	{%include file="ship/common/menu.phtml"%}
	{%include file="ship/common/footer.phtml"%}
{% /if %}
