{% if $action == 'start' %}
	{% include file="ship/common/header.phtml" headerAd=1 %}

	<div id="diamond">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			宝石商人の店<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="money" style="color:#7c4825;text-align:right;">
			金貨:${%$shipUser.asset|outputdollars%}&nbsp;ﾀﾞｲﾔ:{%$shipUser.asset_diamond%}ｺ&nbsp;<br />
		</div><!--/.money-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ﾀﾞｲﾔはﾐｸｼｨﾎﾟｲﾝﾄで購入できます｡ﾀﾞｲﾔを効率的に使用して､最強の海賊艦隊を目指せ!ﾀﾞｲﾔの無駄遣いには注意しましょう{% emoji code="F8F6" %}<br />
		</div><!--/.description-->
		<div class="invite" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F9BC" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/ship/invite" %}'>ﾏｲﾐｸ招待でﾀﾞｲﾔGET</a><br />
		</div><!--/.invite-->
		<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="67" align="center" valign="top" style="width:67px;text-align:center;vertical-align:center;"><img src="{%$staticUrl%}/apps/ship/img/dia/1.gif" width="63" height="60" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F99F" %}<span style="color:#7c4825;">ﾀﾞｲﾔ x1</span><br />
						価格:70pt<br />
						<div style="text-align:center;">
							<form method="post" action="#">
								<input type="submit" value=" 購入する " /><br />
							</form>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="67" align="center" valign="top" style="width:67px;text-align:center;vertical-align:center;"><img src="{%$staticUrl%}/apps/ship/img/dia/2.gif" width="63" height="60" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F99F" %}<span style="color:#7c4825;">ﾀﾞｲﾔ x2</span><br />
						価格:100pt<br />
						<div style="text-align:center;">
							<form method="post" action="#">
								<input type="submit" value=" 購入する " /><br />
							</form>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="67" align="center" valign="top" style="width:67px;text-align:center;vertical-align:center;"><img src="{%$staticUrl%}/apps/ship/img/dia/7.gif" width="63" height="60" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F99F" %}<span style="color:#7c4825;">ﾀﾞｲﾔ x7</span><br />
						価格:200pt<br />
						<div style="text-align:center;">
							<form method="post" action="#">
								<input type="submit" value=" 購入する " /><br />
							</form>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="67" align="center" valign="top" style="width:67px;text-align:center;vertical-align:center;"><img src="{%$staticUrl%}/apps/ship/img/dia/20.gif" width="63" height="60" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F99F" %}<span style="color:#7c4825;">ﾀﾞｲﾔ x20</span><br />
						価格:300pt<br />
						<div style="text-align:center;">
							<form method="post" action="#">
								<input type="submit" value=" 購入する " /><br />
							</form>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
		<div class="invite" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F9BC" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/ship/invite" %}'>ﾏｲﾐｸ招待でﾀﾞｲﾔGET</a><br />
		</div><!--/.invite-->
	</div><!--/#diamond-->
	{%include file="ship/common/menu.phtml"%}
	{% include file="ship/common/footer.phtml" footerAd=1 %}
{% elseif $action == 'complete' %}
	{% include file="ship/common/header.phtml" %}
	<div id="buydiamond">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			購入完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			ﾀﾞｲﾔﾓﾝﾄﾞの購入が完了しました｡<br />
			ﾀﾞｲﾔの数が<span style="color:#cd424a;">8個</span>に増えました!<br />
		</div><!--/.description-->
	</div><!--/#buydiamond	-->
	{%include file="ship/common/ad_complete.phtml"%}
	{%include file="ship/common/menu.phtml"%}
	{%include file="ship/common/footer.phtml"%}
{% /if %}
