{% if $action == 'start' %}
	{% include file="ship/common/header.phtml" headerAd=0 %}
	<div id="itemShop">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			購入確認<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="commodity" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/ship/img/items/card_{%$cardInfo.sid%}.gif" width="156" height="100" style="margin:3px 0;" /><br />
		</div><!--/.commodity-->
		<div class="inner">
			{%$cardInfo.introduce%}<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">購入する商品</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			{% emoji code="F9A3" %}<span style="color:#7c4825;">{%$cardInfo.name%}</span><br />
			価格:{%if $cardInfo.price%}${%$cardInfo.price|outputdollars%}{%else%}ﾀﾞｲﾔ{%$cardInfo.diamond%}ｺ{%/if%}<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">購入後のｽﾃｰﾀｽ</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			{% if $cardInfo.price > 0 %}
				金貨:${%$shipUser.asset|outputdollars%}→<span style="color:#cd424a;">{%if $remainAsset < 0%}金貨不足{%else%}${%$remainAsset|outputdollars%}{%/if%}</span><br />
			{% else %}
				ﾀﾞｲﾔ:{%$shipUser.asset_diamond%}→<span style="color:#cd424a;">{%if $remainAsset < 0%}ﾀﾞｲﾔ不足{%else%}{%$remainAsset%}{%/if%}</span><br />
			{% /if %}
		</div><!--/.inner-->
		<div class="submit" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $remainAsset < 0 %}
				{% if $cardInfo.price %}
					<span style="color:#cd424a;">金貨が足りません!</span><br />
				{% else %}
					<span style="color:#cd424a;">ﾀﾞｲﾔが足りません!</span><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BC" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/ship/invite" %}'>ﾏｲﾐｸ招待でﾀﾞｲﾔGET</a><br />
				{% /if %}
			{% else %}
				<form method="post" action='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$cardInfo.sid`/CF_step/complete"|mixiurl %}'>
					<input type="submit" value=" 購入する " />
				</form>
			{% /if %}
		</div><!--/.submit-->
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/#itemShop-->
	{% include file="ship/common/footer.phtml" footerAd=0 %}
{% elseif $action == 'complete' %}
	{% include file="ship/common/header.phtml" %}
	<div id="itemShop">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			購入完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="item">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $result.status == 1 %}
				{%$result.cardName%}を購入しました｡<br />
				{%if $result.assetType==1%}
					金貨が<span style="color:#cd424a;">${%$result.remainAsset|outputdollars%}</span>になりました｡<br />
				{%else%}
					ﾀﾞｲﾔが<span style="color:#cd424a;">{%$result.remainAsset%}ｺ</span>になりました｡<br />
				{%/if%}
			{% elseif $result.status == -2 %}
				金貨/ﾀﾞｲﾔが不足しています<br />
			{% else %}
				すでに購入が完了しています<br />
			{% /if %}
		</div><!--/.item-->

		{%include file="ship/common/ad_complete.phtml"%}

		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/myitem"|mixiurl %}'>ｱｲﾃﾑを使用する</a><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/itemshop"|mixiurl %}'>続けて買い物する</a><br />
		</div><!--/.link-->
	</div><!--/#itemShop-->
	{%include file="ship/common/menu.phtml"%}
	{%include file="ship/common/footer.phtml"%}
{% /if %}
