{% include file="ship/common/header.phtml" %}
<div id="estate">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		変更完了<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		{% if $result.status == 1 %}
			海賊島の変更が完了しました<br />
		{% else %}
			すでに変更が完了しています<br />
		{% /if %}
	</div><!--/.description-->

	{%include file="ship/common/ad_complete.phtml"%}

    <div class="link">
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}'>海賊ﾏｲﾍﾟｰｼﾞへ</a><br />
    </div><!--/.link-->
</div><!--/#estate-->
{%include file="ship/common/menu.phtml"%}
{%include file="ship/common/footer.phtml"%}
