{% if $action == 'start' %}
	{% include file="ship/common/header.phtml" headerAd=1 %}
	<div id="changeShip">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			所有船と交換する<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="money" style="color:#7c4825;text-align:right;">
			金貨:${%$shipUser.asset|outputdollars%}&nbsp;ﾀﾞｲﾔ:{%$shipUser.asset_diamond%}ｺ&nbsp;<br />
		</div><!--/.money-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#7c4825;">{%$shipInfo.name%}号</span>と交換する所有船を選択してください<br />
		</div><!--/.description-->
		<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
		{% foreach from=$shipList item=data key=key %}
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="78" align="center" style="width:78px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/ship/{%$data.cav_name%}_s.gif" width="74" height="58" /></td>
						<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F947"%}<span style="color:#7c4825;">{%$data.shipName|escape%}号</span><br />
							下取り価格:${%$data.price|outputdollars%}<br />
							<div style="color:#aaaaaa;text-align:right;">
								<a href='{% "$baseUrl/mobile/ship/changeship/CF_shipId/`$shipId`/CF_userShipId/`$data.id`/CF_step/confirm"|mixiurl %}'>この海賊船を選択</a>&nbsp;<br />
							</div></div></td>
					</tr>
				</table>
				<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
			</div><!--/.section-->
		{% /foreach %}
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/#changeShip-->
	{% include file="ship/common/footer.phtml" footerAd=1 %}
	
{% elseif $action == 'confirm' %}

	{% include file="ship/common/header.phtml" headerAd=0 %}
	<div id="buyShip">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			購入確認<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="commodity" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/ship/img/ship/{%$shipInfo.cav_name%}.gif" width="200" height="120" style="margin:3px 0;" /><br />
		</div><!--/.commodity-->
		<div class="inner">
			<span style="color:#9e623a;">購入する商品</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			{% emoji code="F947"%}<span style="color:#7c4825;">海賊船 {%$shipInfo.name%}号</span><br />
			価格:${%$shipInfo.price%}<span style="color:#777;">/</span>強奪率:{%$shipInfo.times*100%}%<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">下取りする所有船</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			{% emoji code="F947"%}<span style="color:#7c4825;">海賊船 {%$userShipInfo.name%}号</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">購入後のｽﾃｰﾀｽ</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			所有船:{%$shipUser.ship_count%}→{%$shipUser.ship_count%}<br />
			金　貨:${%$shipUser.asset|outputdollars%}→<span style="color:#cd424a;">{%if $remainAsset < 0%}金貨不足{%else%}${%$remainAsset|outputdollars%}{%/if%}</span><br />
		</div><!--/.inner-->
		<div class="submit" style="text-align:center;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $remainAsset < 0 %}
				<span style="color:#cd424a;">金貨が足りません!</span><br />
			{% else %}
				<form method="post" action='{% "$baseUrl/mobile/ship/changeship/CF_shipId/`$shipId`/CF_userShipId/`$userShipId`/CF_step/complete"|mixiurl %}'>
					<input type="submit" value="下取りして購入" /><br />
				</form>
				<form method="post" action='{% "$baseUrl/mobile/ship/shipfactory"|mixiurl %}'>
					<input type="submit" value="　キャンセル　" /><br />
				</form>
			{% /if %}
		</div><!--/.submit-->
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/#buyShip-->
	{% include file="ship/common/footer.phtml" footerAd=0 %}
	
{% elseif $action == 'complete' %}

	{%include file="ship/common/header.phtml"%}
	<div id="changeShip">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			購入完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $result.status == 1 %}
				<span style="color:#7c4825;">海賊船 {%$result.shipName|escape%}号</span>を造船しました!<br />
					金貨が<span style="color:#cd424a;">${%$result.remainAsset|outputdollars%}</span>になりました｡<br />
			{% else %}
				すでに造船が完了しています<br />
			{% /if %}
		</div><!--/.description-->
		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/rankingfriend"|mixiurl %}'>さっそくﾏｲﾐｸの島を攻めにいく!</a><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/shipfactory"|mixiurl %}'>続けて造船する</a><br />
		</div><!--/.link-->
	</div><!--/#changeShip-->
	{%include file="ship/common/menu.phtml"%}
	{%include file="ship/common/footer.phtml"%}
{% /if %}
