{%include file="ship/common/header.phtml"%}

<div id="invite">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
    <div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
        <div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
        エラー発生<br />
        <div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
    </div><!--/.headline-->
    <div class="description">
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        ｼｽﾃﾑｴﾗｰが発生しました｡恐れ入りますが､ﾏｲﾍﾟｰｼﾞに戻り､再度実行いただきますようお願いいたします｡<br />
    </div><!--/.description--> 

    <div class="link">
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}'>海賊ﾏｲﾍﾟｰｼﾞへ</a><br />
    </div><!--/.link-->
</div><!--/#invite-->

{%include file="ship/common/menu.phtml"%}
{%include file="ship/common/footer.phtml"%}