{%include file="ship/common/header.phtml" headerAd=1 %}

<div id="welcome">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ﾃﾞｲﾘｰｷﾞﾌﾄ<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->

	{% if $action == 'start' %}
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			海賊ﾏｽﾀｰからのﾌﾟﾚｾﾞﾝﾄ! 1日1回、財宝かﾀﾞｲﾔﾓﾝﾄﾞがもらえるよ｡<br />
			<div class="gift" style="text-align:center;"><a href='{% "$baseUrl/mobile/ship/gift/CF_step/complete"|mixiurl %}'><img src="{%$staticUrl%}/apps/ship/img/giftBox.gif" width="74" height="58" style="margin-top:3px;" /></a><a href='{% "$baseUrl/mobile/ship/gift/CF_step/complete"|mixiurl %}'><img src="{%$staticUrl%}/apps/ship/img/giftBox.gif" width="74" height="58" style="margin-top:3px;" /></a><a href='{% "$baseUrl/mobile/ship/gift/CF_step/complete"|mixiurl %}'><img src="{%$staticUrl%}/apps/ship/img/giftBox.gif" width="74" height="58" style="margin-top:3px;" /></a></div>
		</div><!--/.inner-->
	{% else %}
		<div class="inner">
			<div class="item" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/ship/img/{%$giftInfo.img%}.gif" width="156" height="100" style="margin:3px 0;" /><br />
				{%$giftInfo.message%}<br />
			</div><!--/.item-->
			{% if $giftInfo.cid < 5 %}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<table width="228" cellpadding="2" cellspacing="1" border="0" align="center;" style="background:#333333;text-align:center;">
				<tr>
					<td style="background:#cccccc;text-align:left;"><div style="{%if $ua==1%}font-size:x-small;{%/if%}">【{%$giftInfo.name%}】<br />{%$giftInfo.introduce%}</div></td>
				</tr>
			</table>
			{% /if %}
			<div class="link">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}'>あなたの島を見に行く</a><br />
			</div><!--/.link-->
		</div><!--/.inner-->
	{% /if %}
</div><!--/#welcome-->

{%include file="ship/common/footer.phtml" headerAd=1 %}