{% include file="ship/common/header.phtml" %}

<div id="invite">
    <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
    <div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
        <div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
        マイミク招待完了<br />
        <div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
    </div><!--/.headline-->
    <div class="description">
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        ﾏｲﾐｸ招待が完了しました｡ﾀﾞｲﾔﾓﾝﾄﾞの獲得は､招待したﾏｲﾐｸがｱﾌﾟﾘを追加後､2-3日お時間がかかることがあります｡あらかじめご了承ください<br />
    </div><!--/.description--> 

    {%include file="ship/common/ad_complete.phtml"%}

    <div class="link">
        <img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
        <span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}'>海賊ﾏｲﾍﾟｰｼﾞへ</a><br />
    </div><!--/.link-->
</div><!--/#invite-->

{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" %}
