{% include file="ship/common/header.phtml" headerAd=1 %}

<div id="itemshop">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		海賊市場<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="money" style="color:#7c4825;text-align:right;">
		金貨:${%$shipUser.asset|outputdollars%}&nbsp;ﾀﾞｲﾔ:{%$shipUser.asset_diamond%}ｺ&nbsp;<br />
	</div><!--/.money-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ｱｲﾃﾑを使ってﾗﾝｷﾝｸﾞ上位を目指せ{% emoji code="F8F5" %}<br />
	</div><!--/.description-->
	<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
	{% foreach from=$storeList item=data key=key %}
		<div class="section">
			{% emoji code="F9A3" %}<span style="color:#7c4825;">{%$data.name%}</span><br />
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/items/card_{%$data.sid%}_s.gif" width="60" height="38" /></td>
					<td><div style="{%if $ua==1%}font-size:x-small;{%/if%}">
						価格:{%if $data.price%}金貨 ${%$data.price|outputdollars%}{%else%}ﾀﾞｲﾔ {%$data.diamond%}ｺ{%/if%}<br />
						{%*
						{%$data.introduce%}<br />
						<div style="color:#aaa;text-align:right;">{% if $shipUser.asset >= $data.price && $shipUser.asset_diamond >= $data.diamond %}<a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>{% else %}購入する{% /if %}&nbsp;<br /></div>
						*%}
						<div style="color:#aaa;text-align:right;"><a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br /></div>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
	{% /foreach %}
</div><!--/#itemshop-->
{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" footerAd=1 %}
