{% include file="ship/common/header.phtml" headerAd=1 %}

<div id="myitem">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		アイテム一覧<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
	{% foreach from=$itemList item=data key=key %}
		<div class="section">
			{% emoji code="F9A3" %}<span style="color:#7c4825;">{%$data.name%}×{%$data.count%}</span><br />
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/items/card_{%$data.sid%}_s.gif" width="60" height="38" /></td>
					<td valign="top" style="vertical-align:top;"><div style="{%if $ua==1%}font-size:x-small;{%/if%}">
						{%$data.introduce%}<br />
						<div style="color:#aaa;text-align:right;">
							{% if $data.count < 1 %}
								使用する <a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br />
							{% elseif $data.sid == 1 %}
								使用可 <a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br />
							{% elseif $data.sid == 2 %}
								{% if $nowTime - $shipUser.last_bribery_time < 3*24*60*60 %}
									<span style="color:#cd424a;">使用中</span> <a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br />
								{% else %}
									<a href='{% "$baseUrl/mobile/ship/useitem/CF_sid/`$data.sid`"|mixiurl %}'>使用する</a> <a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br />
								{% /if %}
							{% else %}
								<a href='{% "$baseUrl/mobile/ship/useitem/CF_sid/`$data.sid`"|mixiurl %}'>使用する</a> <a href='{% "$baseUrl/mobile/ship/buyitem/CF_sid/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;<br />
							{% /if %}
						</div></div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
	{% /foreach %}
</div><!--/#myitem-->

{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" footerAd=1 %}
