{% include file="ship/common/header.phtml" headerAd=1 %}

<div id="myship">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		海賊船一覧<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		所有船の状態をﾁｪｯｸし､埋蔵金貨をある程度運びこんだ船があったら､ﾊﾞﾚないうちに移動させよう!<br />
	</div><!--/.description-->
	<div class="help" style="text-align:right;">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/help?CF_help=b06"|mixiurl %}'>海賊船を増やすには?</a>&nbsp;<br />
	</div><!--/.help-->
	<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
	{%*
		{%include file="ship/common/userasset.phtml"%}
		<div>{%$shipCount%}件中 1-{%$shipCount%}件</div>
		<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
	*%}
	{% foreach from=$ships item=data key=key %}
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="78" align="center" style="width:78px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/ship/{%$data.cav_name%}_s.gif" width="74" height="58" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F947"%}<a href='{% "$baseUrl/mobile/ship/setship/CF_userShipId/`$data.id`"|mixiurl %}' style="color:#7c4825;"><span style="color:#7c4825;">{%$data.shipName|escape%}号</span></a><br />
						{%if $data.activation == 1%}
    						{% if $data.temp != 0 %}
								<img src="{%$staticUrl%}/apps/ship/img/meter/meter_{%$data.temp%}.gif" width="89" height="3" style="margin:3px 0;" /><br />
								{%$data.status%}<br />
	    						<div style="text-align:right;">
	    						  {%if $data.shipStatus==1%}収入:{%/if%}{%$data.money%}&nbsp;<br />
							    </div>
							{% else %}
								{%$data.status%}<br />
							{% /if %}
						{%else%}
    						非激活状态<br />
						{%/if%}
				    </div></td>
				</tr>
			</table>
			<div style="text-align:center"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
	{% /foreach %}
	<div class="link">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/shipfactory"|mixiurl %}'>造船所へ</a>&nbsp;<br />
	</div><!--/.link-->
</div><!--/#myship-->

{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" footerAd=1 %}
