{% include file="ship/common/header.phtml" headerAd=1 %}

<div id="ranking">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		資産ランキング<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
	<div class="switch" style="text-align:center;">
		ﾐｸｼｨ全体<span style="color:#999;">|</span><a href='{% "$baseUrl/mobile/ship/rankingfriend"|mixiurl %}'>ﾏｲﾐｸｼｨ内</a><br />
	</div><!--/.switch-->
	<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
	{% foreach from=$rankUser item=data key=key %}
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="44" style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" /></td>
					<td><div style="{%if $ua==1%}font-size:x-small;{%/if%}">
						{% emoji code="F9BF"%}<span style="color:#7c4825;">{%$key+1%}位</span><br />
						{% if $data.uid == $shipUser.uid %}{% emoji code="F99F"%}{%$data.displayName%}{% else %}{% emoji code="F995"%}<a href='{% "$baseUrl/mobile/ship/index/CF_uid/`$data.uid`"|mixiurl %}'>{%$data.displayName%}</a>{% /if %}<br />
						<div style="text-align:right;">${%$data.asset|outputdollars%}&nbsp;</div>
						</div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
	{% /foreach %}
</div><!--/#ranking-->

{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" footerAd=1 %}
