{% if $action == 'start' %}
	{% include file="ship/common/header.phtml" headerAd=1 %}
	<div id="renameship">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			海賊船の名前を変更する<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			名前を入力し[変更]を押してください｡<br />
			<div class="ship" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/ship/img/ship/{%$shipInfo.cav_name%}.gif" width="200" height="120" style="margin:3px 0;" /><br />
			</div><!--/.ship-->

            {% if $nameError != -1 %}
			<div class="alert">
				<table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#cc0000;text-align:center;">
					<tr>
						<td align="left" style="background:#ffcccc;text-align:left;"><div style="color:#cc0000;{% if $ua==1 %}font-size:x-small;{% /if %}">
							{% emoji code="F9DC" %}入力ｴﾗｰ<br />
							{% if $nameError == 1 %}
							・海賊船の名前が未入力です<br />
							{% elseif $nameError == 2 %}
							・10文字以内で入力してください<br />
							{% /if %}
							</div>
						</td>
					</tr>
				</table>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.alert-->
			{% /if %}

			<form method="post" action='{% "$baseUrl/mobile/ship/renameship/CF_step/complete"|mixiurl %}'>
				{% emoji code="F947"%}<span style="color:#9e623a;">海賊船の名前</span><br />
				<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<input type="hidden" name="CF_userShipId" value="{%$userShipId%}" />
				<input name="CF_name" type="text" value="{%$shipInfo.shipName%}" /><br />
				
				<div style="text-align:right;">※10文字以内&nbsp;</div>
				<div class="btn" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<input type="submit" value=" 変 更 " />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/ship/myship"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" ｷｬﾝｾﾙ " />
				</div><!--/.btn-->
			</form>
		</div><!--/.inner-->
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/#renameship-->
	{% include file="ship/common/footer.phtml" footerAd=1 %}
{% elseif $action == 'complete' %}
	{% include file="ship/common/header.phtml" %}
	<div id="renameship">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			変更完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="inner">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			海賊船の名前を変更しました<br />
		</div><!--/.inner-->

		{%include file="ship/common/ad_complete.phtml"%}

		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/myship"|mixiurl %}'>海賊船一覧へ</a><br />
		</div><!--/.link-->
	</div><!--/#renameship-->
	{%include file="ship/common/menu.phtml"%}
	{%include file="ship/common/footer.phtml"%}
{% /if %}
