{% include file="ship/common/header.phtml" headerAd=1 %}

<div id="shipfactory">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		造船所<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="money" style="color:#7c4825;text-align:right;">
		金貨:${%$shipUser.asset|outputdollars%}&nbsp;ﾀﾞｲﾔ:{%$shipUser.asset_diamond%}ｺ&nbsp;<br />
	</div><!--/.money-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		海賊船は8隻まで所有可能です｡海賊船を増やして､最強の海賊艦隊を目指せ{% emoji code="F9A2" %}<br />
	</div><!--/.description-->
	<div style="text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/twoline.gif" width="230" height="27" /></div>
	{%include file="ship/common/pager.phtml"%}
	<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
	{% foreach from=$shipList item=data key=key %}
		<div class="section">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="78" align="center" style="width:78px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/ship/{%$data.cav_name%}_s.gif" width="74" height="58" /></td>
					<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{% emoji code="F947"%}<span style="color:#7c4825;">{%$data.name%}号</span><br />
						価　格:{%if $data.price%}${%$data.price|outputdollars%}{%/if%}{%if $data.diamond%}/ﾀﾞｲﾔ {%$data.diamond%}ｺ{%/if%}<br />
						強奪率:{%$data.times*100%}%<br />
						<div style="color:#aaaaaa;text-align:right;">{% if $userAllShipCount < 8 && $data.ship_count < 3 && ($shipUser.asset >= $data.price || ( $data.diamond > 0 && $shipUser.asset_diamond >= $data.diamond)) %}<a href='{% "$baseUrl/mobile/ship/buyship/CF_shipId/`$data.sid`"|mixiurl %}'>購入する</a>&nbsp;{% else %}購入する&nbsp;{% /if %}{% if $data.ship_count < 3 && $shipUser.asset >= ($data.price - $maxPrice*0.9) %}<a href='{% "$baseUrl/mobile/ship/changeship/CF_shipId/`$data.sid`"|mixiurl %}'>所有船と交換</a>&nbsp;{% else %}所有船と交換&nbsp;{% /if %}<br /></div></div></td>
				</tr>
			</table>
			<div style="text-align:center;" class="lineDash"><img src="{%$staticUrl%}/apps/ship/img/newLine.gif" width="230" height="27" /></div>
		</div><!--/.section-->
	{% /foreach %}
	{%include file="ship/common/pager.phtml"%}
</div><!--/#shipfactory-->

{%include file="ship/common/menu.phtml"%}
{% include file="ship/common/footer.phtml" footerAd=1 %}
