{%include file="ship/common/header.phtml"%}

{% if $action == 'start' %}
	<div id="useitem">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			アイテムを使う<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$cardInfo.name%}を使用しますか?<br />
		</div><!--/.description-->
		<div class="inner" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/ship/img/items/card_{%$cardInfo.sid%}.gif" width="156" height="100" style="margin:3px 0;" /><br />
			<table width="156" cellpadding="2" cellspacing="1" border="0" align="center" style="text-align:center;">
				<tr>
					<td style="background-color:#999999;text-align:left;"><div style="background-color:#999999;color:#000;{%if $ua==1%}font-size:x-small;{%/if%}">{%$cardInfo.introduce%}</div></td>
				</tr>
			</table>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a href='{% "$baseUrl/mobile/ship/useitem/CF_sid/`$cardInfo.sid`/CF_step/complete"|mixiurl %}'>使用する</a><br />
		</div><!--/.inner-->
		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/myitem"|mixiurl %}'>アイテム一覧にもどる</a><br />
		</div><!--/.link-->
	</div><!--/#useitem-->
{% elseif $action == 'complete' %}
	<div id="useitem">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
			アイテム使用完了<br />
			<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		</div><!--/.headline-->
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% if $result.status == 1 %}
				{%$result.cardName%}を使用しました<br />
			{% elseif $result.status == -3 %}
				このカードを使える区画がありません<br />
			{% else %}
				{%$result.cardName%}の使用に失敗しました<br />
			{% /if %}
		</div><!--/.description-->
		<div class="inner" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/ship/img/items/card_{%$result.cardId%}.gif" width="156" height="100" style="margin:3px 0;" /><br />
			<table width="156" cellpadding="2" cellspacing="1" border="0" align="center" style="background:#999999;text-align:center;">
				<tr>
					<td style="text-align:left;"><div style="{%if $ua==1%}font-size:x-small;{%/if%}">{%$result.cardIntroduce%}</div></td>
				</tr>
			</table>
		</div><!--/.inner-->
		<div class="link">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/myitem"|mixiurl %}'>アイテム一覧にもどる</a><br />
		</div><!--/.link-->
	</div><!--/#useitem-->
{% /if %}

{%include file="ship/common/menu.phtml"%}
{%include file="ship/common/footer.phtml"%}