
        <br />
	<div style="color:#5b2806;">	
        <a name="top"></a>
      <span style="color:#5b2806; font-size:large:">ﾏｲﾐｸ情報</span><br />
        <br />
        <span style="color:#cc6600;">Q1.</span><a href='#001'>ﾏｲﾐｸ情報とは何ですか?</a><br />
        <span style="color:#cc6600;">Q2.</span><a href='#002'>ｱﾌﾟﾘを削除したﾏｲﾐｸの情報は、どうなりますか?</a><br />
        <span style="color:#cc6600;">Q3.</span><a href='#003'>mixiﾒﾆｭｰにある『このｱﾌﾟﾘを使っているﾏｲﾐｸ』の人数とﾏｲﾐｸ情報の人数が違います。</a><br />
        <span style="color:#cc6600;">Q4.</span><a href='#004'>ﾏｲﾐｸ情報にﾏｲﾐｸが表示されません。</a><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" style='width="100%"' %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="001"></a>
      <span style="color:#cc6600;">Q1.ﾏｲﾐｸ情報とは何ですか?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>ﾏｲﾐｸ情報とは､自分のﾏｲﾐｸが取得した最新のご当地ｷｬﾗｸﾀｰ及びｱﾜｰﾄﾞが表示されます｡<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" style='width="100%"' %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="002"></a>
        <span style="color:#cc6600;">Q2.ｱﾌﾟﾘを削除したﾏｲﾐｸの情報は、どうなりますか?</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A2.</span>ﾏｲﾐｸがｱﾌﾟﾘを削除しても、ﾏｲﾐｸ情報から消去されることは、ありません。<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" style='width="100%"' %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="003"></a>
        <span style="color:#cc6600;">Q3.mixiﾒﾆｭｰにある『このｱﾌﾟﾘを使っているﾏｲﾐｸ』の人数とﾏｲﾐｸ情報の人数が違います。</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A3.</span>ﾏｲﾐｸ情報は、ｱﾌﾟﾘ登録後、最初にご当地ｷｬﾗｸﾀｰをGETしないと一覧には、表示されません。そのため、実際にｱﾌﾟﾘで遊んでいるﾏｲﾐｸの数とｱﾌﾟﾘに登録だけしているﾏｲﾐｸの数は、異なります。数が異なる場合、恐らく、そのﾏｲﾐｸは、まだご当地ｷｬﾗｸﾀｰをGETしていない可能性があります｡<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>    
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" style='width="100%"' %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="004"></a>
        <span style="color:#cc6600;">Q4.ﾏｲﾐｸ情報にﾏｲﾐｸが表示されません</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A4.</span>下記の仕様をご確認ください。<br />･「ﾏｲﾐｸ情報」にはｱﾌﾟﾘを登録しただけで、ご当地ｷｬﾗｸﾀｰをGETしていないﾏｲﾐｸは表示されません。<br />･ﾏｲﾐｸの表示順は新着順ではありません。<br />･ﾍﾟｰｼﾞ下の『次へ』ﾘﾝｸを見落としていませんか？11人目以降は、次のﾍﾟｰｼﾞに表示されます。<br />なお、1度ﾏｲﾐｸになった人の情報は、ﾏｲﾐｸをやめた後も「ﾏｲﾐｸ情報」に掲載されますが、更新はされません。
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>    
	</div>