			
			<br />
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">課金情報について</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span>課金情報について詳しく教えてください。<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			<span style="color:#cc6600;">Q1.課金情報について詳しく教えてください。</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<span style="color:#3300FF;">A1.</span>
			課金情報については、<a href="#">こちら</a>をご確認ください。<br />
			 