			
			<br />
			<div style="color:#5b2806;">
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">ご当地ﾏｯﾌﾟ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>他の地方をみるには?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>都道府県の横の数字は､何ですか?</a><br />
			<span style="color:#cc6600;">Q3.</span><a href='#003'>ご当地ｷｬﾗｸﾀｰの詳細を見るには?</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.他の地方をみるには?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>現在表示されているご当地ﾏｯﾌﾟの都道府県名下部にある地方名を押下してください｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />

			<a name="002"></a>
			<span style="color:#cc6600;">Q2.都道府県の横の数字は､何ですか?</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />                   
			<span style="color:#3300FF;">A2.</span>重複して手に入れているご当地ｷｬﾗｸﾀｰ数です｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="003"></a>
			<span style="color:#cc6600;">Q3.ご当地ｷｬﾗｸﾀｰの詳細を見るには?</span><br />            
			{% disneyimg style='height="5"' name="dot0" %}<br />           
			<span style="color:#3300FF;">A3.</span>ご当地ﾏｯﾌﾟの各都道府県名を押下してください｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			</div>
			
