	<br />
	<div style="color:#5b2806;">

	<span style="color:#cc6600;">Q1.</span><a href='#001'>ﾃﾞｺﾒををGETするには?</a><br />
	<span style="color:#cc6600;">Q2.</span><a href='#002'>待受けをGETするには?</a><br />
	<span style="color:#cc6600;">Q3.</span><a href='#003'>auのｹｰﾀｲでﾃﾞｺﾒと待受けが保存できません。</a><br />
	<br />

	<a name="001"></a>
		<span style="color:#cc6600;">Q1.ﾃﾞｺﾒをGETするには?</span><br />
		{% disneyimg style='height="5"' name="dot0" %}<br />
		<span style="color:#3300FF;">A1.</span>自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢ﾃﾞｺﾒにする｣を押下してください｡mixiﾎﾟｲﾝﾄの消費の確認をした後､購入を選択するとﾃﾞｺﾒﾋﾟｸﾁｬｰが表示されます｡お使いの携帯の機能沿って､画像保存をして下さい｡一度､ﾃﾞｺﾒにしたご当地ｷｬﾗｸﾀｰは､mixiﾎﾟｲﾝﾄを使用せずに画像保存することができます｡<br />
		<span style="color:#ff0000;">※ﾃﾞｺﾒ化には､mixiﾎﾟｲﾝﾄが50pt必要です｡</span><br />
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
		</div>
		{% disneyimg style='height="5"' name="dot0" %}<br />
		{% disneyimg name="fna_line2" style='width="100%"' %}<br />
		{% disneyimg style='height="5"' name="dot0" %}<br />

		<a name="002"></a>
		<span style="color:#cc6600;">Q2.待受けをGETするには?</span><br /> 
		{% disneyimg style='height="5"' name="dot0" %}<br />
		<span style="color:#3300FF;">A2.</span>自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢待受け｣を押下してください｡mixiﾎﾟｲﾝﾄの消費の確認をした後､購入を選択すると待受け画像が表示されます｡お使いの携帯の機能沿って､画像保存をして下さい｡一度､待受けにしたご当地ｷｬﾗｸﾀｰは､mixiﾎﾟｲﾝﾄを使用せずに画像保存することができます｡<br />
		<span style="color:#ff0000;">※待受け購入には､mixiﾎﾟｲﾝﾄが80pt必要です｡</span><br />
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
		</div>
		{% disneyimg style='height="5"' name="dot0" %}<br />
		{% disneyimg name="fna_line2" style='width="100%"' %}<br />
		{% disneyimg style='height="5"' name="dot0" %}<br />
		<a name="003"></a>
		<span style="color:#cc6600;">Q3.auのｹｰﾀｲで、ﾃﾞｺﾒと待受けを保存することができません。</span><br /> 
		{% disneyimg style='height="5"' name="dot0" %}<br />
		<span style="color:#3300FF;">A3.</span>auのｹｰﾀｲで、保存出来ない場合、端末の画面に表示されている『次へ』ﾎﾞﾀﾝを押してください。押した後に、購入した画像が表示されますので、そこで保存を行ってください。<br />
		<br />
		<div style="text-align:right;">
			<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
		</div>
		{% disneyimg style='height="5"' name="dot0" %}<br />
		{% disneyimg name="fna_line2" style='width="100%"' %}<br />
		{% disneyimg style='height="5"' name="dot0" %}<br />
	</div>