	<br />
	<div style="color:#5b2806;">
	<a name="top"></a>
	<span style="color:#5b2806; font-size:large:">ﾀｰｹﾞｯﾄﾂｱｰ</span><br />
	<br />
	<span style="color:#cc6600;">Q1.</span><a href='#001'>移動したのに､ﾀｰｹﾞｯﾄまでの距離が変わりません｡</a><br />
	<span style="color:#cc6600;">Q2.</span><a href='#002'>ﾀｰｹﾞｯﾄ達成後､｢ﾁｪｯｸする｣ﾎﾞﾀﾝがなくなりました｡</a><br />
	<span style="color:#cc6600;">Q3.</span><a href='#003'>ﾀｰｹﾞｯﾄを変更したら､移動距離があらたに設定されました｡</a><br />
	<span style="color:#cc6600;">Q4.</span><a href='#004'>ﾀｰｹﾞｯﾄﾂｱｰで移動したのに0Kmと表示されます。</a><br />
	<span style="color:#cc6600;">Q5.</span><a href='#005'>ﾀｰｹﾞｯﾄﾂｱｰにおいて、達成と表示されているのにﾏｯﾌﾟをみるとｷｬﾗｸﾀｰが表示されていません。</a><br />
	{% disneyimg style='height="5"' name="dot0" %}<br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	{% disneyimg style='height="5"' name="dot0" %}<br />

	<a name="001"></a>
	<span style="color:#cc6600;">Q1.移動したのに､ﾀｰｹﾞｯﾄまでの距離が変わりません｡</span><br />
	{% disneyimg style='height="5"' name="dot0" %}<br />
	<span style="color:#3300FF;">A1.</span>ﾀｰｹﾞｯﾄﾂｱｰの距離は､位置情報をもとに算出されています｡そのため､移動開始場所と移動終了場所が同じだと0kmになってしまいます｡<br />
	<div style="text-align:right;">
		<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
	</div>
	{% disneyimg style='height="5"' name="dot0" %}<br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	{% disneyimg style='height="5"' name="dot0" %}<br />

	<a name="002"></a>
	<span style="color:#cc6600;">Q2.ﾀｰｹﾞｯﾄ達成後､｢ﾁｪｯｸする｣ﾎﾞﾀﾝがなくなりました｡</span><br /> 
	{% disneyimg style='height="5"' name="dot0" %}<br />
	<span style="color:#3300FF;">A2.</span>ﾀｰｹﾞｯﾄが達成されるとﾀｰｹﾞｯﾄ設定をしなければﾂｱｰで遊ぶことは､できません｡そのため､未設定の場合は､非表示になります､一度､設定されているかを確認してください｡<br />
	<div style="text-align:right;">
		<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
	</div>
	{% disneyimg style='height="5"' name="dot0" %}<br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	{% disneyimg style='height="5"' name="dot0" %}<br />

	<a name="003"></a>
	<span style="color:#cc6600;">Q3.ﾀｰｹﾞｯﾄを変更したら､移動距離があらたに設定されました｡</span><br />
	{% disneyimg style='height="5"' name="dot0" %}<br />
	<span style="color:#3300FF;">A3.</span>ﾀｰｹﾞｯﾄを再設定すると､今までのﾀｰｹﾞｯﾄまでの距離がﾘｾｯﾄされ､再設定した地域までの距離が表示されます｡<br />
	<div style="text-align:right;">
		<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
	</div>
	{% disneyimg style='height="5"' name="dot0" %}<br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	{% disneyimg style='height="5"' name="dot0" %}<br />

	<a name="004"></a>
	<span style="color:#cc6600;">Q4.ﾀｰｹﾞｯﾄﾂｱｰで移動したのに0Kmと表示されます。</span><br />
	{% disneyimg style='height="5"' name="dot0" %}<br />
	<span style="color:#3300FF;">A4.</span>下記のｹｰｽが考えられます。<br />･ﾀｰｹﾞｯﾄ設定後「ﾁｪｯｸ!」ﾎﾞﾀﾝを押さずに移動し、移動先でのみ「ﾁｪｯｸ!」を行った。<br />･0～5Km（地域により差があります）以内など、同じ基地局内で「ﾁｪｯｸ!」を行った。<br />
	･「ﾁｪｯｸ!」ﾎﾞﾀﾝではなく「ご当地GET」ﾎﾞﾀﾝを押している。<br />･TOPﾍﾟｰｼﾞの残りKmが更新されていない場合、端末の機能で再読み込みをしていない。<br />
	･24時間以上経過してから「ﾁｪｯｸ!」を行った。<br /><br />上記いずれも当てはまらない場合は、できるだけ詳細な下記情報と一緒にお問い合わせください。<br />
	･最初に「ﾁｪｯｸ!」した場所、地域名<br />･最後に「ﾁｪｯｸ!」した場所、地域名<br />
	･移動中に利用したmixiｱﾌﾟﾘ名称(もしあれば)<br /><br />
	※mixiから「提供者に問い合わせる」を行う場合、mixiIDや機種情報などの通知をしない設定でお問い合わせいただいた場合、回答はできかねます。
	<div style="text-align:right;">
		<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
	</div>
	{% disneyimg style='height="5"' name="dot0" %}<br />
	{% disneyimg name="fna_line2" style='width="100%"' %}<br />
	{% disneyimg style='height="5"' name="dot0" %}<br />

	<a name="005"></a>
	<span style="color:#cc6600;">Q5.ﾀｰｹﾞｯﾄﾂｱｰにおいて、達成と表示されているのにﾏｯﾌﾟをみるとｷｬﾗｸﾀｰが表示されていません。</span><br />
	{% disneyimg style='height="5"' name="dot0" %}<br />
	<span style="color:#3300FF;">A5.</span>現在、ﾀｰｹﾞｯﾄﾂｱｰにおいて不具合が発生しております。そのため、実際には、達成してい状態で達成という表示になっております。ご迷惑をおかけし、誠に申し訳ございません。<br />
	<div style="text-align:right;">
		<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
	</div>
	</div>