			<br />
			<div style="color:#5b2806;">
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">各種設定</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>ﾏｲﾀｳﾝ設定とは､何ですか?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>ﾏｲﾀｳﾝ設定をしたら自宅と違う県が設定されてしまいましたが､なぜですか?</a><br /> 
			<span style="color:#cc6600;">Q3.</span><a href='#003'>初回のﾏｲﾀｳﾝ設定で自動的に地域が表示されたのですが､これはなぜですか?</a><br />
			<span style="color:#cc6600;">Q4.</span><a href='#004'>ｱﾌﾟﾘ登録後､一度､ﾏｲﾀｳﾝ設定をしたら､変更は､できないのですか?</a><br />
			<span style="color:#cc6600;">Q5.</span><a href='#005'>ｱﾌﾟﾘ登録後､ﾀｰｹﾞｯﾄ設定というものがありましたが､これは何ですか?</a><br />
			<span style="color:#cc6600;">Q6.</span><a href='#006'>ﾀｰｹﾞｯﾄの変更はできますか?</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.ﾏｲﾀｳﾝ設定とは､何ですか?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>ﾏｲﾀｳﾝ設定とは､自分のﾏｲﾀｳﾝ(家)を登録する設定です｡<br />
			ここで設定したものは､ﾀｰｹﾞｯﾄﾂｱｰにおいてﾀｰｹﾞｯﾄとなる地域までの距離を都道府県間で計ります｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="002"></a>
			<span style="color:#cc6600;">Q2.ﾏｲﾀｳﾝ設定をしたら自宅と違う県が設定されてしまいましたが､なぜですか?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A2.</span>ｱﾌﾟﾘを登録後､初回のﾏｲﾀｳﾝ設定では､mixiﾌﾟﾛﾌｨｰﾙ((現住所)を全体に公開に設定している場合､その情報をｱﾌﾟﾘ側で取得します｡現在の自宅がある県が現住所と異なる場合は､設定確認画面で"いいえ"を選択して選び直すか､ﾄｯﾌﾟﾍﾟｰｼﾞからﾏｲﾀｳﾝ設定で位置情報を基に設定し直してください｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="003"></a>
			<span style="color:#cc6600;">Q3.初回のﾏｲﾀｳﾝ設定で自動的に地域が表示されたのですが､これはなぜですか?</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />                   
			<span style="color:#3300FF;">A3.</span>mixiﾌﾟﾛﾌｨｰﾙの現住所を｢全体に公開｣に設定している場合､表示されます｡現住所を"ﾏｲﾀｳﾝ"に設定しない場合は､｢いいえ｣を押して､自分のﾏｲﾀｳﾝ地域を選択してください｡また､ﾏｲﾀｳﾝ設定をした後に､現住所を変更しても､ﾏｲﾀｳﾝは､変更されません｡ﾄｯﾌﾟﾍﾟｰｼﾞの｢ﾏｲﾀｳﾝ設定｣から変更を行ってください｡(ﾏｲﾀｳﾝ設定の変更は､月に1回まで変更ができます)<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="004"></a>
			<span style="color:#cc6600;">Q4.ｱﾌﾟﾘ登録後､一度､ﾏｲﾀｳﾝ設定をしたら､変更は､できないのですか?</span><br />            
			{% disneyimg style='height="5"' name="dot0" %}<br />           
			<span style="color:#3300FF;">A4.</span>ﾄｯﾌﾟﾍﾟｰｼﾞ内の｢ﾏｲﾀｳﾝ設定｣から変更することができます｡<br /><span style="color:ff0000;">また､再設定は､月一回までです｡再設定後のﾏｲﾀｳﾝからﾀｰｹﾞｯﾄの地域は､短縮されることはありません｡</span><br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="005"></a>
			<span style="color:#cc6600;">Q5.ｱﾌﾟﾘ登録後､ﾀｰｹﾞｯﾄ設定というものがありましたが､これは何ですか?</span><br />         
			{% disneyimg style='height="5"' name="dot0" %}<br />   
			<span style="color:#3300FF;">A5.</span>ﾀｰｹﾞｯﾄ設定とは､ﾀｰｹﾞｯﾄﾂｱｰでｺﾞｰﾙに設定する都道府県を登録する設定です｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="006"></a>
			<span style="color:#cc6600;">Q6.ﾀｰｹﾞｯﾄの変更はできますか?</span><br />                  
			{% disneyimg style='height="5"' name="dot0" %}<br />           
			<span style="color:#3300FF;">A6.</span>
			ﾄｯﾌﾟﾍﾟｰｼﾞ内の｢ﾀｰｹﾞｯﾄ設定｣から変更することができます｡<span style="color:ff0000;">再設定後は､今まで稼いだ距離は､ﾘｾｯﾄされます｡</span><br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			</div>
			
