
			<br />
			<div style="color:#5b2806;">
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">お試し版について</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span>お試し版では､何が出来るの?<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			<span style="color:#cc6600;">Q1.お試し版では､何が出来るの?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			         
			<span style="color:#3300FF;">A1.</span>
			お試し版では､下記のｺﾝﾃﾝﾂ及び機能で遊ぶことができます｡<br />
			･現地に行ってご当地GETする<br />
			･ﾏｲﾐｸとﾄﾚｰﾄﾞする<br />
			･ﾀｰｹﾞｯﾄﾂｱｰでご当地ｷｬﾗｸﾀｰをGETする<br />
			<br />
			<!--
			近日､ご当地ｷｬﾗｸﾀｰのﾃﾞｺﾒ化､ﾏｲﾐｸへ"贈る"､ﾁｬﾚﾝｼﾞｹﾞｰﾑをすることができます｡<br />
			<span style="color:ff0000;">※こちらのｺﾝﾃﾝﾂ及び機能は､有料です｡</span><br />
			-->
			</div>
