			
			<br />
			<div style="color:#5b2806;">	
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">mixiﾎﾟｲﾝﾄ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>mixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>mixiﾎﾟｲﾝﾄを購入するにはどうすればいいのですか?</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.mixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ内でmixiﾎﾟｲﾝﾄが必要なｺﾝﾃﾝﾂは下記の通りです｡<br /> 
			･ご当地ｷｬﾗｸﾀｰのﾃﾞｺﾒ化                                 50ﾎﾟｲﾝﾄ<br />
			･ご当地ｷｬﾗｸﾀｰをﾏｲﾐｸに贈る                           200ﾎﾟｲﾝﾄ<br />
			･ｹﾞｰﾑﾁｹｯﾄ購入( 1枚)                                     30ﾎﾟｲﾝﾄ<br />
			･ｹﾞｰﾑﾁｹｯﾄ購入( 5枚)                                     140ﾎﾟｲﾝﾄ<br />
			･ｹﾞｰﾑﾁｹｯﾄ購入(10枚)                                  270ﾎﾟｲﾝﾄ<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" style='width="100%"' %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="002"></a>
			<span style="color:#cc6600;">Q2.mixiﾎﾟｲﾝﾄを購入するにはどうすればいいのですか?</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />
			<span style="color:#3300FF;">A2.</span>mixiﾎﾟｲﾝﾄの購入については､<a href="http://m.mixi.jp/help.pl?guid=ON&mode=item&item=315">こちら</a>をご確認ください｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			
			</div>