
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq001"|mixiurl %}'><span style="color:#5b2806;">各種設定</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq002"|mixiurl %}'><span style="color:#5b2806;">ご当地ｷｬﾗｸﾀｰ取得</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq003"|mixiurl %}'><span style="color:#5b2806;">ご当地ﾏｯﾌﾟ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq004"|mixiurl %}'><span style="color:#5b2806;">ﾄﾚｰﾄﾞ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq005"|mixiurl %}'><span style="color:#5b2806;">ﾃﾞｺﾒ･待受けをGETするには</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq006"|mixiurl %}'><span style="color:#5b2806;">ﾏｲﾐｸに贈る</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq007"|mixiurl %}'><span style="color:#5b2806;">ﾏｲﾐｸ情報</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq008"|mixiurl %}'><span style="color:#5b2806;">ｱﾜｰﾄﾞ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq010"|mixiurl %}'><span style="color:#5b2806;">ﾀｰｹﾞｯﾄﾂｱｰ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq011"|mixiurl %}'><span style="color:#5b2806;">ﾁｬﾚﾝｼﾞｹﾞｰﾑ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq012"|mixiurl %}'><span style="color:#5b2806;">ｹﾞｰﾑﾁｹｯﾄ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq013"|mixiurl %}'><span style="color:#5b2806;">ﾗﾝｷﾝｸﾞ</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq014"|mixiurl %}'><span style="color:#5b2806;">ﾏｲﾐｸ招待</span></a><br />
			<!-- 
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq015"|mixiurl %}'><span style="color:#5b2806;">お試し版について</span></a><br />
			-->
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq016"|mixiurl %}'><span style="color:#5b2806;">通信中断</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq017"|mixiurl %}'><span style="color:#5b2806;">mixiﾎﾟｲﾝﾄ</span></a><br />
			<!--
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq018"|mixiurl %}'><span style="color:#5b2806;">課金情報について</span></a><br />
			-->
			･<a href='{% "$baseUrl/mobile/disney/help?CF_help=faq019"|mixiurl %}'><span style="color:#5b2806;">入退会</span></a><br />
			･<a href='{% "$baseUrl/mobile/disney/phone"|mixiurl %}'><span style="color:#5b2806;">対応機種</span></a><br />  
			<br />
			{% disneyimg name="faq_line" style='align="top" width="100%"' %}
			<div style="background-color:#ccff66;text-align:left;">
				{% disneyimg style='height="5"' name="dot0" %}<br />
				
				<span style="color:#3ea124;">├</span>{% emoji code="F97A"%}<a href='{% "$baseUrl/mobile/disney/charge"|mixiurl %}'>有料ｻｰﾋﾞｽ利用規約</a><br />
				<span style="color:#3ea124;">└</span>{% emoji code="F9B8"%}<a href='{% "$baseUrl/mobile/disney/tokus"|mixiurl %}'>特定商取引法に基づく表示</a><br />
				{% disneyimg style='height="3"' name="dot0" %}<br />
			</div> 