{%include file="school/common/header.phtml" bgColor=1 headAd=0 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="recommendFinish" style="background:#5ac5ff;color:#003366;">
		<div id="bgImage" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
		</div><!--/#bgImage-->
		<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳ｱﾌﾟﾘをｵｽｽﾒ♪</div>
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%$profileInfo.displayName%}ｻﾝにあしあと帳ｵｽｽﾒしました｡<br />
		</div><!--/.description-->
		{%include file="school/common/ad_complete.phtml"%}
		<div class="footlink">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$profileInfo.uid`"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">{%$profileInfo.displayName%}ｻﾝの時間割</span></a><br />
		</div><!--/.footlink-->
		<div id="keyvisual" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
		</div><!--/#keyvisual-->
	</div><!--/#recommendFinish-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=0 %}