{%include file="school/common/header.phtml" bgColor=1 headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="info" style="background:#5ac5ff;color:#003366;">
		<div id="bgImage" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
		</div><!--/#bgImage-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳はもう使った?</div>
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			あしあと帳を設定しておくと､ﾏｲﾐｸや同級生がｱﾅﾀの時間割に訪れたとき､ひとことｺﾒﾝﾄがもらえて楽しくなります｡<br />
			<br />
			利用はｶﾝﾀﾝ♪<br />
			<br />
			あしあと帳ｱﾌﾟﾘを追加すれば､すぐにあしあと帳機能が利用できますよ｡<br />
			<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#f58320;">⇒</span><a href="/{%$boardAppId%}/?guid=ON" style="color:#003366;"><span style="color:#003366;">あしあと帳ｱﾌﾟﾘを追加</span></a><br />
			<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/home"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">みんなの時間割♪ﾄｯﾌﾟ</span></a><br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.description-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div id="keyvisual" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
		</div><!--/#keyvisual-->
	</div><!--/#info-->
	{%include file="school/common/copyright.phtml"%}
</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}