{% if $step=="start" %}

	{%include file="school/common/header.phtml" bgColor=1 headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="boardAdd" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳 ｺﾒﾝﾄ書き込み</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ｺﾒﾝﾄを入力し[確認]を押してください｡<br />
				{% if $errMsg %}
				<div class="errorMsg" style="color:#cc0000;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%emoji code="F9DC"%}入力ｴﾗｰ<br />
					{%$errMsg|nl2br%}
				</div><!--/.errorMsg-->
				{% /if %}
			</div><!--/.description-->
			<div class="inputElement">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/ashiatoadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="confirm" />
					<input type="hidden" name="CF_uid" value="{%$profileInfo.uid%}" />
					○宛先<br />
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$profileInfo.miniThumbnailUrl%}" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{%$profileInfo.displayName%}さん</div></td>
						</tr>
					</table>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					○ｺﾒﾝﾄ<br />
					<textarea name="txtComment" rows="3">{%$commentInfo.content|unescape_emoji%}</textarea>
					<div style="text-align:right;">※全角100文字以内</div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 確 認 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/profile"|mixiurl %}'>
					<input type="hidden" name="CF_uid" value="{%$profileInfo.uid%}" />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/.inputElement-->
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
			</div><!--/#keyvisual-->
		</div><!--/#boardAdd-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=1 %}
{% elseif $step=="confirm" %}

	{%include file="school/common/header.phtml" bgColor=1 headAd=0 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="boardAdd" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳 ｺﾒﾝﾄ書き込み</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				入力内容を確認し､よろしければ[送信]を押してください｡<br />
			</div><!--/.description-->
			<div class="inputElement">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/ashiatoadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="complete" />
					<input type="hidden" name="CF_uid" value="{%$profileInfo.uid%}" />
					○宛先<br />
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$profileInfo.miniThumbnailUrl%}" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">{%$profileInfo.displayName%}さん</div></td>
						</tr>
					</table>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					○ｺﾒﾝﾄ<br />
					{%$commentInfo.content|escape|nl2br|unescape_emoji%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 送 信 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/ashiatoadd"|mixiurl %}'>
					<input type="hidden" name="CF_uid" value="{%$profileInfo.uid%}">
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 修 正 " />
					</div><!--/.btn-->
				</form>
			</div><!--/.inputElement-->
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
			</div><!--/#keyvisual-->
		</div><!--/#boardAdd-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step=="complete" %}

	{%include file="school/common/header.phtml" bgColor=1 headAd=0 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="boardAdd" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳 ｺﾒﾝﾄ書き込み</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$profileInfo.displayName%}ｻﾝのあしあと帳にｺﾒﾝﾄを送信しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$profileInfo.uid`"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">{%$profileInfo.displayName%}ｻﾝの時間割</span></a><br />
				{%*<span style="color:#f58320;">⇒</span><a href='/{%$boardAppId%}/?guid=ON' style="color:#003366;"><span style="color:#003366;">{%$profileInfo.displayName%}ｻﾝのあしあと帳</span></a><br />*%}
			</div><!--/.footlink-->
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
			</div><!--/#keyvisual-->
		</div><!--/#boardAdd-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=0 %}

{% else %}

	{%include file="school/common/header.phtml" bgColor=1 headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="boardAdd" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#3c88e5;color:#ffffff;">あしあと帳 ｺﾒﾝﾄ書き込み</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$profileInfo.displayName%}ｻﾝのあしあと帳するには､あしあと帳ｱﾌﾟﾘを追加する必要があります｡<br />
			</div><!--description-->
			<div class="recommendlink" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				≫<a href="/{%$boardAppId%}/?guid=ON" style="color:#003366;"><span style="color:#003366;">あしあと帳ｱﾌﾟﾘを追加</span></a>≪
			</div><!--/#recommendlink-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$profileInfo.uid`"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">{%$profileInfo.displayName%}ｻﾝの時間割</span></a><br />
			</div><!--/.footlink-->
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
			</div><!--/#keyvisual-->
		</div><!--/#boardAdd-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=1 %}

{% /if %}
