{%include file="school/common/header.phtml" bgColor=1 headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="help" style="background:#5ac5ff;color:#003366;">
		<div id="bgImage" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" />
		</div><!--/#bgImage-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#3c88e5;color:#ffffff;">特定商取引法に基づく表記</div>
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			会社名:<br />
			株式会社ｺﾐｭﾆﾃｨﾌｧｸﾄﾘｰ<br />
			代表取締役 松本龍祐<br />
			<br />
			事務所:<br />
			〒151-0051<br />
			東京都渋谷区千駄ヶ谷3-29-4 LinNoビル<br />
			<br />
			資本金:<br />
			26,200,000円<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.description-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div id="keyvisual" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" />
		</div><!--/#keyvisual-->
	</div><!--/#help-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}