{%include file="school/common/header.phtml" headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="changeSchedule">
		{%if $pager.count %}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				類似授業の確認<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				｢{%$classname|escape%}｣と類似する授業が{%$pager.count%}件あります｡入力の違いで､同じ授業が重複して登録されると授業ﾄﾋﾟｯｸで有益な情報が得られなくなりますので､今一度ご確認ください｡<br />
				<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.description-->
				<div class="count">{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件</div>
				<div class="list">
					{% foreach from=$lstName item=data key=key %}
						<div class="section" style="background:#{% if ($key%2) == 0 %}e5efbd{%else%}fcf5cc{%/if%};">
							{%$data.name%}({%$data.teacher%})<br />
							<div style="text-align:right;"><span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/scheduleaddfinish?CF_cid=`$data.cid`&CF_wday=`$wday`&CF_part=`$part`&CF_action=`$actionUrl`"|mixiurl %}'>この授業を追加</a></div>
						</div><!--/.section-->
					{% /foreach %}
				</div><!--/.list-->
			{%include file="school/common/pager.phtml"%}
			<a id="scheduleAddNew" name="scheduleAddNew"></a>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				類似授業が見つからない場合<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				類似授業が見つからない場合は､入力した｢{%$classname|escape%}｣を新規追加します｡よろしければ､担当講師の苗字を正しく入力し､[確認]を押してください｡<br />
				{% if $errorMsg %}
					<div class="errorMsg" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{% emoji code="F9DC"%}入力ｴﾗｰ<br />
						{% $errorMsg|nl2br %}<br />
					</div><!--/.errorMsg-->
				{% /if %}
			</div><!--/.description-->
			<form method="post" action='{% "$baseUrl/mobile/school/scheduleaddconfirm"|mixiurl %}'>
				<input type="hidden" name="CF_wday" value="{%$wday%}" />
				<input type="hidden" name="CF_part" value="{%$part%}" />
				<input type="hidden" name="CF_cid" value="{%$cid%}" />
				<input type="hidden" name="CF_action" value="{%$actionUrl%}" />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<input type="text" name="classNameTeacher" value="{%$teachername%}"/><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" 確 認 " /><br />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/school/`$actionUrl`"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_wday" value="{%$wday%}" />
					<input type="hidden" name="CF_part" value="{%$part%}" />
					<input type="hidden" name="CF_cid" value="{%$cid%}" />
					<input type="hidden" name="CF_isSession" value="1" />
					<input type="submit" value=" ｷｬﾝｾﾙ " /><br />
				</div><!--/.btn-->
			</form>
		{%else%}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				講師名を入力して追加<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				｢{%$classname|escape%}｣を新規追加します｡担当講師の苗字を正しく入力し､よろしければ[確認]を押してください｡<br />
				{% if $errorMsg %}
					<div class="errorMsg" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{% emoji code="F9DC"%}入力ｴﾗｰ<br />
						{% $errorMsg|nl2br %}<br />
					</div><!--/.errorMsg-->
				{% /if %}
			</div><!--/.description-->
			<form method="post" action='{% "$baseUrl/mobile/school/scheduleaddconfirm"|mixiurl %}'>
				<input type="hidden" name="CF_wday" value="{%$wday%}" />
				<input type="hidden" name="CF_part" value="{%$part%}" />
				<input type="hidden" name="CF_cid" value="{%$cid%}" />
				<input type="hidden" name="CF_action" value="{%$actionUrl%}" />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<input type="text" name="classNameTeacher" value="{%$teachername%}"/><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" 確 認 " /><br />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/school/`$actionUrl`"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_wday" value="{%$wday%}" />
					<input type="hidden" name="CF_part" value="{%$part%}" />
					<input type="hidden" name="CF_cid" value="{%$cid%}" />
					<input type="hidden" name="CF_isSession" value="1" />
					<input type="submit" value=" ｷｬﾝｾﾙ " /><br />
				</div><!--/.btn-->
			</form>
		{%/if%}
		</div><!--/#changeSchedule-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}