{%include file="school/common/header.phtml" headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="classInfo">
		{%include file="school/common/headline.phtml"%}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
			<tr>
				<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
					{% if $classInfo.introduce && $classInfo.status!=5 %}{%$classInfo.introduce|escape|unescape_emoji|nl2br%}<br />{% else %}共同編集ﾉｰﾄは､授業のﾒﾓ･概要･関連情報･攻略法をみんなで編集する情報共有型ｳｨｷです｡<br />{% /if %}
					<div style="text-align:right;">[<a href='{% "$baseUrl/mobile/school/classnoteadd?CF_cid=`$classInfo.cid`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">共同編集</span></a>]</div>
					</div></td>
			</tr>
		</table>
		{% if $listEditor %}
		<div id="author">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ffdb33;">共同編集ﾉｰﾄ 執筆者履歴</div>
			<div class="list">
			{% foreach name=editorlist from=$listEditor item=ldata key=key %}
				<div class="section" style="{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
					{%emoji code="F995"%}<a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$ldata.uid`"|mixiurl %}'>{%$ldata.displayName%}</a><br />
				</div><!--/.section-->
			{% /foreach %}
			</div><!--/.list-->
		</div><!--/#author-->
		{% /if %}
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="footlink">
			<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
		</div><!--/.footlink-->
	</div><!--/#classInfo-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}