{%if $step=="start"%}

	{%include file="school/common/header.phtml" headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classDescription">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8fc31f;">共同編集ﾉｰﾄ</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				共同編集ﾉｰﾄは､授業のﾒﾓ･概要･関連情報･攻略法をみんなで編集する情報共有型ｳｨｷです｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ﾃｷｽﾄを入力し､[確認]を押してください｡<br />
				{% if $errMsg %}
				<div class="errorMsg" style="color:#cc0000;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%emoji code="F9DC"%}入力ｴﾗｰ<br />
					{%$errMsg|nl2br%}
				</div><!--/.errorMsg-->
				{% /if %}
			</div><!--/.description-->
			<div class="inputElement">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/classnoteadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="confirm" />
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					○共同編集ﾉｰﾄ<br />
					<textarea name="txtNote" rows="5">{% if $noteInfo.introduce && $classInfo.status!=5 %}{%$noteInfo.introduce|unescape_emoji%}{% /if %}</textarea>
					<div style="text-align:right;">※全角30000文字以内</div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 確 認 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/classnote"|mixiurl %}'>
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/.inputElement-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#classDescription-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=1 %}

{%elseif $step=="confirm"%}

	{%include file="school/common/header.phtml" headAd=0 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classDescription">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8fc31f;">共同編集ﾉｰﾄ</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				入力内容を確認し､[送信]を押してください｡<br />
			</div><!--/.description-->
			<div class="inputElement">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/classnoteadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="complete" />
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					○共同編集ﾉｰﾄ<br />
					{%$noteInfo.introduce|escape|nl2br|unescape_emoji%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 送 信 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/classnoteadd"|mixiurl %}'>
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 修 正 " />
					</div><!--/.btn-->
				</form>
			</div><!--/.inputElement-->
		</div><!--/#classDescription-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=0 %}

{%elseif $step=="complete"%}

	{%include file="school/common/header.phtml" %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classDescription">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8fc31f;">共同編集ﾉｰﾄ</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				共同編集ﾉｰﾄを編集しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/classnote?CF_cid=`$classInfo.cid`"|mixiurl %}'>共同編集ﾉｰﾄを確認</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#classDescription-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" %}

{% else %}

	{%include file="school/common/header.phtml" headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classDescription">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#8fc31f;">共同編集ﾉｰﾄ</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%emoji code="F9DC"%}他のﾕｰｻﾞｰが編集中ですので、少々お待ちください｡{%emoji code="F9DC"%}<br />
			</div><!--/.description-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#classDescription-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

	{%include file="school/common/footer.phtml" footAd=1 %}

{%/if%}
