{% if $step == 'reset' %}

	{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeDesign">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">みんなの時間割♪に招待しよう!!</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				同級生やﾏｲﾐｸを招待する､あるいは､一定期間､毎日ﾛｸﾞｲﾝすると､無料ﾃﾞｻﾞｲﾝが必ずもらえるｽﾋﾟｰﾄﾞくじに挑戦できます｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#aa89bd;">招待した人だけではなく､招待された人も挑戦権がもらえる</span>ので､ﾌﾟﾚｾﾞﾝﾄ気分でｲﾛﾝﾅ人を招待してくださいね{%emoji code="F9EF"%}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%emoji code="F8E6"%}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/dynamite/invitefinish" %}'>ﾏｲﾐｸを招待する</a><br />
				{%emoji code="F8E6"%}<a href='{% "invite:classmate?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/school/invitefinish" %}'>同級生を招待する</a>
			</div><!--/.description-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/designlist"|mixiurl %}'>時間割 ﾃﾞｻﾞｲﾝ変更へ</a><br />
			</div><!--/.footlink-->
		</div><!--/#changeDesign-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step == 'finish' %}

	{%include file="school/common/header.phtml"%}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeDesign">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">時間割 ﾃﾞｻﾞｲﾝ設定</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				時間割のﾃﾞｻﾞｲﾝを変更しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>時間割を見る</a><br />
			</div><!--/.footlink-->
		</div><!--/#changeDesign-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% elseif $step == 'lottery' %}

	{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeDesign">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">ｽﾋﾟｰﾄﾞくじに挑戦!!</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				すべてのﾃﾞｻﾞｲﾝをGETしてしまったため､{% $miniInfo.displayName %}ｻﾝはｽﾋﾟｰﾄﾞくじに挑戦できません｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				新着ﾃﾞｻﾞｲﾝは定期的に追加されますので､たいへん申し訳ありませんが､後日挑戦してください｡<br />
			</div><!--/.description-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/designlist"|mixiurl %}'>時間割 ﾃﾞｻﾞｲﾝ一覧</a><br />
			</div><!--/.footlink-->
		</div><!--/#changeDesign-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% /if%}