{%include file="school/common/header.phtml" headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="changeDesign">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#b7cb6d;">時間割 ﾃﾞｻﾞｲﾝ変更</div>
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			時間割のﾃﾞｻﾞｲﾝを変更できます｡お好みのﾃﾞｻﾞｲﾝを選択してください｡<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			[?]のﾃﾞｻﾞｲﾝは､ﾏｲﾐｸや同級生を招待して挑戦できるｽﾋﾟｰﾄﾞくじでGETできます｡ｲﾛﾝﾅ人を誘って､個性的なﾃﾞｻﾞｲﾝを手に入れよう!<br />
			<div style="text-align:right;"><span style="color:#f58320;">⇒</span>{% if $miniInfo.lottery_chance == 0 %}<a href='{% "$baseUrl/mobile/school/designfinish?CF_step=reset"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a></div>{% elseif $pager.count == $aryNum %}<a href='{% "$baseUrl/mobile/school/designfinish?CF_step=lottery"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a></div>{% else %}<a href='{% "$baseUrl/mobile/school/designview?CF_step=lottery"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a></div>{%/if%}
		</div><!--/.description-->

		{%*
		<div class="typeSelect">
			<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			ｶﾃｺﾞﾘ:無料 <a href="#">ﾌﾟﾚﾐｱﾑ</a><br />
		</div><!--/.typeSelect-->
		*%}

		<div class="count">
			<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			全{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件<br />
		</div><!--/.count-->
		<div class="content" style="text-align:center;">
			<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
{% foreach from=$lstDesign item=data key=key %}{% if $data.type == 's' %}<img src="{%$staticUrl%}/apps/school/mobile/img/thumb/{%$data.did%}/s.gif" width="76" height="76" />{% elseif $data.type == 'f' %}<a href='{% "$baseUrl/mobile/school/designview?CF_step=view&CF_did=`$data.did`"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/thumb/{%$data.did%}/f.gif" width="76" height="76" /></a>{% else %}<a href='{% "$baseUrl/mobile/school/designfinish?CF_step=reset"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/design/secret.gif" width="76" height="76" /></a>{% /if %}{% if $key == 2 || $key == 5 || $key == 8%}<br />{% /if %}{% /foreach %}
		</div><!--/.content-->
		{%include file="school/common/pager.phtml"%}
	</div><!--/#changeDesign-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}