{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">

{% if $step == 'view' %}
	
	{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeDesign">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">時間割 ﾃﾞｻﾞｲﾝ変更</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				ﾃﾞｻﾞｲﾝﾌﾟﾚﾋﾞｭｰを確認し､よろしければ[変更]を押してください。<br />
			</div><!--/.description-->
			<div class="preview">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				○ﾃﾞｻﾞｲﾝﾌﾟﾚﾋﾞｭｰ<br />
				<div class="screenshot" style="text-align:center;"><img src="{%$staticUrl%}/apps/school/mobile/img/thumb/{%$did%}/preview.gif" width="228" height="304" /></div>
			</div><!--/.preview-->
			<form method="post" action='{% "$baseUrl/mobile/school/designfinish?CF_step=finish"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_step" value="finish" />
					<input type="hidden" name="CF_did" value="{%$did%}" />
					<input type="submit" value=" 変 更 " />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/school/designlist"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" ｷｬﾝｾﾙ " />
				</div><!--/.btn-->
			</form>
		</div><!--/#changeDesign-->
			{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step == 'change' %}

	{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeDesign">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">ｽﾋﾟｰﾄﾞくじに挑戦!!</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				新しい時間割ﾃﾞｻﾞｲﾝを手に入れました!<br />
				<div class="screenshot" style="text-align:center;"><img src="{%$staticUrl%}/apps/school/mobile/img/thumb/{%$did%}/preview.gif" width="228" height="304" /></div>
			</div><!--/.description-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/designfinish?CF_step=finish&CF_did=`$did`"|mixiurl %}'>このﾃﾞｻﾞｲﾝを使う!</a><br />
				<span style="color:#f58320;">⇒</span>{% if $miniInfo.lottery_chance == 0 %}<a href='{% "$baseUrl/mobile/school/designfinish?CF_step=reset"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a><br />{% elseif $count == $aryNum %}<a href='{% "$baseUrl/mobile/school/designfinish?CF_step=lottery"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a><br />{% else %}<a href='{% "$baseUrl/mobile/school/designview?CF_step=lottery"|mixiurl %}'>ｽﾋﾟｰﾄﾞくじに挑戦</a><br />{%/if%}
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/designlist"|mixiurl %}'>時間割 ﾃﾞｻﾞｲﾝ一覧</a><br />
			</div><!--/.footlink-->
		</div><!--/#changeDesign-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step == 'lottery' %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changeDesign">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">ｽﾋﾟｰﾄﾞくじに挑戦!!</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%$inviteCnt%}人のﾏｲﾐｸを招待したので､あと{%$miniInfo.lottery_chance%}回 ｽﾋﾟｰﾄﾞくじに挑戦できます!<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					次の9つのｶｰﾄﾞから1枚選んでください｡<br />
				</div><!--/.description-->
				<div class="content" style="text-align:center;">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/1.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/2.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/3.gif" width="76" height="76" /></a><br/>
					<a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/4.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/5.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/6.gif" width="76" height="76" /></a><br/>
					<a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/7.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/8.gif" width="76" height="76" /></a><a href='{% "$baseUrl/mobile/school/designview?CF_step=change"|mixiurl %}'><img src="{%$staticUrl%}/apps/school/mobile/img/card/9.gif" width="76" height="76" /></a><br />
				</div><!--/.content-->
			</div><!--/#changeDesign-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}
	
{% /if %}