{% if $step=="start" %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="enquete">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を編集する</div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
					<tr>
						<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
							Q.{%$enquiryInfo.question|escape|unescape_emoji%}<br />
							<div style="text-align:right;">ｶﾃｺﾞﾘ:{%$enquiryInfo.name|escape%} 回答:{%$enquiryInfo.answer_count%} ｱｸｾｽ:{%$enquiryInfo.visit_count%}</div>
							</div></td>
					</tr>
				</table>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					この質問への回答を編集します｡変更内容を入力し､[確認]を押してください｡<br />
					{% if $errorMsg %}
						<div class="errorMsg" style="color:#cc0000;">
							<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
							{% emoji code="F9DC"%}入力ｴﾗｰ<br />
							{% $errorMsg|nl2br %}<br />
						</div><!--/.errorMsg-->
					{% /if %}
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryansweredit"|mixiurl %}'>
						○回答ｺﾒﾝﾄ<br />
						<textarea name="classTopicComment" rows="3">{%$topiccomment|escape|escape|unescape_emoji%}</textarea>
						<div style="text-align:right;">※全角300文字以内</div>
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_step" value="confirm" />
							<input type="hidden" name="CF_qid" value="{%$qid%}" />
							<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
							<input type="submit" value=" 確 認 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryanswerlist"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_qid" value="{%$qid%}" />
							<input type="submit" value=" ｷｬﾝｾﾙ " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
				{% if $commentInfo.good_count == 0 %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を削除する</div>
					<div class="description">
						<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
						回答を削除するには､以下の[確認]を押してください｡<br />
					</div><!--/.description-->
					<div class="inputElement">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<form method="post" action='{% "$baseUrl/mobile/school/enquiryanswerdel"|mixiurl %}'>
							<div class="btn" style="text-align:center;">
								<input type="hidden" name="CF_qid" value="{%$qid%}" />
								<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
								<input type="hidden" name="CF_step" value="confirm" />
								<input type="submit" value=" 確 認 " />
							</div><!--/.btn-->
						</form>
					</div><!--/.inputElement-->
				{%/if%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			</div><!--/#enquete-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step=="confirm" %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="enquete">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を編集する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					入力内容を確認し､よろしければ[送信]を押してください｡<br />
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryansweredit"|mixiurl %}'>
						○回答ｺﾒﾝﾄ<br />
						{%$topiccomment|escape|unescape_emoji%}<br />
						<input type="hidden" name="classTopicComment" value="{%$topiccomment%}" />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_step" value="finish" />
							<input type="hidden" name="CF_qid" value="{%$qid%}" />
							<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
							<input type="submit" value=" 送 信 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryansweredit"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_qid" value="{%$qid%}" />
							<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
							<input type="submit" value=" 修 正 " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
			</div><!--/#enquete-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step=="finish" %}

	{%include file="school/common/header.phtml"%}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="enquete">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を編集する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					回答ｺﾒﾝﾄの変更が完了しました｡<br />
					{% if $randQid %}
						<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$randQid`"|mixiurl %}'>続けて質問に回答する</a><br />
					{%/if%}
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/profile"|mixiurl %}'>{% $miniInfo.displayName %}ｻﾝのﾌﾟﾛﾌ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$qid`"|mixiurl %}'>回答した質問を確認</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			</div><!--/#enquete-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}
