{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="enquete">
			<div class="listGroup">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#7ecef4;">{%if $sort == 'u' %}新着の教えて!プロフ{%else%}回答数が多い 教えて!ﾌﾟﾛﾌ{%/if%}</div>
				<div class="cat">{%if $cid == 0 %}すべて{%else%}<a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=`$orderBy`&CF_categoryid=0"|mixiurl %}'>すべて</a>{% /if %}{% foreach from=$nbTypeLst item=data key=key %}{%if $cid == $data.id %}<span style="color:#cccccc;">|</span>{%$data.name%}{%else%}<span style="color:#cccccc;">|</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_categoryid=`$data.id`&CF_orderBy=`$orderBy`"|mixiurl %}'>{%$data.name%}</a>{% /if %}{% /foreach %}<br />
					<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.cat-->
			{%if $pager.count %}
					<div class="count">
						{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件<br />
						<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.count-->
					<div class="list">
					{% foreach from=$categoryLst item=data key=key %}
						<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
						{%if $data.isdelete == 1 %}
							このコメントは削除されました｡<br />
						{%else%}
							<span style="color:#a35625;">{%if $cid %}[{%$data.update_time|date_format:"%y/%m/%d %H:%M"%}]{% else %}[{%$data.format_time%}]{%$data.name%}{% /if %}</span><br />
							<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$data.qid`"|mixiurl %}'>{%$data.question%}({%$data.answer_count%})</a><br />
						{%/if%}
						</div><!--/.section-->
					{% /foreach %}
					</div><!--/.list-->
					{%include file="school/common/pager.phtml"%}
				</div><!--/.listGroup-->
				<div class="footlink">
					<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%if $sort == 'a' %}
						<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=update_time&CF_categoryid=`$cid`"|mixiurl %}'>新着順に表示</a>
					{%else%}
						<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=answer_count&CF_categoryid=`$cid`"|mixiurl %}'>回答数の多い順に表示</a>
					{%/if%}<br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			{%else%}
					<div class="description" style="text-align:center;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						まだ質問がありません｡<br />
					</div><!--/.description-->
				</div><!--/.listGroup-->
				<div class="footlink">
					<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			{%/if%}
		</div><!--/#enquete-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}