{%include file="school/common/header.phtml" headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="enquete">
			<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答一覧</div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
			<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
				<tr>
					<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
						Q.{%$enquiryInfo.question|escape%}<br />
						<div style="text-align:right;">ｶﾃｺﾞﾘ:<a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_categoryid=`$enquiryInfo.category`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">{%$enquiryInfo.name|escape%}</span></a> 回答:{%$enquiryInfo.answer_count%} ｱｸｾｽ:{%$enquiryInfo.visit_count%}</div>
						</div></td>
				</tr>
			</table>
			<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
			<div class="toAdd" style="text-align:center;">
				<table width="228" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#f19149;text-align:center;">
					<tr>
						<td style="background:#fff799;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
							{% emoji code="F9BE"%}{% if $commentId %}<a href='{% "$baseUrl/mobile/school/enquiryansweredit?CF_commentid=`$commentId`"|mixiurl %}'>回答内容を編集する！</a>{%else%}<a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$qid`"|mixiurl %}'>この質問に回答する!</a>{%/if%}<br />
							</div></td>
					</tr>
				</table>
			</div><!--/.toAdd-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
			{%if $pager.count %}
				<div class="count">
					{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件<br />
					<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div>
				<div class="list">
					{% foreach from=$enquiryanswerLst item=data key=key %}
						<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
							<a id="comment{%$key%}" name="comment{%$key%}"></a>
							<a href="#comment{%$key+1%}" style="color:#a35625;"><span style="color:#a35625;">▼</span></a><span style="color:#a35625;">{%*[{%$data.no%}]*%} {%$data.create_time|date_format:"%y/%m/%d %H:%M"%}</span><br />
							<table width="100%" cellpadding="0" cellspacing="0" border="0">
								<tr>
									<td style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" /></td>
									<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
									<a href='{% "$baseUrl/mobile/school/enquiryprofilelist?CF_uid=`$data.userInfo.uid`"|mixiurl %}'>{%$data.displayName%}</a><br />
									<span style="color:#cccc00;">★</span><span style="color:#a35625;">{%$data.userInfo.star_count%}</span><span style="color:#cccc00;">★</span>
									</div></td>
								</tr>
							</table>
							<div class="comment">
								{%$data.comment|escape|unescape_emoji%}
								<div style="text-align:right;">
									{%if $data.uid == $miniInfo.uid %}
										[<a href='{% "$baseUrl/mobile/school/enquiryansweredit?CF_commentid=`$data.comment_id`"|mixiurl %}' style="color:#333333;"><span style="color:#333333;">編集</span></a>]
										[{%emoji code="F9CC"%}<span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})]</span>
									{%else%}
										[{%emoji code="F9CC"%}{%if $data.isAssess %}<span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})]</span>{%else%}<a href='{% "$baseUrl/mobile/school/enquirycommentgood?CF_commentid=`$data.comment_id`"|mixiurl %}' style="color:#333333;"><span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})</span></a>]{%/if%}
									{%/if%}
								</div>
							</div><!--/.comment-->
						</div><!--/.section-->
					{% /foreach %}
				</div><!--/.list-->
				<a id="comment{%$enquiryanswerLst|@count%}" name="comment{%$enquiryanswerLst|@count%}"></a>
				{%include file="school/common/pager.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BE"%}{% if $commentId %}<a href='{% "$baseUrl/mobile/school/enquiryansweredit?CF_commentid=`$commentId`"|mixiurl %}'>回答内容を編集する！</a><br />{%else%}<a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$qid`"|mixiurl %}'>この質問に回答する！</a><br />{%/if%}
					{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$qid`&CF_orderBy=good_count"|mixiurl %}'>ｲｲﾈ!の多い順に読む</a><br />
					<span style="color:#f58320;">⇒</span>{%if $orderBy == 'desc' %}<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$qid`&CF_orderBy=asc"|mixiurl %}'>最初から読む</a>{%else%}<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$qid`&CF_orderBy=desc"|mixiurl %}'>最新順に読む</a>{%/if%}<br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			{%else%}
				<div class="null" style="text-align:center;">
					まだ回答がありません｡<br />
				</div><!--/.null-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$qid`"|mixiurl %}'>この質問に回答する</a><br />
					{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			{%/if%}
		</div><!--/#enquete-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}