{%include file="school/common/header.phtml" headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="enquete">
			<div class="listGroup">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">ｱﾅﾀの質問に対する 教えて!ﾌﾟﾛﾌ</div>
			{%if $pager.count %}
				<div class="count">{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件</div>
				<div class="list">
					{% foreach from=$enquiryLst item=data key=key %}
						<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
						<span style="color:#a35625;">[{%$data.format_time%}]</span>{%$data.name%}<br />
						<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$data.qid`"|mixiurl %}'>{%$data.question%}({%$data.answer_count%})</a><br />
						</div><!--/.section-->
					{% /foreach %}
				</div><!--/.list-->
				{%include file="school/common/pager.phtml"%}
			{%else%}
				<div class="description" style="text-align:center;">
					まだ回答がありません<br />
				</div><!--/.description-->
			{%/if%}
			</div><!--/.listgroup-->
			<div class="footlink">
				<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#enquete-->

		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}