{%include file="school/common/header.phtml" headAd=1 %}

<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="logo" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/prof_title.gif" width="228" height="70" style="margin-top:3px;" />
	</div><!--/#logo-->
	<div id="enquete">
		<div class="about">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌとは!?</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				教えて!ﾌﾟﾛﾌは､<span style="color:#aa89bd;">質問に回答すると､ﾌﾟﾛﾌが充実していく学生限定ｲﾝﾀﾋﾞｭｰｺﾐｭﾆﾃｨ</span>です｡同世代の人限定なので､恋の悩みやﾊﾞｲﾄなどｲﾛｲﾛ聞いてみよう{% emoji code="F9EF"%}<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				{%* ///// to answer page @random ///// *%}
				{% if $randQid %}
				<div class="toAnswer" style="text-align:center;">
					<table width="228" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#f19149;text-align:center;">
						<tr>
							<td style="background:#fff799;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
								{% emoji code="F9F4"%}<a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$randQid`"|mixiurl %}'>未回答の質問に答える</a><br />
							</div></td>
						</tr>
					</table>
				</div><!--/.toAnswer-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				{%/if%}
				<div class="toAdd" style="text-align:center;">
					<table width="228" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#f19149;text-align:center;">
						<tr>
							<td style="background:#fff799;"><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
								{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/enquiryquestionadd"|mixiurl %}'>みんなに質問する</a><br />
								</div></td>
						</tr>
					</table>
				</div><!--/.toAdd-->
				<div class="footlink" style="text-align:right;">
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryprofilelist"|mixiurl %}'>ｱﾅﾀのﾌﾟﾛﾌを確 認</a><br />
				</div><!--/.footlink-->
			</div><!--/.description-->
		</div><!--/.about-->
		<div class="listGroup">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">回答数が多い 教えて!ﾌﾟﾛﾌ</div>
			<div class="cat">
				{%if $cid1 == 0 %}すべて{%else%}<a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=answer_count&CF_categoryid=0"|mixiurl %}'>すべて</a>{% /if %}{% foreach from=$nbTypeLst item=data key=key %}{%if $cid1 == $data.id %}<span style="color:#cccccc;">|</span>{%$data.name%}{%else%}<span style="color:#cccccc;">|</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_categoryid=`$data.id`&CF_orderBy=answer_count"|mixiurl %}'>{%$data.name%}</a>{% /if %}{% /foreach %}<br />
				<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.cat-->
			<div class="list">
				{% foreach from=$enquiryCntByLst item=data key=key %}
				<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
					<span style="color:#a35625;">[{%$data.format_time%}]</span>{%$data.name%}<br />
					<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$data.qid`"|mixiurl %}'>{%$data.question%}({%$data.answer_count%})</a><br />
				</div><!--/.section-->
				{% /foreach %}
			</div><!--/.list-->
			<div class="footlink" style="text-align:right;">
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=answer_count&CF_categoryid=`$cid1`"|mixiurl %}'>もっと見る</a><br />
			</div><!--/.footlink-->
		</div><!--/.listGroup-->
		<div class="listGroup">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">新着の教えて!ﾌﾟﾛﾌ</div>
			<div class="cat">
				{%if $cid2 == 0 %}すべて{%else%}<a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=update_time&CF_categoryid=0"|mixiurl %}'>すべて</a>{% /if %}{% foreach from=$nbTypeLst item=data key=key %}{%if $cid2 == $data.id %}<span style="color:#cccccc;">|</span>{%$data.name%}{%else%}<span style="color:#cccccc;">|</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_categoryid=`$data.id`&CF_orderBy=update_time"|mixiurl %}'>{%$data.name%}</a>{% /if %}{% /foreach %}<br />
				<div class="line" style="background:#7ecef4;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.cat-->
			<div class="list">
				{% foreach from=$enquiryTimeByLst item=data key=key %}
				<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
					<span style="color:#a35625;">[{%$data.format_time%}]</span>{%$data.name%}<br />
					<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$data.qid`"|mixiurl %}'>{%$data.question%}({%$data.answer_count%})</a><br />
				</div><!--/.section-->
				{% /foreach %}
			<div class="footlink" style="text-align:right;">
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquirycategorylist?CF_orderBy=update_time&CF_categoryid=`$cid2`"|mixiurl %}'>もっと見る</a><br />
			</div><!--/.footlink-->
		</div><!--/.listGroup-->
	{%if $myEnquiryLst %}
		<div class="listGroup">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">ｱﾅﾀの質問に対する 教えて!ﾌﾟﾛﾌ</div>
			<div class="list">
			{% foreach from=$myEnquiryLst item=data key=key %}
				<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
					<span style="color:#a35625;">[{%$data.format_time%}]</span>{%$data.name%}<br />
					<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$data.qid`"|mixiurl %}'>{%$data.question%}({%$data.answer_count%})</a><br />
				</div><!--/.section-->
			{% /foreach %}
			</div><!--/.list-->
			<div class="footlink" style="text-align:right;">
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquirylistmine"|mixiurl %}'>もっと見る</a><br />
			</div><!--/.footlink-->
		</div><!--/.listGroup-->
	{%/if%}
	</div><!--/#enquete-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}