{%include file="school/common/header.phtml" %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="enquete">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">ｲｲﾈ!送信完了♪</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$nickname%}さんの回答に{%emoji code="F9CC"%}ｲｲﾈ!しました!<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$qid`"|mixiurl %}'>ｲｲﾈ!した質問に戻る</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#enquete-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" %}
