{% if $step=="confirm" %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="enquete">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を削除する</div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
					<tr>
						<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
							Q.{%$enquiryInfo.question|escape|unescape_emoji%}<br />
							<div style="text-align:right;">ｶﾃｺﾞﾘ:{%$enquiryInfo.name|escape%} 回答:{%$enquiryInfo.answer_count%} ｱｸｾｽ:{%$enquiryInfo.visit_count%}</div>
							</div></td>
					</tr>
				</table>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					上記の質問に対する回答ｺﾒﾝﾄを確認し､よろしければ[削除]を押してください｡<br />
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryanswerdel"|mixiurl %}'>
						○回答ｺﾒﾝﾄ<br />
						{%$commentInfo.comment|escape|unescape_emoji%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_step" value="finish" />
							<input type="hidden" name="CF_qid" value="{%$qid%}" />
							<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
							<input type="submit" value=" 削 除 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/enquiryansweredit"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_commentid" value="{%$commentid%}" />
							<input type="submit" value=" ｷｬﾝｾﾙ " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
			</div><!--/#enquete-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step=="finish" %}
	{%include file="school/common/header.phtml"%}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="enquete">
			<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
			<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ 回答を削除する</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				回答ｺﾒﾝﾄの削除が完了しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryprofilelist?$CF_uid=`$miniInfo.uid`"|mixiurl %}'>{% $miniInfo.displayName %}ｻﾝのﾌﾟﾛﾌ</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#enquete-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=0 %}		
			
{% elseif $step == 'error' %}
	{%include file="school/common/header.phtml"%}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classTopicsAdd">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">教えて!ﾌﾟﾛﾌ 回答</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				たいへん恐れ入りますが､ｲｲﾈ!が1票以上投票されているため､削除できません｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiryprofilelist?$CF_uid=`$miniInfo.uid`"|mixiurl %}'>{% $miniInfo.displayName %}ｻﾝのﾌﾟﾛﾌ</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>教えて!ﾌﾟﾛﾌ ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#enquete-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}

{%/if%}