{%include file="school/common/header.phtml" %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classTopicsDel">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">この授業の休講予報</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% if $agree==1 %}「正しいと思われ」{% else %}「ガセと思われ」{% /if %}に投票しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
			</div><!--/.footlink-->
		</div><!--/#classTopicsDel-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" %}