{%include file="school/common/header.phtml" headAd=1 %}

	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">

		<div id="friendSchedule">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ffdb33;">同級生ﾏｲﾐｸのｽｹｼﾞｭｰﾙ</div>
		{% if $cntFriend==0 %}
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				まだ誰もｱﾌﾟﾘを追加していません｡<br />
				<div class="morelink" style="text-align:right;">
					<span style="color:#f58320;">⇒</span><a href="#">ﾏｲﾐｸを招待する</a><br />
					<span style="color:#f58320;">⇒</span><a href="#">同級生を招待する</a><br />
				</div><!--/.morelink-->
			</div><!--/.description-->
		{% else %}
			<div class="count">
				{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件<br />
				<div class="line" style="background:#f6e99e;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.count-->
			<div class="list">
			{% foreach name=friendlist from=$listFriend item=fdata key=key %}
				<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
					<table width="100%" cellpadding="0" cellspacing="0" border="0">
						<tr>
							<td style="width:44px;text-align:center;"><img src="{%$fdata.miniThumbnailUrl%}" style="margin:1px 0;" /></td>
							<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
									<a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$fdata.uid`"|mixiurl %}'>{%$fdata.displayName%}</a><br />
									{%$fdata.class_name|escape%}<br />
								</div></td>
						</tr>
					</table>
				</div><!--/.section-->
			{% /foreach %}
			</div><!--/.list-->
			{%include file="school/common/pager.phtml"%}
		{% /if %}
		</div><!--/#friendSchedule-->

		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}