{%include file="school/common/header.phtml" bgColor=1 headAd=0 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="wrapper" style="background:#5ac5ff;color:#003366;">
			<div id="logo" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/logo.gif?v=1" width="240" height="60" /><br />
			</div><!--/#logo-->
			{%include file="school/common/ad_header.phtml"%}
			{%*
			<div id="news" color="#cc0000;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				12/26～1/3まで冬期休業の為サポート対応を停止させて頂きます。何卒ご了承ください｡<br />
			</div><!--/#news-->
			*%}
			{% if $listMessage %}
				<div id="info">
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					<div class="inner" style="background:#fcf5cc;">
						<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br />
						{% foreach name=messagelist from=$listMessage item=mdata %}
						{% if $mdata.type==1 %}
						<a href='{% "$baseUrl/mobile/school/inviteclass"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">授業への招待が{%$mdata.msg_count%}通届いています!</span></a><br />
						{% elseif $mdata.type==2 %}
						<a href='{% "$baseUrl/mobile/school/ashiatoinvitereceive?CF_mid=`$mdata.id`"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">あしあと帳ｱﾌﾟﾘの招待が届いています!</span></a><br />
						{% elseif $mdata.type==3 %}
						<a href='{% "$baseUrl/mobile/school/mynewesttopiclist?CF_mid=`$mdata.id`"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">授業Q&amp;Aの質問に回答がありました!</span></a><br />
						{% elseif $mdata.type==4 %}
						<a href='{% "$baseUrl/mobile/school/enquirylistmine?CF_mid=`$mdata.id`"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">教えて!ﾌﾟﾛﾌの質問に回答がありました!</span></a><br />
						{% elseif $mdata.type==5 %}
						<a href='{% "$baseUrl/mobile/school/designview?CF_step=lottery&CF_mid=`$mdata.id`"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">ｽﾋﾟｰﾄﾞくじに挑戦できます!</span></a><br />
						{% elseif $mdata.type==99 %}
						<a href='{% "$baseUrl/mobile/school/enquiryansweradd?CF_qid=`$mdata.randQid`"|mixiurl %}' style="color:#ff6666;"><span style="color:#ff6666;">未回答の質問があります!</span></a><br />
						{% /if %}
						{% /foreach %}
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br />
						<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.inner-->
				</div><!--/#info-->
			{% /if %}
			<div id="profileMenu">
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td style="width:80px;text-align:center;vertical-align:top;"><img src="{%$mineInfo.thumbnailUrl%}" /></td>
						<td style="vertical-align:top;"><div style="color:#003366;{% if $ua==1 %}font-size:x-small;{% /if %}">
							{%$mineInfo.displayName%}<br />
							<span style="color:#ffff66;">★</span><span style="color:#a35625;">{%$mineInfo.star_count%}</span><span style="color:#ffff66;">★</span><br />
							{%emoji code="F9E3"%}時間割 <a href='{% if $hasTimePartS %}{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}{% else %}{% "$baseUrl/mobile/school/schedule?CF_wday=`$wday`"|mixiurl %}{% /if %}' style="color:#003366;"><span style="color:#003366;">{% if $hasTimePartS %}見る</a>|<a href='{% "$baseUrl/mobile/school/schedule"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">編集</span></a>{% else %}作成</span></a>{% /if %}<br />
							{%emoji code="F8D7"%}<a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">教えて!ﾌﾟﾛﾌ</span></a>{%*<a href='{% "$baseUrl/mobile/school/enquiryprofilelist"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">教えて!ﾌﾟﾛﾌ({%$cntMyEnquiry%})</span></a>*%}<br />
							{% if $cntTopic > 0 %}{%emoji code="F9E6"%}<a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">授業Q&amp;A</span></a><br />{% /if %}
							{%emoji code="F8F9"%}<a href="{% if $isAshiatoUser %}/{%$boardAppId%}/?guid=ON{% else %}#lnkashiato{% /if %}" style="color:#003366;"><span style="color:#003366;">あしあと帳({%$cntAshiato%})</span></a><br />
							</div></td>
					</tr>
				</table>
			</div><!--/#profileMenu-->
			<div id="about" style="text-align:right;">
				<a href='{% "$baseUrl/mobile/school/help?CF_param=q1"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">このｱﾌﾟﾘについて</span></a><br />
			</div><!--/#about-->
			<div id="sub" style="background:#fcf5cc;">
				<div id="schedule" style="background:#c5d686;color:#262713;">
					<div id="keyvisual" style="text-align:center;">
						<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
					</div><!--/#keyvisual-->
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="headline" style="text-align:center;">〓{%$scheduleTitle%}〓</div>
					<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
						<tr>
							<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
								{% foreach name=timepartlist from=$mineSchedule item=sdata key=key %}
									<div class="section">
										<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /><br />
										{%$sdata.part%}限:{% if $sdata.cid>0 %}<a href='{% "$baseUrl/mobile/school/class?CF_cid=`$sdata.cid`"|mixiurl %}' style="color:#ffffff;">{% else %}<a href='{% "$baseUrl/mobile/school/classnameadd?CF_part=`$sdata.part`"|mixiurl %}' style="color:#ffffff;">{%/if%}<span style="color:#ffffff;">{%$sdata.c_name|escape%}</span></a>{% if $sdata.cid>0 %}({%$sdata.member_count|escape%}){% if 1==$sdata.is_new %}{%emoji code="F982"%}{% /if %}{% /if %}<br />
										<div style="text-align:right;">{% if $sdata.cid>0 %}{% if $sdata.c_forecast==1 %}{%emoji code="F8A0"%}{% elseif $sdata.c_forecast==2 %}{%emoji code="F8A1"%}{% else %}{%emoji code="F89F"%}{% /if %}{% /if %} {%$sdata.start_h%}:{%$sdata.start_m%}～{%$sdata.end_h%}:{%$sdata.end_m%}</div>
										<div class="line" style="background:#3e4022;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
									</div><!--/.section-->
								{% /foreach %}
									<div class="nav" style="color:#ffffff;text-align:center;">
										<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /><br />
										←[*]<a href='{% if $hasTimePartS %}{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&CF_wday=`$prevWday`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}{% else %}{% "$baseUrl/mobile/school/schedule?CF_wday=`$prevWday`"|mixiurl %}{% /if %}' style="color:#ffffff;" accesskey="*"><span style="color:#ffffff;">前日</span></a>　<a href='{% if $hasTimePartS %}{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&CF_wday=`$nextWday`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}{% else %}{% "$baseUrl/mobile/school/schedule?CF_wday=`$nextWday`"|mixiurl %}{% /if %}' style="color:#ffffff;" accesskey="#"><span style="color:#ffffff;">翌日</span></a>[#]→<br />
									</div><!--/.nav-->
								</div></td>
						</tr>
					</table>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div style="color:#cc0000;text-align:center;">{%emoji code="F89F"%}<a href='{% "$baseUrl/mobile/school/help/help?CF_param=q7"|mixiurl %}'>休講予報について</a>{%emoji code="F89F"%}</div>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				</div><!--/#schedule-->

				{% if $cntFriend > 0 %}
					<div id="friendSchedule">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="headline" style="background:#ffdb33;">同級生ﾏｲﾐｸのｽｹｼﾞｭｰﾙ</div>
						<div class="list">
						{% foreach name=friendlist from=$listFriend item=fdata key=key %}
							<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
								<table width="100%" cellpadding="0" cellspacing="0" border="0">
									<tr>
										<td style="width:44px;text-align:center;"><img src="{%$fdata.miniThumbnailUrl%}" style="margin:1px 0;" /></td>
										<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}">
												<a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$fdata.uid`"|mixiurl %}'>{%$fdata.displayName%}</a><br />
												{%$fdata.class_name|escape%}<br />
											</div></td>
									</tr>
								</table>
							</div><!--/.section-->
						{% /foreach %}
						</div><!--/.list-->
						<div class="footlink" style="text-align:right;">
							<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/friendlist"|mixiurl %}'>もっと見る</a><br />
						</div><!--/.footlink-->
					</div><!--/#friendSchedule-->
				{% /if %}

				<div id="recentEnquete">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="headline" style="background:#7ecef4;">教えて!ﾌﾟﾛﾌ最新書き込み</div>
				{% if $cntEnquiry==0 %}
					<div class="description">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						教えて!ﾌﾟﾛﾌは､質問に回答すると､ﾌﾟﾛﾌが充実していく学生限定ｲﾝﾀﾋﾞｭｰｺﾐｭﾆﾃｨです｡<br />
						<div class="morelink" style="text-align:right;">
							<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>もっと詳しく</a><br />
						</div><!--/.morelink-->
					</div><!--/.description-->
				{% else %}
					<div class="list">
					{% foreach name=enquirylist from=$listEnquiry item=tdata key=key %}
						<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
							<span style="color:#a35625;">[{%$tdata.format_time%}]</span>{%$tdata.name|escape%}<br />
							<a href='{% "$baseUrl/mobile/school/enquiryanswerlist?CF_qid=`$tdata.qid`"|mixiurl %}'>{%$tdata.question|escape%}({%$tdata.answer_count%})</a><br />
						</div><!--/.section-->
					{% /foreach %}
					</div><!--/.list-->
					<div class="footlink" style="text-align:right;">
						<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/enquiry"|mixiurl %}'>もっと見る</a><br />
					</div><!--/.footlink-->
				{% /if %}
				</div><!--/#recentEnquete-->

				{% if $cntTopic > 0 %}
					<div id="classTopics">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="headline" style="background:#b7cb6d;">授業Q&amp;A最新書き込み</div>
						<div class="list">
						{% foreach name=topiclist from=$listTopic item=tdata key=key %}
							<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
								<span style="color:#a35625;">[{%$tdata.format_time%}]</span>{%$tdata.c_name|escape%}<br />
								<a href='{% "$baseUrl/mobile/school/topic?CF_tid=`$tdata.tid`&CF_cid=`$tdata.cid`"|mixiurl %}'>{%$tdata.t_name|escape%}({%$tdata.t_comment_count%})</a><br />
							</div><!--/.section-->
						{% /foreach %}
						</div><!--/.list-->
						<div class="footlink" style="text-align:right;">
							<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>もっと見る</a><br />
						</div><!--/.footlink-->
					</div><!--/#classTopics-->
				{% /if %}

				{% if $cntVisitFootAccess > 0 %}
					<div id="recentAccess">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="headline" style="background:#ffa0fe;">ｱｸｾｽ履歴({%$cntVisitFootAccess%})</div>
						<div class="list">
						{% foreach name=footlist from=$listVisitFoot item=fdata key=key %}
							<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
								{%emoji code="F995"%}<a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$fdata.uid`"|mixiurl %}'>{%$fdata.displayName%}</a>{% if $fdata.is_friend=="1"%}{%emoji code="F99F"%}{% /if %}<br />
							</div><!--/.section-->
						{% /foreach %}
						</div><!--/.list-->
						<div class="footlink" style="text-align:right;">
							{%emoji code="F99F"%}<span style="color:#777777;">…ﾏｲﾐｸ</span> <span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/visitfoot"|mixiurl %}'>もっと見る</a><br />
						</div><!--/.footlink-->
					</div><!--/#recentAccess-->
				{% /if %}

				<div id="recentBoard">
					<a id="boardBlock" name="boardBlock"></a>
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="headline" style="background:#ff9933;">あしあと帳ｺﾒﾝﾄ最新書き込み</div>
				{% if $listAshiato %}
					<div class="list">
					{% foreach name=ashiatolist from=$listAshiato item=tdata key=key %}
						<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
							<span style="color:#a35625;">[{%$tdata.format_time%}]</span>{%$tdata.displayName%}<br />
							{% if $tdata.type==0 %}
							{%$tdata.content|truncatejp:80:"…"|escape|unescape_emoji%}<br />
							{% else %}
							<div class="paint" style="text-align:center;"><img src="{%$tdata.pic_url%}" width="228" height="54" style="margin:1px 0;" /></div>
							{% /if %}
						</div><!--/.section-->
					{% /foreach %}
					</div><!--/.list-->
					<div class="footlink" style="text-align:right;">
						<span style="color:#f58320;">⇒</span><a href="/{%$boardAppId%}/?guid=ON">もっと見る</a><br />
					</div><!--/.footlink-->
				{% else %}
					<div class="description">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						あしあと帳ｱﾌﾟﾘを追加すると､ｱﾅﾀのﾏｲﾐｸや同級生が､ｱﾅﾀに伝言できるようになります｡<br />
						<div class="morelink" style="text-align:right;">
							<span style="color:#f58320;">⇒</span><a name="lnkashiato" href="/{%$boardAppId%}/?guid=ON">あしあと帳を追加</a><br />
						</div><!--/.morelink-->
					</div><!--/.description-->
				{% /if %}
				</div><!--/#recentBoard-->
				{%include file="school/common/menu.phtml"%}
			</div><!--/#sub-->
		</div><!--/#wrapper-->
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}