{%include file="school/common/header.phtml" bgColor=1 headAd=0 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="recommendFinish" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<div class="headline" style="background:#3c88e5;color:#ffffff;">招待完了</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				当ｱﾌﾟﾘへの招待が完了しました｡<br />
			</div><!--/.description-->
			{%include file="school/common/ad_complete.phtml"%}
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				※招待特典(ｽﾋﾟｰﾄﾞくじ挑戦権GET)の反映には2-3日お時間をいただくことがあります｡招待したﾏｲﾐｸが追加したﾀｲﾐﾝｸﾞで招待特典が反映されるわけではありませんので､あらかじめご了承ください｡<br />
			</div><!--/.description-->
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
			</div><!--/#keyvisual-->
		</div><!--/#recommendFinish-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=0 %}