{%include file="school/common/header.phtml" bgColor=1 headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="info" style="background:#5ac5ff;color:#003366;">
			<div id="bgImage" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
			</div><!--/#bgImage-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#3c88e5;color:#ffffff;">時間割のﾌﾟﾗｲﾊﾞｼｰ設定</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				当ｱﾌﾟﾘには時間割の公開範囲を設定できるﾌﾟﾗｲﾊﾞｼｰ設定機能があります｡もしも､まだ変更していない場合は､以下より変更してください｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/privacyset"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ﾌﾟﾗｲﾊﾞｼｰ設定</span></a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/home"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">みんなの時間割♪ﾄｯﾌﾟ</span></a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			</div><!--/.description-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div id="keyvisual" style="text-align:center;">
				<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" />
			</div><!--/#keyvisual-->
		</div><!--/#info-->
		{%include file="school/common/copyright.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}