{% if $step=="start" %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changePrivacy">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 ﾌﾟﾗｲﾊﾞｼｰ設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割の公開範囲が設定できます｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.description-->
				<form method="post" action='{% "$baseUrl/mobile/school/privacyset"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="confirm" />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="inputElement">
						○公開範囲<br />
						<input type="radio" name="rdoMode" value="0" {% if $myMode==0 %}checked="checked"{% /if %} />同級生全員に公開<br />
						<input type="radio" name="rdoMode" value="1" {% if $myMode==1 %}checked="checked"{% /if %} />同級生のﾏｲﾐｸのみ公開<br />
					</div><!--/.inputElement-->
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 確 認 " />
					</div><!--/.btn-->
				</form>

				<form method="post" action='{% "$baseUrl/mobile/school/privacy"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/#changePrivacy-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step=="confirm" %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changePrivacy">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 ﾌﾟﾗｲﾊﾞｼｰ設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					変更内容を確認し､よろしければ[設定]を押してください｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.description-->
				<form method="post" action='{% "$baseUrl/mobile/school/privacyset"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="complete" />
					<div class="inputElement">
						○公開範囲<br />
						{%$myModeName|escape%}<br />
					</div><!--/.inputElement-->
					<div class="description">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						※当ｱﾌﾟﾘは､現役学生以外のﾕｰｻﾞｰから､利用者の時間割や授業ﾃﾞｰﾀにｱｸｾｽできないｼｽﾃﾑとなっております｡安心してご利用ください｡<br />
					</div><!--/.description-->
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 設 定 " />
					</div><!--/.btn-->
				</form>

				<form method="post" action='{% "$baseUrl/mobile/school/privacyset"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 修 正 " />
					</div><!--/.btn-->
				</form>
			</div><!--/#changePrivacy-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step=="complete" %}

	{%include file="school/common/header.phtml" %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changePrivacy">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 ﾌﾟﾗｲﾊﾞｼｰ設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割の公開範囲を変更しました｡
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>時間割を見る</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/timepartset"|mixiurl %}'>時間割 時限設定</a><br />
				</div><!--/.footlink-->
			</div><!--/#changePrivacy-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}