{% if $step == 'start'%}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="resetSchedule">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割一括削除</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割一括削除は一度実行すると再び元の状態に戻せなくなります｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					本当に時間割を一括削除してもよろしいですか?<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					もしもよろしければ[実行]を押してください｡<br />
				</div><!--/.description-->
				<form method="post" action='{% "$baseUrl/mobile/school/schedulereset"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="finish" />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 実 行 " /><br />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/schedule"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " /><br />
					</div><!--/.btn-->
				</form>
			</div><!--/#resetSchedule-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% else %}

	{%include file="school/common/header.phtml"%}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="resetSchedule">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割一括削除</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割の一括削除が完了しました｡<br />
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/schedule"|mixiurl %}'>時間割を作成する</a><br />
				</div><!--/.footlink-->
			</div><!--/#resetSchedule-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}