{%include file="school/common/header.phtml" headAd=0 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	{%if $model == 'add' || $model == 'eait' %}
		<div id="changeSchedule">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				入力内容の確認<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				次の授業を新規追加します｡よろしければ､[追加]を押してください｡<br />
			</div><!--/.description-->
			<form method="post" action='{% "$baseUrl/mobile/school/scheduleaddfinish"|mixiurl %}'>
				<div class="data">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					○授業名:<br />
					{%$classname|escape%}<br />
					<br />
					○担当講師(苗字):<br />
					{%$teachername|escape%}<br />
				</div><!--/.data-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_wday" value="{%$wday%}" />
					<input type="hidden" name="CF_part" value="{%$part%}" />
					<input type="hidden" name="CF_cid" value="{%$cid%}" />
					<input type="hidden" name="CF_action" value="{%$action%}" />
					<input type="submit" value=" 追 加 " /><br />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/school/classteacheradd"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_step" value="update" />
					<input type="hidden" name="CF_wday" value="{%$wday%}" />
					<input type="hidden" name="CF_part" value="{%$part%}" />
					<input type="hidden" name="CF_model" value="{%$model%}" />
					<input type="hidden" name="CF_cid" value="{%$cid%}" />
					<input type="submit" value=" 修 正 " /><br />
				</div><!--/.btn-->
			</form>
		</div><!--/#changeSchedule-->

	{%elseif $model == 'invite' %}

		<div id="scheduleDupulication">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				授業登録({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				重複授業の登録<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				現在､別の授業が登録されているため､追加できません｡変更する場合は､以下の[変更]を押してください｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				○変更前の授業<br />
				{%$oldInfo.name|escape%}({%$oldInfo.teacher|escape%})<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				○変更後の授業<br />
				{%$newInfo.name|escape%}({%$newInfo.teacher|escape%})<br />
			</div><!--/.description-->
			<form method="post" action='{% "$baseUrl/mobile/school/scheduleaddfinish"|mixiurl %}'>
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="btn" style="text-align:center;">
					<input type="hidden" name="CF_wday" value="{%$wday%}" />
					<input type="hidden" name="CF_part" value="{%$part%}" />
					<input type="hidden" name="CF_cid" value="{%$cid%}" />
					<input type="hidden" name="CF_id" value="{%$id%}" />
					<input type="hidden" name="CF_action" value="{%$action%}" />
					<input type="submit" value=" 変 更 " /><br />
				</div><!--/.btn-->
			</form>
			<form method="post" action='{% "$baseUrl/mobile/school/inviteclass"|mixiurl %}'>
				<div class="btn" style="text-align:center;">
					<input type="submit" value=" ｷｬﾝｾﾙ " /><br />
				</div><!--/.btn-->
			</form>
		</div><!--/#scheduleDupulication-->

	{%elseif $model == 'profile' %}

		<div id="changeSchedule">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">時間割編集({%$day%}曜日{%$part%}限)</div>
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				時間割に追加していない授業は閲覧することができません｡<br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$day%}曜日{%$part%}限に｢{%$newInfo.name|escape%}({%$newInfo.teacher|escape%})｣を追加しますか?<br />
			</div><!--/.description-->
			<div class="inputElement">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/scheduleaddfinish"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="hidden" name="CF_wday" value="{%$wday%}" />
						<input type="hidden" name="CF_part" value="{%$part%}" />
						<input type="hidden" name="CF_cid" value="{%$cid%}" />
						<input type="hidden" name="CF_action" value="{%$action%}" />
						<input type="submit" value=" 追 加 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/profile"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="hidden" name="CF_uid" value="{%$fid%}" />
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/.inputElement-->
		</div><!--/#changeSchedule-->
	{%/if%}
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=0 %}