{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="changeSchedule">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				変更前の授業<br />
			</div><!--/.headline-->
			<div class="classNow">
				{%$eaitInfo.name|escape%}({%$eaitInfo.teacher|escape%})<br />
				<div style="text-align:right;"><span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$cid`"|mixiurl %}'><span>この授業を見る</span></a></div>
			</div><!--/.classNow-->
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{%if $pager.count %}
				<div class="headline" style="background:#b7cb6d;">
					時間割編集({%$day%}曜日{%$part%}限)<br />
					<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					同級生が履修中の授業<br />
				</div><!--/.headline-->
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%$day%}曜日{%$part%}限に追加する授業を選択してください｡該当する授業がない場合は<a href="#scheduleAddNew">ｺﾁﾗ</a>より追加してください｡<br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.description-->
				<div class="count">{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件</div>
				<div class="list">
					{% foreach from=$lstCid item=data key=key %}
						<div class="section" style="background:#{% if ($key%2) == 0 %}e5efbd{%else%}fcf5cc{%/if%};">
							{%$data.c_name|escape%}({%$data.c_teacher|escape%})<br />
							<div style="text-align:right;"><span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/scheduleaddfinish?CF_cid=`$data.cid`&CF_wday=`$wday`&CF_part=`$part`&CF_action=scheduleedit"|mixiurl %}'>この授業を追加</a></div>
						</div><!--/.section-->
					{% /foreach %}
				</div><!--/.list-->
				{%include file="school/common/pager.phtml"%}
			{%/if%}
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a id="scheduleAddNew" name="scheduleAddNew"></a>
			<div class="headline" style="background:#b7cb6d;">
				時間割編集({%$day%}曜日{%$part%}限)<br />
				<div class="line" style="background:#e5efbd;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				授業名を入力して追加<br />
			</div><!--/.headline-->
			<div class="description">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{%$day%}曜日{%$part%}限に追加する授業を､以下の入力ﾌｫｰﾑに正しく入力し､[追加]を押してください｡<br />
				{% if $errorMsg %}
					<div class="errorMsg" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{% emoji code="F9DC"%}入力ｴﾗｰ<br />
						{% $errorMsg|nl2br %}<br />
					</div><!--/.errorMsg-->
				{% /if %}
			</div><!--/.description-->
			<form method="post" action='{% "$baseUrl/mobile/school/classteacheradd"|mixiurl %}'>
				<input type="hidden" name="CF_wday" value="{%$wday%}" />
				<input type="hidden" name="CF_part" value="{%$part%}" />
				<input type="hidden" name="CF_cid" value="{%$cid%}" />
				<input type="hidden" name="CF_model" value="eait" />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				○授業名(30文字以内)<br />
				<input type="text" id="classNameText" name="classNameText" size="10" value="{%$cname%}" /><input type="submit" value="追加" />
			</form>
		</div><!--/#changeSchedule-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->

{%include file="school/common/footer.phtml" footAd=1 %}