{%include file="school/common/header.phtml" headAd=1 %}
<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="changeSchedule">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#b7cb6d;">時間割編集</div>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
			<tr>
				<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
					<div class="dayOfweek" style="text-align:center;"><img src="{%$staticUrl%}/apps/school/mobile/img/{%$wdayImage%}.gif" width="218" height="20" /></div>
					<div class="nav" style="color:#ffffff;text-align:center;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /><br />
						{% if $wday > 0 %}
							{% if $wday == 1 %}
								←[*]<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=6"|mixiurl %}' style="color:#ffffff;" accesskey="*"><span style="color:#ffffff;">前日</span></a>
							{% else %}
								←[*]<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=`$wday-1`"|mixiurl %}' style="color:#ffffff;" accesskey="*"><span style="color:#ffffff;">前日</span></a>
							{% /if %}
							{% if $wday == 6 %}
								<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=1"|mixiurl %}' style="color:#ffffff;" accesskey="#"><span style="color:#ffffff;">翌日</span></a>[#]→
							{% else %}
								<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=`$wday+1`"|mixiurl %}' style="color:#ffffff;" accesskey="#"><span style="color:#ffffff;">翌日</span></a>[#]→
							{% /if %}
						{% /if %}<br />
					</div><!--/.nav-->
					{% foreach from=$mineSchedule item=data key=key %}
						<div class="section">
							<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /><br />
							{%$data.c_name|escape%}<br />
							{%if $data.model == 1 %}
								<div style="text-align:right;"><a href='{% "$baseUrl/mobile/school/classnameadd?CF_wday=`$wday`&CF_part=`$key+1`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">授業追加</span></a></div>
							{%elseif $data.model == 2 %}
								<div style="text-align:right;"><a href='{% "$baseUrl/mobile/school/scheduleedit?CF_wday=`$wday`&CF_part=`$key+1`&CF_cid=`$data.cid`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">授業変更</span></a> <a href='{% "$baseUrl/mobile/school/scheduleaddfinish?CF_wday=`$wday`&CF_part=`$key+1`&CF_cid=`$data.cid`&CF_action=delschedule"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">授業なし</span></a></div>
							{%else%}
								<div style="text-align:right;"><a href='{% "$baseUrl/mobile/school/classnameadd?CF_wday=`$wday`&CF_part=`$key+1`"|mixiurl %}' style="color:#ffffff;"><span style="color:#ffffff;">授業追加</span></a></div>
							{%/if%}
							<div class="line" style="background:#3e4022;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
						</div><!--/.section-->
					{% /foreach %}
					<div class="nav" style="color:#ffffff;text-align:center;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="2" /><br />
						{% if $wday > 0 %}
							{% if $wday == 1 %}
								←[*]<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=6"|mixiurl %}' style="color:#ffffff;" accesskey="*"><span style="color:#ffffff;">前日</span></a>
							{% else %}
								←[*]<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=`$wday-1`"|mixiurl %}' style="color:#ffffff;" accesskey="*"><span style="color:#ffffff;">前日</span></a>
							{% /if %}
							{% if $wday == 6 %}
								<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=1"|mixiurl %}' style="color:#ffffff;" accesskey="#"><span style="color:#ffffff;">翌日</span></a>[#]→
							{% else %}
								<a href='{% "$baseUrl/mobile/school/schedule?CF_wday=`$wday+1`"|mixiurl %}' style="color:#ffffff;" accesskey="#"><span style="color:#ffffff;">翌日</span></a>[#]→
							{% /if %}
						{% /if %}<br />
					</div><!--/.nav-->
				</div></td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#b7cb6d;">時間割一括削除</div>
		<div class="description">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			作成済の時間割をﾘｾｯﾄ(一括削除)する場合は､以下の[時間割を一括削除]を押してください｡<br />
		</div><!--/.description-->
		<form method="post" action='{% "$baseUrl/mobile/school/schedulereset"|mixiurl %}'>
			<div class="btn" style="text-align:center;">
				<input type="hidden" name="CF_step" value="start" />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<input type="submit" value=" 時間割を一括削除 " />
			</div><!--/.btn-->
		</form>
	</div><!--/#changeSchedule-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}