{% if $step=="start" %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changeTime">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 時限設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割の授業1回あたりの時間と､各開始時間が設定できます｡
					{% if $errMsg %}
					<div class="errorMsg" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{%emoji code="F9DC"%}入力ｴﾗｰ<br />
						{%$errMsg|nl2br%}<br />
					</div><!--/.errorMsg-->
					{% /if %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.description-->
				<form method="post" action='{% "$baseUrl/mobile/school/timepartset"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="confirm">
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○授業1回の時間(共通)<br />
						<select name="selPartMinutes">{% html_options options=$aryPartMinutes selected=$lstTimepart.0.part_minutes %}</select>
						<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.section-->
					{% foreach name=timepartlist from=$lstTimepart item=tdata key=key %}
					{% if $key<14 %}
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○{%$tdata.part%}時限開始時刻<br />
						<select name="selStartHour{%$key+1%}">
							{% if 1==$tdata.is_hide %}
								{% if $tdata.ary_fix_hour_option %}{% html_options options=$tdata.ary_fix_hour_option %}{% else %}{% html_options options=$aryHourNull %}{% /if %}
							{% else %}
								{% html_options options=$aryHour selected=$tdata.start_h %}
							{% /if %}
						</select>
						<select name="selStartMinute{%$key+1%}">
							{% if 1==$tdata.is_hide %}
								{% if $tdata.ary_fix_minute_option %}{% html_options options=$tdata.ary_fix_minute_option %}{% else %}{% html_options options=$aryMinuteNull %}{% /if %}
							{% else %}
								{% html_options options=$aryMinute selected=$tdata.start_m %}
							{% /if %}
						</select>
						{% if 0==$tdata.has_class %}<div style="text-align:right;"><input type="checkbox" name="chkHide{%$key+1%}" value="{%$tdata.part%}" {% if 1==$tdata.is_hide %}checked="checked"{% /if %} />{%$tdata.part%}限は全日授業なし</div>{% /if %}
						<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.section-->
					{% /if %}
					{% /foreach %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 確 認 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/home"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/#changeTime-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step=="confirm" %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changeTime">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 時限設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					入力内容を確認し､[設定]を押してください｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.description-->
				<form method="post" action='{% "$baseUrl/mobile/school/timepartset"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="complete" />
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○授業1回の時間(共通)<br />
						<input type="hidden" id="classTime" name="classTime" value="90" />
						{%$cfmTimepart.0.part_minutes%}分<br />
						<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.section-->

					{% foreach name=timepartconfirm from=$cfmTimepart item=tdata %}
					{% if $tdata.is_hide==0 %}
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○{%$tdata.part%}時限開始時刻<br />
						{%$tdata.start_h%}時{%$tdata.start_m%}分～<br />
						<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.section-->
					{% /if %}
					{% /foreach %}

					{% if $lstChkPart %}
					<div class="section">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○全日授業なし<br />
						{% foreach from=$lstChkPart item=pdata %}{%$pdata%}限 {% /foreach %} <br />
						<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					</div><!--/.section-->
					{% /if %}
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 設 定 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/timepartset"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 修 正 " />
					</div><!--/.btn-->
				</form>
			</div><!--/#changeTime-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step=="complete" %}

	{%include file="school/common/header.phtml" %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="changeTime">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">時間割 時限設定</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					時間割の時限設定を変更しました｡
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/sflash?CF_uid=`$mineInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$mineInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>時間割を見る</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/privacyset"|mixiurl %}'>時間割 ﾌﾟﾗｲﾊﾞｼｰ設定</a><br />
				</div><!--/.footlink-->
			</div><!--/#changeTime-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}