{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="classInfo">
			{%include file="school/common/headline.phtml"%}
		</div><!--/#classInfo-->
		<div id="classTopics">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#b7cb6d;">この授業に関するQ&amp;A</div>
			{% if $topicList %}
				<div class="count">
					{%$topicCount%}件中 {%$startNm%}-{%$endNm%}件<br />
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.count-->
				<div class="list">
					{%foreach from=$topicList item=rowdata key=key%}
						<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
							<span style="color:#a35625;">[{% $rowdata.create_time|date_format:"%y/%m/%d %H:%M" %}]</span><br />
							<a href='{% "$baseUrl/mobile/school/topic?CF_tid=`$rowdata.tid`&CF_cid=`$rowdata.cid`"|mixiurl %}'>{%$rowdata.title%}({%$rowdata.comment_count%})</a><br />
						</div><!--/.section-->
					{%/foreach%}
				</div><!--/.list-->
				{%include file="school/common/pager.phtml"%}
			{% else %}
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					まだ何もありません｡{%$classInfo.name|escape%}の攻略法やｱﾄﾞﾊﾞｲｽなど､授業Q&amp;Aでﾅﾝﾃﾞﾓ聞いてみよう!<br />
				</div><!--/.description-->
			{% /if %}
				<div class="footlink">
					<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
					{%emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/topicadd?CF_cid=`$classInfo.cid`"|mixiurl %}'>授業Q&amp;Aで質問する</a><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>履修中授業のQ&amp;A一覧</a><br />
				</div><!--/.footlink-->
		</div><!--/#classTopics-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}
