{%if $step=="start"%}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">授業Q&amp;Aで質問する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					｢{%$classInfo.name|escape%}｣に関する質問を投稿します｡ﾀｲﾄﾙ･質問内容を入力し､[確認]を押してください｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					※質問は匿名で投稿されますが､公序良俗に反する内容の場合､運営者によって削除されることがあります｡あらかじめご了承ください｡<br />
					{% if $errMsg %}
					<div class="errorMsg" style="color:#cc0000;">
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						{%emoji code="F9DC"%}入力ｴﾗｰ<br />
						{%$errMsg|nl2br%}
					</div><!--/.errorMsg-->
					{% /if %}
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/topicadd"|mixiurl %}'>
						<input type="hidden" name="CF_step" value="confirm" />
						<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
						○ﾀｲﾄﾙ<br />
						<input type="text" name="txtTitle" value="{%$topicInfo.title%}" maxlength="30" /><br />
						<div style="text-align:right;">※全角30文字以内</div>
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○質問内容<br />
						<textarea name="txtIntroduce" rows="3">{%$topicInfo.introduce|escape|unescape_emoji%}</textarea>
						<div style="text-align:right;">※全角300文字以内</div>
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 確 認 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" ｷｬﾝｾﾙ " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topiclist?CF_cid=`$classInfo.cid`"|mixiurl %}'>この授業に関するQ&amp;A</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>履修中授業のQ&amp;A一覧</a><br />
				</div><!--/.footlink-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{%elseif $step=="confirm"%}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">授業Q&amp;Aで質問する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					入力内容を確認し､よろしければ[送信]を押してください｡<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					※質問は匿名で投稿されますが､公序良俗に反する内容の場合､運営者によって削除されることがあります｡あらかじめご了承ください｡<br />
				</div><!--/.description-->

				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/topicadd"|mixiurl %}'>
						<input type="hidden" name="CF_step" value="complete" />
						<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
						○ﾀｲﾄﾙ<br />
						{%$topicInfo.title|escape%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						○質問内容<br />
						{%$topicInfo.introduce|escape|nl2br|unescape_emoji%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 送 信 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/topicadd"|mixiurl %}'>
						<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 修 正 " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{%elseif $step=="complete"%}

	{%include file="school/common/header.phtml" %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">授業Q&amp;Aで質問する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					質問の送信が完了しました｡<br />
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topic?CF_tid=`$topicInfo.tid`&CF_cid=`$classInfo.cid`"|mixiurl %}'>質問したQ&amp;A</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topiclist?CF_cid=`$classInfo.cid`"|mixiurl %}'>この授業のQ&amp;A一覧</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>履修中授業のQ&amp;A一覧</a><br />
				</div><!--/.footlink-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" %}

{%/if%}