{%if $step == 'start' %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業に関するQ&A</div>
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
					<tr>
						<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
							Q.{%$tInfo.title|escape%}<br />
							<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
							{%$tInfo.introduce|escape|unescape_emoji%}<br />
							<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
							<div style="text-align:right;">回答:{%$tInfo.comment_count%} ｱｸｾｽ:{%$tInfo.visit_count%}</div>
							</div></td>
					</tr>
				</table>
				<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					この質問への回答を入力し､[確認]を押してください｡<br />
					{% if $errMsg %}
						<div class="errorMsg" style="color:#cc0000;">
							<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
							{% emoji code="F9DC"%}入力ｴﾗｰ<br />
							{% $errMsg|nl2br %}<br />
						</div><!--/.errorMsg-->
					{% /if %}
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/topiccommentadd"|mixiurl %}'>
						○回答ｺﾒﾝﾄ<br />
						<input type="hidden" name="CF_tid" value="{%$tid%}" />
						<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
						<input type="hidden" name="CF_step" value="confirm" />
						<textarea name="classTopicComment" rows="3">{%$comment|escape|unescape_emoji%}</textarea>
						<div style="text-align:right;">※全角300文字以内</div>
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" 確 認 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/topic"|mixiurl %}'>
						<input type="hidden" name="CF_tid" value="{%$tid%}" />
						<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
						<div class="btn" style="text-align:center;">
							<input type="submit" value=" ｷｬﾝｾﾙ " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topiclist?CF_cid=`$classInfo.cid`"|mixiurl %}'>この授業に関するQ&A</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>履修中授業のQ&A一覧</a><br />
				</div><!--/.footlink-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step == 'confirm' %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業に関するQ&A</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					入力内容を確認し､よろしければ[送信]を押してください｡<br />
				</div><!--/.description-->
				<div class="inputElement">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<form method="post" action='{% "$baseUrl/mobile/school/topiccommentadd"|mixiurl %}'>
						○回答ｺﾒﾝﾄ<br />
						{%$comment|escape|unescape_emoji%}<br />
						<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
						<div class="btn" style="text-align:center;">
							<input type="hidden" name="CF_tid" value="{%$tid%}" />
							<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
							<input type="hidden" name="CF_step" value="finish" />
							<input type="hidden" id="classTopicComment" name="classTopicComment" value="{%$comment%}" />
							<input type="submit" value=" 送 信 " />
						</div><!--/.btn-->
					</form>
					<form method="post" action='{% "$baseUrl/mobile/school/topiccommentadd"|mixiurl %}'>
						<div class="btn" style="text-align:center;">
							<input type="hidden" id="classTopicComment" name="classTopicComment" value="{%$comment%}" />
							<input type="hidden" name="CF_tid" value="{%$tid%}" />
							<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
							<input type="submit" value=" 修 正 " />
						</div><!--/.btn-->
					</form>
				</div><!--/.inputElement-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0 %}

{% elseif $step == 'finish' %}

	{%include file="school/common/header.phtml"%}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業に関するQ&A</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					回答ｺﾒﾝﾄの送信が完了しました｡<br />
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topic?CF_cid=`$classInfo.cid`&CF_tid=`$tid`"|mixiurl %}'>回答した質問を確認</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topiclist?CF_cid=`$classInfo.cid`"|mixiurl %}'>この授業のQ&A一覧</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/newesttopiclist"|mixiurl %}'>履修中授業のQ&A一覧</a><br />
				</div><!--/.footlink-->
			</div><!--/#classTopicsAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}
