{%include file="school/common/header.phtml" headAd=1 %}
<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
	<div id="classInfo">
		{%include file="school/common/headline.phtml"%}
	</div><!--/#classInfo-->
	<div id="classTopics">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="headline" style="background:#b7cb6d;">この授業に関するQ&A</div>
		<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
		<table width="228" cellpadding="2" cellspacing="3" border="0" align="center" style="background:#a35625;text-align:center;">
			<tr>
				<td style="background:#262713;text-align:left;"><div style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">
					Q.{%$tInfo.title|escape%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					{%$tInfo.introduce|escape|unescape_emoji%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
					<div style="text-align:right;">回答:{%$tInfo.comment_count%} ｱｸｾｽ:{%$tInfo.visit_count%}</div>
					</div></td>
			</tr>
		</table>
		<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
		<div class="info" style="text-align:center;">
			{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/topiccommentadd?CF_tid=`$tid`&CF_cid=`$classInfo.cid`&CF_step=start"|mixiurl %}'>この質問に回答する!</a><br />
		</div><!--/.info-->
		<img src="http://mm.mixi.net/img/dot0.gif" width="3" height="3" /><br />
		{%if $pager.count %}
			<div class="count">
				全回答{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件<br />
				<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			</div><!--/.count-->
			<div class="list">
				{% foreach from=$topicLst item=data key=key %}
					<div class="section" style="background:#{% if ($key%2) == 0 %}fffddb{%else%}fcf5cc{%/if%};">
						<a id="comment{%$key%}" name="comment{%$key%}"></a>
						<a href="#comment{%$key+1%}" style="color:#a35625;"><span style="color:#a35625;">▼</span></a>
						<span style="color:#a35625;">[{%$data.no%}] {%$data.format_data%}</span><br />
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td style="width:44px;text-align:center;"><img src="{%$data.miniThumbnailUrl%}" /></td>
								<td><div style="{% if $ua==1 %}font-size:x-small;{% /if %}"><a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$data.uid`"|mixiurl %}'>{%$data.displayName%}</a><br />
									<span style="color:#cccc00;">★</span><span style="color:#a35625;">{%$data.userInfo.star_count%}</span><span style="color:#cccc00;">★</span></div></td>
							</tr>
						</table>
						<div class="comment">
							{%$data.comment|escape|unescape_emoji%}
							<div style="text-align:right;">{%if $data.uid == $miniInfo.uid %}{%if $data.good_count >= 1 %}[<a href='{% "$baseUrl/mobile/school/topiccommentdel?CF_commentid=`$data.comment_id`&CF_cid=`$classInfo.cid`&CF_tid=`$tid`&CF_step=error"|mixiurl %}' style="color:#333333;"><span style="color:#333333;">削除</span></a>]{%else%}[<a href='{% "$baseUrl/mobile/school/topiccommentdel?CF_commentid=`$data.comment_id`&CF_cid=`$classInfo.cid`&CF_tid=`$tid`"|mixiurl %}' style="color:#333333;"><span style="color:#333333;">削除</span></a>]{%/if%}[{%emoji code="F9CC"%}<span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})]</span>{%else%}[{%emoji code="F9CC"%}{%if $data.isAssess %}<span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})]</span>{%else%}<a href='{% "$baseUrl/mobile/school/classtopicgoodfinish?CF_cid=`$classInfo.cid`&CF_commentid=`$data.comment_id`&CF_tid=`$tid`"|mixiurl %}' style="color:#333333;"><span style="color:#333333;">ｲｲﾈ!({%$data.good_count%})</span></a>]{%/if%}{%/if%}</div>
						</div><!--/.comment-->
					</div><!--/.section-->
				{% /foreach %}
			</div><!--/.list-->
			<a id="comment{%$topicLst|@count%}" name="comment{%$topicLst|@count%}"></a>
			{%include file="school/common/pager.phtml"%}
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/topiccommentadd?CF_tid=`$tid`&CF_cid=`$classInfo.cid`&CF_step=start"|mixiurl %}'>この質問に回答する</a><br />
				{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/topicadd?CF_cid=`$classInfo.cid`"|mixiurl %}'>授業Q&Aで質問する</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topic?CF_tid=`$tid`&CF_cid=`$classInfo.cid`&CF_orderby=good_count"|mixiurl %}'>ｲｲﾈ!の多い順に読む</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/topic?CF_tid=`$tid`&CF_cid=`$classInfo.cid`&CF_orderby=create_time"|mixiurl %}'>最初から読む</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name%}ﾄｯﾌﾟ</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/mynewesttopiclist"|mixiurl %}'>履修中授業のQ&A一覧</a><br />
			</div><!--/.footlink-->
		{%else%}
			<div class="null" style="text-align:center;">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				まだ回答がありません｡<br />
			</div><!--/.null-->
			<div class="footlink">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				{% emoji code="F9BE"%}<a href='{% "$baseUrl/mobile/school/topicadd?CF_cid=`$classInfo.cid`"|mixiurl %}'>授業Q&Aで質問する</a><br />
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
				<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/mynewesttopiclist"|mixiurl %}'>履修中授業のQ&A一覧</a><br />
			</div><!--/.footlink-->
		{%/if%}
	</div><!--/#classTopics-->
	{%include file="school/common/menu.phtml"%}
</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}