{%include file="school/common/header.phtml" headAd=1 %}
	<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
		<div id="recentAccess">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<div class="headline" style="background:#ffa0fe;">ﾌﾟﾛﾌ ｱｸｾｽ履歴({%$cntVisitFootAccess%})</div>
			{% if $listVisitFoot %}
				<div class="count">
					最新{%$pager.count%}件中 {%$startNm%}-{%$endNm%}件 <span style="color:#777777;">…ﾏｲﾐｸ</span><br />
					<div class="line" style="background:#ffa0fe;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
				</div><!--/.count-->
				<div class="list">
				{% foreach name=footlist from=$listVisitFoot item=fdata key=key %}
					<div class="section" style="background:{% if $key%2==0 %}#fffddb{% else %}#fcf5cc{% /if %};">
						{% emoji code="F995"%}<a href='{% "$baseUrl/mobile/school/profile?CF_uid=`$fdata.uid`"|mixiurl %}'>{%$fdata.displayName%}</a>{% if $fdata.is_friend=="1"%}{%emoji code="F99F"%}{% /if %}<br />
					</div><!--/.section-->
				{% /foreach %}
				</div><!--/.list-->
				{%include file="school/common/pager.phtml"%}
			{% else %}
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					まだ誰もｱﾅﾀのﾌﾟﾛﾌにｱｸｾｽしていません｡<br />
				</div><!--/.description-->
			{% /if %}
		</div><!--/#recentAccess-->
		{%include file="school/common/menu.phtml"%}
	</div><!--/#container-->
{%include file="school/common/footer.phtml" footAd=1 %}