{% if $step=="start" %}

	{%include file="school/common/header.phtml" headAd=1 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classVoteAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業を評価する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%$classInfo.name|escape%}を評価します｡評価内容を選択し､[確認]を押してください｡<br />
					{% if $errMsg %}
						<div class="errorMsg" style="color:#cc0000;">
							<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
							{%emoji code="F9DC"%}入力ｴﾗｰ<br />
							{%$errMsg|nl2br%}
						</div><!--/.errorMsg-->
					{% /if %}
				</div><!--/.description-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/voteadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="confirm" />
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					内　容:<select name="selContent" style="vertical-align:middle;">{% html_options options=$aryContent selected=$myVote.vote_content %}</select><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					難易度:<select name="selDifficult" style="vertical-align:middle;">{% html_options options=$aryDifficult selected=$myVote.vote_difficult %}</select><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					宿　題:<select name="selWork" style="vertical-align:middle;">{% html_options options=$aryWork selected=$myVote.vote_work %}</select><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					試　験:<select name="selTest" style="vertical-align:middle;">{% html_options options=$aryTest selected=$myVote.vote_test %}</select><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					出　席:<select name="selAttend" style="vertical-align:middle;">{% html_options options=$aryAttend selected=$myVote.vote_attend %}</select><br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 確 認  " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" ｷｬﾝｾﾙ " />
					</div><!--/.btn-->
				</form>
			</div><!--/#classVoteAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=1 %}

{% elseif $step=="confirm" %}

	{%include file="school/common/header.phtml" headAd=0 %}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classVoteAdd">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業を評価する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					入力内容を確認し､よろしければ[送信]を押してください｡<br />
				</div><!--/.description-->
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<form method="post" action='{% "$baseUrl/mobile/school/voteadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="complete" />
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					内　容:{%$voteContent%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					難易度:{%$voteDifficult%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					宿　題:{%$voteWork%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					試　験:{%$voteTest%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					出　席:{%$voteAttend%}<br />
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 送 信 " />
					</div><!--/.btn-->
				</form>
				<form method="post" action='{% "$baseUrl/mobile/school/voteadd"|mixiurl %}'>
					<input type="hidden" name="CF_step" value="start" />
					<input type="hidden" name="CF_cid" value="{%$classInfo.cid%}" />
					<div class="btn" style="text-align:center;">
						<input type="submit" value=" 修 正 " />
					</div><!--/.btn-->
				</form>
			</div><!--/#classVoteAdd-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml" footAd=0%}

{% elseif $step=="complete" %}

	{%include file="school/common/header.phtml"%}
		<div id="container" style="{% if $ua==1 %}font-size:x-small;{% /if %}">
			<div id="classInfo">
				{%include file="school/common/headline.phtml"%}
			</div><!--/#classInfo-->
			<div id="classTopicsDel">
				<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
				<div class="headline" style="background:#b7cb6d;">この授業を評価する</div>
				<div class="description">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					{%$classInfo.name|escape%}への評価が完了しました｡<br />
				</div><!--/.description-->
				{%include file="school/common/ad_complete.phtml"%}
				<div class="footlink">
					<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
					<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/class?CF_cid=`$classInfo.cid`"|mixiurl %}'>{%$classInfo.name|escape%}ﾄｯﾌﾟ</a><br />
				</div><!--/.footlink-->
			</div><!--/#classTopicsDel-->
			{%include file="school/common/menu.phtml"%}
		</div><!--/#container-->
	{%include file="school/common/footer.phtml"%}

{% /if %}
