{%include file="millionminds/common/header.phtml"%}

<body>
    {%include file="topad.phtml"%}
    <script type="text/javascript" src="{%$staticUrl%}/apps/millionminds/js/index.js?{%$version.js%}"></script>

	<div id="container">
        {%include file="millionminds/common/hdr.phtml"%}

		<ul id="gnav">
			<li class="top"><a class="active">MillionMindsトップ</a></li>
			<li class="profile"><a href="{%$baseUrl%}/millionminds/profile">プロフィール</a></li>
			<li class="log"><a href="{%$baseUrl%}/millionminds/log">あしあと</a></li>
			<li class="archive"><a href="{%$baseUrl%}/millionminds/archive">アーカイブ</a></li>
			<li class="add"><a href="{%$baseUrl%}/Millionminds/newquestion">クエスチョン作成</a></li>
			<li class="help"><a href="{%$baseUrl%}/millionminds/help">ヘルプ</a></li>
			<li class="invite"><a href="javascript:void(0)" onclick="invite();">友達を招待</a></li>
		</ul><!--/#grav-->
        
		<div id="content">
		
			<div id="mainColumn">
			
			    {% if $beginNature %}
			    <div id="first">
					<p><a href="{%$baseUrl%}/millionminds/nature">性格診断で本当のアナタを知る</a></p>
				</div><!--/#first-->
				{% /if %}
				
				{%include file="millionminds/common/nature.phtml"%}
				{%include file="millionminds/common/answer.phtml"%}

				<div class="article" id="divPopular">
					<h2 class="popular">人気のクエスチョン</h2>
					<ul class="cat" id="ulPopular">
						<li class="all"><a href="javascript:void(0)" class="active" onclick="jQuery.top.getQuestion(0,1);">すべて</a></li>
						<li class="character"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(1,1)">性格診断</a></li>
						<li class="politics"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(2,1)">政治・経済</a></li>
						<li class="life"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(3,1);">社会生活</a></li>
						<li class="entertainment"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(4,1);">芸能・スポーツ</a></li>
						<li class="hobby"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(5,1);">趣味・その他</a></li>
					</ul><!--/.cat-->
					{% if $popularQuestion %}
					<table width="100%" cellpadding="0" cellspacing="0" border="0" class="list">
						<tr>
							<th class="title"></th>
							<th class="count descend"><a href="{%$baseUrl%}/millionminds/archive?field=1">回答数▼</a></th>
							<th class="date ascend"><a href="{%$baseUrl%}/millionminds/archive?field=2">作成日▼</a></th>
						</tr>
						{% foreach from=$popularQuestion item=data%}
						<tr class="section">
							<td class="title stringCut"><a href="{%$baseUrl%}/millionminds/question?qid={%$data.qid%}" class="ico">{%$data.question|escape%}</a></td>
							<td class="count">{%$data.answer|escape%}</td>
							<td class="date">{%$data.create_time%}</td>
						</tr><!--/.section-->
						{% /foreach %}
					</table>
					<p class="more">⇒<a href="{%$baseUrl%}/millionminds/archive?field=1">人気のクエスチョンをもっと見る</a></p>
					{% else %}
					<p class="null"><a href="{%$baseUrl%}/millionminds/newquestion">クエスチョンを作成する</a></p>
					{% /if %}
				</div><!--/.article-->

				<div class="article" id="divRecent">
					<h2 class="recent">新着のクエスチョン</h2>
					<ul class="cat">
						<li class="all"><a href="javascript:void(0)" class="active" onclick="jQuery.top.getQuestion(0,2);">すべて</a></li>
						<li class="character"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(1,2);">性格診断</a></li>
						<li class="politics"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(2,2);">政治・経済</a></li>
						<li class="life"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(3,2);">社会生活</a></li>
						<li class="entertainment"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(4,2);">芸能・スポーツ</a></li>
						<li class="hobby"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(5,2);">趣味・その他</a></li>
					</ul><!--/.cat-->
					{% if $newQuestion %}
					<table width="100%" cellpadding="0" cellspacing="0" border="0" class="list">
						<tr>
							<th class="title"></th>
							<th class="count descend"><a href="{%$baseUrl%}/millionminds/archive?field=1">回答数▼</a></th>
							<th class="date ascend"><a href="{%$baseUrl%}/millionminds/archive?field=2">作成日▼</a></th>
						</tr>
						{% foreach from=$newQuestion item=data%}
						<tr class="section">
							<td class="title stringCut"><a href="{%$baseUrl%}/millionminds/question?qid={%$data.qid%}" class="ico">{%$data.question|escape%}</a></td>
							<td class="count">{%$data.answer|escape%}</td>
							<td class="date">{%$data.create_time%}</td>
						</tr><!--/.section-->
						{% /foreach %}
					</table>
					<p class="more">⇒<a href="{%$baseUrl%}/millionminds/archive?field=2">新着のクエスチョンをもっと見る</a></p>
					{% else %}
					<p class="null"><a href="{%$baseUrl%}/millionminds/newquestion">クエスチョンを作成する</a></p>
					{% /if %}					
				</div><!--/.article-->

			</div><!--/#mainColumn-->

			<div id="subColumn">
				{%include file="millionminds/common/ad.phtml"%}
				{% if $friendQuestion %}
				<div class="article">
					<h3 class="friend">マイミクが回答したクエスチョン</h3>
					<div class="inner">
						<ul>
						    {% foreach from=$friendQuestion item=data%}
							<li style="width:230px"><a href="{%$baseUrl%}/millionminds/question?qid={%$data.qid%}" class="ico stringCut">{%$data.question|escape%}</a></li>
							{% /foreach %}
						</ul>
						<p class="more">⇒<a href="{%$baseUrl%}/millionminds/archive?field=1">もっと見る</a></p>
					</div><!--/.inner-->
				</div><!--/.article-->
				{% /if %}
			</div><!--/#subColumn-->

		</div><!--/#content-->

{%include file="millionminds/common/footer.phtml"%}
