{%include file="millionminds/common/header.phtml"%}

<body>
    {%include file="topad.phtml"%}
    <script type="text/javascript" src="{% $staticUrl %}/apps/millionminds/js/index.js?{%$version.js%}"></script>
    <script type="text/javascript" language="javascript">
    $().ready(function() 
    {    
        $("#timerImg").attr("src","{% $staticUrl %}/apps/millionminds/img/timer.gif");
    });
    </script>
    <div id="container">
    {%include file="millionminds/common/hdr.phtml"%}

		<ul id="gnav">
			<li class="top"><a href="{%$baseUrl%}/millionminds/index">MillionMindsトップ</a></li>
			<li class="profile"><a href="{%$baseUrl%}/millionminds/profile">プロフィール</a></li>
			<li class="log"><a href="{%$baseUrl%}/millionminds/log">あしあと</a></li>
			<li class="archive"><a href="{%$baseUrl%}/millionminds/archive">アーカイブ</a></li>
			<li class="add"><a href="{%$baseUrl%}/millionminds/newquestion"">クエスチョン作成</a></li>
			<li class="help"><a href="{%$baseUrl%}/millionminds/help">ヘルプ</a></li>
			<li class="invite"><a href="javascript:void(0)" onclick="invite();">友達を招待</a></li>
		</ul><!--/#grav-->

		<div id="content">
		
			<div id="mainColumn">
                
				<div id="q">
					{% if $qst.public_type eq 1 %}<h3 class="default">相性診断クエスチョン</h3>{% elseif $qst.public_type eq 2 %}<h3 class="ltd_i">マイミク限定クエスチョン</h3>{% else %}<h3 class="ltd_ii">マイミクのマイミクまで限定クエスチョン</h3>{% /if %}
					<table width="100%" cellpadding="0" cellspacing="0" border="0" class="q">
						<tr>
							{% if $qst.nickname_auth eq 1 %}<td class="author"><span><a href="/millionminds/profile/uid/{% $qst.uid %}" style="background-image: url( {% $qst.thumbnailUrl%} );" title="{% $qst.displayName %}">{% $qst.displayName %}</a></span></td>{% else %}<td class="author"><span class="secret">匿名希望</span></td>{% /if %}
							<td class="content">
							    <h2 style="width:480px;" class="stringCut">{% $qst.question|escape %}</h2>
								<dl>
									<dt>作成者：</dt>
									{% if $qst.nickname_auth eq 1 %}<dd><a href="/millionminds/profile/uid/{% $qst.uid %}">{% $qst.displayName %}</a>さん</dd>{% else %}<dd>匿名希望さん</dd>{% /if %}
									<dt>カテゴリー：</dt>
									<dd><a>{% $qst.category %}</a></dd>
									<dt>回答数：</dt>
									<dd>{% $qst.answer %}</dd>
								</dl></td>
						</tr>
					</table><!--/.q-->
					<p class="timer"><img width="580" height="25" alt="" id="timerImg"/></p>
					<ul class="select">
    					{% foreach from=$asw item=data %}
    					   <li><a href="{%$baseUrl%}/millionminds/{% if $qst.qid < 51 %}nature{% else %}answer{% /if %}?qid={%$qst.qid%}&aid={% $data.aid %}"><strong>{% $data.answer|escape %}</strong></a></li>
    					{% /foreach %}
					</ul><!--/.select-->
					<h3 class="answers">このクエスチョンに回答した人</h3>
					<ul class="answers">
					    {% if $hasList eq 0 %}
					    そのクエスチョンを回答したユーザーはない
					    <!--
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						<li><span><a href="#" style="background-image: url(http://profile.img.mixi.jp/photo/member/29/35/2522935_151773150s.jpg);" title="jun★Spark">jun★Spark</a></span></li>
						-->
						{% else %}
						{% foreach from=$listInfo item=user %}
    					   <li><span><a href="/millionminds/profile/uid/{% $user.uid %}" style="background-image: url( {% $user.thumbnailUrl %} );" title="{% $user.displayName %}">{% $user.displayName %}</a></span></li>
    					{% /foreach %}
    					{% /if %}
					</ul>
				</div><!--/#q-->
                
				<div class="article" id="divPopular">
					<h2 class="popular">人気のクエスチョン</h2>
					<ul class="cat" id="ulPopular">
						<li class="all"><a href="javascript:void(0)" class="active" onclick="jQuery.top.getQuestion(0,1);">すべて</a></li>
						<li class="character"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(1,1)">性格診断</a></li>
						<li class="politics"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(2,1)">政治・経済</a></li>
						<li class="life"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(3,1);">社会生活</a></li>
						<li class="entertainment"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(4,1);">芸能・スポーツ</a></li>
						<li class="hobby"><a href="javascript:void(0)" onclick="jQuery.top.getQuestion(5,1);">趣味・その他</a></li>
					</ul><!--/.cat-->
					{% if $popularQuestion %}
					<table width="100%" cellpadding="0" cellspacing="0" border="0" class="list">
						<tr>
							<th class="title"></th>
							<th class="count descend"><a href="{%$baseUrl%}/millionminds/archive?field=1">回答数▼</a></th>
							<th class="date ascend"><a href="{%$baseUrl%}/millionminds/archive?field=2">作成日▼</a></th>
						</tr>
						{% foreach from=$popularQuestion item=data%}
						<tr class="section">
							<td class="title stringCut"><a href="{%$baseUrl%}/millionminds/question?qid={%$data.qid%}" class="ico">{%$data.question|escape%}</a></td>
							<td class="count">{%$data.answer%}</td>
							<td class="date">{%$data.create_time%}</td>
						</tr><!--/.section-->
						{% /foreach %}
					</table>
					<p class="more">⇒<a href="{%$baseUrl%}/millionminds/archive?field=1">人気のクエスチョンをもっと見る</a></p>
					{% else %}
					<p class="null"><a href="{%$baseUrl%}/millionminds/newquestion">クエスチョンを作成する</a></p>
					{% /if %}
				</div><!--/.article-->
				
			</div><!--/#mainColumn-->

{%include file="millionminds/common/subColumn.phtml"%}

		</div><!--/#content-->
		
{%include file="millionminds/common/footer.phtml"%}