{%include file="header.phtml"%}

<body id="admin">
	<h1>OPENSOCIAL APPS ADMIN</h1>
	{%include file="nav.phtml"%}

	<div id="container">
		<h2>みんなの時間割 - コンテンツ監視</h2>
		<div id="appsAdmin">
			<ul class="nav">
				<li><span>トップページ</span></li>
				<!-- <li><a href="{%$baseUrl%}/school/forbidword">禁止語の設定</a></li>
				<li><a href="{%$baseUrl%}/school/dealstat">処理の集計</a></li> -->
			</ul><!--/.nav-->
			<table width="100%" cellpadding="0" cellspacing="0" border="0" id="dataGrid">
				<thead>
					<tr class="head">
						<th>監視項目</th>
						<th>カテゴリ別コンテンツ一覧</th>
					</tr>
				</thead>
				<tbody>
					<tr class="a">
						<td>授業Q&A 質問・回答</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'topiccomment');return false;">［容疑({%$lstTopicComment.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'topiccomment');return false;">［未処理({%$lstTopicComment.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'topiccomment');return false;">［保留({%$lstTopicComment.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'topiccomment');return false;">［問題なし({%$lstTopicComment.3%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'topiccomment');return false;">［違反({%$lstTopicComment.5%})］</a></td>
					</tr>
					<tr class="b">
						<td>授業Q&A</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'topic');return false;">［容疑({%$lstTopic.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'topic');return false;">［未処理({%$lstTopic.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'topic');return false;">［保留({%$lstTopic.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'topic');return false;">［問題なし({%$lstTopic.3%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'topic');return false;">［違反({%$lstTopic.5%})］</a></td>
					</tr>
					<tr class="a">
						<td>教えて!プロフ 質問・ 回答</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'enquirycomment');return false;">［容疑({%$lstEnquiryComment.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'enquirycomment');return false;">［未処理({%$lstEnquiryComment.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'enquirycomment');return false;">［保留({%$lstEnquiryComment.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'enquirycomment');return false;">［問題なし({%$lstEnquiryComment.3%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'enquirycomment');return false;">［違反({%$lstEnquiryComment.5%})］</a></td>
					</tr>
					<tr class="b">
						<td>教えて!プロフ 質問・</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'enquiry');return false;">［容疑({%$lstEnquiry.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'enquiry');return false;">［未処理({%$lstEnquiry.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'enquiry');return false;">［保留({%$lstEnquiry.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'enquiry');return false;">［問題なし({%$lstEnquiry.3%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'enquiry');return false;">［違反({%$lstEnquiry.5%})］</a></td>
					</tr>
					<tr class="a">
						<td>授業共同編集・</td>
						<td><a href="javascript:void(0)" onclick="goPage(2,'classnote');return false;">［容疑({%$lstClassnote.2%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(1,'classnote');return false;">［未処理({%$lstClassnote.1%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(4,'classnote');return false;">［保留({%$lstClassnote.4%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(3,'classnote');return false;">［問題なし({%$lstClassnote.3%})］</a>
						    <a href="javascript:void(0)" onclick="goPage(5,'classnote');return false;">［違反({%$lstClassnote.5%})］</a></td>
					</tr>
				</tbody>
			</table><!--/#dataGrid-->
		</div><!--/#appsAdmin-->
		<form method="post" id="frmTop" name="frmTop">
			<input type="hidden" id="srhStatus" name="srhStatus" value="0" />
		</form>
	</div><!--/#container-->
	<script type="text/javascript" language="javascript">
        /**
         * search comment/title/des action
         * @param  integer status
         * @param  string page
         * @return void
         */
        function goPage(status, page) {
        	$('frmTop').action = UrlConfig.BaseUrl + '/aschool/watch' + page;
        	$('srhStatus').value = parseInt(status);
            $('frmTop').submit();
        }
	</script>

{%include file="footer.phtml"%}