<div id="error" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">みんなの時間割♪へようこそ!</div>
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		みんなの時間割は、大学生以上しか利用することが出来ません。
		<br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="color:#f58320;">⇒</span><a href='{% "select:school?callback=$baseUrl/mobile/school/callbackschool?forward=$baseUrl/mobile/school/error?CF_error=signupconfirm" %}' style="color:#003366;"><span style="color:#003366;">学校情報を送信する</span></a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#error-->
