<div id="error" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">みんなの時間割♪へようこそ!</div>
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		みんなの時間割♪は､同じ学校に通う現役学生を対象とした<span style="color:#cc0000;">大学生以上を対象とした学生限定ｱﾌﾟﾘ</span>です｡<br />
		<br />
		当ｱﾌﾟﾘを利用するには､登録している学校情報を送信する必要があります｡<br />
		<br />
		以下の点にご注意のうえ､在学中の学校を選んでください。<br />
		<br />
		ﾐｸｼｨで登録した学校情報を送信する際には､｢詳細選択欄｣でご利用の学校名をﾌﾟﾙﾀﾞｳﾝで選択した後､<span style="color:#cc0000;">｢学部学科、卒業年も選択する｣のﾁｪｯｸを解除した状態で選択</span>ﾎﾞﾀﾝをｸﾘｯｸしてください｡<br />
		<br />
		※<span style="color:#cc0000;">ﾁｪｯｸを解除せず登録すると､当ｱﾌﾟﾘ内で同級生と情報交換ができなくなります</span>のでご注意ください｡<br />
		<br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="color:#f58320;">⇒</span><a href='{% "select:school?callback=$baseUrl/mobile/school/callbackschool?forward=$baseUrl/mobile/school/error?CF_error=signupconfirm" %}' style="color:#003366;"><span style="color:#003366;">学校情報を送信する</span></a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#error-->
