<div id="error" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" />
	</div><!--/#bgImage-->
	{%include file="school/common/recomment.phtml"%}
	<img src="{%$staticUrl%}/apps/school/mobile/img/spacer.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">送信された学校情報ではご利用いただけません</div>
	<div class="description">
		<img src="{%$staticUrl%}/apps/school/mobile/img/spacer.gif" width="1" height="3" /><br />
		みんなの時間割♪は現在､在学中の大学生･大学院生･専門学校生を対象としたｱﾌﾟﾘです｡<br />
		誠に申し訳ございませんが､お客様の送信された学校情報では､ご利用いただけません｡<br />
		<img src="{%$staticUrl%}/apps/school/mobile/img/spacer.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="{%$staticUrl%}/apps/school/mobile/img/spacer.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" />
	</div><!--/#keyvisual-->
</div><!--/#error-->
