<div id="error" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">ご確認ください</div>
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		学校情報の送信時に｢詳細選択欄｣で学校名をﾌﾟﾙﾀﾞｳﾝで選択した後､<span style="color:#cc0000;">｢学部学科､卒業年も選択する｣のﾁｪｯｸﾎﾞｯｸｽを解除した状態で選択ﾎﾞﾀﾝをｸﾘｯｸしましたか?</span><br />
		<br />
		もし<br />
		<br />
		・｢学部学科､卒業年も選択する｣のﾁｪｯｸﾎﾞｯｸｽを解除せずに登録してしまった場合<br />
		<br />
		・｢同級生選択｣欄で『●●大学 ■■学部▲▲学科（yyyy年卒業）』を選択して登録してしまった場合<br />
		<br />
		当ｱﾌﾟﾘ内で､<span style="color:#cc0000;">同級生と情報交換ができなくなってしまいます｡</span><br />
		<br />
		もしも誤ってご登録された場合､変更時に登録した時間割ﾃﾞｰﾀを削除しなくてはならなくなりますため､ご注意ください｡<br />
		<br />
		なおご心配な場合は以下ﾘﾝｸより再度､学校情報を送信してください｡<br />
		<br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<span style="color:#f58320;">⇒</span><a href='{% "select:school?callback=$baseUrl/mobile/school/callbackschool?forward=$baseUrl/mobile/school/error?CF_error=signupconfirm" %}' style="color:#003366;"><span style="color:#003366;">学校情報を送信しなおす</span></a><br />
		<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/home"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">みんなの時間割♪ﾄｯﾌﾟ</span></a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#error-->
