<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja" id="mixiapps_admin">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta http-equiv="Cache-Control" content="no-cache" />
	<meta http-equiv="imagetoolbar" content="no" />
	<meta http-equiv="Content-Style-Type" content="text/css" />
	<meta http-equiv="Content-Script-Type" content="text/javascript" />
	<!--[if lt IE 7]><![endif]-->
	<script type="text/javascript" language="javascript" src="{%$staticUrl%}/cmn/js/prototype-1.6.0.2.js?{%$version.js%}"></script>
	<script type="text/javascript" language="javascript" src="{%$staticUrl%}/cmn/js/effects.js?{%$version.js%}"></script>
	<script type="text/javascript" language="javascript" src="{%$staticUrl%}/cmn/js/mixi.js?{%$version.js%}"></script>
	<script type="text/javascript" language="javascript" src="{%$staticUrl%}/cmn/js/common.js?{%$version.js%}"></script>
	<script type="text/javascript" language="javascript">
		var UrlConfig =  {
		    BaseUrl : '{%$baseUrl%}',
		    StaticUrl : '{%$staticUrl%}',
		    PhotoUrl : '{%$photoUrl%}'
		};
	</script>
	<link rel="stylesheet" href="{%$staticUrl%}/admin/css/admin.css?{%$version.css%}" type="text/css" media="all" />
	<title>{%$title%}</title>
	<link rel="shortcut icon" href="{%$staticUrl%}/favicon.ico" />
</head>