<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
{% if $ua==1 %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% else %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% /if %}
	<title>どきどきダイナマイトパニック - mixiｱﾌﾟﾘ</title>
	<style type="text/css">
		a:link{color:#ff9933;}
		a:visited{color:#ff9933;}
		*{
			color:#ffffff;
			{% if $ua==1 %}
                font-size: x-small;
            {% elseif $ua==2 %}
                font-size: x-small;
            {% elseif $ua==3 %}
                font-size:5;
            {% /if %}
		}
	</style>
</head>
<body style="color:#ffffff;background:#000000;">
<div class="cf_app_content">
<a id="pagetop" name="pagetop"></a>

{% if $headAd %}
	<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="header" id="e13e01e7665fd609fcbaefd8c14529db05f65184" />
{% /if %}
