    <div id="menu">
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
        <div class="headline" style="background:#777777;color:#ffffff;">アプリメニュー</div>
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
        <div class="inner">
        {% emoji code="F987"%}<a href='{% "$baseUrl/mobile/dynamite/home"|mixiurl %}' accesskey="1">{%$myDynamiteInfo.displayName%}組</a><br />
        {% emoji code="F989"%}<a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$myDynamiteInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}' accesskey="3">{%$myDynamiteInfo.displayName%}組のｱｼﾞﾄ</a><br />
        {% emoji code="F8A3"%}<a href='{% "$baseUrl/mobile/dynamite/itemlist"|mixiurl %}'>所有ｱｲﾃﾑ一覧({%$myDynamiteInfo.item_count%})</a><br />
        └<a href='{% "$baseUrl/mobile/dynamite/itemshop"|mixiurl %}'>ｱｲﾃﾑｽﾄｱ</a><br />
        {% emoji code="F995"%}<a href='{% "$baseUrl/mobile/dynamite/mymixilist"|mixiurl %}'>参加ﾏｲﾐｸ一覧({%$myDynamiteInfo.friend_count%})</a><br />
            └<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/dynamite/invitefinish" %}'>ﾏｲﾐｸ招待で強力ｱｲﾃﾑGET{% emoji code="F977"%}</a><br />
        {% emoji code="F996"%}<a href='{% "$baseUrl/mobile/dynamite/enemylist"|mixiurl %}'>敵対ﾕｰｻﾞｰ一覧({%$myDynamiteInfo.enemy_count%})</a><br />
        {% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/dynamite/rankingmoney"|mixiurl %}'>所持金ランキング</a><br />
        {% emoji code="F9A5"%}<a href='{% "$baseUrl/mobile/dynamite/rankingdamage"|mixiurl %}'>ｱｼﾞﾄ壊滅数ランキング</a><br />
            <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
        {% emoji code="F8F2"%}<a href='{% "$baseUrl/mobile/dynamite/feed"|mixiurl %}'>更新情報を確認</a><br />
        {% emoji code="F9A9"%}<a href='{% "$baseUrl/mobile/dynamite/help"|mixiurl %}'>ﾍﾙﾌﾟ･このｹﾞｰﾑの遊び方</a><br />

        {% emoji code="F8E4"%}<a href='{% "$baseUrl/mobile/dynamite/help?CF_help=privacy"|mixiurl %}'>ﾌﾟﾗｲﾊﾞｼｰﾎﾟﾘｼｰ</a><br />
        {% emoji code="F8E4"%}<a href='{% "$baseUrl/mobile/dynamite/help?CF_help=tokusho"|mixiurl %}'>特商法に基づく表記</a><br />

        </div><!--/.inner-->
    </div><!--/#menu-->

    <div id="recommend">
	    <img src="{%$staticUrl%}/apps/dynamite/mobile/img/spacer.gif" width="1" height="3" /><br />
	    <div class="headline" style="background:#006699;color:#ffffff;">おすすめｱﾌﾟﾘ情報</div>
	    <div class="section" style="text-align:center;">
			<a href="http://m.mixi.jp/view_appli.pl?id=19008&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/expose_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />オモシロ質問に答えよ～♪</a><br />
	    </div><!--/.section-->
	    <div class="section" style="text-align:center;">
			<a href="http://m.mixi.jp/view_appli.pl?id=19735&guid=ON"><img src="http://friendex.apps.communityfactory.net/static/apps/expose/cmn/img/shindan_banner.gif" width="192" height="53" alt="" style="margin-top:3px;" /><br />おﾊﾞｶな検定が盛りだくさん!</a><br />
	    </div><!--/.section-->
    </div><!--/#recommend-->

	<div id="footerInfo">
		<br />
		<br />
		<br />
		お問い合わせの前に､今一度<a href='{% "$baseUrl/mobile/dynamite/help?CF_help=other"|mixiurl %}'>ﾍﾙﾌﾟ･よくある質問</a>をご確認くださいますよう､お願いいたします｡
	</div><!--/#footerInfo-->
