    <div class="innerBox">
    	<div class="inner">
    		<div id="ad001"><a href=""><img src="{%$staticUrl%}/apps/chat/cmn/img/dummy/ad.gif" width="250" height="250" alt="" /></a></div>
    		<p class="btn"><a href="{%$baseUrl%}/chat/add"><img src="{%$staticUrl%}/apps/chat/cmn/img/mainArea/content/btn_invite.png" width="228" height="34" alt="友達を招待する" /></a></p>
    	</div><!--/.inner-->
    </div><!--/.innerBox-->