		<div id="menu">
			<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="5" /><br />
			<div class="nav" style="background:#eee;">
				<div style="text-align:center;">{% emoji code="F98B"%}<a href='{% "$baseUrl/mobile/parking/start?opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$uid`&parking_rand=$rand" | mobile_flashurl %}' accesskey="5">駐車場をﾁｪｯｸ</a>{% emoji code="F8F2"%}</div>
			</div><!--/.nav-->
			<img src="{%$staticUrl%}/apps/parking/mimg/spacer.gif" width="1" height="2" /><br />
			<span style="color:#cd424a;">◆</span>駐車戦争ﾒﾆｭｰ<br />
			<span style="color:#777;">├</span>{% emoji code="F9F4"%}<a href='{% "$baseUrl/mobile/parking/newsfeed"|mixiurl %}'>更新情報</a><br />
			<span style="color:#777;">├</span>{% emoji code="F8BF"%}<a href='{% "$baseUrl/mobile/parking/car"|mixiurl %}'>所有車一覧</a><br />
			<span style="color:#777;">├</span>{% emoji code="F9A3"%}<a href='{% "$baseUrl/mobile/parking/item"|mixiurl %}'>ｱｲﾃﾑ一覧</a><br />
			<span style="color:#777;">├</span>{% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/parking/rank"|mixiurl %}'>総資産ﾗﾝｷﾝｸﾞ</a><br />
			<span style="color:#777;">├</span>{% emoji code="F8BF"%}<a href='{% "$baseUrl/mobile/parking/carshop"|mixiurl %}'>ｶｰｼｮｯﾌﾟ</a><br />
			<span style="color:#777;">├</span>{% emoji code="F8C5"%}<a href='{% "$baseUrl/mobile/parking/house"|mixiurl %}'>不動産屋</a><br />
			<span style="color:#777;">├</span>{% emoji code="F9A3"%}<a href='{% "$baseUrl/mobile/parking/itemshop"|mixiurl %}'>ｱｲﾃﾑｼｮｯﾌﾟ</a><br />
			<span style="color:#777;">├</span>{% emoji code="F9A0"%}<a href="http://ma001.mixi.jp/view_community.pl?id=4172244">ｻﾎﾟｰﾄｺﾐｭﾆﾃｨ</a><br />
			<span style="color:#777;">└</span>{% emoji code="F999"%}<a href='{% "$baseUrl/mobile/parking/help"|mixiurl %}'>ﾍﾙﾌﾟ</a><br />
		</div><!--/#menu-->		
	</div><!--/#container-->
</body>
</html>