<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
{% if $ua==1 %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=Shift_JIS" />
{% else %}
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
{% /if %}
    <title>脳を鍛える!ﾏｲﾐｸ頭脳くらべ - mixiｱﾌﾟﾘ</title>
    <style type="text/css">
        a:link{color:#3399cc;}
        a:visited{color:#3399cc;}
        a:focus{}
        *{
			{% if $ua==3 %}
			font-size:5;
			{% else %}
			font-size:x-small;
			{% /if %}
			color:#777777;
		}
    </style>
</head>
<body style="background-color:#ffffcc;">
	<div id="container">