<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
    <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
    <title>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ</title>
    <style type="text/css">
    a:link{color:#0000ff;}
    a:visited{color:#7c027c;}
    </style>
</head>
<body>
    <div id="award" style="font-size:x-small;text-align:center;">
        <img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/img_docomo/sub_ti_award_d.gif" />
        <br /><br />
        <div aling="center">
            Disneyﾃﾞｺﾒ公式サイト、メールファクトリーのユーザーは特別ｶｰﾄﾞが●でもらえるよ！「登録確認」をクリックすると使えるようになるよ!
            ※次のページはDisney公式サイトの頁です。
            <br /><br />
        </div>
        <a href="#">ﾒｰﾙﾌｧｸﾄﾘｰに登録する</a><br />
        <a href="#">登録確認</a>
        <br />
    </div>
</body>
</html>