<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
	<title>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ</title>

</head>
<body  style="background-color:#FFFCC7;">

<div id="award" style="background-color:#FFFCC7;font-size:x-small; text-align:center; color:#930;" >
	<br />
	Disney公式ｻｲﾄ登録状況確認<br />
	
    <img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/disneylink/orange_line_d.gif" height="1" /><br />
	
	<br />
	<div class="message" style="text-align:left;">	
		Disney公式携帯ｻｲﾄの会員は特別なｱﾜｰﾄﾞをGETできるよ!<br />
	</div>
	<br />
	
	<div class="message" style="text-align:left;">
		登録が確認できました!いつもﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰをご利用いただきありがとうございます｡下のﾎﾞﾀﾝからｱﾌﾟﾘに戻って会員特典をGETしてね!<br />
		<br />
		※取得できるのは1人1回までです｡<br />
	</div>
	<br />
	<a href='http://ma.mixi.net/{%$appid%}/?guid=ON&url=http%3A%2F%2F{%$host%}%2Fmobile%2Fdisney%2Fdisneycup'><img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/disneylink/mail_btn_d.gif"></a><br />
	<br />

</div>

</body>
</html>
