<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
	<title>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝ</title>

</head>
<body>
	<div id="award" style="background-color:#FFFCC7;font-size:x-small; text-align:center; color:#930;" >

	Disney公式ｻｲﾄ登録状況確認<br />
    
    <img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/disneylink/orange_line_d.gif" height="1" /><br />

  	<br />
    <div class="message" style="text-align:left;">	
  		Disney公式ﾃﾞｺﾒｻｲﾄ｢ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘ-｣の会員登録をしてからこのﾍﾟｰｼﾞにｱｸｾｽしてね｡<br />
    </div>
    <img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
  	
        <div class="message" style="text-align:left;">
        <img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
        </div>    
        <div class="tokuten" style="background-color:#F96;text-align:center;">
        	特典入手方法
        </div>
        <img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
            手順は簡単!3ｽﾃｯﾌﾟ!<br />
        <img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
        <div style="background:#f60;text-align:center;">
			<img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/dotline_fff5f5.gif" width="230" height="1" />
		</div>
        <br />
        <div class="tezyun" style="text-align:left;">
			<div class="ti_01" style="text-align:center;">
				★手順その1★<br />
			</div>
            <a href="http://m.mixi.jp/list_skin_deluxe_disney.pl?id=500028&guid=ON">こちら</a>から｢ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ｣の<span style="color:#ff0000;">月額会員登録</span>をしてね｡<span style="color:#ff0000;">ﾃｨﾝｶｰ･ﾍﾞﾙの画像が入り口の目印だよ｡</span><br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<div style="text-align:center;">
				<img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/mf_sum.gif" width="50" height="50" /><br />
				↓↓↓<br />
			</div>
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<div class="ti_01" style="text-align:center;">
				★手順その2★<br />
			</div>
			このﾍﾟｰｼﾞに再ｱｸｾｽしてね｡<br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<div style="text-align:center;">
				↓↓↓<br />
			</div>
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<div class="ti_01" style="text-align:center;">
				★手順その3★<br />
			</div>
			mixiｱﾌﾟﾘ｢ご当地ｺﾚｸｼｮﾝ｣にｱｸｾｽすると自動的に会員特典をGETできるよ<br />
			<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
			<!--<div style="text-align:center;">
				<img src="http://mxtravel-m.disney.co.jp/st/apps/disney/img/mf_sum.gif" width="50" height="50" /><br />
				↓↓↓<br />
				<img src="http://mm.mixi.net/img/dot0.gif" height="3"/><br />
				まずは<a href="http://m.mixi.jp/pr.pl?id=500028&guid=ON"><span style="#ff0000;">ﾃﾞｨｽﾞﾆｰ･ﾒｰﾙﾌｧｸﾄﾘｰ</span></a>にGO!<br />
			</div>-->
            <br />
		</div>
		⇒<a href="http://m.mixi.jp/pr.pl?id=500028&guid=ON">Disney on mixiﾄｯﾌﾟへ</a><br />

</div>

</body>
</html>
