    <div id="menu">
        <hr class="hrWhite" size="1" />
        <div class="headlineFun">アプリメニュー</div>
        <hr class="hrWhite" size="1" />

        <div class="inner" style="color:#ff9933;">
            ■[0]<a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}' accesskey="0">ホテルトップ</a><br />
            ■[1]<a href='{% "$baseUrl/mobile/hotel/roomlist"|mixiurl %}' accesskey="1">建築物一覧</a><br />
            <!--■[2]<a href='{% "$baseUrl/mobile/hotel/myspylist"|mixiurl %}' accesskey="2">使者一覧</a><br />-->
            ■[2]<a href='{% "$baseUrl/mobile/hotel/hotelshop"|mixiurl %}' accesskey="2">商店</a><br />
            ■[3]<a href='{% "$baseUrl/mobile/hotel/itemlist"|mixiurl %}' accesskey="3">所有アイテム</a><br />
            ■[4]<a href='{% "$baseUrl/mobile/hotel/ranking?CF_pos=2"|mixiurl %}' accesskey="4">ランキング</a><br />
            ■[5]<a href='{% "$baseUrl/mobile/hotel/minifeed"|mixiurl %}' accesskey="5">履歴</a><br />
            ■[6]<a href='{% "$baseUrl/mobile/hotel/minifeed"|mixiurl %}' accesskey="6">更新情報を確認</a><br />
            ■[7]<a href='{% "$baseUrl/mobile/hotel/help"|mixiurl %}' accesskey="7">このｹﾞｰﾑの遊び方</a><br />
        </div><!--/.inner-->
    </div><!--/#menu-->