<div class="section" style="background:#000000;">
    <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
            <td colspan="2" align="left" style="text-align:left;">
                <span style="color:#ff9933;">⇒</span>
                    <a href='{% "$baseUrl/mobile/hotel/profile"|mixiurl %}'>Nickさんの使者を追払う</a><br />
                <span style="color:#ff9933;">⇒</span>
                    <a href="#">○○さんの車を通報する</a>
            </td>
        </tr>
    </table>
</div><!--/.section-->