<div id="help" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">
		ヘルプ よくある質問<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		目次<br />
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		お客様から寄せられる､よくある質問にお答えします｡<br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		Q1.<a href='{% "$baseUrl/mobile/school/help?CF_param=q1"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">このｱﾌﾟﾘについて</span></a><br />

		Q2.<a href='{% "$baseUrl/mobile/school/help?CF_param=q2"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">このｱﾌﾟﾘは誰でも利用できる?</span></a><br />

		Q3.<a href='{% "$baseUrl/mobile/school/help?CF_param=q3"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ｺﾒﾝﾄ投稿時のﾙｰﾙは?</span></a><br />

		Q4.<a href='{% "$baseUrl/mobile/school/help?CF_param=q4"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">時間割のﾌﾟﾗｲﾊﾞｼｰ設定は?</span></a><br />

		Q5.<a href='{% "$baseUrl/mobile/school/help?CF_param=q5"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">時間割を一括削除したい</span></a><br />

		Q6.<a href='{% "$baseUrl/mobile/school/help?CF_param=q6"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ｱﾌﾟﾘ削除後に投稿したﾃﾞｰﾀは残りますか?</span></a><br />

		Q7.<a href='{% "$baseUrl/mobile/school/help?CF_param=q7"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">休講予報って何ですか?</span></a><br />

		Q8.<a href='{% "$baseUrl/mobile/school/help?CF_param=q8"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">授業Q&Aの回答を削除したい</span></a><br />

		Q9.<a href='{% "$baseUrl/mobile/school/help?CF_param=q9"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ﾏｲﾐｸ/同級生を招待したが､ｽﾋﾟｰﾄﾞくじが利用できない</span></a><br />

		Q10.<a href='{% "$baseUrl/mobile/school/help?CF_param=q10"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">利用学校を変更したい</span></a><br />

		Q11.<a href='{% "$baseUrl/mobile/school/help?CF_param=q11"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">どこが運営しているの?</span></a><br />

		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#help-->