<div id="help" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">
		利用学校の変更<br />
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		利用学校の変更を行います。<br />
		<br />
		※現在利用している時間割のデータなどはすべて削除されますので、あらかじめご了承ください。<br />
		<br />
		変更する場合は､次の[変更]を押してください｡<br />
		<br />
		<form method="post" action='{% "$baseUrl/mobile/school/help"|mixiurl %}'>
			<input type="hidden" name="CF_param" value="helpfinish" />
			<div class="btn" style="text-align:center;">
				<input type="submit" value=" 変 更 " />
			</div><!--/.btn-->
		</form>
		<form method="post" action='{% "$baseUrl/mobile/school/help"|mixiurl %}'>
			<input type="hidden" name="CF_param" value="q10" />
			<div class="btn" style="text-align:center;">
				<input type="submit" value=" ｷｬﾝｾﾙ " />
			</div><!--/.btn-->
		</form>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#help-->