<div id="help" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">
		ヘルプ よくある質問<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		Q10.利用学校を変更したい<br />
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		大学から大学院に進級した場合や､その他編入した場合など､利用中の学校を変更することが可能です｡<br />
		<br />
		ただし、変更を実行すると、現在利用している時間割のﾃﾞｰﾀがすべて削除されますので、あらかじめご了承ください。<br />
		<br />
		変更する場合は､次の[確認]を押してください｡<br />
		<br />
		<form method="post" action='{% "$baseUrl/mobile/school/help"|mixiurl %}'>
			<input type="hidden" name="CF_param" value="helpconfirm" />
			<div class="btn" style="text-align:center;">
				<input type="submit" value=" 確 認 " />
			</div><!--/.btn-->
		</form>
		<form method="post" action='{% "$baseUrl/mobile/school/help"|mixiurl %}'>
			<div class="btn" style="text-align:center;">
				<input type="submit" value=" ｷｬﾝｾﾙ " />
			</div><!--/.btn-->
		</form>
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" />
	</div><!--/#keyvisual-->
</div><!--/#help-->