<div id="help" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">
		ヘルプ よくある質問<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		Q6.ｱﾌﾟﾘ削除後に投稿したﾃﾞｰﾀは残りますか?<br />
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		はい､残ります｡<br />
		<br />
		ただし､一部ﾃﾞｰﾀに関して､ﾃﾞｰﾀを残すことを望まない場合は､お手数ですが､それぞれのﾃﾞｰﾀを削除後､当ｱﾌﾟﾘを削除してください｡<br />
		<br />
		もしもお客様が削除等を行わなかった場合､それまでに投稿したﾃﾞｰﾀは残り続けます(お問い合わせでの個別削除は行っておりません｡あらかじめご了承ください)｡<br />
		<br />
		<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/help"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ヘルプ目次</span></a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#help-->