<div id="help" style="background:#5ac5ff;color:#003366;">
	<div id="bgImage" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/sky.gif" width="240" height="25" /><br />
	</div><!--/#bgImage-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#3c88e5;color:#ffffff;">
		ヘルプ よくある質問<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
		Q9.ﾏｲﾐｸ/同級生を招待したが､ｽﾋﾟｰﾄﾞくじが利用できない<br />
	</div><!--/.headline-->
	<div class="description">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		招待特典の反映には､招待した方が当ｱﾌﾟﾘを追加後から2-3日のお時間を必要とします｡<br />
		<br />
		特典が反映されない場合は､しばらく待ってから再度ご確認くださいますよう､お願い申し上げます｡<br />
		<br />
		<span style="color:#f58320;">⇒</span><a href='{% "$baseUrl/mobile/school/help"|mixiurl %}' style="color:#003366;"><span style="color:#003366;">ヘルプ目次</span></a><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	</div><!--/.description-->
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div id="keyvisual" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/school/mobile/img/school.gif" width="240" height="62" /><br />
	</div><!--/#keyvisual-->
</div><!--/#help-->