{%include file="slave/common/header.phtml"%}

<body id="twoColumn">
<div id="continer">

	{%include file="slave/common/hdr.phtml"%}
	<script type="text/javascript">
		$j('#gNavHelp').addClass('active');
	</script>

	<div id="mainColumn">
		<div id="helpBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_help.png" width="296" height="23" alt="ワタシのドレイちゃんの遊び方" /></h2>
			</div><!--/.hdr-->
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_1.png" width="565" height="25" alt="ドレイちゃんゲームの概要" /></h3>
				<p>
mixiに登録している全てのユーザーが、ドレイ市場に売られてるよ。<br />
<br />
<em>マイミクをドレイちゃんとして買い取って、屈辱的なニックネームをつけたり、変なセリフを言わせたり、他のユーザーをからかったり、強制労働をさせて楽しんじゃおう！</em><br />
<br />
ドレイちゃん自身は、たくさんイジられることで、どんどん人気ドレイちゃんとして市場価値が上がっていくよ！<br />
<br />
自分自身ドレイちゃんとして、市場価値を高めつつ、所有してるドレイちゃんをゴリゴリ働かせて、どんどんお金を稼いでトップを目指せっ<br />
				</p>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_2.png" width="565" height="25" alt="お金について" /></h3>
				<ul>
<li>・所持金で、ドレイちゃんを購入できるよ。</li>
<li>・所持金で、ギフトを購入できるよ。</li>

<li>・以下の方法で、所持金を増やすことができるよ。<br />
	<ol>
		<li>１）自分のドレイちゃんが、他のユーザーに購入される</li>
		<li>２）自分のドレイちゃんをポイ捨てする</li>
		<li>３）自分のドレイちゃんの革命を阻止する</li>
		<li>４）所有しているギフトを売る</li>
		<li>５）ドレイちゃんに、強制労働をさせる。</li>
	</ol>
</li>
<li>・以下の時に、所持金が減っちゃうよ。<br />
	<ol>
		<li>１）ドレイちゃんを、新たに購入する</li>
		<li>２）自分が起こした革命を阻止される</li>
		<li>３）ギフトを、新たに購入する。</li>
	</ol>
</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_3.png" width="565" height="25" alt="ドレイちゃんについて" /></h3>
				<ul>
<li>・すべてのmixiユーザーが、ドレイ市場で売られているよ。（※自分が所有しているドレイが、売られる事は防げないんだ。）</li>
<li>・ご主人様は、最大で４匹のドレイちゃんしか所有できないよ。</li>
<li>・ドレイちゃんは、１人のご主人様にしか仕えてくれないよ。</li>
<li>・以下の時に、ドレイちゃんの市場価格が上昇するよ。<br />
	<ol>
		<li>１）ドレイちゃんが、他のユーザーに購入される</li>
		<li>２）ドレイちゃんが、他のユーザーをからかう</li>
		<li>３）誰かに、ギフトを贈る</li>
		<li>４）ドレイちゃんの職業Lv.を昇格させる</li>
		<li>５）ご主人様への革命に成功する</li>
	</ol>
</li>
<li>・以下の時に、ドレイちゃんの市場価格が下落しちゃうよ。<br />
	<ol>
		<li>１）ご主人様からポイ捨てされる</li>
		<li>２）ドレイちゃんから革命を起こされ、成功される</li>
		<li>３）ペナルティ発生時（※品格を疑われるような行為をした場合）</li>
	</ol>
</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_4.png" width="565" height="25" alt="ドレイちゃんのニックネーム、ふきだしを編集" /></h3>
				<ul>
<li>・自分のドレイちゃんのニックネームは自由に編集することができるよ。屈辱的なニックネームをつけて楽しんじゃおう！！</li>
<li>・放送禁止用語などを入力すると、ペナルティがあるから気をつけよう。（あくまで常識の範囲内で楽しんでねっ）</li>
<li>・自分のドレイちゃんのフキダシは自由に編集することができるよ。屈辱的なセリフをしゃべらせて楽しんじゃおう！！</li>
<li>・放送禁止用語などを入力すると、ペナルティがあるから気をつけよう。（あくまで常識の範囲内で楽しんでねっ）</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_5.png" width="565" height="25" alt="ドレイちゃんでからかう" /></h3>
				<ul>
<li>・自分のドレイちゃんを使って、他のユーザーを自由にからかう事が出来るよ。悪ノリ度に合わせて市場価値が上昇するヨ！からかう内容は自分で作ることも出来るから自由に楽しんじゃおう！</li>
<li>・放送禁止用語を入力したり、不適切な画像をUPしたりすると、ペナルティがあるから気をつけよう。（あくまで常識の範囲内で楽しんでねっ）</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_6.png" width="565" height="25" alt="ドレイちゃんに強制労働させる" /></h3>
				<ul>
<li>・自分のドレイちゃんには、強制労働をさせてお金を稼ぐことができるよ。</li>
<li>・強制労働をさせると、ドレイちゃんの体力が減っちゃうよ。体力は少しずつ回復していくから、ドレイちゃんにあまり無理をさせないであげてね。</li>
<li>・労働の種類に応じて、職業のランクが上がっていくよっ。（ひょっとしたら、隠れ職業が登場したりするかも？！）</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_7.png" width="565" height="25" alt="ご主人様に革命を起こす" /></h3>
				<ul>
<li>・ドレイちゃんは、日ごろ酷い扱いをしているご主人様に対して、革命を起こすことができるよ。</li>
<li>・革命を起こしてから、12時間ご主人様に見つからなければ革命が成功。ご主人様に見つかってしまった場合は、残念ながら革命失敗になるよ。</li>
<li>・<em>革命が成功すると、主従関係が逆転するヨ。（自分のドレイちゃんの評価額もUp！）</em></li>
<li>・革命が失敗に終わると、ご主人様に所持金を没収されちゃうから気をつけよう。</li>
<li>・革命成功時、ドレイちゃんを4匹Maxで所有している場合は、一番評価額が低いドレイちゃんを勝手にポイ捨てして、ご主人様をドレイちゃんにしちゃうよ。</li>
				</ul>
			</div>
			<div class="helpBlock">
				<h3><img src="{%$staticUrl%}/apps/slave/img/content/subTit_help_8.png" width="565" height="25" alt="ギフトについて" /></h3>
				<ul>
<li>・ギフトを購入して、他のユーザーにプレゼントすることが出来るよ！たくさんアイテムがあるから、おもしろレアアイテムを探して、友達に送りつけてみよう。</li>
<li>・ギフトを贈ると、ギフトをもらった人のドレイちゃん評価額がUpするよ。</li>
<li>・ギフトは売ることも出来るよ。</li>
				</ul>
			</div>



		</div><!--/#helpBox.box-->
	</div><!--/#mainColumn-->

	<div id="subColumn">
	{%include file="slave/common/adbox.phtml"%}
	{%include file="slave/common/logbox.phtml"%}
	{%include file="slave/common/popularbox.phtml"%}
	</div><!--/#subColumn-->

<script type="text/javascript">
	$j(document).ready( function() {adjustHeight();} );
</script>
{%include file="slave/common/footer.phtml"%}