{%include file="slave/common/header.phtml"%}

<body id="home">
<div id="continer">
	{%include file="slave/common/hdr.phtml"%}
	<script type="text/javascript">
		$j('#gNavProfile').addClass('active');
		var hidPos = '{%$hasPos%}';
    	if (null != cm_getCookie('app_top_url') && '1' != hidPos) {
    		top.location.href = cm_getCookie('app_top_url') +  '#pagetop';
    	}
	</script>

	<div id="profColumn">
		<div id="profBox" class="box">
			<p class="comment">{% if $slaveInfo.balloon %}{%$slaveInfo.balloon|escape%}{% else %}誰か私を買って下さい{% /if %}<span></span></p>
			<p class="pic"><a style="background-image: url({%$mixiPic|replace:"s.jpg":".jpg"|replace:"76.gif":"180.gif"%}); cursor:default;">{%$mixiName%}</a></p>
			<h2><span>{%$mixiName%} 改め </span>{%if $slaveInfo.nickname %}{%$slaveInfo.nickname|escape%}{% else %}{%$mixiName%}ちゃん{% /if %}</h2>
			<p class="price">市場価値：&yen;{%$slaveInfo.fomat_price%}（{%$slaveInfo.rank_price%}位）</p>
			<p class="job">職業：{%$slaveInfo.work_category|escape%}</p>
			<p class="money">所持金：&yen;{%$slaveInfo.fomat_cash%}（{%$slaveInfo.rank_cash%}位）</p>

			{% if not $isMyprofile %}
			  {% if $isMineSlave %}<!-- myslave -->
			  	{% if 1 == $slaveInfo.is_in_revolution %}<p id="btnPrevent" class="btn"><a href="{%$baseUrl%}/slave/stoprevolute?uid={%$profileUid%}">革命を阻止する</a></p>
    			{% else %}<p id="btnPrevent" class="btn disable"><a>革命を阻止する</a></p>
    			{% /if %}
    			<p id="btnNickname" class="btn"><a href="{%$baseUrl%}/slave/setnickname?uid={%$slaveInfo.uid%}">ニックネームを編集</a></p>
    			<p id="btnEdit" class="btn"><a href="{%$baseUrl%}/slave/setballoon?uid={%$slaveInfo.uid%}">フキダシを編集</a></p>
    			{% if $mineSlaveCnt < 2 %}<p id="btnTease" class="btn disable"><a>からかう</a></p>
    			{% else %}<p id="btnTease" class="btn"><a href="{%$baseUrl%}/slave/tease?uid={%$slaveInfo.uid%}">からかう</a></p>
    			{% /if %}
    			<p id="btnLabor" class="btn"><a href="{%$baseUrl%}/slave/work?uid={%$slaveInfo.uid%}">強制労働させる</a></p>
    			{% if $mineGiftCnt < 1 %}<p id="btnGift" class="btn disable"><a>ギフトを贈る</a></p>
    			{% else %}<p id="btnGift" class="btn"><a href="{%$baseUrl%}/slave/presentgift?uid={%$slaveInfo.uid%}">ギフトを贈る</a></p>
    			{% /if %}
    			<p id="btnThrow" class="btn"><a href="{%$baseUrl%}/slave/sellslave?uid={%$slaveInfo.uid%}">ポイ捨てする</a></p>
			  {% else %}<!-- not my slave -->
			  	{% if 1 == $slaveInfo.is_in_revolution2 && 1==$isMineSlaveSlave %}<p id="btnPrevent" class="btn"><a href="{%$baseUrl%}/slave/stoprevolute?uid={%$profileUid%}">革命を阻止する</a></p>
			  	{% /if %}
    			{% if ($mineCash < $slaveInfo.price) or $isMineMaster %}<p id="btnPurchase" class="btn disable"><a>購入する</a></p>
    			{% else %}<p id="btnPurchase" class="btn"><a href="{%$baseUrl%}/slave/buyslave?uid={%$slaveInfo.uid%}">購入する</a></p>
    			{% /if %}
    			{% if $mineSlaveCnt < 1 %}<p id="btnTease" class="btn disable"><a>からかう</a></p>
    			{% else %}<p id="btnTease" class="btn"><a href="{%$baseUrl%}/slave/tease?uid={%$slaveInfo.uid%}">からかう</a></p>
    			{% /if %}
    			{% if $mineGiftCnt < 1 %}<p id="btnGift" class="btn disable"><a>ギフトを贈る</a></p>
    			{% else %}<p id="btnGift" class="btn"><a href="{%$baseUrl%}/slave/presentgift?uid={%$slaveInfo.uid%}">ギフトを贈る</a></p>
    			{% /if %}
			  {% /if %}<!-- is mineslave end -->
			{% /if %}<!-- is not myprofile end -->

			<div id="owner">
			{% if $isFreedom %}
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_owner.png" width="135" height="23" alt="ご主人様" /></h2>
				<p class="pic"><a style="background-image: url({%$staticUrl%}/apps/slave/img/dummy/pic_s_13.png);">永遠のご主人様</a></p>
				<p class="name"><span><a>ドレイちゃん伯爵</a> 改め </span>永遠のご主人様</p>
				<p class="price">市場価値：&yen;999,999</p>
				<p class="money">所持金：&yen;450,000</p>
			{% else %}
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_owner.png" width="135" height="23" alt="ご主人様" /></h2>
				<p class="pic"><a href="{%$baseUrl%}/slave/profile?uid={%$masterInfo.uid%}" style="background-image: url({%$msPic%});">{%$msName%}</a></p>
				<p class="name"><span><a href="{%$baseUrl%}/slave/profile?uid={%$masterInfo.uid%}">{%$msName%}</a> 改め </span>{%if $masterInfo.nickname %}{%$masterInfo.nickname|escape%}{% else %}{%$msName%}ちゃん{% /if %}</p>
				<p class="price">価格：&yen;{%$masterInfo.fomat_price%}</p>
				<p class="job">職業：{%$masterInfo.work_category|escape%}</p>
				<p class="money">所持金：&yen;{%$masterInfo.fomat_cash%}</p>
			{% /if %}
			</div><!--/#owner-->

			{% if $isMyprofile %}
			{% if $isFreedom || $isAlreadyInRev %}
			<p id="btnRevolution" class="btn disable"><a>革命を起こす</a></p>
			{% else %}
			<p id="btnRevolution" class="btn"><a href="{%$baseUrl%}/slave/revolute">革命を起こす</a></p>
			{% /if %}
			{% /if %}
		</div><!--/#profBox.box-->

		<div id="giftBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_gift.png" width="116" height="20" alt="ギフトケース" /></h2>
				<ul class="allowList" style="{% if not $cntGift or 1==$cntGift %}display:none;{% /if %}"><!--
					--><li class="allowLeft"><a id="btnLeft" href="javascript:void(0);">左</a></li><!--
					--><li class="allowRight"><a id="btnRight" href="javascript:void(0);">右</a></li><!--
				--></ul>
			</div><!--/.hdr-->

			{% if $cntGift %}

			<div id="divgift" >
				<p class="pic" style="cursor:default;"><span style="background-image:url({% if $lstGift.gift_big_pic %}{%$lstGift.gift_big_pic%}{% else %}{%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png{% /if %})">{%$lstGift.name|escape%}</span></p>
				<p class="name">{%$lstGift.name|escape%}</p>
				<p class="price">価格：&yen;{%$lstGift.format_price%}</p>
				{% if $isMyprofile %}
				<ul class="action box"><!--
					--><li><a href="{%$baseUrl%}/slave/presentgift?id={%$lstGift.id%}">プレゼントする</a></li><!--
					--><li><a href="{%$baseUrl%}/slave/sellgift?id={%$lstGift.id%}">ギフト屋に売る</a></li><!--
				--></ul><!--/.action.box-->
				{% /if %}
			</div>

			{% else %}

			<p class="pic homeNull"><a href="{%$baseUrl%}/slave/giftshop?more=1" style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_null1.png)"></a></p>
			<div id="btnRakuten" class="homeNull"><a href="{%$baseUrl%}/slave/giftshop?more=1">ギフト屋を見る</a></div>

			{% /if %}
			<input type="hidden" id="pageIndex" value="1" />
			<input type="hidden" id="hidCntGift" value="{%$cntGift%}" />
		</div><!--/#giftBox.box-->

	</div><!--/#profColumn-->


	<div id="mainColumn">

		<div id="neighborBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_photo.png" width="205" height="19" alt="お隣のドレイちゃん" /></h2>
			</div><!--/.hdr-->
			<div id="memberFrame" style="height:69px;overflow:hidden;position:relative;width:419px;">
				<div id="innaerFrame" style="position:absolute;top:0;width:990000px;">
				<ul id="ulFriend"><!--
					{% foreach name=neighberlist from=$lstNeighber item=ndata key=idx %}
						{% if $ndata.fid=="0" %}
						--><li><a href="javascript:void(0);" onclick="mixi_invite();return false;"><img height="60px" width="60px" src="{%$staticUrl%}/apps/slave/img/dummy/pic_s_4.png" alt="招待する" /></a></li><!--
						{% else %}
						--><li {% if $ndata.fid==$profileUid %}class="active select"{% /if %}><a href="javascript:void(0);" onclick="lnkProfile(this,{%$ndata.fid%});return false;" style="background-image: url({%$ndata.thumbnailUrl%});"><img height="60px" width="60px" src="{%$staticUrl%}/apps/slave/img/dummy/spacer.gif" alt="{%$ndata.displayName%}" /></a></li><!--
						{% /if %}
					{% /foreach %}
				--></ul>
				</div>
			</div>
			<p class="preButton"><a id="navLeft" href="javascript:void(0);">left</a></p>
			<p class="nextButton"><a id="navRight" href="javascript:void(0);">right</a></p>
			<input type="hidden" id="hidCntPos" value="{%$neiCount%}" />
			<input type="hidden" id="hidPosprev" value="{%$neiStart%}" />
			<input type="hidden" id="hidPosnext" value="{%$neiEnd%}" />
			<input type="hidden" id="hidHasPos" value="{%$hasPos%}" />
		</div><!--/#neighborBox.box-->

		<div id="newsBox" class="box" {% if 0==$cntFeed %}style="display:none"{% /if %}>
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_news.png" width="159" height="19" alt="わるのりニュース" /></h2>
			</div><!--/.hdr-->

			<div id="newsFeed" {% if 5>$cntFeed %}class="homeNull"{% /if %}>
				<ul><!--
    			{% foreach name=feedlist from=$lstFeed item=fdata %}
					--><li>
					   <p class="pic"><a class="noLink" style="background-image:url({%$fdata.pic_url%});"></a></p>
					   <p class="date">[{%$fdata.format_time%}]</p>
					   <p class="action">{%$fdata.message%}</p>
					</li><!--
    			{% /foreach %}
    			--></ul>
			</div><!--/#newsFeed-->
			<input type="hidden" id="hidProfileUid" value="{%$profileUid%}" />
			<input type="hidden" id="hidUid" value="{%$uid%}" />
		</div><!--/#newsBox.box-->

		<div id="doreiActionBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_dorei.png" width="190" height="19" alt="飼育中のドレイちゃん" /></h2>
			</div><!--/.hdr-->

			<!-- profile mine -->
			{% if $isMyprofile %}
			{% if $lstSlaves %}
			<ul><!--
			{% foreach name=slavelist from=$lstSlaves item=sdata %}
			--><li>
					<p class="pic"><a href="{%$baseUrl%}/slave/profile?uid={%$sdata.uid%}" style="background-image:url({%$sdata.thumbnailUrl%})">{%$sdata.displayName%}</a>{% if 1==$sdata.is_in_revolution %}<img src="{%$staticUrl%}/apps/slave/img/content/icn_warning.gif" width="16" height="16" alt="" />{% /if %}</p>
					<p class="name"><span><a href="{%$baseUrl%}/slave/profile?uid={%$sdata.uid%}">{%$sdata.displayName%}</a> 改め </span>{%if $sdata.nickname %}{%$sdata.nickname|escape%}{% else %}{%$sdata.displayName%}ちゃん{% /if %}</p>
					<p class="comment">{% if $sdata.balloon %}{%$sdata.balloon|escape%}{% else %}誰か私を買って下さい{% /if %}　<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;{%$sdata.format_price%}</li><!--
						--><li class="job">職業：{%$sdata.work_category|escape%}</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a href="{%$baseUrl%}/slave/setnickname?uid={%$sdata.uid%}">ニックネームを編集</a></li><!--
						--><li class="actionComment"><a href="{%$baseUrl%}/slave/setballoon?uid={%$sdata.uid%}">フキダシを編集</a></li><!--
						{% if $mineSlaveCnt < 2 %}--><li class="actionPoke"><a class="disable">からかう</a></li><!--
						{% else %}--><li class="actionPoke"><a href="{%$baseUrl%}/slave/tease?uid={%$sdata.uid%}">からかう</a></li><!--
						{% /if %}
						--><li class="actionWork"><a href="{%$baseUrl%}/slave/work?uid={%$sdata.uid%}">強制労働させる</a></li><!--
						{% if $mineGiftCnt < 1 %}}--><li class="actionGift"><a class="disable">ギフトを贈る</a></li><!--
						{% else %}--><li class="actionGift"><a href="{%$baseUrl%}/slave/presentgift?uid={%$sdata.uid%}">ギフトを贈る</a></li><!--
						{% /if %}
						--><li class="actionDelete"><a href="{%$baseUrl%}/slave/sellslave?uid={%$sdata.uid%}">ポイ捨てする</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
			{% /foreach %}
			--></ul>
			{% else %}
			<ul class="homeNull"><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>ニックネームを編集</a></li><!--
						--><li class="actionComment"><a>フキダシを編集</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionWork"><a>強制労働させる</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
						--><li class="actionDelete"><a>ポイ捨てする</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>ニックネームを編集</a></li><!--
						--><li class="actionComment"><a>フキダシを編集</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionWork"><a>強制労働させる</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
						--><li class="actionDelete"><a>ポイ捨てする</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>ニックネームを編集</a></li><!--
						--><li class="actionComment"><a>フキダシを編集</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionWork"><a>強制労働させる</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
						--><li class="actionDelete"><a>ポイ捨てする</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>ニックネームを編集</a></li><!--
						--><li class="actionComment"><a>フキダシを編集</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionWork"><a>強制労働させる</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
						--><li class="actionDelete"><a>ポイ捨てする</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
			--></ul>
			{% /if %}

			<!-- profile viewer slave -->
			{% else %}
			{% if $lstSlaves %}
			<ul><!--
			{% foreach name=slavelist from=$lstSlaves item=sdata %}
			--><li>
					<p class="pic"><a href="{%$baseUrl%}/slave/profile?uid={%$sdata.uid%}" style="background-image:url({%$sdata.thumbnailUrl%})">{%$sdata.displayName%}</a>{% if 1==$sdata.is_in_revolution %}<img src="{%$staticUrl%}/apps/slave/img/content/icn_warning.gif" width="16" height="16" alt="" />{% /if %}</p>
					<p class="name"><span><a href="{%$baseUrl%}/slave/profile?uid={%$sdata.uid%}">{%$sdata.displayName%}</a> 改め </span>{%if $sdata.nickname %}{%$sdata.nickname|escape%}{% else %}{%$sdata.displayName%}ちゃん{% /if %}</p>
					<p class="comment">{% if $sdata.balloon %}{%$sdata.balloon|escape%}{% else %}誰か私を買って下さい{% /if %}　<span></span></p>
					<ul><!--
						--><li class="price">市場価値：&yen;{%$sdata.format_price%}</li><!--
						--><li class="job">職業：{%$sdata.work_category|escape%}</li><!--
					--></ul>
					<ul class="actionList"><!--
						{% if $mineCash < $slaveInfo.price %}--><li class="actionName"><a class="disable">購入する</a></li><!--
						{% else %}--><li class="actionName"><a href="{%$baseUrl%}/slave/buyslave?uid={%$sdata.uid%}">購入する</a></li><!--
						{% /if %}
						{% if $mineSlaveCnt < 1 %}--><li class="actionPoke"><a class="disable">からかう</a></li><!--
						{% else %}--><li class="actionPoke"><a href="{%$baseUrl%}/slave/tease?uid={%$sdata.uid%}">からかう</a></li><!--
						{% /if %}
						{% if $mineGiftCnt < 1 %}--><li class="actionGift"><a class="disable">ギフトを贈る</a></li><!--
						{% else %}--><li class="actionGift"><a href="{%$baseUrl%}/slave/presentgift?uid={%$sdata.uid%}">ギフトを贈る</a></li><!--
						{% /if %}
					--></ul><!--/.atctionList-->
				</li><!--
			{% /foreach %}
			--></ul>
			{% else %}
			<ul class="profileNull"><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">価格：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>購入する</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
						--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">価格：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>購入する</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">価格：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>購入する</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
				--><li>
					<p class="pic"><a style="background-image:url({%$staticUrl%}/apps/slave/img/dummy/pic_n_s.png)">?????</a></p>
					<p class="name"><span>????? 改め </span>?????</p>
					<p class="comment">誰か私を買って下さい。<span></span></p>
					<ul><!--
						--><li class="price">価格：&yen;??????</li><!--
						--><li class="job">職業：??????</li><!--
					--></ul>
					<ul class="actionList"><!--
						--><li class="actionName"><a>購入する</a></li><!--
						--><li class="actionPoke"><a>からかう</a></li><!--
						--><li class="actionGift"><a>ギフトを贈る</a></li><!--
					--></ul><!--/.atctionList-->
				</li><!--
			--></ul>
			{% /if %}

			{% /if %}
		</div><!--/#doreiActionBox.box-->
		<input type="hidden" id="activity" value="{%$activity%}" />
		<input type="hidden" id="activityNew" value="{%$activityNew%}" />
		<input type="hidden" id="activityPic" value="{%$activityPic%}" />
	</div><!--/#mainColumn-->

	<div id="subColumn">
		{%include file="slave/common/adbox.phtml"%}
		{%include file="slave/common/logbox.phtml"%}
		{%include file="slave/common/popularbox.phtml"%}
	</div><!--/#subColumn-->

	<script type="text/javascript" src="{%$staticUrl%}/apps/slave/js/profile.js?{%$version.js%}"></script>
{%include file="slave/common/footer.phtml"%}