{%include file="slave/common/header.phtml"%}

<body id="twoColumn">
<div id="continer">
	{%include file="slave/common/hdr.phtml"%}
	<script type="text/javascript">
    	if (null != cm_getCookie('app_top_url')) {
    		top.location.href = cm_getCookie('app_top_url') +  '#pagetop';
    	}
	</script>

	<div id="mainColumn">
		<div id="changeFukidashiBox" class="box">

			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_changeFukidashi.png" width="160" height="23" alt="フキダシを編集" /></h2>
			</div><!--/.hdr-->

			<div id="step1">
			<p class="intro"><span>{%$tarName%}のフキダシを変更するよ。</span>
			<span>次の入力フォームにつぶやかせたいメッセージを入力してね。</span></p>
			<div class="section">
				<p class="pic"><a class="noLink" style="background-image:url({%$tarPic%})">{%$tarName%}</a></p>
				<p class="name">{%$tarName%} 改め <span>{%if $tarSlaveInfo.nickname %}{%$tarSlaveInfo.nickname|escape%}{% else %}{%$tarName%}ちゃん{% /if %}</span></p>
				<p class="commentForm"><input id="txtBalloon" name="txtBalloon" type="text" value="{%$tarSlaveInfo.balloon%}" title="{%$tarSlaveInfo.balloon%}" size="50" maxlength="25" /><span></span></p>
				<p class="alert" style="display:none">ジョークの範囲を超えると、社会的信頼を失う恐れがあります</p>
			</div><!--/.section-->
			<ul class="actionList"><!--
				--><li class="actionAbolish disable"><a href="javascript:cm_goBack();">キャンセル</a></li><!--
				--><li class="actionNext"><a id="btnConfirm" href="javascript:void(0);">つぎへ</a></li><!--
			--></ul><!--/.actionList-->
			</div>

			<div id="step2" style="display:none">
			<p class="intro"><span>{%$tarName%}のフキダシを変更するよ。</span>
			<span>入力した内容を確認してね。</span></p>
			<div class="section">
				<p class="pic"><a class="noLink" style="background-image:url({%$tarPic%})">{%$tarName%}</a></p>
				<p class="name">{%$tarName%} 改め <span>{%if $tarSlaveInfo.nickname %}{%$tarSlaveInfo.nickname|escape%}{% else %}{%$tarName%}ちゃん{% /if %}</span></p>
				<p id="lblBalloon" class="comment"> <span></span></p>
			</div><!--/.section-->
			<ul class="actionList"><!--
				--><li class="actionAbolish disable"><a id="btnBack" href="javascript:void(0);">もどる</a></li><!--
				--><li class="actionDecision"><a id="btnSet" href="javascript:void(0);">決定</a></li><!--
			--></ul><!--/.actionList-->
			</div>

			<div id="step3" style="display:none">
			<p class="intro"><span>{%$tarName%}のフキダシを変更したよ。</span>
			<span>ドレイちゃんのフキダシは定期的に変更して、可愛がってあげてね。</span></p>
			<div class="section">
				<p class="pic"><a class="noLink" style="background-image:url({%$tarPic%})">{%$tarName%}</a></p>
				<p class="name">{%$tarName%} 改め <span>{%if $tarSlaveInfo.nickname %}{%$tarSlaveInfo.nickname|escape%}{% else %}{%$tarName%}ちゃん{% /if %}</span></p>
				<p id="lblBalloon1" class="comment"> <span></span></p>
			</div><!--/.section-->
			<p class="actionLookatSlave btn"><a href="{%$baseUrl%}/slave/profile?uid={%$tarSlaveInfo.uid%}">このドレイちゃんのプロフィールを見る</a></p>
			</div>

			<input type="hidden" id="hidTarUid" value="{%$tarSlaveInfo.uid%}" />
		</div><!--/#changeFukidashiBox.box-->
	</div><!--/#mainColumn-->

	<div id="subColumn">
		{%include file="slave/common/adbox.phtml"%}
		{%include file="slave/common/logbox.phtml"%}
	</div><!--/#subColumn-->

	<script type="text/javascript" src="{%$staticUrl%}/apps/slave/js/setballoon.js?{%$version.js%}"></script>
{%include file="slave/common/footer.phtml"%}