{%include file="slave/common/header.phtml"%}

<body id="twoColumn">

<div id="continer">
	{%include file="slave/common/hdr.phtml"%}
	<script type="text/javascript">
    	if (null != cm_getCookie('app_top_url')) {
    		top.location.href = cm_getCookie('app_top_url') +  '#pagetop';
    	}
	</script>

	<div id="mainColumn">
		<div id="toRakutenBox" class="box">
			<div class="hdr">
				<h2><img src="{%$staticUrl%}/apps/slave/img/content/tit_toRakuten.png" width="197" height="23" alt="楽天市場で購入する" /></h2>
			</div><!--/.hdr-->

			<p class="intro">ここから先は楽天市場内の商品ページとなります。ゲームではなく、現実のショッピングとなりますので、あらかじめご理解したうえで、移動してください。</p>
				<div class="section">
					<p class="pic"><a style="cursor:default;background-image:url({%$giftInfo.gift_small_pic%})">レイヤー</a></p>
					<p class="intro">{%$giftInfo.name%}</p>
					<p class="price">価格：¥{%$giftInfo.gift_format_price%}</p>
				</div><!--/.section-->
			<ul class="actionList"><!--
				--><li class="actionAbolish disable"><a href="javascript:cm_goBack();">キャンセル</a></li><!--
				--><li class="actionToRakuten"><a href="javascript:void(0);" onclick="to_outer_site('{%$giftInfo.url%}');">楽天市場に移動する</a></li><!--
			--></ul><!--/.actionList-->

		</div><!--/#toRakutenBox.box-->
	</div><!--/#mainColumn-->

	<div id="subColumn">
	{%include file="slave/common/adbox.phtml"%}
	{%include file="slave/common/logbox.phtml"%}
	</div><!--/#subColumn-->

<script type="text/javascript">
    $j(document).ready(function() {
		adjustHeight();
    });
</script>
{%include file="slave/common/footer.phtml"%}