
        <br />
	<div style="color:#5b2806;">	
        <a name="top"></a>
      <span style="color:#5b2806; font-size:large:">ご当地ｷｬﾗｸﾀｰ取得</span><br />
        <br />
        <span style="color:#cc6600;">Q1.</span><a href='#001'>｢ご当地GET!｣とは､何ですか?</a><br />
        <span style="color:#cc6600;">Q2.</span><a href='#002'>その県まで自分がいかないと｢ご当地ｷｬﾗｸﾀｰ｣はもらえないの?</a><br />
        <span style="color:#cc6600;">Q3.</span><a href='#003'>｢ﾁｪｯｸする｣とは､何ですか?</a><br />
        <span style="color:#cc6600;">Q4.</span><a href='#004'>ﾄﾚｰﾄﾞは､どうすればできますか?</a><br />
        <span style="color:#cc6600;">Q5.</span><a href='#005'>県の境界では､ご当地ｷｬﾗｸﾀｰは､2つ取得できますか?</a><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="001"></a>
      <span style="color:#cc6600;">Q1.｢ご当地GET｣とは､何ですか?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>各都道府県にあるご当地ｷｬﾗｸﾀｰを手に入れることができます｡また、同じご当地ｷｬﾗｸﾀｰは､3体まで手に入れることができます｡<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
      
      <a name="002"></a>
      <span style="color:#cc6600;">Q2.その県まで自分がいかないと｢ご当地ｷｬﾗｸﾀｰ｣はもらえないの?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A2.</span>ご当地ｷｬﾗｸﾀｰの取得方法は､その県に行って取得する以外にも､ﾏｲﾐｸとﾄﾚｰﾄﾞ､ﾀｰｹﾞｯﾄﾂｱｰで取得することができます｡<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
      
        <a name="003"></a>
        <span style="color:#cc6600;">Q3.｢ﾁｪｯｸする｣とは､何ですか?</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A3.</span>ﾀｰｹﾞｯﾄﾂｱｰにおける日々の移動距離を測定するﾎﾞﾀﾝです｡都道府県内でも都道府県外への移動でも､位置情報をもとに測定します｡<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="004"></a>
        <span style="color:#cc6600;">Q4.ﾄﾚｰﾄﾞは､どうすればできますか?</span><br />            
        {% disneyimg style='height="5"' name="dot0" %}<br />           
        <span style="color:#3300FF;">A4.</span>ﾏｲﾐｸ情報からﾏｲﾐｸのﾆｯｸﾈｰﾑを押下後､表示される画面の｢ﾄﾚｰﾄﾞ｣ﾎﾞﾀﾝを押下してください｡完了画面まで表示されたらﾄﾚｰﾄﾞﾘｸｴｽﾄの完了です｡ﾄﾚｰﾄﾞは､相手が､ﾘｸｴｽﾄを承認されるまで､されません｡<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="005"></a>
        <span style="color:#cc6600;">Q5.県の境界では､ご当地ｷｬﾗｸﾀｰは､2つ取得できますか?</span><br />          
        {% disneyimg style='height="5"' name="dot0" %}<br />   
        <span style="color:#3300FF;">A5.</span>ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝは､ｹｰﾀｲの基地局情報をもとに､距離や､都道府県を判断しています｡そのため､ﾕｰｻﾞｰの皆様がいる場所から一番近い基地局からﾃﾞｰﾀを取得し､どちらか､一方のご当地ｷｬﾗｸﾀｰを手に入れることが出来ます｡<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
	 </div> 
	  