			
			<br />
			<div style="color:#5b2806;">		
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">ｹﾞｰﾑﾁｹｯﾄ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>ｹﾞｰﾑﾁｹｯﾄを買うには､どうすればいいですか?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>ｹﾞｰﾑﾁｹｯﾄは､他にも使えますか?</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.ｹﾞｰﾑﾁｹｯﾄを買うには､どうすればいいですか?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>ﾄｯﾌﾟﾍﾟｰｼﾞ内､のりものﾙｰﾚｯﾄ下部にある｢ﾁｹｯﾄ購入はこちら｣から購入画面へと進んでください｡<br />
			<span style="#ff0000">※購入には､mixiﾎﾟｲﾝﾄが必要です｡(ﾁｹｯﾄ1枚30pt･5枚140pt･10枚270pt)</span><br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="002"></a>
			<span style="color:#cc6600;">Q2.ｹﾞｰﾑﾁｹｯﾄは､他にも使えますか?</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />                   
			<span style="color:#3300FF;">A2.</span>現在は､のりものﾙｰﾚｯﾄのみに対応しています｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			</div>	
