			
			<br />
			<div style="color:#5b2806;">
			<span style="color:#5b2806; font-size:large:">ﾏｲﾐｸ招待</span><br />
			<br />
			<span style="color:#cc6600;">Q1.ﾏｲﾐｸを招待したのに､ｹﾞｰﾑﾁｹｯﾄがもらえません｡</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>
			ﾏｲﾐｸを招待後､そのﾏｲﾐｸがﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝに登録しなければﾁｹｯﾄを手に入れることができません｡まだ､登録していないか､招待ﾒｯｾｰｼﾞに気づいていない可能性があります｡<br />
			
			</div>
