
        <br />
	<div style="color:#5b2806;">	
        <a name="top"></a>
      <span style="color:#5b2806; font-size:large:">ﾒｰﾙﾌｧｸﾄﾘｰ会員特典</span><br />
        <br />
        <span style="color:#cc6600;">Q1.</span><a href='#001'>ﾒｰﾙﾌｧｸﾄﾘｰ会員特典とは､何ですか?</a><br />
        <span style="color:#cc6600;">Q2.</span><a href='#002'>会員なのに､特典ｱﾜｰﾄﾞがもらえません｡</a><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="001"></a>
      <span style="color:#cc6600;">Q1.ﾒｰﾙﾌｧｸﾄﾘｰ会員特典とは､何ですか?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>ﾃﾞｨｽﾞﾆｰﾓﾊﾞｲﾙ公式ｻｲﾄ｢ﾒｰﾙﾌｧｸﾄﾘｰ｣の会員に贈る特別特典です｡非会員の場合は､会員登録後､お楽しみください｡※このﾍﾟｰｼﾞは､会員登録状況確認のため途中外部ｻｲﾄへ移動します｡<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="002"></a>
        <span style="color:#cc6600;">Q2.会員なのに､特典ｱﾜｰﾄﾞがもらえません｡</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A2.</span>登録確認の途中何らかの原因で､確認状況完了画面まで表示されなかった場合､ｱﾜｰﾄﾞを手に入れことができません｡もう一度､最初からやり直してください｡<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>
	</div>	
		