			
			<br />
			<div style="color:#5b2806;">	
			<a name="top"></a>
			<span style="color:#5b2806; font-size:large:">ﾁｬﾚﾝｼﾞｹﾞｰﾑ</span><br />
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>のりものﾙｰﾚｯﾄって､何ですか?</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>のりものﾙｰﾚｯﾄができません｡</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.のりものﾙｰﾚｯﾄって､何ですか?</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>
			ﾀｰｹﾞｯﾄﾂｱｰの距離を稼ぐﾐﾆｹﾞｰﾑです｡のりものによって､距離は異なります｡<br />
			<span style="color:ff0000;">※ｹﾞｰﾑをするには､ｹﾞｰﾑﾁｹｯﾄが必要になります｡</span><br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="002"></a>
			<span style="color:#cc6600;">Q2.のりものﾙｰﾚｯﾄができません｡</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />                   
			<span style="color:#3300FF;">A2.</span>
			のりものﾙｰﾚｯﾄをするには､ｹﾞｰﾑﾁｹｯﾄを事前に購入する必要があります｡<br />
			<span style="color:ff0000;">※購入には､mixiﾎﾟｲﾝﾄが必要です｡(ﾁｹｯﾄ1枚30pt･5枚140pt･10枚270pt)</span><br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			</div>	
