
        <br />
	<div style="color:#5b2806;">
      <span style="color:#5b2806; font-size:large:">ｱﾜｰﾄﾞ</span><br />
        <br />
        <span style="color:#cc6600;">Q1.</span><a href='#001'>ｱﾜｰﾄﾞって何ですか?</a><br />
        <span style="color:#cc6600;">Q2.</span><a href='#002'>ｱﾜｰﾄﾞは、その場でもらえますか?</a><br />
        
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="001"></a>
      <span style="color:#cc6600;">Q1.ｱﾜｰﾄﾞって何ですか?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>ｱﾜｰﾄﾞは､あなたのｱﾌﾟﾘ内での様々な｢功績｣に対して付与されるｺﾚｸｼｮﾝｱｲﾃﾑです｡GETすると､｢功績｣には､例えば｢ﾏｲﾐｸを5人招待する｣､｢あるｴﾘｱのご当地ｷｬﾗｸﾀｰを全て集める｣など､様々な種類が用意されています｡どんな功績にｱﾜｰﾄﾞが付与されるかはﾋﾐﾂですが､｢もっとﾂｱｰを楽しもう｣ｺｰﾅｰに情報が出ることもあるようです｡また､ｱﾜｰﾄﾞをGETすると､ﾗﾝｷﾝｸﾞに作用する｢点数｣も付与されます｡(高得点のものが多いようです)<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>		
      
	  {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
	  
        <a name="002"></a>
      <span style="color:#cc6600;">Q2.ｱﾜｰﾄﾞは、その場でもらえますか?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A2.</span>ｱﾜｰﾄﾞは、翌日にご当地ｺﾚｸｼｮﾝへｱｸｾｽしたﾀｲﾐﾝｸﾞで付与されます。<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
	 </div> 
