
        <br />
	<div style="color:#5b2806;">	
        <a name="top"></a>
      <span style="color:#5b2806; font-size:large:">ｱｲﾃﾑｼｮｯﾌﾟ</span><br />
        <br />
        <span style="color:#cc6600;">Q1.</span><a href='#001'>ｱｲﾃﾑｼｮｯﾌﾟとは?</a><br />
        <span style="color:#cc6600;">Q2.</span><a href='#002'>ｱｲﾃﾑの種類は、何種類ありますか?</a><br />
        <span style="color:#cc6600;">Q3.</span><a href='#003'>ｱｲﾃﾑは、回数がある限り、移動距離に反映されますか?</a><br />
        <span style="color:#cc6600;">Q4.</span><a href='#004'>一度購入したｱｲﾃﾑを変更することは、できますか?</a><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="001"></a>
      <span style="color:#cc6600;">Q1.ｱｲﾃﾑｼｮｯﾌﾟとは?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>稼いだ距離を自動的に数倍にするｱｲﾃﾑを購入する事ができるｼｮｯﾌﾟです。<br />
      <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
      </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="002"></a>
        <span style="color:#cc6600;">Q2.ｱｲﾃﾑの種類は、何種類ありますか?</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A2.</span>現在、快適ｼｭｰｽﾞとｺﾞｰﾙﾄﾞ･ｼｭｰｽﾞの2種類あります。<br />
		ｰ快適ｽﾆｰｶｰは、2倍以上稼ぐ事が出来ます。(mixiﾎﾟｲﾝﾄが50pt必要です)<br />
		ｰｺﾞｰﾙﾄ・ｼｭｰｽﾞは、5倍以上稼ぐ事が出来ます。(mixiﾎﾟｲﾝﾄが100pt必要です）<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="003"></a>
        <span style="color:#cc6600;">Q3.ｱｲﾃﾑは、回数がある限り、移動距離に反映されますか?</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A3.</span>一度、ｱｲﾃﾑを購入すると、次回の「ﾁｪｯｸ!｣時にもｱｲﾃﾑの効果は、反映されます。<br />
　		なお、移動距離が0kmの場合は、ｱｲﾃﾑの効果は、反映されません(使用回数も消費されません）<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>    
      {% disneyimg style='height="5"' name="dot0" %}<br />
        {% disneyimg name="fna_line2" %}<br />
      {% disneyimg style='height="5"' name="dot0" %}<br />
        <a name="004"></a>
        <span style="color:#cc6600;">Q4.一度購入したｱｲﾃﾑを変更することは、できますか?</span><br /> 
        {% disneyimg style='height="5"' name="dot0" %}<br />                   
        <span style="color:#3300FF;">A4.</span>一度購入したｱｲﾃﾑは、使い切るまで、他のｱｲﾃﾑ並びに同じｱｲﾃﾑを続けて購入することはできません。<br />
　 		他のｱｲﾃﾑを購入したい場合、現在、持っているｱｲﾃﾑを全て使用した後に、購入してください。<br />
        <div style="text-align:right;">
            <a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
        </div>    
	</div>