
        <br />
	<div style="color:#5b2806;">
      <span style="color:#5b2806; font-size:large:">ﾏｲﾐｸに贈る</span><br />
        <br />
      <span style="color:#cc6600;">Q1.ﾏｲﾐｸにご当地ｷｬﾗｸﾀｰを贈るには?</span><br />
      {% disneyimg style='height="5"' name="dot0" %}<br />         
        <span style="color:#3300FF;">A1.</span>自分のご当地ﾏｯﾌﾟ内の各都道府県名をｸﾘｯｸ後､｢ﾏｲﾐｸに贈る｣を押下してください｡その後､贈りたいﾏｲﾐｸを選択し､送付の完了画面が表示されたら完了となります｡また､贈ったご当地ｷｬﾗｸﾀｰは､自分の手元にも残ります｡※｢友達に贈る｣には､mixiﾎﾟｲﾝﾄが200pt必要です｡<br />

    </div>
	  