			
			<br />
			<a name="top"></a>
			<div style="color:#5b2806;">
			<br />
			<span style="color:#cc6600;">Q1.</span><a href='#001'>ﾀｰｹﾞｯﾄﾂｱｰで移動距離が正しくないような気がします。</a><br />
			<span style="color:#cc6600;">Q2.</span><a href='#002'>｢ご当地GET!｣を押したら現在地と異なるご当地ｷｬﾗｸﾀｰが取得されました｡</a><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="001"></a>
			<span style="color:#cc6600;">Q1.ﾀｰｹﾞｯﾄﾂｱｰで移動距離が正しくないような気がします。</span><br />
			{% disneyimg style='height="5"' name="dot0" %}<br />         
			<span style="color:#3300FF;">A1.</span>
			ﾃﾞｨｽﾞﾆｰご当地ｺﾚｸｼｮﾝは、携帯電話の基地局の場所を基に距離を算出しています。そのため、実際の移動距離ではなく、最初に”ﾁｪｯｸする!”を押した地点に一番近い基地局と、次に移動して”ﾁｪｯｸする!”を押した地点で一番近い基地局の間の距離を測ります。ﾀｰｹﾞｯﾄﾂｱｰでは、距離を移動距離として表示しています。<br />※GPS機能を用いた位置情報確認では、ありません。
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			{% disneyimg style='height="5"' name="dot0" %}<br />
			{% disneyimg name="fna_line2" %}<br />
			{% disneyimg style='height="5"' name="dot0" %}<br />
			
			<a name="002"></a>
			<span style="color:#cc6600;">Q2.｢ご当地GET!｣を押したら現在地と異なるご当地ｷｬﾗｸﾀｰが取得されました｡</span><br /> 
			{% disneyimg style='height="5"' name="dot0" %}<br />                   
			<span style="color:#3300FF;">A2.</span>
			｢ご当地GET!｣は､現在いる場所から一番近い基地局の情報を取得します｡そのため､県境にいた場合､一番近い基地局の情報を基にご当地ｷｬﾗｸﾀｰを取得することになります｡<br />※GPS機能を用いた位置情報確認では､ありません｡<br />
			<div style="text-align:right;">
				<a href="#top">ﾍﾟｰｼﾞの先頭へ戻る</a><br />
			</div>
			</div>
