<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="robots" content="noindex,nofollow" />
</head>
<body>
<div style="margin: -5px 0px -5px -5px; width: 250px; left: -690px; position: absolute; height: 250px; top: -35px;">
<script type="text/javascript" language="javascript">
    var url ="http://mixi.jp/ad_application_program_invoker.pl?appli_id={%$appId%}&ad_id=f542a475c4fdec8367ed9831d3b2f92c28557075";
    document.writeln(['<scri','pt src="',url,'&ts=',(new Date).getTime(),'">','</scri','pt>'].join(''));
</script>
</div>
</body>
</html>
