	{% disneyimg name="faq_line" style='align="top" width="100%"' %}
	<div style="background-color:#ccff66;text-align:left;">
		{% disneyimg style='height="3"' name="dot0" %}<br />
		<span style="color:#3ea124;">├</span>{% emoji code="F8E4"%}<a href='{% "$baseUrl/mobile/disney/rule"|mixiurl %}'>利用規約</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F97A"%}<a href='{% "$baseUrl/mobile/disney/charge"|mixiurl %}'>有料ｻｰﾋﾞｽ利用規約</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9B8"%}<a href='{% "$baseUrl/mobile/disney/tokus"|mixiurl %}'>特定商取引法に基づく表示</a><br />
		<span style="color:#3ea124;">└</span>{% emoji code="F9A0"%}<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}'>よくある質問</a><br />
		{% disneyimg style='height="3"' name="dot0" %}<br />
	</div>
</div>

</body>
</html>