        
            {% emoji code="F9E5"%}<a href='{% "$baseUrl/mobile/disney/map"|mixiurl %}'><span style="color:#430FBD;">ご当地ﾏｯﾌﾟ</span></a>
            {% emoji code="F9D8"%}<!--<a href='#game'>--><span style="color:#430FBD;">ｹﾞｰﾑ(準備中)</span><!--</a>--><br />
        
        <div style="text-align:center; background-color:#FFB300;" >    
            {% emoji code="F8C4"%}<a href='{% "$baseUrl/mobile/disney/index"|mixiurl %}'><span style="color:#D6340C;">TOP</span></a>
            {% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/disney/cuplist"|mixiurl %}'><span style="color:#D6340C;">ｱﾜｰﾄﾞ</span></a>
            {% emoji code="F9CB"%}<a href='{% "$baseUrl/mobile/disney/mymixilist"|mixiurl %}'><span style="color:#D6340C;">ﾏｲﾐｸ情報</span></a><br />
        </div></div> 