{%include file="dynamite/common/header.phtml" headAd=1 %}

<div id="itemConfirm">

    <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
    <div class="headline" style="background:#777777;color:#ffffff;">アイテム購入</div>
    <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	<table width="100%" cellpadding="0" cellspacing="0" border="0">
		<tr>
			<td width="60" valign="top" align="center" style="width:60px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/item/{%$selectedItem.cid%}.gif" width="56" height="56" /></td>
			<td style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">{%$selectedItem.name%}</td>
		</tr>
	</table>

	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	<table width="228" cellpadding="2" cellspacing="1" border="0" align="center" style="background:#eeaa55;text-align:center;">
		<tr>
			<td style="background:#fffdde;text-align:left;"><div style="color:#000000;{% if $ua==1 %}font-size:x-small;{% /if %}">【アイテム効果】<br />{%$selectedItem.introduce%}</div></td>
		</tr>
	</table>

	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	<div class="status">
		{%if $selectedItem.cid==60 || $selectedItem.cid==61 || $selectedItem.cid==62%}
			ﾀﾞｲﾅﾏｲﾄ所持数:{%$myDynamiteInfo.bomb_count%}個<br />
        {% else %}
			所持数:{%$itemCount%}個<br />
		{% /if %}
		{%if $price==0%}
			<span style="color:#ff0000;">※このｱｲﾃﾑは､所持金では購入できません</span><br />
		{% else %}
			所持金:${%$bonus%}<br />
			価　格:${%$price%}<br />
		{%/if%}
	</div><!--/.status-->

	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	{%if $flag=='noEnoughMoney'%}
		<div class="purchase">
			◎所持金で購入する<br />
			<div style="color:#ff0000;text-align:center;">所持金不足です！</div>
		</div><!--/.purchase-->
	{%/if%}

	{%if $flag=='twoMethod'%}
		<div class="purchase">
			◎所持金で購入する<br />
			<div class="buy" style="text-align:center;">
				<form name="buyitem" action='{% "$baseUrl/mobile/dynamite/buyitemconfirm"|mixiurl %}' method="post">
					<input type="hidden" name="CF_cid" value="{%$selectedItem.cid%}" />
					{%$buyNum|create_select%}
					<input type="submit" style="color:#333333;" value=" 購 入 " />
				</form>
			</div><!--/.buy-->
		</div><!--/.purchase-->

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	{%/if%}

	<div class="purchase">
		◎mixiﾎﾟｲﾝﾄで購入する<br />
		<div class="buy" style="text-align:center;">
			<form name="buyitem" action='{% "$baseUrl/mobile/dynamite/buyitembymixipointconfirm"|mixiurl %}' method="post">
				<input type="hidden" name="CF_cid" value="{%$selectedItem.cid%}" />
				<input type="submit" style="color:#333333;" value=" 購 入 " />
			</form>
			<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
			<a href='{% "$baseUrl/mobile/dynamite/help?CF_help=privacy"|mixiurl %}'>ﾌﾟﾗｲﾊﾞｼｰﾎﾟﾘｼｰ</a><br />
			<a href='{% "$baseUrl/mobile/dynamite/help?CF_help=tokusho"|mixiurl %}'>特商法に基づく表記</a><br />
		</div><!--/.buy-->
	</div><!--/.purchase-->

	<br />

	<div class="toTop">
		<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/itemshop"|mixiurl %}'>アイテムストアへ</a><br />
	</div><!--/.toTop-->

</div><!--/#itemConfirm-->
{%include file="dynamite/common/footer.phtml" footAd=1 %}
