{%include file="dynamite/common/header.phtml" headAd=1 %}

<div id="itemConfirm">
	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	<div class="headline" style="background:#777777;color:#ffffff;">ｱｲﾃﾑｽﾄｱ</div>
	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	<div class="section">
		<table width="100%" cellpadding="0" cellspacing="0" border="0">
			<tr>
				<td width="60" valign="top" align="center" style="width:56px;text-align:center;vertical-align:top;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/item/{%$buyItemInfo.selectedItem.cid%}.gif" width="56" height="56" style="margin:2px 0;" /></td>
				<td style="color:#ffffff;{% if $ua==1 %}font-size:x-small;{% /if %}">{%$buyItemInfo.selectedItem.name%}</td>
			</tr>
		</table>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<table width="228" cellpadding="2" cellspacing="1" border="0" style="background:#eeaa55;text-align:center;">
			<tr>
				<td style="background:#fffdde;text-align:left;"><div style="color:#000000;{% if $ua==1 %}font-size:x-small;{% /if %}">【アイテム効果】<br />{%$buyItemInfo.selectedItem.introduce%}</div></td>
			</tr>
		</table>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="status">
			{%if $buyItemInfo.selectedItem.cid==60 || $buyItemInfo.selectedItem.cid==61 || $buyItemInfo.selectedItem.cid==62 %}ﾀﾞｲﾅﾏｲﾄ所持数:{%$myDynamiteInfo.bomb_count%}{% else %}所持数:{%$buyItemInfo.itemCount%}{% /if %}個<br />
			{%if $buyItemInfo.itemPrice==0%}
				mixiﾎﾟｲﾝﾄでのみ購入可<br />
			{%else%}
				所持金:${%$buyItemInfo.bonus|outputdollars%}<br />
				価　格:${%$buyItemInfo.itemPrice|outputdollars%}<br />
			{%/if%}
		</div><!--/.status-->

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div style="color:#ff0000;text-align:center;">所持数の最大値を越えるため<br />購入出来ません</div>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

    </div><!--/.section-->

    <div class="toTop">
		<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/itemshop"|mixiurl %}'>アイテムストアへ</a>&nbsp;
    </div><!--/.toTop-->

</div><!--/#itemConfirm-->
{%include file="dynamite/common/footer.phtml" footAd=1 %}