{%include file="dynamite/common/header.phtml" headAd=0 %}

<div id="itemFinish">

	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	<div class="headline" style="background:#777777;color:#ffffff;">ｱｲﾃﾑ購入完了</div>
	<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

	<div class="description">
		{%$itemName%}を購入しました！<br />
		最強のｱｼﾞﾄを目指してがんばろう！<br />
	</div><!--/.description-->

	<div class="ad" style="text-align:center;">
		<ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="center" id="e13e01e7665fd609fcbaefd8c14529db05f65184" />
	</div><!--/.ad-->

	<div class="toTop">
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
		<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/itemlist"|mixiurl %}'>所有ｱｲﾃﾑ一覧へ</a><br />
		<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/itemshop"|mixiurl %}'>ｱｲﾃﾑｽﾄｱへ</a><br />
	</div><!--/.toTop-->

</div><!--/#itemFinish-->
{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}