{%include file="dynamite/common/header.phtml" headAd=1 %}

	{% if $mode=="1" %}
	<div id="dynamiteSet">
		<div class="actionImg" style="text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/set/{%$picName%}" width="210" height="160" style="margin:3px 0;" /></div>
		<div class="description">{%$profileInfo.displayName%}組にﾀﾞｲﾅﾏｲﾄを設置しました。{% $waitTime %}分以上経過すると、爆破することができます。</div>
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="toTop">
			{% if $isFromFlash %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$profileInfo.profile_uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>{%$profileInfo.displayName%}組のｱｼﾞﾄへ</a>&nbsp;
			{% else %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$profileInfo.profile_uid`"|mixiurl %}'>{%$profileInfo.displayName%}組へ</a>&nbsp;
			{% /if %}
		</div><!--/.toTop-->
	</div><!--/#dynamiteSet-->
	{% /if %}

	{% if $mode=="2" %}
	<div id="dynamiteHoihoi">
		<div class="actionImg" style="text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/hoihoi.gif" width="90" height="90" style="margin:3px 0;" /></div>
		<div class="description">{%$profileInfo.displayName%}組のｱｼﾞﾄにﾀﾞｲﾅﾏｲﾄほいほいが仕掛けられていたため、設置しようとしたﾀﾞｲﾅﾏｲﾄが奪われてしまいました!</div>
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="toTop">
			{% if $isFromFlash %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$profileInfo.profile_uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>{%$profileInfo.displayName%}組のｱｼﾞﾄへ</a>&nbsp;
			{% else %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$profileInfo.profile_uid`"|mixiurl %}'>{%$profileInfo.displayName%}組へ</a>&nbsp;
			{% /if %}
		</div><!--/.toTop-->
	</div><!--/#dynamiteHoihoi-->
	{% /if %}

	{% if $mode=="3" %}
	<div id="clash">
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
		<div class="headline" style="background:#777777;color:#ffffff;">設置失敗!!</div>
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="description">
			他の組織に先を越されました…。
		</div><!--/.description-->

		<div class="nullImage" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/dynamite/mobile/img/null.gif" width="118" height="106" style="margin:2px 0;" />
		</div><!--/.nullImage-->

		<div class="toProfile">
			{% if $isFromFlash %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$profileInfo.profile_uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>{%$profileInfo.displayName%}組のｱｼﾞﾄへ</a>
			{% else %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$profileInfo.profile_uid`"|mixiurl %}'>{%$profileInfo.displayName%}組へ</a>
			{% /if %}
		</div><!--/.toProfile-->
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	</div><!--/#clash-->
	{% /if %}

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}