{%include file="dynamite/common/header.phtml" headAd=1 %}

    <div id="dynamitelist">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">設置中のダイナマイト</div>

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="dynamite" style="text-align:right;">ﾀﾞｲﾅﾏｲﾄ:設置中x{%$setBombCount%}<span style="color:#666666;">|</span>未使用x{%$myDynamiteInfo.remainder_bomb_count%}&nbsp;</div><!--/.dynamite-->

        {% foreach from=$userBomb item=data key=key %}
            <div class="section" style="background:#{%if $key%2==0 %}#000000{%else%}#333333{%/if%};">
                <table width="100%" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <td width="23" align="center" style="width:27px;text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/dynamite/b/{%$data.bomb_power%}_mine{%if $data.needWait!=1%}_use{%/if%}.gif" width="23" height="32" style="margin:2px 0;" /></td>
                        <td style="color:#ffffff;font-size:x-small;"><a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$data.bomb_uid`&CF_hitmanid=`$data.bomb_hitman`"|mixiurl %}'>{%$data.displayName%}</a><span style="color:#ff9933;">組</span><br />
                            {%if $data.waitTime>0%}あと{%$data.waitTime%}分で爆破可能!{%else%}今すぐ爆破できます!!{%/if%}</td>
                    </tr>
                </table>
            </div><!--/.section-->
        {% foreachelse %}
            <div class="nullImage" style="text-align:center;">
                <img src="{%$staticUrl%}/apps/dynamite/mobile/img/null.gif" width="118" height="106" />
            </div><!--/.nullImage-->

            <div class="description">
                まだﾀﾞｲﾅﾏｲﾄを設置していません。<br />
                <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
                爆破される前に爆破する…それが理解できない奴には屈辱が待っている。<br />
                はやくﾀﾞｲﾅﾏｲﾄを設置しよう！<br />
            </div><!--/.description-->

            <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

            <div class="toAgit" style="text-align:center;">
                <span style="color:#ff9933;">≫</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$myDynamiteInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>ｱｼﾞﾄを巡回する!</a><span style="color:#ff9933;">≪</span>
            </div><!--/.toAgit-->

        {% /foreach %}

        {% if $pager.maxPager > 1 %}
            <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

            <div class="nav" style="color:#ff9933;text-align:center;">
                <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
                {%include file="dynamite/common/pager.phtml"%}
            </div><!--/.nav-->
        {% /if %}
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
		※ﾀﾞｲﾅﾏｲﾄは設置中･未使用含め､合計26個まで所有できます｡<br />
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

    </div><!--/#dynamitelist-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}

