{%include file="dynamite/common/header.phtml" headAd=1 %}

	{% if $mode=="1" %}
	<div id="dynamiteRemove">

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
		<div class="headline" style="background:#777777;color:#ffffff;">ダイナマイト撤去</div>
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="dynamiteImg" style="text-align:center;">{% foreach name=bomblist from=$lstRemoveBomb item=bdata %}<img src="{%$staticUrl%}/apps/dynamite/mobile/img/remove/{%$bdata.bomb_power%}.gif" width="51" height="58" style="margin:0 2px;" />{% /foreach %}</div>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="description">ﾀﾞｲﾅﾏｲﾄを撤去し、ﾀﾞｲﾅﾏｲﾄを{%$cntRemoveBomb%}つGETしました！{%$myDynamiteInfo.displayName%}組を敵に回したことを後悔させてあげましょう。</div>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		{% if $lstRemoveBomb %}
		<div class="toTop">
			{% foreach name=linklist from=$lstRemoveBomb item=ldata %}
			{% if $isFromFlash %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$ldata.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>{%$ldata.displayName%}組のｱｼﾞﾄへ</a>&nbsp;<br />
			{% else %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$ldata.uid`"|mixiurl %}'>{%$ldata.displayName%}組へ</a>&nbsp;<br />
			{% /if %}
			{% /foreach %}
		</div><!--/.toTop-->
		{% /if %}
	</div><!--/#dynamiteRemove-->
	{% /if %}

	{% if $mode=="3" %}
	<div id="clash">
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
		<div class="headline" style="background:#777777;color:#ffffff;">撤去失敗!!</div>
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="description">
			他の組織に先を越されました…。
		</div><!--/.description-->

		<div class="nullImage" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/dynamite/mobile/img/null.gif" width="118" height="106" style="margin:2px 0;" />
		</div><!--/.nullImage-->

		<div class="toProfile">
			{% if $isFromFlash %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$myDynamiteInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>{%$myDynamiteInfo.displayName%}組のｱｼﾞﾄへ</a>
			{% else %}
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$myDynamiteInfo.uid`"|mixiurl %}'>{%$myDynamiteInfo.displayName%}組へ</a>
			{% /if %}
		</div><!--/.toProfile-->

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	</div><!--/#clash-->
	{% /if %}

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}