{%include file="dynamite/common/header.phtml" headAd=1 %}

    <div id="enemylist">
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">敵対ﾕｰｻﾞｰ一覧({%if $enemyCount%}{%$enemyCount%}{%else%}0{%/if%})</div>

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {% if $enemyCount > 0 %}
            <div class="description">
                        ﾊﾞﾄﾙ履歴のあるﾕｰｻﾞｰを最新順に表示しています｡
            </div><!--/.description-->
    
            <hr style="color:#333333;background-color:#333333;height:1px;border:0px solid #333333;margin:0.3em 0;" size="1" />
        
            <div class="description">{%$enemyCount%}件中 {%if $startNm==$endNm%}{%$startNm%}{%else%}{%$startNm%}-{%$endNm%}{%/if%}件</div>
        {% /if %}
        
        {% foreach from=$enemyList item=data key=key %}
            <div class="section" style="background:{%if $key%2==0 %}#000000{%else%}#333333{%/if%};">
                <table width="100%" cellpadding="0" cellspacing="0" border="0">
                    <tr>
                        <td width="44" valign="top" align="center" style="width:44px;text-align:center;vertical-align:top;"><img src="{%$data.miniThumbnailUrl%}" style="margin:2px 0;" /></td>
                        <td style="color:#ffffff;font-size:x-small;"><a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$data.uid`"|mixiurl %}'>{%$data.displayName%}</a><span style="color:#ff9933;">組</span><br />
                            所持金 ${%$data.bonus|outputdollars%}</td>
                    </tr>
                </table>
            </div><!--/.section-->
        {% foreachelse %}
            <div class="description">
                まだﾊﾞﾄﾙしたﾕｰｻﾞｰが参加していません｡
            </div><!--/.description-->
    
            <div class="nullImage" style="text-align:center;">
                <img src="{%$staticUrl%}/apps/dynamite/mobile/img/null.gif" width="118" height="106" style="margin:2px 0;" />
            </div><!--/.nullImage-->
    
            <div class="toInvite" style="text-align:center;">
                <span style="color:#ff9933;">⇒</span>
                    <a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/dynamite/home" %}'>ﾏｲﾐｸ招待で強力ｱｲﾃﾑGET!</a>
            </div><!--/.toInvite-->
        {% /foreach %}
        
        
        {% if $pager.maxPager > 1 %}
            <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
    
            <div class="nav" style="color:#ff9933;text-align:center;">
                <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
                {%include file="dynamite/common/pager.phtml"%}
            </div><!--/.nav-->
        {% /if %}
        
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

    </div><!--/#enemylist-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}