{%include file="dynamite/common/header.phtml" headAd=0 %}

    <div id="error">

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">ｼｽﾃﾑｴﾗｰ</div>

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
                ｼｽﾃﾑｴﾗｰが発生しました。たいへんお手数ですが、TOPにお戻りください。
        </div><!--/.description-->

        <div class="nullImage" style="text-align:center;">
            <img src="{%$staticUrl%}/apps/dynamite/mobile/img/null.gif" width="118" height="106" style="margin:2px 0;" />
        </div><!--/.nullImage-->

        <div class="toTop">
            <span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/home"|mixiurl %}'>TOPﾍﾟｰｼﾞへ</a>
        </div><!--/.toTop-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

    </div><!--/#mistake-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=0 %}