{%include file="dynamite/common/header.phtml" headAd=1 %}

    <div id="minifeed">
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="font-size:x-small;background:#777777;color:#ffffff;">更新情報</div>

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description" style="color:#ffffff;font-size:x-small;">
            {%$myDynamiteInfo.displayName%}組に関連する情報の最新10件を表示しています｡
        </div><!--/.description-->

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        {% foreach from=$feed item=data %}
        <div class="section" style="color:#ffffff;font-size:x-small;">
            <hr style="color:#333333;background-color:#333333;height:1px;border:0px solid #333333;margin:0.3em 0;" size="1" />
            <span style="color:#666666;">〓</span>{%$data.feed_type%}<span style="color:#666666;">〓</span><br />
            <div class="inner" style="font-size:x-small;color:#cccccc;">{%$data.title%}</div>
            <div style="text-align:right;">{%$data.create_time|date_format:"%y/%m/%d %H:%M"%}</div>
        </div><!--/.section-->
        {% /foreach %}

    </div><!--/#minifeed-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}