{%include file="dynamite/common/header.phtml" headAd=0 %}

    <div id="inviteFinish">
        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="headline" style="background:#777777;color:#ffffff;">ｱﾌﾟﾘ招待 送信完了</div>

        <hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

        <div class="description">
			ｱﾌﾟﾘ招待の送信が完了しました｡強力ｱｲﾃﾑの獲得に関しては､招待した方が当ｱﾌﾟﾘを追加した後､2-3日ほどお時間がかかることがあります｡あらかじめご了承ください｡<br />
        </div><!--/.description-->

		<div class="ad" style="text-align:center;">
            <ad xmlns="http://m.mixi.jp/2009/AdProgram/" type="center" id="e13e01e7665fd609fcbaefd8c14529db05f65184" />
        </div><!--/.ad-->

    </div><!--/#inviteFinish-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=0 %}