{%include file="dynamite/common/header.phtml" headAd=1 %}

	<div id="profile">
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="owner" style="background:#666666;">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="44" align="center" style="width:44px;text-align:center;"><img src="{%$profileDynamiteInfo.miniThumbnailUrl%}" style="margin:2px 0;" /></td>
					<td style="color:#ffffff;font-size:x-small;">{%$profileDynamiteInfo.displayName%}組<br />
						所持金 ${%$profileDynamiteInfo.format_bonus%}<br />
						{% if $profileDynamiteInfo.game_mode==1 %}ﾏｲﾐｸ限定ﾓｰﾄﾞ{% else %}ﾐｸｼｨ全体ﾓｰﾄﾞ{% /if %}</td>
				</tr>
			</table>
		</div><!--/.owner-->

		<div class="toAgit" style="text-align:center;"><a href='{% "$baseUrl/mobile/dynamite/agit?CF_uid=`$profileDynamiteInfo.uid`&opensocial_app_id=`$APP_ID`&opensocial_owner_id=`$myDynamiteInfo.uid`&rand=`$rand`"|mobile_flashurl %}'>≫ｱｼﾞﾄに潜入する!≪</a></div>

		<div class="section" style="background:#333333;">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/hitman/{%$profileDynamiteInfo.hitman_pic_1%}" width="60" height="60" style="margin:2px 0;" /></td>
					<td style="color:#ffffff;font-size:x-small;">ﾋｯﾄﾏﾝA{% if 0==$profileDynamiteInfo.hitman_life1 %}(殉職){% /if %}<br />
						<img src="{%$staticUrl%}/apps/dynamite/mobile/img/heart/max{%$profileDynamiteInfo.max_life%}/{%$profileDynamiteInfo.hitman_life1%}.gif" width="135" height="14" style="margin-top:2px;" /><br />
						<div style="text-align:right;">懸賞金 ${% if 0==$profileDynamiteInfo.hitman_life1 %}0{% else %}{%$profileDynamiteInfo.format_reward%}{% /if %}&nbsp;</div></td>
				</tr>
			</table>

			{% if "1"==$profileDynamiteInfo.has_my_bomb_hitman_1 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=1"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫ﾀﾞｲﾅﾏｲﾄ設置中!≪</span></a>
			</div><!--/.enemy-->
			{% else %}
				{% if $profileDynamiteInfo.setted_bomb_count_hitman_1 >0 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=1"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫敵対組織が襲撃中!≪</span></a>
			</div><!--/.enemy-->
				{% else %}
				{% if $canSetBomb == 1 && $profileDynamiteInfo.hitman_life1>0 && $myDynamiteInfo.remainder_bomb_count>0 %}<div class="hint" style="text-align:right;"><span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/dynamiteset?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=1"|mixiurl %}'>ﾀﾞｲﾅﾏｲﾄ設置</a>&nbsp;</div><!--/.hint-->{% /if %}
				{% /if %}
			{% /if %}
		</div><!--/.section-->

		<div class="section" style="background:#000000;">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/hitman/{%$profileDynamiteInfo.hitman_pic_2%}" width="60" height="60" style="margin:2px 0;" /></td>
					<td style="color:#ffffff;font-size:x-small;">ﾋｯﾄﾏﾝB{% if 0==$profileDynamiteInfo.hitman_life2 %}(殉職){% /if %}<br />
						<img src="{%$staticUrl%}/apps/dynamite/mobile/img/heart/max{%$profileDynamiteInfo.max_life%}/{%$profileDynamiteInfo.hitman_life2%}.gif" width="135" height="14" style="margin-top:2px;" /><br />
						<div style="text-align:right;">懸賞金 ${% if 0==$profileDynamiteInfo.hitman_life2 %}0{% else %}{%$profileDynamiteInfo.format_reward%}{% /if %}&nbsp;</div></td>
				</tr>
			</table>

			{% if "1"==$profileDynamiteInfo.has_my_bomb_hitman_2 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=2"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫ﾀﾞｲﾅﾏｲﾄ設置中!≪</span></a>
			</div><!--/.enemy-->
			{% else %}
				{% if $profileDynamiteInfo.setted_bomb_count_hitman_2 >0 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=2"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫敵対組織が襲撃中!≪</span></a>
			</div><!--/.enemy-->
				{% else %}
				{% if $canSetBomb == 1 && $profileDynamiteInfo.hitman_life2>0 && $myDynamiteInfo.remainder_bomb_count>0 %}<div class="hint" style="text-align:right;"><span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/dynamiteset?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=2"|mixiurl %}'>ﾀﾞｲﾅﾏｲﾄ設置</a>&nbsp;</div><!--/.hint-->{% /if %}
				{% /if %}
			{% /if %}
		</div><!--/.section-->

		<div class="section" style="background:#333333;">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">
				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/hitman/{%$profileDynamiteInfo.hitman_pic_3%}" width="60" height="60" style="margin:2px 0;" /></td>
					<td style="color:#ffffff;font-size:x-small;">ﾋｯﾄﾏﾝC{% if 0==$profileDynamiteInfo.hitman_life3 %}(殉職){% /if %}<br />
						<img src="{%$staticUrl%}/apps/dynamite/mobile/img/heart/max{%$profileDynamiteInfo.max_life%}/{%$profileDynamiteInfo.hitman_life3%}.gif" width="135" height="14" style="margin-top:2px;" /><br />
						<div style="text-align:right;">懸賞金 ${% if 0==$profileDynamiteInfo.hitman_life3 %}0{% else %}{%$profileDynamiteInfo.format_reward%}{% /if %}&nbsp;</div></td>
				</tr>

			</table>

			{% if "1"==$profileDynamiteInfo.has_my_bomb_hitman_3 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=3"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫ﾀﾞｲﾅﾏｲﾄ設置中!≪</span></a>
			</div><!--/.enemy-->
			{% else %}
				{% if $profileDynamiteInfo.setted_bomb_count_hitman_3 >0 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=3"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫敵対組織が襲撃中!≪</span></a>
			</div><!--/.enemy-->
				{% else %}
				{% if $canSetBomb == 1 && $profileDynamiteInfo.hitman_life3>0 && $myDynamiteInfo.remainder_bomb_count>0 %}<div class="hint" style="text-align:right;"><span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/dynamiteset?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=3"|mixiurl %}'>ﾀﾞｲﾅﾏｲﾄ設置</a>&nbsp;</div><!--/.hint-->{% /if %}
				{% /if %}
			{% /if %}
		</div><!--/.section-->

		<div class="section" style="background:#000000;">
			<table width="100%" cellpadding="0" cellspacing="0" border="0">

				<tr>
					<td width="64" align="center" style="width:64px;text-align:center;"><img src="{%$staticUrl%}/apps/dynamite/mobile/img/hitman/{%$profileDynamiteInfo.hitman_pic_4%}" width="60" height="60" style="margin:2px 0;" /></td>
					<td style="color:#ffffff;font-size:x-small;">ﾋｯﾄﾏﾝD{% if 0==$profileDynamiteInfo.hitman_life4 %}(殉職){% /if %}<br />
						<img src="{%$staticUrl%}/apps/dynamite/mobile/img/heart/max{%$profileDynamiteInfo.max_life%}/{%$profileDynamiteInfo.hitman_life4%}.gif" width="135" height="14" style="margin:2px 0;" /><br />
						<div style="text-align:right;">懸賞金 ${% if 0==$profileDynamiteInfo.hitman_life4 %}0{% else %}{%$profileDynamiteInfo.format_reward%}{% /if %}&nbsp;</div></td>
				</tr>
			</table>

			{% if "1"==$profileDynamiteInfo.has_my_bomb_hitman_4 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=4"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫ﾀﾞｲﾅﾏｲﾄ設置中!≪</span></a>
			</div><!--/.enemy-->
			{% else %}
				{% if $profileDynamiteInfo.setted_bomb_count_hitman_4 >0 %}
			<div class="enemy" style="text-align:center;">
			<a href='{% "$baseUrl/mobile/dynamite/attacklist?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=4"|mixiurl %}' style="color:#ff0000;"><span style="color:#ff0000;text-decoration:blink;">≫敵対組織が襲撃中!≪</span></a>
			</div><!--/.enemy-->
				{% else %}
				{% if $canSetBomb == 1 && $profileDynamiteInfo.hitman_life4>0 && $myDynamiteInfo.remainder_bomb_count>0 %}<div class="hint" style="text-align:right;"><span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/dynamiteset?CF_uid=`$profileDynamiteInfo.uid`&CF_hitmanid=4"|mixiurl %}'>ﾀﾞｲﾅﾏｲﾄ設置</a>&nbsp;</div><!--/.hint-->{% /if %}
				{% /if %}
			{% /if %}
		</div><!--/.section-->

		<div class="nav" style="color:#ff9933;text-align:center;">
			<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
			←[*]<a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$profileDynamiteInfo.prev_uid`"|mixiurl %}' accesskey="*">左の組織</a>　<a href='{% "$baseUrl/mobile/dynamite/profile?CF_uid=`$profileDynamiteInfo.next_uid`"|mixiurl %}' accesskey="#">右の組織</a>[#]→
		</div><!--/.nav-->

	</div><!--/#profile-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}