{%include file="dynamite/common/header.phtml" headAd=1 %}

	<div id="provideDynamite">
		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="headline" style="background:#777777;color:#ffffff;">ﾀﾞｲﾅﾏｲﾄ支給</div>

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />

		<div class="description">
			ﾀﾞｲﾅﾏｲﾄをすべて使いきったため、新品ﾀﾞｲﾅﾏｲﾄが4つ支給されました!
		</div><!--/.description-->

		<div class="dynamite" style="text-align:center;">
			<img src="{%$staticUrl%}/apps/dynamite/mobile/img/provide.gif" width="210" height="58" style="margin:2px 0;" />
		</div><!--/.dynamite-->

		<div class="toTop">
			<span style="color:#ff9933;">⇒</span><a href='{% "$baseUrl/mobile/dynamite/home"|mixiurl %}'>{%$myDynamiteInfo.displayName%}組へ</a>
		</div><!--/.toTop-->

		<hr style="color:#000000;background-color:#000000;height:1px;border:0px solid #000000;margin:0.3em 0;" size="1" />
	</div><!--/#provideDynamite-->

{%include file="dynamite/common/menu.phtml"%}
{%include file="dynamite/common/footer.phtml" footAd=1 %}