<ul id="gNav"><!--
    --><li id="gNav01"><a href="{%$baseUrl%}/parking">パーキング</a></li><!--
    --><li id="gNav02"><a href="{%$baseUrl%}/parking/carshop">ショップ</a></li><!--
    --><li id="gNav03"><a href="{%$baseUrl%}/parking/house">アイテム</a></li><!--
    --><li id="gNav04"><a href="{%$baseUrl%}/parking/itemshop">ランキング</a></li><!--
    --><li id="gNav05"><a href="{%$baseUrl%}/parking/help">このゲームの遊び方</a></li><!--
--></ul>