<div id="subArea">

    <div id="subAreaAd">
        <iframe id="subAreaAdFrame" src="{%$staticUrl%}/apps/parking/img/ad/{%$bannerUrl%}?{%$version.js%}" width="250" height="250" scrolling="no" frameborder="0"></iframe>
    </div><!--/#subAreaAdd-->

	<div id="itemBox">
            <div class="header">
                <h2>所有アイテム</h2>
            </div>
            <ul>
                <input type="hidden" id="last_bribery_time" name="last_bribery_time" value="{%$last_bribery_time%}">
                <input type="hidden" id="last_evasion_time" name="last_evasion_time" value="{%$last_evasion_time%}">
                <input type="hidden" id="last_yanki_time" name="last_yanki_time" value="{%$last_yanki_time%}">
                <input type="hidden" id="havaFreePark" name="havaFreePark" value="{%$havaFreePark%}">
                <input type="hidden" id="haveFriends" name="haveFriends" value="{%$haveFriends%}">
                {%foreach from=$userItemInfo item=rowdata key=index%}

                <li id="li.{% $rowdata.sid %}">
                    <p class="img"><img src="{%$staticUrl%}/apps/parking/img/items/{% $rowdata.sid %}_s.gif" width="63" height="40" alt="" /></p>
                    <p class="name">{%$rowdata.name%}</p>
                    <p class="count">{%$rowdata.count%}</p>

                    {% if ($rowdata.sid==1) %}
                            {% if ($havaFreePark==0)%}
                                        <p class="status used"><a></a></p>
                                {% else %}
                                    {%if ($rowdata.count>0)%}
                                        <p class="status use"><a href="javascript:void(0);" onclick="new Item.Free();"></a></p>
                                    {%/if%}
                            {%/if%}
                    {% /if %}

                    {%if $rowdata.sid==2 %}
                        {%if ($rowdata.count>0)%}
                            <p class="status able"><a></a></p>
                        {%/if%}
                    {%/if%}

                    {%if $rowdata.sid==3%}
                            {%if $rowdata.count>0%}
                                {%if ($last_bribery_time<=3)%}<p class="status used"><a></a></p>{%/if%}
                                {%if ($last_bribery_time>3)%}<p class="status use"><a href="javascript:void(0);" onclick="new Item.Bribery();"></a></p>{%/if%}
                            {%/if%}
                            {%if $rowdata.count==0%}
                                {%if ($last_bribery_time<=3)%}<p class="status used"><a></a></p>{%/if%}

                            {%/if%}
                    {%/if%}

                    {%if $rowdata.sid==4 %}
                        {%if ($rowdata.count>0)%}
                            <p class="status able"><a></a></p>
                        {%/if%}
                    {%/if%}

                    {% if ($rowdata.sid==5) %}
                            {%if ($rowdata.count>0)%}
                                <p class="status use"><a href="javascript:void(0);" onclick="new Item.Bomb();"></a></p>
                            {%/if%}
                    {%/if%}



                    {%if $rowdata.sid==6%}
                            {%if $rowdata.count>0%}
                                {%if ($last_check_time<=1)%}<p class="status used"><a></a></p>{%/if%}
                                {%if ($last_check_time>1)%}<p class="status use"><a href="javascript:void(0);" onclick="new Item.Check();"></a></p>{%/if%}
                            {%/if%}

                            {%if $rowdata.count==0%}
                                {%if ($last_check_time<=1)%}<p class="status used"><a></a></p>{%/if%}

                            {%/if%}
                    {%/if%}

                    {% if ($rowdata.sid==7)%}
                            {%if ($rowdata.count>0)%}
                                {%if ($rowdata.insurance_card == 0)%}
                                    <p class="status use"><a href="javascript:void(0);" onclick="new Item.Insurance();"></a></p>
                                {%/if%}
                                {%if ($rowdata.insurance_card == 1)%}
                                    <p class="status used"><a></a></p>
                                {%/if%}
                            {%/if%}
                            {%if ($rowdata.count == 0)%}
                                {%if ($rowdata.insurance_card == 1)%}
                                    <p class="status used"><a></a></p>
                                {%/if%}
                            {%/if%}
                    {%/if%}

                    {%if $rowdata.sid==8%}
                            {%if $rowdata.count>0%}
                                {%if ($last_evasion_time<=2)%}<p class="status used"><a></a></p>{%/if%}
                                {%if ($last_evasion_time>2)%}<p class="status use"><a href="javascript:void(0);" onclick="new Item.Evasion();"></a></p>{%/if%}
                            {%/if%}
                            {%if $rowdata.count==0%}
                                {%if ($last_evasion_time<=2)%}<p class="status used"><a></a></p>{%/if%}

                            {%/if%}
                    {%/if%}

                    {%if $rowdata.sid==9%}
                            {%if ($rowdata.count>0)%}
                                <p class="status use"><a href="javascript:void(0);" onclick="new Item.Guard();"></a></p>
                            {%/if%}
                    {%/if%}


                    {% if ($rowdata.sid==10)%}
                            {%if ($rowdata.count>0)%}
                                <p class="status use"><a href="javascript:void(0);" onclick="new Item.Repair();"></a></p>
                            {%/if%}
                    {%/if%}

                    {% if ($rowdata.sid==11)%}
                            {%if $rowdata.count > 0%}
                                    {% if ($haveFriends != null && $haveFriends != '')%}
                                        <p class="status use"><a href="javascript:void(0);" onclick="new Item.Yanki();"></a></p>
                                    {%/if%}
                            {%/if%}
                    {%/if%}

                 </li>
                {%/foreach%}
            </ul>
	</div><!--/#itemBox-->
</div><!--/#subArea-->