<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		海賊船をﾏｲﾐｸに譲りたい<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		海賊船をﾏｲﾐｸに譲る手順は次の通りです｡<br />
		<br />
		1.｢<a href='{% "$baseUrl/mobile/ship/myship"|mixiurl %}'>海賊船一覧</a>｣画面に移動<br />
		2.譲渡したい海賊船を選択<br />
		3.｢この海賊船をﾏｲﾐｸに譲渡する｣を選択<br />
		4.海賊船を譲渡するﾏｲﾐｸをﾌﾟﾙﾀﾞｳﾝで選択し｢決定｣を実行<br />
		5.譲渡完了<br />
		<br />
		※不正行為防止のため､30日に1隻まで譲渡可能となります｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
