<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		使用中の海賊島を変更したい<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		使用している海賊島を変更する手順は次の通りです｡<br />
		<br />
		1.｢<a href='{% "$baseUrl/mobile/ship/myisland"|mixiurl %}'>海賊島一覧</a>｣画面に移動<br />
		2.使用したい海賊島の｢使用する｣を実行<br />
		3.変更完了<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
