<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		廃船とは?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		廃船とは､所有している海賊船がﾏｲﾐｸの海賊島で｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i03"|mixiurl %}'>隠し砲台ｶｰﾄﾞ</a>｣による一斉攻撃被害を受けた場合に陥る状態を示します｡<br />
		<br />
		廃船状態になると､修理するまで操作することができなくなります｡<br />
		<br />
		海賊船を修理する手順は次の通りです｡<br />
		<br />
		1.｢<a href='{% "$baseUrl/mobile/ship/myship"|mixiurl %}'>海賊船一覧</a>｣画面に移動<br />
		2.修理したい海賊船を選択<br />
		3.｢この海賊船を修理する｣を選択<br />
		4.修理費用が支払える場合､｢実行｣を選択<br />
		5.修理完了<br />
		<br />
		なお､｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i03"|mixiurl %}'>隠し砲台ｶｰﾄﾞ</a>｣による一斉攻撃(廃船化)を防ぐには｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i04"|mixiurl %}'>特殊装甲ｶｰﾄﾞ</a>｣を使用する必要があります｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
