<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		金貨を増やすには?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		金貨を増やす方法は､次の3つとなります｡<br />
		<br />
		1.<a href='{% "$baseUrl/mobile/ship/help?CF_help=b02"|mixiurl %}'>強奪</a>:ﾏｲﾐｸの海賊島の埋蔵金貨を運び出す<br />
		2.<a href='{% "$baseUrl/mobile/ship/help?CF_help=b03"|mixiurl %}'>襲撃</a>:ｱﾅﾀの海賊島で埋蔵金貨を運び出している海賊団(ﾏｲﾐｸ)から､金貨を奪い返す<br />
		3.<a href='{% "$baseUrl/mobile/ship/help?CF_help=b04"|mixiurl %}'>通報</a>:第三者の海賊島で埋蔵金貨を運び出すﾏｲﾐｸを世界政府に通報する<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
