<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		埋蔵金貨を運び出すには?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ﾏｲﾐｸの海賊島で埋蔵金貨を運び出すことに成功すると､金貨が増えます｡金貨を運び出す手順は次の通りです｡<br />
		<br />
		1.ﾏｲﾐｸの海賊島に移動<br />
		2.｢金貨を運び出す｣を実行<br />
		3.運び出す海賊船を選択<br />
		<br />
		4.一定時間待ちます…<br />
		※15分ごとに強奪金額が上昇!<br />
		<br />
		5.1のﾏｲﾐｸ以外の海賊島に移動<br />
		6.｢金貨を運び出す｣を実行<br />
		7.3で選択した海賊船を選択<br />
		8.埋蔵金貨獲得！<br />
		<br />
		※15分ごとに運び出す金額が上昇し､最大8時間まで上昇し続けます｡<br />
		※埋蔵金貨を運び出していることが海賊島のｵｰﾅｰ(ｱﾅﾀのﾏｲﾐｸ)にﾊﾞﾚるとそれまでに運び込んだ金貨がすべて奪われてしまいますので注意しましょう｡<br />
		※埋蔵金貨を運んでも､ﾏｲﾐｸの金貨量が減るわけではありませんので安心してください｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
