<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		通報するには?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		第三者の海賊島で埋蔵金貨を運び出しているﾏｲﾐｸを世界政府に通報すると､謝礼がもらえます｡通報の手順は次の通りです｡<br />
		<br />
		1.第三者の海賊島に移動<br />
		2.金貨強奪中の海賊船(ﾏｲﾐｸ)を探す<br />
		3.｢世界政府に通報する｣を実行<br />
		4.一定時間後､2のﾏｲﾐｸが他の海賊島に移動しなかった場合､通報成功<br />
		5.金貨獲得!<br />
		<br />
		※獲得額は強奪予定額の一部となります｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
