<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		世界政府の検問とは?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ﾏｲﾐｸの海賊島で埋蔵金貨を運び出すには､一定時間の経過が必要です｡<br />
		<br />
		ただし､すべての区画において最大8時間までしか金額は上昇しませんので､8時間以上運び出す行為を続けていると､世界政府の検問に引っかかり､それまで運び出していた金貨がすべて没収されてしまいます｡<br />
		<br />
		なお､｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i02"|mixiurl %}'>許可証ｶｰﾄﾞ</a>｣というｱｲﾃﾑを使用すると､一定時間､世界政府の検問が免除されます｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
