<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		島を開拓するには?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		島を開拓するには､｢<a href='{% "$baseUrl/mobile/ship/island"|mixiurl %}'>島の開拓</a>｣画面で新たな島を開拓する必要があります｡島を開拓する利点は次の通りです｡<br />
		<br />
		1.宝箱の数が増える<br />
		2.埋蔵金貨が増える<br />
		<br />
		埋蔵金貨が増えた結果､ｱﾅﾀのﾏｲﾐｸから埋蔵金貨が運ばれる可能性が高くなります｡<br />
		<br />
		ﾏｲﾐｸにｱﾅﾀの島で積極的に埋蔵金貨を運ばせ､よこどりすると結果的にｱﾅﾀの海賊団の金貨量が多く獲得できるようになります｡<br />
		<br />
		※開拓するには､ﾀﾞｲﾔが必要です｡<br />
		※海賊島には使用期限がありますのでご注意ください｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
