<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		ダイヤを増やすには?<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ﾀﾞｲﾔは金貨と交換することができません｡そのため､ﾀﾞｲﾔを増やすには､ｱﾅﾀのﾏｲﾐｸをこのｱﾌﾟﾘに招待する必要があります｡<br />
		<br />
		<div style="text-align:center;">{% emoji code="F9BC" %}<a href='{% "invite:friends?callback=$baseUrl/mobile/callback/invite?forward=$baseUrl/mobile/ship/invite" %}'>ﾏｲﾐｸ招待でﾀﾞｲﾔGET</a><br /></div>
		<br />
		ｱﾌﾟﾘ招待によるﾀﾞｲﾔﾓﾝﾄﾞ獲得に関する注意は次の通りです｡<br />
		<br />
		1.ﾏｲﾐｸを1人招待するごとにﾀﾞｲﾔﾓﾝﾄﾞが1つ支給されます｡<br />
		2.ﾀﾞｲﾔﾓﾝﾄﾞは､ﾏｲﾐｸをｱﾌﾟﾘに招待した時点で支給されるのではなく､招待したﾏｲﾐｸがｱﾌﾟﾘを追加した時点から2-3日程度で支給されます｡<br />
		3.1度ｱﾌﾟﾘを追加したことがあるﾏｲﾐｸを招待しても､ﾀﾞｲﾔﾓﾝﾄﾞは獲得できません｡<br />
		4.<span style="color:#cc0000;">招待したﾏｲﾐｸがｱﾌﾟﾘを追加した場合､その旨を個別通知しておりません｡</span>そのため､ﾀﾞｲﾔﾓﾝﾄﾞの増加に関しては､<a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}'>ﾏｲﾍﾟｰｼﾞ</a>にてご確認ください｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
