<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		よくある質問<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">Q.埋蔵金貨が奪われると所有する金貨の量が減りますか?</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cc0000;">A.</span>いいえ､減りません｡[海賊島にある埋蔵金貨]と[海賊団が所有する金貨]は“別の金貨”となります｡<br />
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">Q.ﾏｲﾐｸ以外の海賊団から強奪･襲撃･通報されることはありますか?</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cc0000;">A.</span>いいえ､当ｱﾌﾟﾘではﾏｲﾐｸ以外のﾕｰｻﾞｰとｹﾞｰﾑ内で交流することはありません｡<br />
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">Q.ﾗﾝｷﾝｸﾞの総資産とはなんですか?</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cc0000;">A.</span><a href='{% "$baseUrl/mobile/ship/rankingfriend"|mixiurl %}'>ﾗﾝｷﾝｸﾞ</a>の総資産は､所有する金貨･海賊船の合計額となります｡ﾀﾞｲﾔ･海賊島･ｱｲﾃﾑは資産には計上されませんのでご注意ください｡<br />
		</div><!--/.section-->
		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#9e623a;">Q.ﾏｲﾐｸを招待したのにﾀﾞｲﾔがもらえません</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cc0000;">A.</span>ﾀﾞｲﾔﾓﾝﾄﾞは､ﾏｲﾐｸをｱﾌﾟﾘに招待した時点で支給されるのではなく､招待したﾏｲﾐｸがｱﾌﾟﾘを追加した時点から2-3日程度で支給されます｡また､1度ｱﾌﾟﾘを追加したことがあるﾏｲﾐｸを招待しても､ﾀﾞｲﾔﾓﾝﾄﾞは獲得できません｡<br />
		</div><!--/.section-->

		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
