<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		ヒミツ通報カード<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		ﾋﾐﾂ通報ｶｰﾄﾞは｢1度だけ､世界政府に匿名で通報できる｣ｱｲﾃﾑです｡<br />
		<br />
		通常の｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=b04"|mixiurl %}'>世界政府への通報</a>｣は通報者が誰であるかが､通報されたﾕｰｻﾞｰに通知されます｡<br />
		<br />
		ﾋﾐﾂ通報ｶｰﾄﾞを使うと､誰が通報したかを相手に伝えずに通報することが可能です｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
