<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		許可証カード<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		許可証ｶｰﾄﾞは｢使用後72時間､世界政府の検問が免除される｣ｱｲﾃﾑです｡<br />
		<br />
		通常､｢金貨を運び出す｣行為を8時間以上行った場合､<a href='{% "$baseUrl/mobile/ship/help?CF_help=b05"|mixiurl %}'>世界政府の検問</a>を受け､運び出した金貨が没収されてしまうことがあります｡<br />
		<br />
		許可証ｶｰﾄﾞを使うと､使用後72時間は､世界政府の検問を受けることはなく､金貨が没収されることもありません｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
