<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		隠し砲台カード<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		隠し砲台ｶｰﾄﾞは｢金貨を運び出す海賊船へ一斉攻撃を仕掛ける｣ｱｲﾃﾑです｡<br />
		<br />
		隠し砲台ｶｰﾄﾞを使うと､ﾏｲﾐｸがｱﾅﾀの海賊島で金貨を運び出そうとしたとき､待ち伏せた大砲が一斉攻撃を仕掛け､金貨を運び出そうとした海賊船を廃船状態にします｡<br />
		<br />
		廃船状態になると､<a href='{% "$baseUrl/mobile/ship/help?CF_help=a04"|mixiurl %}'>修理する</a>まで動かすことができなくなります｡<br />
		<br />
		なお､隠し砲台ｶｰﾄﾞは｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i04"|mixiurl %}'>特殊装甲ｶｰﾄﾞ</a>｣を所有している場合､効果が無効となります｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
