<div id="help">
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		特殊装甲カード<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		特殊装甲ｶｰﾄﾞは｢隠し砲台による一斉攻撃から､1度だけ身を守る｣ｱｲﾃﾑです｡<br />
		<br />
		特殊装甲ｶｰﾄﾞを使うと､ﾏｲﾐｸの海賊島で｢<a href='{% "$baseUrl/mobile/ship/help?CF_help=i03"|mixiurl %}'>隠し砲台ｶｰﾄﾞ</a>｣による一斉攻撃を受けた場合､ｱﾅﾀの海賊船の廃船を免れることができます｡<br />
		<br />
		通常､大砲の一斉攻撃を受けた場合､廃船となり､<a href='{% "$baseUrl/mobile/ship/help?CF_help=a04"|mixiurl %}'>修理する</a>まで動かすことができなくなります｡<br />
		<br />
		以上となります｡<br />
		<div class="nomenuAlert">
			<br />
			直前のﾍﾟｰｼﾞは{% emoji code="F8E9" %}の<span style="color:#cd424a;">[戻るﾎﾞﾀﾝ]</span>でお戻りください<br />
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		</div><!--/.nomenuAlert-->
	</div><!--/.content-->
</div><!--/#help-->
