<div id="help">
	<div id="title" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/ship/img/title.gif" width="240" height="100" style="margin:3px 0;" /><br />
	</div><!--/#title-->
	<div class="headline" style="background:#7c4825;color:#ffffff;text-align:center;">
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
		ヘルプ・遊び方<br />
		<div class="line" style="background:#ffffff;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /><br /></div>
		もくじ<br />
		<div class="line" style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br /></div>
	</div><!--/.headline-->
	<div class="content">

		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E4"%}<span style="color:#9e623a;">基本ルール</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b01"|mixiurl %}'>≫</a>金貨を増やすには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b02"|mixiurl %}'>≫</a>埋蔵金貨を運び出すには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b03"|mixiurl %}'>≫</a>埋蔵金貨を奪い返すには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b04"|mixiurl %}'>≫</a>通報するには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b05"|mixiurl %}'>≫</a>世界政府の検問とは?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b06"|mixiurl %}'>≫</a>海賊船を増やすには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b07"|mixiurl %}'>≫</a>海賊船の強奪率とは?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b08"|mixiurl %}'>≫</a>島を開拓するには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b09"|mixiurl %}'>≫</a>アイテムを購入するには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b10"|mixiurl %}'>≫</a>アイテムを使用するには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b11"|mixiurl %}'>≫</a>ダイヤを増やすには?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b12"|mixiurl %}'>≫</a>更新情報とは?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=b13"|mixiurl %}'>≫</a>ﾃﾞｲﾘｰｷﾞﾌﾄとは?<br />
		</div><!--/.section-->

		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E4"%}<span style="color:#9e623a;">中級者向けルール</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=a01"|mixiurl %}'>≫</a>海賊船の名前を変更したい<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=a02"|mixiurl %}'>≫</a>海賊船をﾏｲﾐｸに譲りたい<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=a03"|mixiurl %}'>≫</a>使用中の海賊島を変更したい<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=a04"|mixiurl %}'>≫</a>廃船とは?<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=a05"|mixiurl %}'>≫</a><span style="color:#cd424a;">同型船の最大所有数</span>{% emoji code="F982" %}<br />
		</div><!--/.section-->

		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E4"%}<span style="color:#9e623a;">アイテム説明</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=i01"|mixiurl %}'>≫</a>ヒミツ通報カード<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=i02"|mixiurl %}'>≫</a>許可証カード<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=i03"|mixiurl %}'>≫</a>隠し砲台カード<br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=i04"|mixiurl %}'>≫</a>特殊装甲カード<br />
		</div><!--/.section-->

		<div class="section">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			{% emoji code="F8E4"%}<span style="color:#9e623a;">その他</span><br />
			<div style="background:#9e623a;"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<a href='{% "$baseUrl/mobile/ship/help?CF_help=faq"|mixiurl %}'>≫</a>よくある質問<br />
		</div><!--/.section-->

	</div><!--/.content-->
</div><!--/#help-->

{%include file="ship/common/menu.phtml"%}

