<div id="welcome">
	<div id="title" style="text-align:center;">
		<img src="{%$staticUrl%}/apps/ship/img/title.gif" width="240" height="100" style="margin-top:3px;" /><br />
		<span style="color:#7c4825;">金貨を奪って海賊王を目指せ{% emoji code="F9AD" %}</span><br />
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#aa947f;">
			<tr>
				<td style="background:#f2ebd4;text-align:center;"><div style="{%if $ua==1%}font-size:x-small;{%/if%}">
					<a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}' style="color:#a40000;"><span style="color:#a40000;">海賊ﾏｲﾍﾟｰｼﾞへ</span></a>{% emoji code="F9A2" %}<br />
					</div></td>
			</tr>
		</table>
	</div><!--/#title-->
	<div id="guide">
		<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
		<div class="wrapper" style="background:#d7cfb3;text-align:center;">
			<img src="{%$staticUrl%}/apps/ship/img/menu_head.gif" width="240" height="10" ><br />
			<img src="{%$staticUrl%}/apps/ship/img/top01.gif" width="240" height="70" style="margin:5px 0 15px 0;" ><br />
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="84" align="center" style="width:84px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/top02.gif" width="80" height="80" ></td>
						<td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;text-align:left;"><img src="{%$staticUrl%}/apps/ship/img/top03.gif" width="146" height="25" /><br />
							ﾏｲﾐｸの海賊島からﾊﾞﾚないように宝を盗み出すだけ!</td>
					</tr>
				</table>
				<img src="{%$staticUrl%}/apps/ship/img/top_line.gif" width="230" height="29" /><br />
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="84" align="center" style="width:84px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/top04.gif" width="80" height="80" ></td>
						<td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;text-align:left;"><img src="{%$staticUrl%}/apps/ship/img/top05.gif" width="146" height="25" /><br />
							強奪中に攻めると、金貨が奪い返せるぞ！</td>
					</tr>
				</table>
				<img src="{%$staticUrl%}/apps/ship/img/top_line.gif" width="230" height="29" /><br />
			</div><!--/.section-->
			<div class="section">
				<table width="100%" cellpadding="0" cellspacing="0" border="0">
					<tr>
						<td width="84" align="center" style="width:84px;text-align:center;"><img src="{%$staticUrl%}/apps/ship/img/top06.gif" width="80" height="80" ></td>
						<td valign="top" style="{% if $ua==1 %}font-size:x-small;{% /if %}vertical-align:top;text-align:left;"><img src="{%$staticUrl%}/apps/ship/img/top07.gif" width="146" height="25" /><br />
							通報されると世界政府から攻撃されるので注意しよう</td>
					</tr>
				</table>
				<img src="{%$staticUrl%}/apps/ship/img/top_line.gif" width="230" height="29" /><br />
			</div><!--/.section-->
			<table width="230" cellpadding="3" cellspacing="1" border="0" align="center" style="background:#aa947f;">
				<tr>
					<td style="background:#f2ebd4;text-align:center;"><div style="{%if $ua==1%}font-size:x-small;{%/if%}">
						<a href='{% "$baseUrl/mobile/ship/index"|mixiurl %}' style="color:#a40000;"><span style="color:#a40000;">海賊ﾏｲﾍﾟｰｼﾞへ</span></a>{% emoji code="F9A2" %}<br />
						</div></td>
				</tr>
			</table>
			<img src="{%$staticUrl%}/apps/ship/img/menu_foot.gif" width="240" height="10" ><br />
		</div><!--/.wrapper-->
		<div class="more" style="text-align:right;">
			<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
			<span style="color:#cd424a;">⇒</span><a href='{% "$baseUrl/mobile/ship/help"|mixiurl %}'>もっと詳しく</a>&nbsp;<br />
		</div><!--/.more-->
	</div><!--/#guide-->
	<br />
</div><!--/#welcome-->

