<div style="background-color:#ccff66;text-align:left;">
	{% disneyimg name="foote2" %}
	{% disneyimg style='height="3"' name="dot0" %}<br />
		<span style="color:#3ea124;">├</span>{% emoji code="F987"%}<a href='{% "$baseUrl/mobile/disney/index"|mixiurl %}' accesskey="1">ご当地ｺﾚｸｼｮﾝTOP</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9E5"%}<a href='{% "$baseUrl/mobile/disney/map"|mixiurl %}'>ご当地ﾏｯﾌﾟ</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9BF"%}<a href='{% "$baseUrl/mobile/disney/cuplist"|mixiurl %}'>ｱﾜｰﾄﾞ</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9D8"%}<a href='{% "$baseUrl/mobile/disney/game"|mixiurl %}'>ﾁｬﾚﾝｼﾞｹﾞｰﾑ</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9CB"%}<a href='{% "$baseUrl/mobile/disney/mymixilist"|mixiurl %}'>ﾏｲﾐｸ情報</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F981"%}<a href='{% "$baseUrl/mobile/disney/enjoy"|mixiurl %}'>もっとﾂｱｰを楽しもう</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F8E4"%}<a href='{% "$baseUrl/mobile/disney/rule"|mixiurl %}'>利用規約</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F97A"%}<a href='{% "$baseUrl/mobile/disney/charge"|mixiurl %}'>有料ｻｰﾋﾞｽ利用規約</a><br />
		<span style="color:#3ea124;">├</span>{% emoji code="F9B8"%}<a href='{% "$baseUrl/mobile/disney/tokus"|mixiurl %}'>特定商取引法に基づく表示</a><br />
		<span style="color:#3ea124;">└</span>{% emoji code="F9A0"%}<a href='{% "$baseUrl/mobile/disney/help"|mixiurl %}'>よくある質問</a><br />
	{% disneyimg style='height="3"' name="dot0" %}<br />
</div>
</div>

</body>
</html>