		<div id="inviteBtnBox"><a href="javascript:void(0);" onclick="mixi_invite();return false;">マイミクを招待</a></div>
		<div id="adBox" class="box">
			<a style="display:block;margin-bottom:4px;" href="{%$mixiHostUrl%}/run_appli.pl?id=6230" target="_blank"><img src="{%$staticUrl%}/apps/slave/img/dummy/ddp_250x89.jpg" /></a>
			<a style="display:block;margin-bottom:4px;" href="{%$mixiHostUrl%}/run_appli.pl?id=2689" target="_blank"><img src="{%$staticUrl%}/apps/slave/img/dummy/ttm_250x89.jpg" /></a>
			<a style="display:block;" href="{%$mixiHostUrl%}/run_appli.pl?id=2385" target="_blank"><img src="{%$staticUrl%}/apps/slave/img/dummy/chome_250x89.jpg" /></a>
			<!-- <a href="{%$objAd.adLink%}"><img src="{%$staticUrl%}/apps/slave/img/dummy/ad{%$objAd.adNum%}.png" width="250" height="250" alt="広告" /></a> -->
		</div><!--/#adBox.box-->
