{%include file="afrac/common/header.phtml"%}
<body id="home">
<div id="container">
	<div id="mainColumn">
		
		<div id="playArea">
			<img src="{%$staticUrl%}/apps/afrac/img/error.png" width="498" height="490" alt="" />
		</div><!--/#playArea-->
		
		<div id="rankingArea">
			<h2><img src="{%$staticUrl%}/apps/afrac/img/ranking_header.png" width="177" height="47" alt="あなたは何番目？スコアランキング" /></h2>
			<ol><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>1位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>2位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>3位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>4位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>5位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
				--><li>
					<p class="pic" style="background-image:url({%$staticUrl%}/apps/afrac/img/default_pic.gif);">ユーザー名</p>
					<p class="rank">〓<span>6位</span>〓</p>
					<p class="name">????さん</p>
					<p class="score">????点</p>
				</li><!--
			--></ol>
			<ul id="scoreController"><!--
				--><li id="scoreUp"><a href="">上</a></li><!--
				--><li id="scoreDown"><a href="">下</a></li><!--
			--></ul>
			<p id="allRanking" class="btn active"><a href="">ミイクシィ全体ランキング</a></p>
			<p id="myMixiRanking" class="btn"><a href="">マイミクシィ内ランキング</a></p>
		</div><!--/#rankingArea-->
		
		<address><img src="{%$staticUrl%}/apps/afrac/img/copyright.png" width="680" height="25" alt="Copyright 2009 Aflac Japan  AFH広告" /></address>
	
	</div><!--/#mainColumn-->

	<div id="subColumn">
		
		<p class="btn"><a href=""><img src="{%$staticUrl%}/apps/afrac/img/btn_invite.png" width="250" height="35" alt="マイミクシィを招待する" /></a></p>
		
		<div id="adBanner" class="banner"><a href="" target="_top"><img src="{%$staticUrl%}/apps/afrac/img/ad_shoulder.png" width="250" height="250" alt="しあわせをまねくまねきねこダックとマイミクになろう" title="" /></a></div>
		
		<div id="helpBanner" class="banner"><img src="{%$staticUrl%}/apps/afrac/img/howto.png" width="250" height="225" alt="ゲームの遊びかた" /></div>
			
	</div><!--/#subColumn-->
	
	<div id="bigBanner"><a href="" target="_top"><img src="{%$staticUrl%}/apps/afrac/img/ad_footer.png" width="945" height="129" alt="まねきねこダッグの歌" title="" /></a></div>

</div><!--/#container-->
</body>
</html>
