<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" dir="ltr">
<head>
	<meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
	<title>ディズニーご当地コレクション</title>

	<link rel="stylesheet" href="{%$staticUrl%}/apps/disney/img/disneyfaq/main.css" type="text/css" media="all" />
	<style type="text/css">
		<![CDATA[
		a:link{color:#0000ff;}
		a:visited{color:#7c027c;}
		]]>
	</style>
	
</head>
<body style="background:#edd9ae;">
<div id="continer" style="font-size:x-small;background:#edd9ae;">

<h1><img src="{%$staticUrl%}/apps/disney/img/disneyfaq/title.gif" alt="よくある質問" /></h1>