<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
<div class="headline">
	{% emoji code="F9E6"%}{%$classInfo.name|escape%}({%$classInfo.member_count%})<br />
	<div class="line" style="background:#b7cb6d;"><img src="http://mm.mixi.net/img/dot0.gif" width="2" height="2" /></div>
	<div style="text-align:right;">{%$nextSchedule.wday%}･{%$nextSchedule.part%}限<span style="color:#cccccc;">|</span>{%$nextSchedule.start_h%}:{%$nextSchedule.start_m%}～{%$nextSchedule.end_h%}:{%$nextSchedule.end_m%}<span style="color:#cccccc;">|</span>{%$classInfo.teacher|escape%}</div>
</div><!--/.headline-->