{% if $pager.maxPager > 1 %}
<div class="nav" style="text-align:center;">
	<div class="line" style="background:{% if $pager.lineColor %}{%$pager.lineColor%}{% else %}#ffa0fe;{% /if %}"><img src="http://mm.mixi.net/img/dot0.gif" width="1" height="1" /></div>
	<img src="http://mm.mixi.net/img/dot0.gif" width="1" height="3" /><br />
	{% if $pager.pageIndex != 1 %}{% emoji code="F98A"%}<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex-1``$pager.pageParam`"|mixiurl %}' accesskey="4">前を表示</a>{% /if %}
	{% if $pager.maxPager != $pager.pageIndex%}{% emoji code="F98C"%}<a href='{% "$baseUrl/`$pager.requestUrl`?CF_page=`$pager.pageIndex+1``$pager.pageParam`"|mixiurl %}' accesskey="6">次を表示</a>{% /if %}
</div>
{% /if %}